var searchData=
[
  ['w_0',['Persist your configuration using &lt;span class=&quot;tt&quot;&gt;-w&lt;/span&gt;',['../index.html#persist-your-configuration-using--w',1,'']]],
  ['w_20so_20you_20don’t_20repeat_20flags_1',['Persist your configuration using &lt;span class=&quot;tt&quot;&gt;-w&lt;/span&gt; (so you don’t repeat flags)',['../index.html#persist-your-configuration-using--w-so-you-dont-repeat-flags',1,'']]],
  ['weaknesses_2',['Weaknesses',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#weaknesses',1,'']]],
  ['web_20interface_3',['Web Interface',['../index.html#web-interface',1,'']]],
  ['web_20interface_20http_4',['Enable the Web Interface (HTTP)',['../index.html#enable-the-web-interface-http',1,'']]],
  ['web_20interface_20over_20tcp_20ip_5',['Web Interface over TCP/IP',['../index.html#web-interface-over-tcpip',1,'']]],
  ['web_20interface_20over_20unix_20domain_20sockets_6',['Web Interface over UNIX Domain Sockets',['../index.html#web-interface-over-unix-domain-sockets',1,'']]],
  ['web_20ui_20after_20the_20configuration_20has_20been_20saved_7',['(For development only) Use custom HTML templates for the Web UI (after the configuration has been saved)',['../index.html#for-development-only-use-custom-html-templates-for-the-web-ui-after-the-configuration-has-been-saved',1,'']]],
  ['websockets_8',['WebSockets',['../index.html#optional-use-unix-domain-websockets',1,'(Optional) Use Unix Domain WebSockets'],['../index.html#mqtt-over-unix-domain-websockets',1,'MQTT over UNIX Domain WebSockets'],['../index.html#mqtt-over-unix-domain-websockets-1',1,'MQTT over UNIX Domain WebSockets'],['../index.html#mqtt-over-unix-domain-websockets-2',1,'MQTT over UNIX Domain WebSockets'],['../index.html#mqtt-over-websockets',1,'MQTT over WebSockets'],['../index.html#mqtt-over-websockets-1',1,'MQTT over WebSockets'],['../index.html#mqtt-over-websockets-2',1,'MQTT over WebSockets'],['../index.html#quick-tls-checklist-for-mqtttcp-and-mqtt-over-websockets',1,'Quick TLS checklist for MQTT(TCP) and MQTT over WebSockets']]],
  ['websockets_20specifics_9',['WebSockets specifics',['../index.html#websockets-specifics',1,'']]],
  ['websockets_20specifics_20that_20often_20trip_20clients_10',['WebSockets specifics that often trip clients',['../index.html#websockets-specifics-that-often-trip-clients',1,'WebSockets specifics that often trip clients'],['../index.html#websockets-specifics-that-often-trip-clients-1',1,'WebSockets specifics that often trip clients']]],
  ['websockets_20tls_20_3a_11',['WebSockets TLS :',['../index.html#example-websocketstls',1,'Example (WebSockets/TLS):'],['../index.html#example-websocketstls-1',1,'Example (WebSockets/TLS):']]],
  ['websockets_20tls_20layered_20on_20the_20ws_20endpoint_20_3a_12',['Example (Unix Domain WebSockets, TLS layered on the WS endpoint):',['../index.html#example-unix-domain-websockets-tls-layered-on-the-ws-endpoint',1,'']]],
  ['websockets_20wss_13',['(Optional) Use WebSockets (WSS)',['../index.html#optional-use-websockets-wss',1,'']]],
  ['well_20in_20production_14',['well in production',['../index.html#why-this-layout-works-well-in-production',1,'Why this layout works well in production'],['../index.html#why-this-layout-works-well-in-production-1',1,'Why this layout works well in production']]],
  ['what_15',['what',['../classnlohmann_1_1JsonPatchFormatException.html#a46b9315072364d6f30d523d9a90cf6bf',1,'nlohmann::JsonPatchFormatException']]],
  ['what_20is_20it_16',['What is it?',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#what-is-it',1,'']]],
  ['when_17',['when',['../structmqtt_1_1lib_1_1MqttMapper_1_1ScheduledPublish.html#aa0f0f5034872fa93a1a7e8b7ed5a10c7',1,'mqtt::lib::MqttMapper::ScheduledPublish']]],
  ['when_20mqtt_20mapping_20file_20is_20provided_18',['Embedded MQTTIntegrator (when &lt;span class=&quot;tt&quot;&gt;--mqtt-mapping-file&lt;/span&gt; is provided)',['../index.html#embedded-mqttintegrator-when---mqtt-mapping-file-is-provided',1,'']]],
  ['when_20you_20need_20logic_19',['Switch to a template mapping when you need logic',['../index.html#switch-to-a-template-mapping-when-you-need-logic',1,'']]],
  ['why_20this_20layout_20works_20well_20in_20production_20',['Why this layout works well in production',['../index.html#why-this-layout-works-well-in-production',1,'Why this layout works well in production'],['../index.html#why-this-layout-works-well-in-production-1',1,'Why this layout works well in production']]],
  ['wildcard_20examples_21',['Wildcard examples',['../index.html#wildcard-examples',1,'']]],
  ['willmessage_22',['willMessage',['../classmqtt_1_1bridge_1_1lib_1_1Broker.html#a554eb6627aa4d92607f47aca793b6952',1,'mqtt::bridge::lib::Broker::willMessage'],['../classmqtt_1_1mqttcli_1_1lib_1_1Mqtt.html#afe3a3c98893f7b035b4f15845756d84a',1,'mqtt::mqttcli::lib::Mqtt::willMessage']]],
  ['willmessageopt_23',['willMessageOpt',['../classmqtt_1_1mqttcli_1_1lib_1_1ConfigSession.html#a34f6cca6dae7f3edc82935052b07b8ea',1,'mqtt::mqttcli::lib::ConfigSession']]],
  ['willqos_24',['willQoS',['../classmqtt_1_1bridge_1_1lib_1_1Broker.html#ad101dd83df655099017f92539a94a128',1,'mqtt::bridge::lib::Broker::willQoS'],['../classmqtt_1_1mqttcli_1_1lib_1_1Mqtt.html#a64672f54162eb2bd9658b13ede2ac8d0',1,'mqtt::mqttcli::lib::Mqtt::willQoS']]],
  ['willqosopt_25',['willQoSOpt',['../classmqtt_1_1mqttcli_1_1lib_1_1ConfigSession.html#af867f693660c2cd73decf7373bc96f65',1,'mqtt::mqttcli::lib::ConfigSession']]],
  ['willretain_26',['willRetain',['../classmqtt_1_1bridge_1_1lib_1_1Broker.html#aaf8d73b588e50698be0fcd832148b1fc',1,'mqtt::bridge::lib::Broker::willRetain'],['../classmqtt_1_1mqttcli_1_1lib_1_1Mqtt.html#a3908fb32eb5e0b5140e939cb145a3cb0',1,'mqtt::mqttcli::lib::Mqtt::willRetain']]],
  ['willretainopt_27',['willRetainOpt',['../classmqtt_1_1mqttcli_1_1lib_1_1ConfigSession.html#afc713391e1cf8c988c284e060893807f',1,'mqtt::mqttcli::lib::ConfigSession']]],
  ['willtopic_28',['willTopic',['../classmqtt_1_1bridge_1_1lib_1_1Broker.html#ab4d93f3dce35c5a2cb28d082eb872db2',1,'mqtt::bridge::lib::Broker::willTopic'],['../classmqtt_1_1mqttcli_1_1lib_1_1Mqtt.html#a00e159e75456d7444062294e467bc1d8',1,'mqtt::mqttcli::lib::Mqtt::willTopic']]],
  ['willtopicopt_29',['willTopicOpt',['../classmqtt_1_1mqttcli_1_1lib_1_1ConfigSession.html#aeb84dbbb8f7b5e204860d07649928d6a',1,'mqtt::mqttcli::lib::ConfigSession']]],
  ['with_20a_20simple_20static_20mapping_30',['Add a concrete subscription with a simple static mapping',['../index.html#add-a-concrete-subscription-with-a-simple-static-mapping',1,'']]],
  ['with_20ajv_20cli_31',['Validate against the schema (example with &lt;span class=&quot;tt&quot;&gt;ajv-cli&lt;/span&gt;)',['../index.html#validate-against-the-schema-example-with-ajv-cli',1,'']]],
  ['with_20common_20tools_32',['Quick sanity checks with common tools',['../index.html#quick-sanity-checks-with-common-tools',1,'']]],
  ['with_20hunter_20package_20manager_33',['Building with Hunter package manager',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#building-with-hunter-package-manager',1,'']]],
  ['with_20mqttsuites_20command_20line_20tool_34',['Quick sanity checks with MQTTSuites command line tool',['../index.html#quick-sanity-checks-with-mqttsuites-command-line-tool',1,'']]],
  ['with_20mutual_20tls_3a_35',['Example (TCP/TLS) with mutual TLS:',['../index.html#example-tcptls-with-mutual-tls',1,'']]],
  ['with_20the_20mapping_20description_36',['Behavior aligned with the Mapping Description',['../index.html#behavior-aligned-with-the-mapping-description',1,'']]],
  ['with_20your_20mapping_37',['Run the integrator with your mapping',['../index.html#run-the-integrator-with-your-mapping',1,'']]],
  ['within_20another_20project_38',['Building as a CMake-subdirectory from within another project',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#building-as-a-cmake-subdirectory-from-within-another-project',1,'']]],
  ['workflow_20recommended_39',['Persist-once workflow (recommended)',['../index.html#persist-once-workflow-recommended',1,'']]],
  ['works_20well_20in_20production_40',['works well in production',['../index.html#why-this-layout-works-well-in-production',1,'Why this layout works well in production'],['../index.html#why-this-layout-works-well-in-production-1',1,'Why this layout works well in production']]],
  ['wrapparagraph_41',['wrapParagraph',['../mqttcli_2lib_2Mqtt_8cpp.html#af65432cee33a80f84b065ea6e060d702',1,'Mqtt.cpp']]],
  ['write_42',['write',['../classinja_1_1Environment.html#ae64c18f23f81e8ee787d406ccd4d35dc',1,'inja::Environment::write(const std::filesystem::path &amp;filename, const json &amp;data, const std::string &amp;filename_out)'],['../classinja_1_1Environment.html#a832e72bad384f9c59f587ff73eb9a235',1,'inja::Environment::write(const Template &amp;temp, const json &amp;data, const std::string &amp;filename_out)']]],
  ['write_5fwith_5fjson_5ffile_43',['write_with_json_file',['../classinja_1_1Environment.html#ad6a6b713e78516f4f6fd68c58f309f3c',1,'inja::Environment::write_with_json_file(const std::filesystem::path &amp;filename, const std::string &amp;filename_data, const std::string &amp;filename_out)'],['../classinja_1_1Environment.html#a9c6eb9a291cf99615991f999128248a7',1,'inja::Environment::write_with_json_file(const Template &amp;temp, const std::string &amp;filename_data, const std::string &amp;filename_out)']]],
  ['ws_20endpoint_20_3a_44',['Example (Unix Domain WebSockets, TLS layered on the WS endpoint):',['../index.html#example-unix-domain-websockets-tls-layered-on-the-ws-endpoint',1,'']]],
  ['wss_45',['WSS',['../index.html#optional-use-websockets-wss',1,'(Optional) Use WebSockets (WSS)'],['../index.html#tls-checklist-for-client-connections-mqtts--wss--uds-wss',1,'TLS checklist for client connections (MQTTS / WSS / UDS-WSS)']]],
  ['wss_20uds_20wss_46',['TLS checklist for client connections (MQTTS / WSS / UDS-WSS)',['../index.html#tls-checklist-for-client-connections-mqtts--wss--uds-wss',1,'']]]
];
