var searchData=
[
  ['making_20configuration_20persistent_20recommended_0',['Making configuration persistent (recommended)',['../index.html#making-configuration-persistent-recommended',1,'']]],
  ['manager_1',['Building with Hunter package manager',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#building-with-hunter-package-manager',1,'']]],
  ['mandatory_2',['Mandatory',['../index.html#mandatory',1,'']]],
  ['mandatory_20libraries_20and_20frameworks_3',['Mandatory Libraries and Frameworks',['../index.html#mandatory-libraries-and-frameworks',1,'']]],
  ['mapping_4',['mapping',['../index.html#static-mapping',1,'&lt;span class=&quot;tt&quot;&gt;static&lt;/span&gt; mapping'],['../index.html#add-a-concrete-subscription-with-a-simple-static-mapping',1,'Add a concrete subscription with a simple static mapping'],['../index.html#run-the-integrator-with-your-mapping',1,'Run the integrator with your mapping']]],
  ['mapping_20description_5',['Mapping Description',['../index.html#behavior-aligned-with-the-mapping-description',1,'Behavior aligned with the Mapping Description'],['../index.html#mqtt-mapping-description',1,'MQTT Mapping Description']]],
  ['mapping_20example_20json_3a_6',['Save as &lt;span class=&quot;tt&quot;&gt;~/mapping-example.json&lt;/span&gt;:',['../index.html#save-as-mapping-examplejson',1,'']]],
  ['mapping_20file_7',['Skeleton mapping file',['../index.html#skeleton-mapping-file',1,'']]],
  ['mapping_20file_20canonical_20test_20case_20below_8',['Attach your mapping file (canonical test case below)',['../index.html#attach-your-mapping-file-canonical-test-case-below',1,'']]],
  ['mapping_20file_20is_20provided_9',['Embedded MQTTIntegrator (when &lt;span class=&quot;tt&quot;&gt;--mqtt-mapping-file&lt;/span&gt; is provided)',['../index.html#embedded-mqttintegrator-when---mqtt-mapping-file-is-provided',1,'']]],
  ['mapping_20in_20mqtt_20_3a_10',['Run the integrator for this mapping (in-mqtt):',['../index.html#run-the-integrator-for-this-mapping-in-mqtt',1,'']]],
  ['mapping_20object_20big_20picture_11',['The &lt;span class=&quot;tt&quot;&gt;mapping&lt;/span&gt; Object (big picture)',['../index.html#the-mapping-object-big-picture',1,'']]],
  ['mapping_20sections_12',['Mapping Sections',['../index.html#mapping-sections',1,'']]],
  ['mapping_20template_20object_13',['&lt;span class=&quot;tt&quot;&gt;json&lt;/span&gt; mapping (template, object)',['../index.html#json-mapping-template-object',1,'']]],
  ['mapping_20template_20scalar_14',['&lt;span class=&quot;tt&quot;&gt;value&lt;/span&gt; mapping (template, scalar)',['../index.html#value-mapping-template-scalar',1,'']]],
  ['mapping_20test_20case_15',['Canonical Mapping &amp;amp; Test Case',['../index.html#canonical-mapping--test-case',1,'']]],
  ['mapping_20when_20you_20need_20logic_16',['Switch to a template mapping when you need logic',['../index.html#switch-to-a-template-mapping-when-you-need-logic',1,'']]],
  ['mariadb_20bootstrap_3a_20database_20user_20and_20permissions_17',['2. MariaDB bootstrap: database, user, and permissions',['../md_docs_2mqttstore-user-guide.html#autotoc_md2-mariadb-bootstrap-database-user-and-permissions',1,'']]],
  ['minimal_20bridge_20config_20json_18',['Create a minimal &lt;span class=&quot;tt&quot;&gt;bridge-config.json&lt;/span&gt;',['../index.html#create-a-minimal-bridge-configjson',1,'']]],
  ['minimal_20shapes_19',['Minimal shapes',['../index.html#minimal-shapes',1,'']]],
  ['minimum_20required_20compiler_20versions_20',['Minimum Required Compiler Versions',['../index.html#minimum-required-compiler-versions',1,'']]],
  ['missing_21',['Projection rows are missing',['../md_docs_2mqttstore-user-guide.html#projection-rows-are-missing',1,'']]],
  ['modern_20c_22',['JSON schema validator for JSON for Modern C++',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#json-schema-validator-for-json-for-modern-c',1,'']]],
  ['more_20complex_20hierarchy_23',['A more complex hierarchy',['../index.html#a-more-complex-hierarchy',1,'']]],
  ['mqtt_20_3a_24',['Run the integrator for this mapping (in-mqtt):',['../index.html#run-the-integrator-for-this-mapping-in-mqtt',1,'']]],
  ['mqtt_20broker_20over_20tcp_20ipv4_25',['Connect to a plain MQTT broker over TCP/IPv4',['../index.html#connect-to-a-plain-mqtt-broker-over-tcpipv4',1,'']]],
  ['mqtt_20client_20options_26',['&lt;span class=&quot;tt&quot;&gt;mqtt&lt;/span&gt; (client options)',['../index.html#mqtt-client-options',1,'']]],
  ['mqtt_20instance_27',['mqtt instance',['../index.html#disable-all-but-the-in-mqtt-instance',1,'Disable all but the &lt;span class=&quot;tt&quot;&gt;in-mqtt&lt;/span&gt; instance'],['../index.html#disable-all-but-the-in-mqtt-instance-1',1,'Disable all but the &lt;span class=&quot;tt&quot;&gt;in-mqtt&lt;/span&gt; instance']]],
  ['mqtt_20listener_20on_20tcp_20ipv4_28',['Start a plain MQTT listener on TCP/IPv4',['../index.html#start-a-plain-mqtt-listener-on-tcpipv4',1,'']]],
  ['mqtt_20mapping_20description_29',['MQTT Mapping Description',['../index.html#mqtt-mapping-description',1,'']]],
  ['mqtt_20mapping_20file_20is_20provided_30',['Embedded MQTTIntegrator (when &lt;span class=&quot;tt&quot;&gt;--mqtt-mapping-file&lt;/span&gt; is provided)',['../index.html#embedded-mqttintegrator-when---mqtt-mapping-file-is-provided',1,'']]],
  ['mqtt_20over_20tcp_20ip_31',['MQTT over TCP IP',['../index.html#mqtt-over-tcpip',1,'MQTT over TCP/IP'],['../index.html#mqtt-over-tcpip-1',1,'MQTT over TCP/IP'],['../index.html#mqtt-over-tcpip-2',1,'MQTT over TCP/IP']]],
  ['mqtt_20over_20unix_20domain_20sockets_32',['MQTT over UNIX Domain Sockets',['../index.html#mqtt-over-unix-domain-sockets',1,'MQTT over UNIX Domain Sockets'],['../index.html#mqtt-over-unix-domain-sockets-1',1,'MQTT over UNIX Domain Sockets'],['../index.html#mqtt-over-unix-domain-sockets-2',1,'MQTT over UNIX Domain Sockets']]],
  ['mqtt_20over_20unix_20domain_20websockets_33',['MQTT over UNIX Domain WebSockets',['../index.html#mqtt-over-unix-domain-websockets',1,'MQTT over UNIX Domain WebSockets'],['../index.html#mqtt-over-unix-domain-websockets-1',1,'MQTT over UNIX Domain WebSockets'],['../index.html#mqtt-over-unix-domain-websockets-2',1,'MQTT over UNIX Domain WebSockets']]],
  ['mqtt_20over_20websockets_34',['MQTT over WebSockets',['../index.html#mqtt-over-websockets',1,'MQTT over WebSockets'],['../index.html#mqtt-over-websockets-1',1,'MQTT over WebSockets'],['../index.html#mqtt-over-websockets-2',1,'MQTT over WebSockets'],['../index.html#quick-tls-checklist-for-mqtttcp-and-mqtt-over-websockets',1,'Quick TLS checklist for MQTT(TCP) and MQTT over WebSockets']]],
  ['mqtt_20tcp_20and_20mqtt_20over_20websockets_35',['Quick TLS checklist for MQTT(TCP) and MQTT over WebSockets',['../index.html#quick-tls-checklist-for-mqtttcp-and-mqtt-over-websockets',1,'']]],
  ['mqtt_20traffic_36',['6. Generate example MQTT traffic',['../md_docs_2mqttstore-user-guide.html#autotoc_md6-generate-example-mqtt-traffic',1,'']]],
  ['mqttbridge_37',['MQTTBridge',['../index.html#mqttbridge',1,'']]],
  ['mqttbroker_38',['MQTTBroker',['../index.html#connection-instances-of-default-builds-of-mqttbroker',1,'Connection instances of default builds of &lt;em&gt;MQTTBroker&lt;/em&gt;'],['../index.html#mqttbroker',1,'MQTTBroker']]],
  ['mqttcli_39',['MQTTCli',['../index.html#mqttcli',1,'']]],
  ['mqttintegrator_40',['MQTTIntegrator',['../index.html#connection-instances-of-default-builds-of-mqttintegrator',1,'Connection instances of default builds of &lt;em&gt;MQTTIntegrator&lt;/em&gt;'],['../index.html#mqttintegrator',1,'MQTTIntegrator']]],
  ['mqttintegrator_20when_20mqtt_20mapping_20file_20is_20provided_41',['Embedded MQTTIntegrator (when &lt;span class=&quot;tt&quot;&gt;--mqtt-mapping-file&lt;/span&gt; is provided)',['../index.html#embedded-mqttintegrator-when---mqtt-mapping-file-is-provided',1,'']]],
  ['mqtts_20instead_20of_20plain_20tcp_42',['(Optional) Use TLS (MQTTS) instead of plain TCP',['../index.html#optional-use-tls-mqtts-instead-of-plain-tcp',1,'']]],
  ['mqtts_20wss_20uds_20wss_43',['TLS checklist for client connections (MQTTS / WSS / UDS-WSS)',['../index.html#tls-checklist-for-client-connections-mqtts--wss--uds-wss',1,'']]],
  ['mqttstore_44',['MQTTStore',['../index.html#mqttstore',1,'']]],
  ['mqttstore_20creates_20automatically_45',['1. What MQTTStore creates automatically',['../md_docs_2mqttstore-user-guide.html#autotoc_md1-what-mqttstore-creates-automatically',1,'']]],
  ['mqttstore_20starts_20but_20no_20rows_20appear_46',['MQTTStore starts but no rows appear',['../md_docs_2mqttstore-user-guide.html#mqttstore-starts-but-no-rows-appear',1,'']]],
  ['mqttstore_20user_20guide_47',['MQTTStore User Guide',['../md_docs_2mqttstore-user-guide.html',1,'']]],
  ['mqttstore_20with_20automatic_20raw_20table_20generation_48',['4. Start MQTTStore with automatic raw-table generation',['../md_docs_2mqttstore-user-guide.html#autotoc_md4-start-mqttstore-with-automatic-raw-table-generation',1,'']]],
  ['mqttsuite_49',['MQTTSuite',['../index.html#build--install-mqttsuite',1,'Build &amp;amp; Install MQTTSuite'],['../index.html#cross-compile-mqttsuite',1,'Cross-compile MQTTSuite'],['../index.html#deploy-mqttsuite',1,'Deploy MQTTSuite'],['../index.html',1,'MQTTSuite']]],
  ['mqttsuite_20package_20definition_20and_20its_20dependencies_50',['Install the MQTTSuite package definition and its dependencies',['../index.html#install-the-mqttsuite-package-definition-and-its-dependencies',1,'']]],
  ['mqttsuites_20command_20line_20tool_51',['Quick sanity checks with MQTTSuites command line tool',['../index.html#quick-sanity-checks-with-mqttsuites-command-line-tool',1,'']]],
  ['mutual_20tls_3a_52',['Example (TCP/TLS) with mutual TLS:',['../index.html#example-tcptls-with-mutual-tls',1,'']]]
];
