var searchData=
[
  ['safety_0',['Thread-safety',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#thread-safety',1,'']]],
  ['sanity_20checks_20with_20common_20tools_1',['Quick sanity checks with common tools',['../index.html#quick-sanity-checks-with-common-tools',1,'']]],
  ['sanity_20checks_20with_20mqttsuites_20command_20line_20tool_2',['Quick sanity checks with MQTTSuites command line tool',['../index.html#quick-sanity-checks-with-mqttsuites-command-line-tool',1,'']]],
  ['save_20as_20mapping_20example_20json_3a_3',['Save as &lt;span class=&quot;tt&quot;&gt;~/mapping-example.json&lt;/span&gt;:',['../index.html#save-as-mapping-examplejson',1,'']]],
  ['saved_4',['saved',['../index.html#for-development-only-use-custom-html-templates-for-the-web-ui-after-the-configuration-has-been-saved',1,'(For development only) Use custom HTML templates for the Web UI (after the configuration has been saved)'],['../index.html#optional-embed-the-integrator--after-the-configuration-has-been-saved',1,'(Optional) Embed the integrator (after the configuration has been saved)']]],
  ['scalar_5',['&lt;span class=&quot;tt&quot;&gt;value&lt;/span&gt; mapping (template, scalar)',['../index.html#value-mapping-template-scalar',1,'']]],
  ['schema_20example_20with_20ajv_20cli_6',['Validate against the schema (example with &lt;span class=&quot;tt&quot;&gt;ajv-cli&lt;/span&gt;)',['../index.html#validate-against-the-schema-example-with-ajv-cli',1,'']]],
  ['schema_20highlights_7',['Schema Highlights',['../index.html#schema-highlights',1,'']]],
  ['schema_20validator_20for_20json_20for_20modern_20c_8',['JSON schema validator for JSON for Modern C++',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#json-schema-validator-for-json-for-modern-c',1,'']]],
  ['sdk_9',['SDK',['../index.html#choose--download-an-sdk',1,'Choose &amp;amp; download an SDK'],['../index.html#configure-the-sdk',1,'Configure the SDK']]],
  ['sdk_20to_20integrate_20the_20snode_20c_20feed_10',['Patch the SDK to integrate the SNode.C feed',['../index.html#patch-the-sdk-to-integrate-the-snodec-feed',1,'']]],
  ['sections_11',['Mapping Sections',['../index.html#mapping-sections',1,'']]],
  ['selection_20addressing_12',['&lt;span class=&quot;tt&quot;&gt;network&lt;/span&gt; (transport selection + addressing)',['../index.html#network-transport-selection--addressing',1,'']]],
  ['sentence_13',['In one sentence',['../index.html#in-one-sentence',1,'']]],
  ['separate_20installation_20required_14',['Bundled (no separate installation required)',['../index.html#bundled-no-separate-installation-required',1,'']]],
  ['session_20store_20survives_20restarts_15',['session store survives restarts',['../index.html#add-a-persistent-session-store-survives-restarts',1,'Add a persistent session store (survives restarts)'],['../index.html#add-a-persistent-session-store-survives-restarts-1',1,'Add a persistent session store (survives restarts)']]],
  ['shapes_16',['Minimal shapes',['../index.html#minimal-shapes',1,'']]],
  ['shared_20library_17',['Building as shared library',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#building-as-shared-library',1,'']]],
  ['short_18',['Building directly, finding a CMake-package. (short)',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#building-directly-finding-a-cmake-package-short',1,'']]],
  ['simple_20static_20mapping_19',['Add a concrete subscription with a simple static mapping',['../index.html#add-a-concrete-subscription-with-a-simple-static-mapping',1,'']]],
  ['skeleton_20mapping_20file_20',['Skeleton mapping file',['../index.html#skeleton-mapping-file',1,'']]],
  ['snode_20c_21',['Install SNode.C',['../index.html#install-snodec',1,'']]],
  ['snode_20c_20feed_22',['Patch the SDK to integrate the SNode.C feed',['../index.html#patch-the-sdk-to-integrate-the-snodec-feed',1,'']]],
  ['so_20you_20don’t_20repeat_20flags_23',['Persist your configuration using &lt;span class=&quot;tt&quot;&gt;-w&lt;/span&gt; (so you don’t repeat flags)',['../index.html#persist-your-configuration-using--w-so-you-dont-repeat-flags',1,'']]],
  ['sockets_24',['Sockets',['../index.html#mqtt-over-unix-domain-sockets',1,'MQTT over UNIX Domain Sockets'],['../index.html#mqtt-over-unix-domain-sockets-1',1,'MQTT over UNIX Domain Sockets'],['../index.html#mqtt-over-unix-domain-sockets-2',1,'MQTT over UNIX Domain Sockets'],['../index.html#web-interface-over-unix-domain-sockets',1,'Web Interface over UNIX Domain Sockets']]],
  ['sockets_25',['sockets',['../index.html#notes-for-unix-domain-sockets',1,'Notes for UNIX domain sockets'],['../index.html#unix-domain-sockets',1,'UNIX domain sockets']]],
  ['source_26',['Build out-of-source',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#build-out-of-source',1,'']]],
  ['specifics_27',['WebSockets specifics',['../index.html#websockets-specifics',1,'']]],
  ['specifics_20that_20often_20trip_20clients_28',['specifics that often trip clients',['../index.html#websockets-specifics-that-often-trip-clients',1,'WebSockets specifics that often trip clients'],['../index.html#websockets-specifics-that-often-trip-clients-1',1,'WebSockets specifics that often trip clients']]],
  ['start_20a_20plain_20mqtt_20listener_20on_20tcp_20ipv4_29',['Start a plain MQTT listener on TCP/IPv4',['../index.html#start-a-plain-mqtt-listener-on-tcpipv4',1,'']]],
  ['start_20recommended_20flow_30',['Start Recommended Flow',['../index.html#quick-start-recommended-flow',1,'Quick Start (Recommended Flow)'],['../index.html#quick-start-recommended-flow-1',1,'Quick Start (Recommended Flow)'],['../index.html#quick-start-recommended-flow-2',1,'Quick Start (Recommended Flow)'],['../index.html#quick-start-recommended-flow-3',1,'Quick Start (Recommended Flow)'],['../index.html#quick-start-recommended-flow-4',1,'Quick Start (Recommended Flow)']]],
  ['static_20mapping_31',['static mapping',['../index.html#static-mapping',1,'&lt;span class=&quot;tt&quot;&gt;static&lt;/span&gt; mapping'],['../index.html#add-a-concrete-subscription-with-a-simple-static-mapping',1,'Add a concrete subscription with a simple static mapping']]],
  ['store_20survives_20restarts_32',['store survives restarts',['../index.html#add-a-persistent-session-store-survives-restarts',1,'Add a persistent session store (survives restarts)'],['../index.html#add-a-persistent-session-store-survives-restarts-1',1,'Add a persistent session store (survives restarts)']]],
  ['structure_33',['Structure',['../index.html#command-structure',1,'Command Structure'],['../index.html#top-level-structure',1,'Top-Level Structure']]],
  ['structure_20at_20a_20glance_34',['Overall Structure (at a glance)',['../index.html#overall-structure-at-a-glance',1,'']]],
  ['style_20systems_20x86_2064_20arm_35',['Installation on Debian-Style Systems (x86-64, ARM)',['../index.html#installation-on-debian-style-systems-x86-64-arm',1,'']]],
  ['subdirectory_20from_20within_20another_20project_36',['Building as a CMake-subdirectory from within another project',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#building-as-a-cmake-subdirectory-from-within-another-project',1,'']]],
  ['subscription_20with_20a_20simple_20static_20mapping_37',['Add a concrete subscription with a simple static mapping',['../index.html#add-a-concrete-subscription-with-a-simple-static-mapping',1,'']]],
  ['subscriptions_20for_20a_20broker_38',['&lt;span class=&quot;tt&quot;&gt;topics&lt;/span&gt; (subscriptions for a broker)',['../index.html#topics-subscriptions-for-a-broker',1,'']]],
  ['subscriptions_20translation_20rules_39',['Subscriptions &amp;amp; Translation Rules',['../index.html#subscriptions--translation-rules',1,'']]],
  ['summary_40',['&lt;span class=&quot;tt&quot;&gt;connection&lt;/span&gt; options (summary)',['../index.html#connection-options-summary',1,'']]],
  ['supported_20systems_20hardware_41',['Supported Systems &amp;amp; Hardware',['../index.html#supported-systems--hardware',1,'']]],
  ['supported_20transports_42',['Supported Transports',['../index.html#supported-transports',1,'Supported Transports'],['../index.html#supported-transports-1',1,'Supported Transports'],['../index.html#supported-transports-2',1,'Supported Transports']]],
  ['survives_20restarts_43',['survives restarts',['../index.html#add-a-persistent-session-store-survives-restarts',1,'Add a persistent session store (survives restarts)'],['../index.html#add-a-persistent-session-store-survives-restarts-1',1,'Add a persistent session store (survives restarts)']]],
  ['switch_20to_20a_20template_20mapping_20when_20you_20need_20logic_44',['Switch to a template mapping when you need logic',['../index.html#switch-to-a-template-mapping-when-you-need-logic',1,'']]],
  ['system_20packages_45',['Install system packages',['../index.html#install-system-packages',1,'']]],
  ['systems_20hardware_46',['Supported Systems &amp;amp; Hardware',['../index.html#supported-systems--hardware',1,'']]],
  ['systems_20x86_2064_20arm_47',['Installation on Debian-Style Systems (x86-64, ARM)',['../index.html#installation-on-debian-style-systems-x86-64-arm',1,'']]]
];
