var searchData=
[
  ['w_0',['Persist your configuration using &lt;span class=&quot;tt&quot;&gt;-w&lt;/span&gt;',['../index.html#persist-your-configuration-using--w',1,'']]],
  ['w_20so_20you_20don’t_20repeat_20flags_1',['Persist your configuration using &lt;span class=&quot;tt&quot;&gt;-w&lt;/span&gt; (so you don’t repeat flags)',['../index.html#persist-your-configuration-using--w-so-you-dont-repeat-flags',1,'']]],
  ['weaknesses_2',['Weaknesses',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#weaknesses',1,'']]],
  ['web_20interface_3',['Web Interface',['../index.html#web-interface',1,'']]],
  ['web_20interface_20http_4',['Enable the Web Interface (HTTP)',['../index.html#enable-the-web-interface-http',1,'']]],
  ['web_20interface_20over_20tcp_20ip_5',['Web Interface over TCP/IP',['../index.html#web-interface-over-tcpip',1,'']]],
  ['web_20interface_20over_20unix_20domain_20sockets_6',['Web Interface over UNIX Domain Sockets',['../index.html#web-interface-over-unix-domain-sockets',1,'']]],
  ['web_20ui_20after_20the_20configuration_20has_20been_20saved_7',['(For development only) Use custom HTML templates for the Web UI (after the configuration has been saved)',['../index.html#for-development-only-use-custom-html-templates-for-the-web-ui-after-the-configuration-has-been-saved',1,'']]],
  ['websockets_8',['WebSockets',['../index.html#optional-use-unix-domain-websockets',1,'(Optional) Use Unix Domain WebSockets'],['../index.html#mqtt-over-unix-domain-websockets',1,'MQTT over UNIX Domain WebSockets'],['../index.html#mqtt-over-unix-domain-websockets-1',1,'MQTT over UNIX Domain WebSockets'],['../index.html#mqtt-over-unix-domain-websockets-2',1,'MQTT over UNIX Domain WebSockets'],['../index.html#mqtt-over-websockets',1,'MQTT over WebSockets'],['../index.html#mqtt-over-websockets-1',1,'MQTT over WebSockets'],['../index.html#mqtt-over-websockets-2',1,'MQTT over WebSockets'],['../index.html#quick-tls-checklist-for-mqtttcp-and-mqtt-over-websockets',1,'Quick TLS checklist for MQTT(TCP) and MQTT over WebSockets']]],
  ['websockets_20specifics_9',['WebSockets specifics',['../index.html#websockets-specifics',1,'']]],
  ['websockets_20specifics_20that_20often_20trip_20clients_10',['WebSockets specifics that often trip clients',['../index.html#websockets-specifics-that-often-trip-clients',1,'WebSockets specifics that often trip clients'],['../index.html#websockets-specifics-that-often-trip-clients-1',1,'WebSockets specifics that often trip clients']]],
  ['websockets_20tls_20_3a_11',['WebSockets TLS :',['../index.html#example-websocketstls',1,'Example (WebSockets/TLS):'],['../index.html#example-websocketstls-1',1,'Example (WebSockets/TLS):']]],
  ['websockets_20tls_20layered_20on_20the_20ws_20endpoint_20_3a_12',['Example (Unix Domain WebSockets, TLS layered on the WS endpoint):',['../index.html#example-unix-domain-websockets-tls-layered-on-the-ws-endpoint',1,'']]],
  ['websockets_20wss_13',['(Optional) Use WebSockets (WSS)',['../index.html#optional-use-websockets-wss',1,'']]],
  ['well_20in_20production_14',['well in production',['../index.html#why-this-layout-works-well-in-production',1,'Why this layout works well in production'],['../index.html#why-this-layout-works-well-in-production-1',1,'Why this layout works well in production']]],
  ['what_20is_20it_15',['What is it?',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#what-is-it',1,'']]],
  ['when_20mqtt_20mapping_20file_20is_20provided_16',['Embedded MQTTIntegrator (when &lt;span class=&quot;tt&quot;&gt;--mqtt-mapping-file&lt;/span&gt; is provided)',['../index.html#embedded-mqttintegrator-when---mqtt-mapping-file-is-provided',1,'']]],
  ['when_20you_20need_20logic_17',['Switch to a template mapping when you need logic',['../index.html#switch-to-a-template-mapping-when-you-need-logic',1,'']]],
  ['why_20this_20layout_20works_20well_20in_20production_18',['Why this layout works well in production',['../index.html#why-this-layout-works-well-in-production',1,'Why this layout works well in production'],['../index.html#why-this-layout-works-well-in-production-1',1,'Why this layout works well in production']]],
  ['wildcard_20examples_19',['Wildcard examples',['../index.html#wildcard-examples',1,'']]],
  ['with_20a_20simple_20static_20mapping_20',['Add a concrete subscription with a simple static mapping',['../index.html#add-a-concrete-subscription-with-a-simple-static-mapping',1,'']]],
  ['with_20ajv_20cli_21',['Validate against the schema (example with &lt;span class=&quot;tt&quot;&gt;ajv-cli&lt;/span&gt;)',['../index.html#validate-against-the-schema-example-with-ajv-cli',1,'']]],
  ['with_20common_20tools_22',['Quick sanity checks with common tools',['../index.html#quick-sanity-checks-with-common-tools',1,'']]],
  ['with_20hunter_20package_20manager_23',['Building with Hunter package manager',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#building-with-hunter-package-manager',1,'']]],
  ['with_20mqttsuites_20command_20line_20tool_24',['Quick sanity checks with MQTTSuites command line tool',['../index.html#quick-sanity-checks-with-mqttsuites-command-line-tool',1,'']]],
  ['with_20mutual_20tls_3a_25',['Example (TCP/TLS) with mutual TLS:',['../index.html#example-tcptls-with-mutual-tls',1,'']]],
  ['with_20the_20mapping_20description_26',['Behavior aligned with the Mapping Description',['../index.html#behavior-aligned-with-the-mapping-description',1,'']]],
  ['with_20your_20mapping_27',['Run the integrator with your mapping',['../index.html#run-the-integrator-with-your-mapping',1,'']]],
  ['within_20another_20project_28',['Building as a CMake-subdirectory from within another project',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#building-as-a-cmake-subdirectory-from-within-another-project',1,'']]],
  ['workflow_20recommended_29',['Persist-once workflow (recommended)',['../index.html#persist-once-workflow-recommended',1,'']]],
  ['works_20well_20in_20production_30',['works well in production',['../index.html#why-this-layout-works-well-in-production',1,'Why this layout works well in production'],['../index.html#why-this-layout-works-well-in-production-1',1,'Why this layout works well in production']]],
  ['ws_20endpoint_20_3a_31',['Example (Unix Domain WebSockets, TLS layered on the WS endpoint):',['../index.html#example-unix-domain-websockets-tls-layered-on-the-ws-endpoint',1,'']]],
  ['wss_32',['WSS',['../index.html#optional-use-websockets-wss',1,'(Optional) Use WebSockets (WSS)'],['../index.html#tls-checklist-for-client-connections-mqtts--wss--uds-wss',1,'TLS checklist for client connections (MQTTS / WSS / UDS-WSS)']]],
  ['wss_20uds_20wss_33',['TLS checklist for client connections (MQTTS / WSS / UDS-WSS)',['../index.html#tls-checklist-for-client-connections-mqtts--wss--uds-wss',1,'']]]
];
