var searchData=
[
  ['in_20bridges_0',['&lt;span class=&quot;tt&quot;&gt;bridge&lt;/span&gt; (each item in &lt;span class=&quot;tt&quot;&gt;bridges&lt;/span&gt;)',['../index.html#bridge-each-item-in-bridges',1,'']]],
  ['in_20brokers_1',['&lt;span class=&quot;tt&quot;&gt;broker&lt;/span&gt; (each item in &lt;span class=&quot;tt&quot;&gt;brokers&lt;/span&gt;)',['../index.html#broker-each-item-in-brokers',1,'']]],
  ['in_20detail_2',['Elements in Detail',['../index.html#elements-in-detail',1,'']]],
  ['in_20mqtt_20_3a_3',['Run the integrator for this mapping (in-mqtt):',['../index.html#run-the-integrator-for-this-mapping-in-mqtt',1,'']]],
  ['in_20mqtt_20instance_4',['in mqtt instance',['../index.html#disable-all-but-the-in-mqtt-instance',1,'Disable all but the &lt;span class=&quot;tt&quot;&gt;in-mqtt&lt;/span&gt; instance'],['../index.html#disable-all-but-the-in-mqtt-instance-1',1,'Disable all but the &lt;span class=&quot;tt&quot;&gt;in-mqtt&lt;/span&gt; instance']]],
  ['in_20one_20sentence_5',['In one sentence',['../index.html#in-one-sentence',1,'']]],
  ['in_20production_6',['in production',['../index.html#why-this-layout-works-well-in-production',1,'Why this layout works well in production'],['../index.html#why-this-layout-works-well-in-production-1',1,'Why this layout works well in production']]],
  ['in_20version_202_7',['New in version 2',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#new-in-version-2',1,'']]],
  ['input_8',['Example input',['../index.html#example-input',1,'']]],
  ['install_9',['Install',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#install',1,'']]],
  ['install_20mqttsuite_10',['Build &amp;amp; Install MQTTSuite',['../index.html#build--install-mqttsuite',1,'']]],
  ['install_20snode_20c_11',['Install SNode.C',['../index.html#install-snodec',1,'']]],
  ['install_20system_20packages_12',['Install system packages',['../index.html#install-system-packages',1,'']]],
  ['install_20the_20mqttsuite_20package_20definition_20and_20its_20dependencies_13',['Install the MQTTSuite package definition and its dependencies',['../index.html#install-the-mqttsuite-package-definition-and-its-dependencies',1,'']]],
  ['install_20tips_14',['Post-Install Tips',['../index.html#post-install-tips',1,'']]],
  ['installation_15',['Installation',['../index.html#installation',1,'']]],
  ['installation_20on_20debian_20style_20systems_20x86_2064_20arm_16',['Installation on Debian-Style Systems (x86-64, ARM)',['../index.html#installation-on-debian-style-systems-x86-64-arm',1,'']]],
  ['installation_20required_17',['Bundled (no separate installation required)',['../index.html#bundled-no-separate-installation-required',1,'']]],
  ['instance_18',['instance',['../index.html#disable-all-but-the-in-mqtt-instance',1,'Disable all but the &lt;span class=&quot;tt&quot;&gt;in-mqtt&lt;/span&gt; instance'],['../index.html#disable-all-but-the-in-mqtt-instance-1',1,'Disable all but the &lt;span class=&quot;tt&quot;&gt;in-mqtt&lt;/span&gt; instance']]],
  ['instances_20of_20default_20builds_20of_20mqttbroker_19',['Connection instances of default builds of &lt;em&gt;MQTTBroker&lt;/em&gt;',['../index.html#connection-instances-of-default-builds-of-mqttbroker',1,'']]],
  ['instances_20of_20default_20builds_20of_20mqttintegrator_20',['Connection instances of default builds of &lt;em&gt;MQTTIntegrator&lt;/em&gt;',['../index.html#connection-instances-of-default-builds-of-mqttintegrator',1,'']]],
  ['instead_20of_20plain_20tcp_21',['(Optional) Use TLS (MQTTS) instead of plain TCP',['../index.html#optional-use-tls-mqtts-instead-of-plain-tcp',1,'']]],
  ['integrate_20the_20snode_20c_20feed_22',['Patch the SDK to integrate the SNode.C feed',['../index.html#patch-the-sdk-to-integrate-the-snodec-feed',1,'']]],
  ['integration_23',['nlohmann-json integration',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#nlohmann-json-integration',1,'']]],
  ['integrator_20after_20the_20configuration_20has_20been_20saved_24',['(Optional) Embed the integrator (after the configuration has been saved)',['../index.html#optional-embed-the-integrator--after-the-configuration-has-been-saved',1,'']]],
  ['integrator_20for_20this_20mapping_20in_20mqtt_20_3a_25',['Run the integrator for this mapping (in-mqtt):',['../index.html#run-the-integrator-for-this-mapping-in-mqtt',1,'']]],
  ['integrator_20with_20your_20mapping_26',['Run the integrator with your mapping',['../index.html#run-the-integrator-with-your-mapping',1,'']]],
  ['interface_27',['Web Interface',['../index.html#web-interface',1,'']]],
  ['interface_20http_28',['Enable the Web Interface (HTTP)',['../index.html#enable-the-web-interface-http',1,'']]],
  ['interface_20over_20tcp_20ip_29',['Web Interface over TCP/IP',['../index.html#web-interface-over-tcpip',1,'']]],
  ['interface_20over_20unix_20domain_20sockets_30',['Web Interface over UNIX Domain Sockets',['../index.html#web-interface-over-unix-domain-sockets',1,'']]],
  ['ip_31',['IP',['../index.html#mqtt-over-tcpip',1,'MQTT over TCP/IP'],['../index.html#mqtt-over-tcpip-1',1,'MQTT over TCP/IP'],['../index.html#mqtt-over-tcpip-2',1,'MQTT over TCP/IP'],['../index.html#web-interface-over-tcpip',1,'Web Interface over TCP/IP']]],
  ['ipv4_32',['IPv4',['../index.html#connect-to-a-plain-mqtt-broker-over-tcpipv4',1,'Connect to a plain MQTT broker over TCP/IPv4'],['../index.html#start-a-plain-mqtt-listener-on-tcpipv4',1,'Start a plain MQTT listener on TCP/IPv4']]],
  ['is_20it_33',['What is it?',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#what-is-it',1,'']]],
  ['is_20provided_34',['Embedded MQTTIntegrator (when &lt;span class=&quot;tt&quot;&gt;--mqtt-mapping-file&lt;/span&gt; is provided)',['../index.html#embedded-mqttintegrator-when---mqtt-mapping-file-is-provided',1,'']]],
  ['it_35',['What is it?',['../dir_bafb6a82dc8bfc8310328cc4c5d47780.html#what-is-it',1,'']]],
  ['item_20in_20bridges_36',['&lt;span class=&quot;tt&quot;&gt;bridge&lt;/span&gt; (each item in &lt;span class=&quot;tt&quot;&gt;bridges&lt;/span&gt;)',['../index.html#bridge-each-item-in-bridges',1,'']]],
  ['item_20in_20brokers_37',['&lt;span class=&quot;tt&quot;&gt;broker&lt;/span&gt; (each item in &lt;span class=&quot;tt&quot;&gt;brokers&lt;/span&gt;)',['../index.html#broker-each-item-in-brokers',1,'']]],
  ['its_20dependencies_38',['Install the MQTTSuite package definition and its dependencies',['../index.html#install-the-mqttsuite-package-definition-and-its-dependencies',1,'']]]
];
