MQTTSuite: mqtt::bridge::lib::Broker Class Reference
mqtt::bridge::lib::Broker Class Reference
#include <Broker.h>
Public Member Functions
Broker (Bridge &bridge, const std::string &sessionStoreFileName, std::string &&clientId, uint16_t keepAlive, bool cleanSession, std::string &&willTopic, std::string &&willMessage, uint8_t willQoS, bool willRetain, std::string &&username, std::string &&password, bool loopPrevention, std::string &&instanceName, std::string &&protocol, std::string &&encryption, std::string &&transport, std::list< iot::mqtt::Topic > &&topics)
Broker (const Broker &)=delete
Broker (Broker &&)=default
Bridge & getBridge () const
const std::string & getSessionStoreFileName () const
const std::string & getClientId () const
uint16_t getKeepAlive () const
bool getCleanSession () const
const std::string & getWillTopic () const
const std::string & getWillMessage () const
uint8_t getWillQoS () const
bool getWillRetain () const
const std::string & getUsername () const
const std::string & getPassword () const
bool getLoopPrevention () const
const std::string & getInstanceName () const
const std::string & getProtocol () const
const std::string & getEncryption () const
const std::string & getTransport () const
const std::list< iot::mqtt::Topic > & getTopics () const
Private Attributes
Bridge & bridge
std::string sessionStoreFileName
std::string clientId
uint16_t keepAlive
bool cleanSession
std::string willTopic
std::string willMessage
uint8_t willQoS
bool willRetain
std::string username
std::string password
bool loopPrevention
std::string instanceName
std::string protocol
std::string encryption
std::string transport
std::list< iot::mqtt::Topic > topics
Detailed Description
Definition at line 60 of file Broker.h.
Constructor & Destructor Documentation
Broker() [1/3]
mqtt::bridge::lib::Broker::Broker (Bridge & bridge, const std::string & sessionStoreFileName, std::string && clientId, uint16_t keepAlive, bool cleanSession, std::string && willTopic, std::string && willMessage, uint8_t willQoS, bool willRetain, std::string && username, std::string && password, bool loopPrevention, std::string && instanceName, std::string && protocol, std::string && encryption, std::string && transport, std::list< iot::mqtt::Topic > && topics)
Definition at line 52 of file Broker.cpp.
        : bridge(bridge)
        , sessionStoreFileName(sessionStoreFileName)
        , clientId(clientId)
        , keepAlive(keepAlive)
        , cleanSession(cleanSession)
        , willTopic(willTopic)
        , willMessage(willMessage)
        , willQoS(willQoS)
        , willRetain(willRetain)
        , username(userName)
        , password(passWord)
        , loopPrevention(loopPrevention)
        , instanceName(std::move(instanceName))
        , protocol(std::move(protocol))
        , encryption(std::move(encryption))
        , transport(std::move(transport))
        , topics(std::move(topics)) {
    }
References bridge, cleanSession, clientId, encryption, instanceName, keepAlive, loopPrevention, password, protocol, sessionStoreFileName, topics, transport, username, willMessage, willQoS, willRetain, and willTopic.
Broker() [2/3]
mqtt::bridge::lib::Broker::Broker (const Broker &) delete
Broker() [3/3]
mqtt::bridge::lib::Broker::Broker (Broker &&) default
Member Function Documentation
getBridge()
Bridge & mqtt::bridge::lib::Broker::getBridge () const
Definition at line 88 of file Broker.cpp.
{
        return bridge;
    }
References bridge.
Referenced by main(), mqtt::bridge::lib::Mqtt::onConnack(), mqtt::bridge::lib::Mqtt::onDisconnected(), and mqtt::bridge::lib::Mqtt::onPublish().
getCleanSession()
bool mqtt::bridge::lib::Broker::getCleanSession () const
Definition at line 104 of file Broker.cpp.
{
        return cleanSession;
    }
References cleanSession.
Referenced by mqtt::bridge::lib::Mqtt::Mqtt(), and mqtt::bridge::lib::Mqtt::onConnected().
getClientId()
const std::string & mqtt::bridge::lib::Broker::getClientId () const
Definition at line 96 of file Broker.cpp.
{
        return clientId;
    }
References clientId.
Referenced by main(), mqtt::bridge::lib::Mqtt::Mqtt(), and mqtt::bridge::lib::Mqtt::onConnected().
getEncryption()
const std::string & mqtt::bridge::lib::Broker::getEncryption () const
Definition at line 144 of file Broker.cpp.
{
        return encryption;
    }
References encryption.
Referenced by main().
getInstanceName()
const std::string & mqtt::bridge::lib::Broker::getInstanceName () const
Definition at line 136 of file Broker.cpp.
{
        return instanceName;
    }
References instanceName.
getKeepAlive()
uint16_t mqtt::bridge::lib::Broker::getKeepAlive () const
Definition at line 100 of file Broker.cpp.
{
        return keepAlive;
    }
References keepAlive.
Referenced by mqtt::bridge::lib::Mqtt::Mqtt(), and mqtt::bridge::lib::Mqtt::onConnected().
getLoopPrevention()
bool mqtt::bridge::lib::Broker::getLoopPrevention () const
Definition at line 132 of file Broker.cpp.
{
        return loopPrevention;
    }
References loopPrevention.
Referenced by mqtt::bridge::lib::Mqtt::Mqtt(), and mqtt::bridge::lib::Mqtt::onConnected().
getPassword()
const std::string & mqtt::bridge::lib::Broker::getPassword () const
Definition at line 128 of file Broker.cpp.
{
        return password;
    }
References password.
Referenced by mqtt::bridge::lib::Mqtt::Mqtt(), and mqtt::bridge::lib::Mqtt::onConnected().
getProtocol()
const std::string & mqtt::bridge::lib::Broker::getProtocol () const
Definition at line 140 of file Broker.cpp.
{
        return protocol;
    }
References protocol.
Referenced by main().
getSessionStoreFileName()
const std::string & mqtt::bridge::lib::Broker::getSessionStoreFileName () const
Definition at line 92 of file Broker.cpp.
{
        return sessionStoreFileName;
    }
References sessionStoreFileName.
Referenced by mqtt::bridge::lib::Mqtt::Mqtt().
getTopics()
const std::list< iot::mqtt::Topic > & mqtt::bridge::lib::Broker::getTopics () const
Definition at line 152 of file Broker.cpp.
{
        return topics;
    }
References topics.
Referenced by main(), and mqtt::bridge::lib::Mqtt::onConnack().
getTransport()
const std::string & mqtt::bridge::lib::Broker::getTransport () const
Definition at line 148 of file Broker.cpp.
{
        return transport;
    }
References transport.
Referenced by main().
getUsername()
const std::string & mqtt::bridge::lib::Broker::getUsername () const
Definition at line 124 of file Broker.cpp.
{
        return username;
    }
References username.
Referenced by mqtt::bridge::lib::Mqtt::Mqtt(), and mqtt::bridge::lib::Mqtt::onConnected().
getWillMessage()
const std::string & mqtt::bridge::lib::Broker::getWillMessage () const
Definition at line 112 of file Broker.cpp.
{
        return willMessage;
    }
References willMessage.
Referenced by mqtt::bridge::lib::Mqtt::Mqtt(), and mqtt::bridge::lib::Mqtt::onConnected().
getWillQoS()
uint8_t mqtt::bridge::lib::Broker::getWillQoS () const
Definition at line 116 of file Broker.cpp.
{
        return willQoS;
    }
References willQoS.
Referenced by mqtt::bridge::lib::Mqtt::Mqtt(), and mqtt::bridge::lib::Mqtt::onConnected().
getWillRetain()
bool mqtt::bridge::lib::Broker::getWillRetain () const
Definition at line 120 of file Broker.cpp.
{
        return willRetain;
    }
References willRetain.
Referenced by mqtt::bridge::lib::Mqtt::Mqtt(), and mqtt::bridge::lib::Mqtt::onConnected().
getWillTopic()
const std::string & mqtt::bridge::lib::Broker::getWillTopic () const
Definition at line 108 of file Broker.cpp.
{
        return willTopic;
    }
References willTopic.
Referenced by mqtt::bridge::lib::Mqtt::Mqtt(), and mqtt::bridge::lib::Mqtt::onConnected().
Member Data Documentation
bridge
Bridge& mqtt::bridge::lib::Broker::bridge private
Definition at line 106 of file Broker.h.
Referenced by Broker(), and getBridge().
cleanSession
bool mqtt::bridge::lib::Broker::cleanSession private
Definition at line 111 of file Broker.h.
Referenced by Broker(), and getCleanSession().
clientId
std::string mqtt::bridge::lib::Broker::clientId private
Definition at line 109 of file Broker.h.
Referenced by Broker(), and getClientId().
encryption
std::string mqtt::bridge::lib::Broker::encryption private
Definition at line 122 of file Broker.h.
Referenced by Broker(), and getEncryption().
instanceName
std::string mqtt::bridge::lib::Broker::instanceName private
Definition at line 120 of file Broker.h.
Referenced by Broker(), and getInstanceName().
keepAlive
uint16_t mqtt::bridge::lib::Broker::keepAlive private
Definition at line 110 of file Broker.h.
Referenced by Broker(), and getKeepAlive().
loopPrevention
bool mqtt::bridge::lib::Broker::loopPrevention private
Definition at line 118 of file Broker.h.
Referenced by Broker(), and getLoopPrevention().
password
std::string mqtt::bridge::lib::Broker::password private
Definition at line 117 of file Broker.h.
Referenced by Broker(), and getPassword().
protocol
std::string mqtt::bridge::lib::Broker::protocol private
Definition at line 121 of file Broker.h.
Referenced by Broker(), and getProtocol().
sessionStoreFileName
std::string mqtt::bridge::lib::Broker::sessionStoreFileName private
Definition at line 107 of file Broker.h.
Referenced by Broker(), and getSessionStoreFileName().
topics
std::list<iot::mqtt::Topic> mqtt::bridge::lib::Broker::topics private
Definition at line 124 of file Broker.h.
Referenced by Broker(), and getTopics().
transport
std::string mqtt::bridge::lib::Broker::transport private
Definition at line 123 of file Broker.h.
Referenced by Broker(), and getTransport().
username
std::string mqtt::bridge::lib::Broker::username private
Definition at line 116 of file Broker.h.
Referenced by Broker(), and getUsername().
willMessage
std::string mqtt::bridge::lib::Broker::willMessage private
Definition at line 113 of file Broker.h.
Referenced by Broker(), and getWillMessage().
willQoS
uint8_t mqtt::bridge::lib::Broker::willQoS private
Definition at line 114 of file Broker.h.
Referenced by Broker(), and getWillQoS().
willRetain
bool mqtt::bridge::lib::Broker::willRetain private
Definition at line 115 of file Broker.h.
Referenced by Broker(), and getWillRetain().
willTopic
std::string mqtt::bridge::lib::Broker::willTopic private
Definition at line 112 of file Broker.h.
Referenced by Broker(), and getWillTopic().
The documentation for this class was generated from the following files:
mqttbridge/lib/Broker.h
mqttbridge/lib/Broker.cpp