MQTTSuite: mqtt::mqttbridge::websocket::SubProtocolFactory Class Reference
mqtt::mqttbridge::websocket::SubProtocolFactory Class Reference
#include <SubProtocolFactory.h>
Public Member Functions
SubProtocolFactory ()
Private Member Functions
iot::mqtt::client::SubProtocol * create (web::websocket::SubProtocolContext *subProtocolContext) override
Detailed Description
Definition at line 54 of file SubProtocolFactory.h.
Constructor & Destructor Documentation
SubProtocolFactory()
mqtt::mqttbridge::websocket::SubProtocolFactory::SubProtocolFactory () explicit
Definition at line 62 of file SubProtocolFactory.cpp.
        : web::websocket::SubProtocolFactory<iot::mqtt::client::SubProtocol>::SubProtocolFactory(NAME) {
    }
References SubProtocolFactory().
Referenced by mqttClientSubProtocolFactory(), and SubProtocolFactory().
Member Function Documentation
create()
iot::mqtt::client::SubProtocol * mqtt::mqttbridge::websocket::SubProtocolFactory::create (web::websocket::SubProtocolContext * subProtocolContext) override private
Definition at line 66 of file SubProtocolFactory.cpp.
{
        iot::mqtt::client::SubProtocol* subProtocol = nullptr;
        const mqtt::bridge::lib::Broker& broker =
            mqtt::bridge::lib::BridgeStore::instance().getBroker(subProtocolContext->getSocketConnection()->getInstanceName());
        VLOG(1) << "  Creating Broker instance '" << broker.getInstanceName() << "' of Bridge '" << broker.getBridge().getName() << "'";
        VLOG(1) << "    Bridge client id : " << broker.getClientId();
        VLOG(1) << "    Transport: " << broker.getTransport();
        VLOG(1) << "    Protocol: " << broker.getProtocol();
        VLOG(1) << "    Encryption: " << broker.getEncryption();
        VLOG(1) << "    Topics:";
        const std::list<iot::mqtt::Topic>& topics = broker.getTopics();
        for (const iot::mqtt::Topic& topic : topics) {
            VLOG(1) << "      " << static_cast<uint16_t>(topic.getQoS()) << ":" << topic.getName();
        }
        if (!topics.empty()) {
            subProtocol = new iot::mqtt::client::SubProtocol(
                subProtocolContext,
                getName(),
                new mqtt::bridge::lib::Mqtt(subProtocolContext->getSocketConnection()->getConnectionName(), broker));
        }
        return subProtocol;
    }
References mqtt::bridge::lib::Broker::getBridge(), mqtt::bridge::lib::BridgeStore::getBroker(), mqtt::bridge::lib::Broker::getClientId(), mqtt::bridge::lib::Broker::getEncryption(), mqtt::bridge::lib::Broker::getInstanceName(), mqtt::bridge::lib::Bridge::getName(), mqtt::bridge::lib::Broker::getProtocol(), mqtt::bridge::lib::Broker::getTransport(), and mqtt::bridge::lib::BridgeStore::instance().
The documentation for this class was generated from the following files:
mqttbridge/websocket/SubProtocolFactory.h
mqttbridge/websocket/SubProtocolFactory.cpp