MQTTSuite: mqtt::bridge::SocketContextFactory Class Reference
mqtt::bridge::SocketContextFactory Class Reference
#include <SocketContextFactory.h>
Public Member Functions
core::socket::stream::SocketContext * create (core::socket::stream::SocketConnection *socketConnection) final
Detailed Description
Definition at line 53 of file SocketContextFactory.h.
Member Function Documentation
create()
core::socket::stream::SocketContext * mqtt::bridge::SocketContextFactory::create (core::socket::stream::SocketConnection * socketConnection) final
Definition at line 60 of file SocketContextFactory.cpp.
{
        iot::mqtt::SocketContext* socketContext = nullptr;
        mqtt::bridge::lib::Broker* broker = mqtt::bridge::lib::BridgeStore::instance().getBroker(socketConnection->getInstanceName());
        if (broker != nullptr) {
            VLOG(1) << "  Creating Broker instance '" << broker->getName() << "' of Bridge '" << broker->getBridge().getName() << "'";
            VLOG(1) << "    Bridge client id : " << broker->getClientId();
            VLOG(1) << "    Transport: " << broker->getTransport();
            VLOG(1) << "    Protocol: " << broker->getProtocol();
            VLOG(1) << "    Encryption: " << broker->getEncryption();
            VLOG(1) << "    Topics:";
            const std::list<iot::mqtt::Topic>& topics = broker->getTopics();
            for (const iot::mqtt::Topic& topic : topics) {
                VLOG(1) << "      " << static_cast<uint16_t>(topic.getQoS()) << ":" << topic.getName();
            }
            socketContext =
                new iot::mqtt::SocketContext(socketConnection, new mqtt::bridge::lib::Mqtt(socketConnection->getConnectionName(), *broker));
        }
        return socketContext;
    }
References mqtt::bridge::lib::Broker::getBridge(), mqtt::bridge::lib::BridgeStore::getBroker(), mqtt::bridge::lib::Broker::getClientId(), mqtt::bridge::lib::Broker::getEncryption(), mqtt::bridge::lib::Bridge::getName(), mqtt::bridge::lib::Broker::getName(), mqtt::bridge::lib::Broker::getProtocol(), mqtt::bridge::lib::Broker::getTopics(), mqtt::bridge::lib::Broker::getTransport(), mqtt::bridge::lib::BridgeStore::instance(), and mqtt::bridge::lib::Mqtt::Mqtt().
The documentation for this class was generated from the following files:
mqttbridge/SocketContextFactory.h
mqttbridge/SocketContextFactory.cpp