MQTTSuite: anonymous_namespace{json-validator.cpp}::string Class Reference
anonymous_namespace{json-validator.cpp}::string Class Reference
Public Member Functions
string (json &sch, root_schema *root)
string (json &sch, root_schema *root)
Public Member Functions inherited from anonymous_namespace{json-validator.cpp}::schema
virtual ~schema ()=default
schema (root_schema *root)
virtual const json & default_value (const json::json_pointer &, const json &, error_handler &) const
void set_default_value (const json &v)
virtual ~schema ()=default
schema (root_schema *root)
virtual const json & default_value (const json::json_pointer &, const json &, error_handler &) const
void set_default_value (const json &v)
Private Member Functions
std::size_t utf8_length (const std::string &s) const
void validate (const json::json_pointer &ptr, const json &instance, json_patch &, error_handler &e) const override
std::size_t utf8_length (const std::string &s) const
void validate (const json::json_pointer &ptr, const json &instance, json_patch &, error_handler &e) const override
Private Attributes
std::pair< bool, size_t > maxLength_ {false, 0}
std::pair< bool, size_t > minLength_ {false, 0}
std::pair< bool, std ::regex > pattern_ {false, std ::regex()}
std::string patternString_
std::pair< bool, std::string > format_
std::tuple< bool, std::string, std::string > content_ {false, "", ""}
Additional Inherited Members
Static Public Member Functions inherited from anonymous_namespace{json-validator.cpp}::schema
static std::shared_ptr< schema > make (json &schema, root_schema *root, const std::vector< std::string > &key, std::vector< nlohmann::json_uri > uris)
static std::shared_ptr< schema > make (json &schema, root_schema *root, const std::vector< std::string > &key, std::vector< nlohmann::json_uri > uris)
Protected Member Functions inherited from anonymous_namespace{json-validator.cpp}::schema
virtual std::shared_ptr< schema > make_for_default_ (std::shared_ptr<::schema > &, root_schema *, std::vector< nlohmann::json_uri > &, nlohmann::json &) const
virtual std::shared_ptr< schema > make_for_default_ (std::shared_ptr<::schema > &, root_schema *, std::vector< nlohmann::json_uri > &, nlohmann::json &) const
Protected Attributes inherited from anonymous_namespace{json-validator.cpp}::schema
root_schema * root_
json default_value_ = nullptr
Detailed Description
Definition at line 704 of file json-validator.cpp.
Constructor & Destructor Documentation
string() [1/2]
anonymous_namespace{json-validator.cpp}::string::string (json & sch, root_schema * root) inline
Definition at line 782 of file json-validator.cpp.
        : schema(root)
    {
        auto attr = sch.find("maxLength");
        if (attr != sch.end()) {
            maxLength_ = {true, attr.value().get<size_t>()};
            sch.erase(attr);
        }
        attr = sch.find("minLength");
        if (attr != sch.end()) {
            minLength_ = {true, attr.value().get<size_t>()};
            sch.erase(attr);
        }
        attr = sch.find("contentEncoding");
        if (attr != sch.end()) {
            std::get<0>(content_) = true;
            std::get<1>(content_) = attr.value().get<std::string>();
            // special case for nlohmann::json-binary-types
            //
            // https://github.com/pboettch/json-schema-validator/pull/114
            //
            // We cannot use explicitly in a schema: {"type": "binary"} or
            // "type": ["binary", "number"] we have to be implicit. For a
            // schema where "contentEncoding" is set to "binary", an instance
            // of type json::value_t::binary is accepted. If a
            // contentEncoding-callback has to be provided and is called
            // accordingly. For encoding=binary, no other type validations are done
            sch.erase(attr);
        }
        attr = sch.find("contentMediaType");
        if (attr != sch.end()) {
            std::get<0>(content_) = true;
            std::get<2>(content_) = attr.value().get<std::string>();
            sch.erase(attr);
        }
        if (std::get<0>(content_) == true && root_->content_check() == nullptr) {
            throw std::invalid_argument{"schema contains contentEncoding/contentMediaType but content checker was not set"};
        }
#ifndef NO_STD_REGEX
        attr = sch.find("pattern");
        if (attr != sch.end()) {
            patternString_ = attr.value().get<std::string>();
            pattern_ = {true, REGEX_NAMESPACE::regex(attr.value().get<std::string>(),
                                                     REGEX_NAMESPACE::regex::ECMAScript)};
            sch.erase(attr);
        }
#endif
        attr = sch.find("format");
        if (attr != sch.end()) {
            if (root_->format_check() == nullptr)
                throw std::invalid_argument{"a format checker was not provided but a format keyword for this string is present: " + format_.second};
            format_ = {true, attr.value().get<std::string>()};
            sch.erase(attr);
        }
    }
References content_, nlohmann::json_schema::root_schema::content_check(), format_, nlohmann::json_schema::root_schema::format_check(), maxLength_, minLength_, pattern_, patternString_, anonymous_namespace{json-validator.cpp}::schema::root_, and anonymous_namespace{json-validator.cpp}::schema::schema().
string() [2/2]
anonymous_namespace{json-validator.cpp}::string::string (json & sch, root_schema * root) inline
Definition at line 782 of file json-validator.cpp.
        : schema(root)
    {
        auto attr = sch.find("maxLength");
        if (attr != sch.end()) {
            maxLength_ = {true, attr.value().get<size_t>()};
            sch.erase(attr);
        }
        attr = sch.find("minLength");
        if (attr != sch.end()) {
            minLength_ = {true, attr.value().get<size_t>()};
            sch.erase(attr);
        }
        attr = sch.find("contentEncoding");
        if (attr != sch.end()) {
            std::get<0>(content_) = true;
            std::get<1>(content_) = attr.value().get<std::string>();
            // special case for nlohmann::json-binary-types
            //
            // https://github.com/pboettch/json-schema-validator/pull/114
            //
            // We cannot use explicitly in a schema: {"type": "binary"} or
            // "type": ["binary", "number"] we have to be implicit. For a
            // schema where "contentEncoding" is set to "binary", an instance
            // of type json::value_t::binary is accepted. If a
            // contentEncoding-callback has to be provided and is called
            // accordingly. For encoding=binary, no other type validations are done
            sch.erase(attr);
        }
        attr = sch.find("contentMediaType");
        if (attr != sch.end()) {
            std::get<0>(content_) = true;
            std::get<2>(content_) = attr.value().get<std::string>();
            sch.erase(attr);
        }
        if (std::get<0>(content_) == true && root_->content_check() == nullptr) {
            throw std::invalid_argument{"schema contains contentEncoding/contentMediaType but content checker was not set"};
        }
#ifndef NO_STD_REGEX
        attr = sch.find("pattern");
        if (attr != sch.end()) {
            patternString_ = attr.value().get<std::string>();
            pattern_ = {true, REGEX_NAMESPACE::regex(attr.value().get<std::string>(),
                                                     REGEX_NAMESPACE::regex::ECMAScript)};
            sch.erase(attr);
        }
#endif
        attr = sch.find("format");
        if (attr != sch.end()) {
            if (root_->format_check() == nullptr)
                throw std::invalid_argument{"a format checker was not provided but a format keyword for this string is present: " + format_.second};
            format_ = {true, attr.value().get<std::string>()};
            sch.erase(attr);
        }
    }
Member Function Documentation
utf8_length() [1/2]
std::size_t anonymous_namespace{json-validator.cpp}::string::utf8_length (const std::string & s) const inline private
Definition at line 717 of file json-validator.cpp.
    {
        size_t len = 0;
        for (auto c : s)
            if ((c & 0xc0) != 0x80)
                len++;
        return len;
    }
Referenced by validate().
utf8_length() [2/2]
std::size_t anonymous_namespace{json-validator.cpp}::string::utf8_length (const std::string & s) const inline private
Definition at line 717 of file json-validator.cpp.
    {
        size_t len = 0;
        for (auto c : s)
            if ((c & 0xc0) != 0x80)
                len++;
        return len;
    }
validate() [1/2]
void anonymous_namespace{json-validator.cpp}::string::validate (const json::json_pointer & ptr, const json & instance, json_patch & , error_handler & e) const inline override private virtual
Implements anonymous_namespace{json-validator.cpp}::schema.
Definition at line 726 of file json-validator.cpp.
    {
        if (minLength_.first) {
            if (utf8_length(instance.get<std::string>()) < minLength_.second) {
                std::ostringstream s;
                s << "instance is too short as per minLength:" << minLength_.second;
                e.error(ptr, instance, s.str());
            }
        }
        if (maxLength_.first) {
            if (utf8_length(instance.get<std::string>()) > maxLength_.second) {
                std::ostringstream s;
                s << "instance is too long as per maxLength: " << maxLength_.second;
                e.error(ptr, instance, s.str());
            }
        }
        if (std::get<0>(content_)) {
            if (root_->content_check() == nullptr)
                e.error(ptr, instance, std::string("a content checker was not provided but a contentEncoding or contentMediaType for this string have been present: '") + std::get<1>(content_) + "' '" + std::get<2>(content_) + "'");
            else {
                try {
                    root_->content_check()(std::get<1>(content_), std::get<2>(content_), instance);
                } catch (const std::exception &ex) {
                    e.error(ptr, instance, std::string("content-checking failed: ") + ex.what());
                }
            }
        } else if (instance.type() == json::value_t::binary) {
            e.error(ptr, instance, "expected string, but get binary data");
        }
        if (instance.type() != json::value_t::string) {
            return; // next checks only for strings
        }
#ifndef NO_STD_REGEX
        if (pattern_.first &&
            !REGEX_NAMESPACE::regex_search(instance.get<std::string>(), pattern_.second))
            e.error(ptr, instance, "instance does not match regex pattern: " + patternString_);
#endif
        if (format_.first) {
            if (root_->format_check() == nullptr)
                e.error(ptr, instance, std::string("a format checker was not provided but a format keyword for this string is present: ") + format_.second);
            else {
                try {
                    root_->format_check()(format_.second, instance.get<std::string>());
                } catch (const std::exception &ex) {
                    e.error(ptr, instance, std::string("format-checking failed: ") + ex.what());
                }
            }
        }
    }
References content_, nlohmann::json_schema::root_schema::content_check(), nlohmann::json_schema::error_handler::error(), format_, nlohmann::json_schema::root_schema::format_check(), maxLength_, minLength_, pattern_, patternString_, anonymous_namespace{json-validator.cpp}::schema::root_, and utf8_length().
validate() [2/2]
void anonymous_namespace{json-validator.cpp}::string::validate (const json::json_pointer & ptr, const json & instance, json_patch & , error_handler & e) const inline override private virtual
Implements anonymous_namespace{json-validator.cpp}::schema.
Definition at line 726 of file json-validator.cpp.
    {
        if (minLength_.first) {
            if (utf8_length(instance.get<std::string>()) < minLength_.second) {
                std::ostringstream s;
                s << "instance is too short as per minLength:" << minLength_.second;
                e.error(ptr, instance, s.str());
            }
        }
        if (maxLength_.first) {
            if (utf8_length(instance.get<std::string>()) > maxLength_.second) {
                std::ostringstream s;
                s << "instance is too long as per maxLength: " << maxLength_.second;
                e.error(ptr, instance, s.str());
            }
        }
        if (std::get<0>(content_)) {
            if (root_->content_check() == nullptr)
                e.error(ptr, instance, std::string("a content checker was not provided but a contentEncoding or contentMediaType for this string have been present: '") + std::get<1>(content_) + "' '" + std::get<2>(content_) + "'");
            else {
                try {
                    root_->content_check()(std::get<1>(content_), std::get<2>(content_), instance);
                } catch (const std::exception &ex) {
                    e.error(ptr, instance, std::string("content-checking failed: ") + ex.what());
                }
            }
        } else if (instance.type() == json::value_t::binary) {
            e.error(ptr, instance, "expected string, but get binary data");
        }
        if (instance.type() != json::value_t::string) {
            return; // next checks only for strings
        }
#ifndef NO_STD_REGEX
        if (pattern_.first &&
            !REGEX_NAMESPACE::regex_search(instance.get<std::string>(), pattern_.second))
            e.error(ptr, instance, "instance does not match regex pattern: " + patternString_);
#endif
        if (format_.first) {
            if (root_->format_check() == nullptr)
                e.error(ptr, instance, std::string("a format checker was not provided but a format keyword for this string is present: ") + format_.second);
            else {
                try {
                    root_->format_check()(format_.second, instance.get<std::string>());
                } catch (const std::exception &ex) {
                    e.error(ptr, instance, std::string("format-checking failed: ") + ex.what());
                }
            }
        }
    }
Member Data Documentation
content_
std::tuple< bool, std::string, std::string > anonymous_namespace{json-validator.cpp}::string::content_ {false, "", ""} private
Definition at line 715 of file json-validator.cpp.
{false, "", ""};
Referenced by string(), and validate().
format_
std::pair< bool, std::string > anonymous_namespace{json-validator.cpp}::string::format_ private
Definition at line 714 of file json-validator.cpp.
Referenced by string(), and validate().
maxLength_
std::pair< bool, size_t > anonymous_namespace{json-validator.cpp}::string::maxLength_ {false, 0} private
Definition at line 706 of file json-validator.cpp.
{false, 0};
Referenced by string(), and validate().
minLength_
std::pair< bool, size_t > anonymous_namespace{json-validator.cpp}::string::minLength_ {false, 0} private
Definition at line 707 of file json-validator.cpp.
{false, 0};
Referenced by string(), and validate().
pattern_
std::pair< bool, std::regex > anonymous_namespace{json-validator.cpp}::string::pattern_ {false, std ::regex()} private
Definition at line 710 of file json-validator.cpp.
{false, REGEX_NAMESPACE::regex()};
Referenced by string(), and validate().
patternString_
std::string anonymous_namespace{json-validator.cpp}::string::patternString_ private
Definition at line 711 of file json-validator.cpp.
Referenced by string(), and validate().
The documentation for this class was generated from the following file:
lib/json-schema-validator/src/json-validator.cpp