MQTTSuite: mqtt::lib::MqttMapper Class Reference
mqtt::lib::MqttMapper Class Reference
#include <MqttMapper.h>
Classes
struct ScheduledPublish
Public Types
using MappedPublishes = std::pair<std::vector<iot::mqtt::packets::Publish>, std::vector<ScheduledPublish>>
Public Member Functions
MqttMapper ()
MqttMapper (const MqttMapper &)=delete
MqttMapper & operator= (const MqttMapper &)=delete
virtual ~MqttMapper ()
bool setMapping (nlohmann::json mappingJson)
const nlohmann::json & getMapping () const
std::string dump ()
const nlohmann::json & getConnection () const
std::list< iot::mqtt::Topic > extractSubscriptions () const
MappedPublishes getMappings (const iot::mqtt::packets::Publish &publish)
Static Public Member Functions
static const std::string & getSchema ()
static const nlohmann::json validate (const nlohmann::json &json)
static const nlohmann::json validate (const nlohmann::json &json, nlohmann::json_schema::basic_error_handler &err)
Private Member Functions
nlohmann::json findMatchingTopicLevel (const nlohmann::json &topicLevel, const std::string &topic)
void publishMappedTemplate (const nlohmann::json &templateMapping, nlohmann::json &json, MappedPublishes &mappedPublishes)
void getTemplateMappings (const nlohmann::json &templateMapping, nlohmann::json &json, const iot::mqtt::packets::Publish &publish, MappedPublishes &mappedPublishes)
Static Private Member Functions
static void extractSubscription (const nlohmann::json &topicLevelJson, const std::string &topic, std::list< iot::mqtt::Topic > &topicList)
static void extractSubscriptions (const nlohmann::json &mappingJson, const std::string &topic, std::list< iot::mqtt::Topic > &topicList)
static void publishMappedMessage (const std::string &topic, const std::string &message, uint8_t qoS, bool retain, double delay, MappedPublishes &mappedPublishes)
static void publishMappedMessage (const nlohmann::json &staticMapping, const iot::mqtt::packets::Publish &publish, MappedPublishes &mappedPublishes)
static void getStaticMappings (const nlohmann::json &staticMapping, const iot::mqtt::packets::Publish &publish, MappedPublishes &mappedPublishes)
Private Attributes
nlohmann::json mappingJson
std::list< void * > pluginHandles
inja::Environment * injaEnvironment
Static Private Attributes
static const nlohmann::json_schema::json_validator validator
static const std::string mappingJsonSchemaString
Detailed Description
Definition at line 73 of file MqttMapper.h.
Member Typedef Documentation
MappedPublishes
using mqtt::lib::MqttMapper::MappedPublishes = std::pair<std::vector<iot::mqtt::packets::Publish>, std::vector<ScheduledPublish>>
Definition at line 80 of file MqttMapper.h.
Constructor & Destructor Documentation
MqttMapper() [1/2]
mqtt::lib::MqttMapper::MqttMapper ()
Definition at line 98 of file MqttMapper.cpp.
        : injaEnvironment(new inja::Environment) {
    }
References injaEnvironment.
MqttMapper() [2/2]
mqtt::lib::MqttMapper::MqttMapper (const MqttMapper &) delete
~MqttMapper()
mqtt::lib::MqttMapper::~MqttMapper () virtual
Definition at line 102 of file MqttMapper.cpp.
{
        delete injaEnvironment;
        for (void* pluginHandle : pluginHandles) {
            core::DynamicLoader::dlClose(pluginHandle);
        }
    }
References injaEnvironment.
Member Function Documentation
dump()
std::string mqtt::lib::MqttMapper::dump ()
Definition at line 206 of file MqttMapper.cpp.
{
        return mappingJson.dump();
    }
References mappingJson.
extractSubscription()
void mqtt::lib::MqttMapper::extractSubscription (const nlohmann::json & topicLevelJson, const std::string & topic, std::list< iot::mqtt::Topic > & topicList) static private
Definition at line 289 of file MqttMapper.cpp.
{
        const std::string name = topicLevelJson["name"];
        if (topicLevelJson.contains("subscription")) {
            const uint8_t qoS = topicLevelJson["subscription"]["qos"];
            topicList.emplace_back(topic + ((topic.empty() || topic == "/") && !name.empty() ? "" : "/") + name, qoS);
        }
        if (topicLevelJson.contains("topic_level")) {
            extractSubscriptions(topicLevelJson, topic + ((topic.empty() || topic == "/") && !name.empty() ? "" : "/") + name, topicList);
        }
    }
Referenced by extractSubscriptions().
extractSubscriptions() [1/2]
std::list< iot::mqtt::Topic > mqtt::lib::MqttMapper::extractSubscriptions () const
Definition at line 214 of file MqttMapper.cpp.
{
        std::list<iot::mqtt::Topic> topicList;
        extractSubscriptions(mappingJson["mapping"], "", topicList);
        return topicList;
    }
Referenced by mqtt::mqttintegrator::lib::Mqtt::Mqtt(), and mqtt::mqttintegrator::lib::Mqtt::resubscribe().
extractSubscriptions() [2/2]
void mqtt::lib::MqttMapper::extractSubscriptions (const nlohmann::json & mappingJson, const std::string & topic, std::list< iot::mqtt::Topic > & topicList) static private
Definition at line 306 of file MqttMapper.cpp.
{
        if (mappingJson.contains("topic_level")) {
            const nlohmann::json& topicLevels = mappingJson["topic_level"];
            if (topicLevels.is_object()) {
                extractSubscription(topicLevels, topic, topicList);
            } else {
                for (const nlohmann::json& topicLevel : topicLevels) {
                    extractSubscription(topicLevel, topic, topicList);
                }
            }
        }
    }
References extractSubscription().
findMatchingTopicLevel()
nlohmann::json mqtt::lib::MqttMapper::findMatchingTopicLevel (const nlohmann::json & topicLevel, const std::string & topic) private
Definition at line 320 of file MqttMapper.cpp.
{
        nlohmann::json foundTopicLevel;
        if (topicLevel.is_object()) {
            const std::string::size_type slashPosition = topic.find('/');
            const std::string topicLevelName = topic.substr(0, slashPosition);
            if (topicLevel["name"] == topicLevelName || topicLevel["name"] == "+" || topicLevel["name"] == "#") {
                if (slashPosition == std::string::npos) {
                    foundTopicLevel = topicLevel;
                } else if (topicLevel.contains("topic_level")) {
                    foundTopicLevel = findMatchingTopicLevel(topicLevel["topic_level"], topic.substr(slashPosition + 1));
                }
            }
        } else if (topicLevel.is_array()) {
            for (const nlohmann::json& topicLevelEntry : topicLevel) {
                foundTopicLevel = findMatchingTopicLevel(topicLevelEntry, topic);
                if (!foundTopicLevel.empty()) {
                    break;
                }
            }
        }
        return foundTopicLevel;
    }
References findMatchingTopicLevel().
Referenced by findMatchingTopicLevel(), and getMappings().
getConnection()
const nlohmann::json & mqtt::lib::MqttMapper::getConnection () const
Definition at line 210 of file MqttMapper.cpp.
{
        return mappingJson["connection"];
    }
Referenced by mqtt::mqttintegrator::lib::Mqtt::Mqtt(), and mqtt::mqttintegrator::lib::Mqtt::onConnected().
getMapping()
const nlohmann::json & mqtt::lib::MqttMapper::getMapping () const
Definition at line 202 of file MqttMapper.cpp.
{
        return mappingJson;
    }
References mappingJson.
Referenced by mqtt::lib::admin::makeMappingAdminRouter().
getMappings()
MqttMapper::MappedPublishes mqtt::lib::MqttMapper::getMappings (const iot::mqtt::packets::Publish & publish)
Definition at line 230 of file MqttMapper.cpp.
{
        MappedPublishes mappedPublishes;
        if (mappingJson.contains("mapping") && !mappingJson["mapping"].empty()) {
            nlohmann::json matchingTopicLevel = findMatchingTopicLevel(mappingJson["mapping"]["topic_level"], publish.getTopic());
            if (!matchingTopicLevel.empty()) {
                const nlohmann::json& subscription = matchingTopicLevel["subscription"];
                if (subscription.contains("static")) {
                    VLOG(1) << "Topic mapping found for:";
                    VLOG(1) << "  Type: static";
                    VLOG(1) << "  Topic: " << publish.getTopic();
                    VLOG(1) << "  Message: " << publish.getMessage();
                    VLOG(1) << "  QoS: " << static_cast<uint16_t>(publish.getQoS());
                    VLOG(1) << "  Retain: " << publish.getRetain();
                    getStaticMappings(subscription["static"], publish, mappedPublishes);
                }
                if (subscription.contains("value")) {
                    VLOG(1) << "Topic mapping found for:";
                    VLOG(1) << "  Type: value";
                    VLOG(1) << "  Topic: " << publish.getTopic();
                    VLOG(1) << "  Message: " << publish.getMessage();
                    VLOG(1) << "  QoS: " << static_cast<uint16_t>(publish.getQoS());
                    VLOG(1) << "  Retain: " << publish.getRetain();
                    nlohmann::json json;
                    json["message"] = publish.getMessage();
                    getTemplateMappings(subscription["value"], json, publish, mappedPublishes);
                }
                if (subscription.contains("json")) {
                    VLOG(1) << "Topic mapping found for:";
                    VLOG(1) << "  Type: json";
                    VLOG(1) << "  Topic: " << publish.getTopic();
                    VLOG(1) << "  Message: " << publish.getMessage();
                    VLOG(1) << "  QoS: " << static_cast<uint16_t>(publish.getQoS());
                    VLOG(1) << "  Retain: " << publish.getRetain();
                    try {
                        nlohmann::json json;
                        json["message"] = nlohmann::json::parse(publish.getMessage());
                        getTemplateMappings(subscription["json"], json, publish, mappedPublishes);
                    } catch (const nlohmann::json::parse_error& e) {
                        VLOG(1) << "  Parsing message into json failed: " << publish.getMessage();
                        VLOG(1) << "     What: " << e.what() << '\n'
                                << "     Exception Id: " << e.id << '\n'
                                << "     Byte position of error: " << e.byte;
                    }
                }
            }
        }
        return mappedPublishes;
    }
References findMatchingTopicLevel(), getStaticMappings(), and getTemplateMappings().
Referenced by mqtt::mqttbroker::lib::Mqtt::onPublish(), and mqtt::mqttintegrator::lib::Mqtt::onPublish().
getSchema()
const std::string & mqtt::lib::MqttMapper::getSchema () static
Definition at line 110 of file MqttMapper.cpp.
{
        return mappingJsonSchemaString;
    }
References mappingJsonSchemaString.
Referenced by mqtt::lib::admin::makeMappingAdminRouter().
getStaticMappings()
void mqtt::lib::MqttMapper::getStaticMappings (const nlohmann::json & staticMapping, const iot::mqtt::packets::Publish & publish, MappedPublishes & mappedPublishes) static private
Definition at line 483 of file MqttMapper.cpp.
{
        if (staticMapping.is_object()) {
            publishMappedMessage(staticMapping, publish, mappedPublishes);
        } else if (staticMapping.is_array()) {
            for (const nlohmann::json& concreteStaticMapping : staticMapping) {
                publishMappedMessage(concreteStaticMapping, publish, mappedPublishes);
            }
        }
    }
References publishMappedMessage().
Referenced by getMappings().
getTemplateMappings()
void mqtt::lib::MqttMapper::getTemplateMappings (const nlohmann::json & templateMapping, nlohmann::json & json, const iot::mqtt::packets::Publish & publish, MappedPublishes & mappedPublishes) private
Definition at line 402 of file MqttMapper.cpp.
{
        json["topic"] = publish.getTopic();
        json["qos"] = publish.getQoS();
        json["retain"] = publish.getRetain();
        json["package_identifier"] = publish.getPacketIdentifier();
        try {
            VLOG(1) << "  Render data: " << json.dump();
            if (templateMapping.is_object()) {
                publishMappedTemplate(templateMapping, json, mappedPublishes);
            } else {
                for (const nlohmann::json& concreteTemplateMapping : templateMapping) {
                    publishMappedTemplate(concreteTemplateMapping, json, mappedPublishes);
                }
            }
        } catch (const nlohmann::json::exception& e) {
            VLOG(1) << "JSON Exception during Render data:\n" << e.what();
        }
    }
References publishMappedTemplate().
Referenced by getMappings().
operator=()
MqttMapper & mqtt::lib::MqttMapper::operator= (const MqttMapper &) delete
publishMappedMessage() [1/2]
void mqtt::lib::MqttMapper::publishMappedMessage (const nlohmann::json & staticMapping, const iot::mqtt::packets::Publish & publish, MappedPublishes & mappedPublishes) static private
Definition at line 446 of file MqttMapper.cpp.
{
        const nlohmann::json& messageMapping = staticMapping["message_mapping"];
        VLOG(1) << "  Message mapping: " << messageMapping.dump();
        if (messageMapping.is_object()) {
            if (messageMapping["message"] == publish.getMessage()) {
                publishMappedMessage(staticMapping["mapped_topic"],
                                     messageMapping["mapped_message"],
                                     staticMapping["qos"],
                                     staticMapping["retain"],
                                     staticMapping["delay"],
                                     mappedPublishes);
            } else {
                VLOG(1) << "    no matching mapped message found";
            }
        } else {
            const nlohmann::json::const_iterator matchedMessageMappingIterator =
                std::find_if(messageMapping.begin(), messageMapping.end(), [&publish](const nlohmann::json& messageMappingCandidat) {
                    return messageMappingCandidat["message"] == publish.getMessage();
                });
            if (matchedMessageMappingIterator != messageMapping.end()) {
                publishMappedMessage(staticMapping["mapped_topic"],
                                     (*matchedMessageMappingIterator)["mapped_message"],
                                     staticMapping["qos"],
                                     staticMapping["retain"],
                                     staticMapping["delay"],
                                     mappedPublishes);
            } else {
                VLOG(1) << "    no matching mapped message found";
            }
        }
    }
Referenced by getStaticMappings().
publishMappedMessage() [2/2]
void mqtt::lib::MqttMapper::publishMappedMessage (const std::string & topic, const std::string & message, uint8_t qoS, bool retain, double delay, MappedPublishes & mappedPublishes) static private
Definition at line 426 of file MqttMapper.cpp.
{
        VLOG(1) << "  Mapped topic:";
        VLOG(1) << "    -> " << topic;
        VLOG(1) << "  Mapped message:";
        VLOG(1) << "    -> " << message;
        VLOG(1) << "  Send mapping:" << (delay > 0 ? " delayed" : "");
        VLOG(1) << "    Topic: " << topic;
        VLOG(1) << "    Message: " << message;
        VLOG(1) << "    QoS: " << static_cast<int>(qoS);
        VLOG(1) << "    retain: " << retain;
        VLOG(1) << "    Delay: " << delay;
        if (delay < 0.0) {
            mappedPublishes.first.emplace_back(0, topic, message, qoS, false, retain);
        } else {
            mappedPublishes.second.push_back({delay, iot::mqtt::packets::Publish(0, topic, message, qoS, false, retain)});
        }
    }
Referenced by publishMappedTemplate().
publishMappedTemplate()
void mqtt::lib::MqttMapper::publishMappedTemplate (const nlohmann::json & templateMapping, nlohmann::json & json, MappedPublishes & mappedPublishes) private
Definition at line 347 of file MqttMapper.cpp.
{
        const std::string& mappingTemplate = templateMapping["mapping_template"];
        const std::string& mappedTopic = templateMapping["mapped_topic"];
        try {
            // Render topic
            const std::string renderedTopic = injaEnvironment->render(mappedTopic, json);
            json["mapped_topic"] = renderedTopic;
            VLOG(1) << "  Mapped topic template: " << mappedTopic;
            VLOG(1) << "    -> " << renderedTopic;
            try {
                // Render message
                const std::string renderedMessage = injaEnvironment->render(mappingTemplate, json);
                VLOG(1) << "  Mapped message template: " << mappingTemplate;
                VLOG(1) << "    -> " << renderedMessage;
                const nlohmann::json& suppressions = templateMapping["suppressions"];
                const bool retain = templateMapping["retain"];
                if (suppressions.empty() || std::find(suppressions.begin(), suppressions.end(), renderedMessage) == suppressions.end() ||
                    (retain && renderedMessage.empty())) {
                    const uint8_t qoS = templateMapping["qos"];
                    const double delay = templateMapping["delay"];
                    VLOG(1) << "  Send mapping:" << (delay > 0 ? " delayed" : "");
                    VLOG(1) << "    Topic: " << renderedTopic;
                    VLOG(1) << "    Message: " << renderedMessage << "";
                    VLOG(1) << "    QoS: " << static_cast<int>(qoS);
                    VLOG(1) << "    retain: " << retain;
                    VLOG(1) << "    Delay: " << delay;
                    publishMappedMessage(renderedTopic, renderedMessage, qoS, retain, delay, mappedPublishes);
                } else {
                    VLOG(1) << "    Rendered message: '" << renderedMessage << "' in suppression list:";
                    for (const nlohmann::json& item : suppressions) {
                        VLOG(1) << "         '" << item.get<std::string>() << "'";
                    }
                    VLOG(1) << "  Send mapping: suppressed";
                }
            } catch (const inja::InjaError& e) {
                VLOG(1) << "  Message template rendering failed: " << mappingTemplate << " : " << json.dump();
                VLOG(1) << "    What: " << e.what();
                VLOG(1) << "    INJA: " << e.type << ": " << e.message;
                VLOG(1) << "    INJA (line:column):" << e.location.line << ":" << e.location.column;
            }
        } catch (const inja::InjaError& e) {
            VLOG(1) << "  Topic template rendering failed: " << mappingTemplate << " : " << json.dump();
            VLOG(1) << "    What: " << e.what();
            VLOG(1) << "    INJA: " << e.type << ": " << e.message;
            VLOG(1) << "    INJA (line:column):" << e.location.line << ":" << e.location.column;
        }
    }
References inja::SourceLocation::column, injaEnvironment, inja::SourceLocation::line, inja::InjaError::location, inja::InjaError::message, publishMappedMessage(), inja::Environment::render(), and inja::InjaError::type.
Referenced by getTemplateMappings().
setMapping()
bool mqtt::lib::MqttMapper::setMapping (nlohmann::json mappingJson)
Definition at line 114 of file MqttMapper.cpp.
                                                        { // can throw
        delete injaEnvironment;
        for (void* handle : pluginHandles) {
            core::DynamicLoader::dlClose(handle);
        }
        pluginHandles.clear();
        injaEnvironment = new inja::Environment;
        nlohmann::json defaultPatch;
        try {
            defaultPatch = validator.validate(mappingJson);
        } catch (const std::exception& e) {
            throw std::runtime_error("Validating JSON failed: Mapping JSON = " + mappingJson.dump(4) + "\n" + e.what());
        }
        try {
            mappingJson = mappingJson.patch(defaultPatch);
        } catch (const std::exception& e) {
            throw std::runtime_error("Patching JSON with default patch failed: Default patch = " + defaultPatch.dump(4) + "\n" + e.what());
        }
        bool mustReconnect = this->mappingJson["connection"] != mappingJson["connection"];
        this->mappingJson = mappingJson;
        if (mappingJson["mapping"].contains("plugins")) {
            for (const nlohmann::json& pluginJson : mappingJson["mapping"]["plugins"]) {
                const std::string plugin = pluginJson;
                void* handle = core::DynamicLoader::dlOpen(plugin);
                if (handle != nullptr) {
                    pluginHandles.push_back(handle);
                    VLOG(1) << "  Loading plugin: " << plugin << " ...";
                    const std::vector<mqtt::lib::Function>* loadedFunctions =
                        static_cast<std::vector<mqtt::lib::Function>*>(core::DynamicLoader::dlSym(handle, "functions"));
                    if (loadedFunctions != nullptr) {
                        VLOG(1) << "  Registering inja 'none void callbacks'";
                        for (const mqtt::lib::Function& function : *loadedFunctions) {
                            VLOG(1) << "    " << function.name;
                            if (function.numArgs >= 0) {
                                injaEnvironment->add_callback(function.name, function.numArgs, function.function);
                            } else {
                                injaEnvironment->add_callback(function.name, function.function);
                            }
                        }
                        VLOG(1) << "  Registering inja 'none void callbacks done'";
                    } else {
                        VLOG(1) << "  No inja none 'void callbacks found' in plugin " << plugin;
                    }
                    const std::vector<mqtt::lib::VoidFunction>* loadedVoidFunctions =
                        static_cast<std::vector<mqtt::lib::VoidFunction>*>(core::DynamicLoader::dlSym(handle, "voidFunctions"));
                    if (loadedVoidFunctions != nullptr) {
                        VLOG(1) << "  Registering inja 'void callbacks'";
                        for (const mqtt::lib::VoidFunction& voidFunction : *loadedVoidFunctions) {
                            VLOG(1) << "    " << voidFunction.name;
                            if (voidFunction.numArgs >= 0) {
                                injaEnvironment->add_void_callback(voidFunction.name, voidFunction.numArgs, voidFunction.function);
                            } else {
                                injaEnvironment->add_void_callback(voidFunction.name, voidFunction.function);
                            }
                        }
                        VLOG(1) << "  Registering inja 'void callbacks' done";
                    } else {
                        VLOG(1) << "  No inja 'void callbacks' found in plugin " << plugin;
                    }
                    VLOG(1) << "  Loading plugin done: " << plugin;
                } else {
                    VLOG(1) << "  Error loading plugin: " << plugin;
                    throw std::runtime_error("Error loading plugin '" + plugin + "': " + core::DynamicLoader::dlError());
                }
            }
            VLOG(1) << "Loading plugins done";
        }
        return mustReconnect;
    }
References injaEnvironment, mappingJson, pluginHandles, nlohmann::json_schema::json_validator::validate(), and validator.
Referenced by mqtt::lib::ConfigApplication::ConfigApplication(), and mqtt::lib::ConfigApplication::setMapping().
validate() [1/2]
const nlohmann::json mqtt::lib::MqttMapper::validate (const nlohmann::json & json) static
Definition at line 222 of file MqttMapper.cpp.
{
        return validator.validate(json);
    }
References nlohmann::json_schema::json_validator::validate(), and validator.
Referenced by mqtt::lib::JsonMappingReader::rollbackTo().
validate() [2/2]
const nlohmann::json mqtt::lib::MqttMapper::validate (const nlohmann::json & json, nlohmann::json_schema::basic_error_handler & err) static
Definition at line 226 of file MqttMapper.cpp.
{
        return validator.validate(json, err);
    }
References nlohmann::json_schema::json_validator::validate(), and validator.
Referenced by mqtt::lib::admin::makeMappingAdminRouter().
Member Data Documentation
injaEnvironment
inja::Environment* mqtt::lib::MqttMapper::injaEnvironment private
Definition at line 130 of file MqttMapper.h.
Referenced by MqttMapper(), publishMappedTemplate(), setMapping(), and ~MqttMapper().
mappingJson
nlohmann::json mqtt::lib::MqttMapper::mappingJson private
Definition at line 126 of file MqttMapper.h.
Referenced by dump(), getMapping(), and setMapping().
mappingJsonSchemaString
const std::string mqtt::lib::MqttMapper::mappingJsonSchemaString static private
Definition at line 134 of file MqttMapper.h.
Referenced by getSchema().
pluginHandles
std::list<void*> mqtt::lib::MqttMapper::pluginHandles private
Definition at line 128 of file MqttMapper.h.
Referenced by setMapping().
validator
const nlohmann::json_schema::json_validator mqtt::lib::MqttMapper::validator static private
Definition at line 132 of file MqttMapper.h.
Referenced by setMapping(), validate(), and validate().
The documentation for this class was generated from the following files:
lib/MqttMapper.h
lib/MqttMapper.cpp