MQTTSuite: mqtt::bridge::lib::Mqtt Class Reference
mqtt::bridge::lib::Mqtt Class Reference
#include <Mqtt.h>
Public Member Functions
Mqtt (const std::string &connectionName, Broker &broker)
const Broker & getBroker () const
Private Types
using Super = iot::mqtt::client::Mqtt
Private Member Functions
void onConnected () final
void onDisconnected () final
bool onSignal (int signum) final
void onConnack (const iot::mqtt::packets::Connack &connack) final
void onPublish (const iot::mqtt::packets::Publish &publish) final
Private Attributes
Broker & broker
Detailed Description
Definition at line 59 of file Mqtt.h.
Member Typedef Documentation
Super
using mqtt::bridge::lib::Mqtt::Super = iot::mqtt::client::Mqtt private
Definition at line 66 of file Mqtt.h.
Constructor & Destructor Documentation
Mqtt()
mqtt::bridge::lib::Mqtt::Mqtt (const std::string & connectionName, Broker & broker) explicit
Definition at line 59 of file Mqtt.cpp.
        : iot::mqtt::client::Mqtt(connectionName, //
                                  broker.getClientId(),
                                  broker.getKeepAlive(),
                                  broker.getSessionStoreFileName())
        , broker(broker) {
        VLOG(1) << "Client Id: " << clientId;
        VLOG(1) << "  Keep Alive: " << keepAlive;
        VLOG(1) << "  Prefix: " << broker.getPrefix();
        VLOG(1) << "  Clean Session: " << broker.getCleanSession();
        VLOG(1) << "  Will Topic: " << broker.getWillTopic();
        VLOG(1) << "  Will Message: " << broker.getWillMessage();
        VLOG(1) << "  Will QoS: " << static_cast<uint16_t>(broker.getWillQoS());
        VLOG(1) << "  Will Retain " << broker.getWillRetain();
        VLOG(1) << "  Username: " << broker.getUsername();
        VLOG(1) << "  Password: " << broker.getPassword();
        VLOG(1) << "  Loop Prevention: " << broker.getLoopPrevention();
    }
References broker, mqtt::bridge::lib::Broker::getCleanSession(), mqtt::bridge::lib::Broker::getClientId(), mqtt::bridge::lib::Broker::getKeepAlive(), mqtt::bridge::lib::Broker::getLoopPrevention(), mqtt::bridge::lib::Broker::getPassword(), mqtt::bridge::lib::Broker::getPrefix(), mqtt::bridge::lib::Broker::getSessionStoreFileName(), mqtt::bridge::lib::Broker::getUsername(), mqtt::bridge::lib::Broker::getWillMessage(), mqtt::bridge::lib::Broker::getWillQoS(), mqtt::bridge::lib::Broker::getWillRetain(), and mqtt::bridge::lib::Broker::getWillTopic().
Referenced by mqtt::bridge::SocketContextFactory::create(), and mqtt::mqttbridge::websocket::SubProtocolFactory::create().
Member Function Documentation
getBroker()
const Broker & mqtt::bridge::lib::Mqtt::getBroker () const
Definition at line 78 of file Mqtt.cpp.
{
        return broker;
    }
References broker.
Referenced by mqtt::bridge::lib::Bridge::publish().
onConnack()
void mqtt::bridge::lib::Mqtt::onConnack (const iot::mqtt::packets::Connack & connack) final private
Definition at line 110 of file Mqtt.cpp.
{
        if (connack.getReturnCode() == 0) {
            mqtt::bridge::lib::BridgeStore::instance().mqttConnected(broker, this);
            sendSubscribe(broker.getTopics());
        }
    }
References broker, mqtt::bridge::lib::Broker::getTopics(), mqtt::bridge::lib::BridgeStore::instance(), and mqtt::bridge::lib::BridgeStore::mqttConnected().
onConnected()
void mqtt::bridge::lib::Mqtt::onConnected () final private
Definition at line 82 of file Mqtt.cpp.
{
        VLOG(1) << "MQTT: Initiating Session";
        sendConnect(broker.getCleanSession(),
                    broker.getWillTopic(),
                    broker.getWillMessage(),
                    broker.getWillQoS(),
                    broker.getWillRetain(),
                    broker.getUsername(),
                    broker.getPassword(),
                    broker.getLoopPrevention());
    }
References broker, mqtt::bridge::lib::Broker::getCleanSession(), mqtt::bridge::lib::Broker::getLoopPrevention(), mqtt::bridge::lib::Broker::getPassword(), mqtt::bridge::lib::Broker::getUsername(), mqtt::bridge::lib::Broker::getWillMessage(), mqtt::bridge::lib::Broker::getWillQoS(), mqtt::bridge::lib::Broker::getWillRetain(), and mqtt::bridge::lib::Broker::getWillTopic().
onDisconnected()
void mqtt::bridge::lib::Mqtt::onDisconnected () final private
Definition at line 95 of file Mqtt.cpp.
{
        mqtt::bridge::lib::BridgeStore::instance().mqttDisconnected(broker, this);
        VLOG(1) << "MQTT: Disconnected";
    }
References broker, mqtt::bridge::lib::BridgeStore::instance(), and mqtt::bridge::lib::BridgeStore::mqttDisconnected().
onPublish()
void mqtt::bridge::lib::Mqtt::onPublish (const iot::mqtt::packets::Publish & publish) final private
Definition at line 118 of file Mqtt.cpp.
{
        broker.getBridge().publish(this, publish);
    }
References broker, mqtt::bridge::lib::Broker::getBridge(), and mqtt::bridge::lib::Bridge::publish().
onSignal()
bool mqtt::bridge::lib::Mqtt::onSignal (int signum) nodiscard final private
Definition at line 101 of file Mqtt.cpp.
{
        VLOG(1) << "MQTT: On Exit due to '" << strsignal(signum) << "' (SIG" << utils::system::sigabbrev_np(signum) << " = " << signum
                << ")";
        sendDisconnect();
        return Super::onSignal(signum);
    }
Member Data Documentation
broker
Broker& mqtt::bridge::lib::Mqtt::broker private
Definition at line 75 of file Mqtt.h.
Referenced by getBroker(), Mqtt(), onConnack(), onConnected(), onDisconnected(), and onPublish().
The documentation for this class was generated from the following files:
mqttbridge/lib/Mqtt.h
mqttbridge/lib/Mqtt.cpp