MQTTSuite: store_ptr_err_handler Class Reference
store_ptr_err_handler Class Reference
Public Member Functions
void reset () override
void reset () override
void reset () override
void reset () override
void reset () override
void reset () override
Public Member Functions inherited from nlohmann::json_schema::basic_error_handler
void error (const json::json_pointer &, const json &, const std::string &) override
operator bool () const
Public Member Functions inherited from nlohmann::json_schema::error_handler
virtual ~error_handler ()
Public Attributes
std::vector< nlohmann::json::json_pointer > failed_pointers
Private Member Functions
void error (const nlohmann::json::json_pointer &ptr, const json &, const std::string &message) override
void error (const nlohmann::json::json_pointer &ptr, const json &instance, const std::string &message) override
void error (const nlohmann::json::json_pointer &ptr, const json &instance, const std::string &message) override
void error (const nlohmann::json::json_pointer &ptr, const json &, const std::string &message) override
void error (const nlohmann::json::json_pointer &ptr, const json &instance, const std::string &message) override
void error (const nlohmann::json::json_pointer &ptr, const json &instance, const std::string &message) override
Detailed Description
Definition at line 73 of file binary-validation.cpp.
Member Function Documentation
error() [1/6]
void store_ptr_err_handler::error (const nlohmann::json::json_pointer & ptr, const json & , const std::string & message) inline override private
Definition at line 75 of file binary-validation.cpp.
    {
        nlohmann::json_schema::basic_error_handler::error(ptr, "", message);
        std::cerr << "ERROR: '" << ptr << "' - '"
                  << ""
                  << "': " << message << "\n";
        failed_pointers.push_back(ptr);
    }
error() [2/6]
void store_ptr_err_handler::error (const nlohmann::json::json_pointer & ptr, const json & , const std::string & message) inline override private
Definition at line 75 of file binary-validation.cpp.
    {
        nlohmann::json_schema::basic_error_handler::error(ptr, "", message);
        std::cerr << "ERROR: '" << ptr << "' - '"
                  << ""
                  << "': " << message << "\n";
        failed_pointers.push_back(ptr);
    }
error() [3/6]
void store_ptr_err_handler::error (const nlohmann::json::json_pointer & ptr, const json & instance, const std::string & message) inline override private
Definition at line 54 of file errors.cpp.
    {
        nlohmann::json_schema::basic_error_handler::error(ptr, instance, message);
        std::cerr << "ERROR: '" << ptr << "' - '" << instance << "': " << message << "\n";
        failed_pointers.push_back(ptr);
    }
error() [4/6]
void store_ptr_err_handler::error (const nlohmann::json::json_pointer & ptr, const json & instance, const std::string & message) inline override private
Definition at line 54 of file errors.cpp.
    {
        nlohmann::json_schema::basic_error_handler::error(ptr, instance, message);
        std::cerr << "ERROR: '" << ptr << "' - '" << instance << "': " << message << "\n";
        failed_pointers.push_back(ptr);
    }
error() [5/6]
void store_ptr_err_handler::error (const nlohmann::json::json_pointer & ptr, const json & instance, const std::string & message) inline override private
Definition at line 54 of file issue-70-root-schema-constructor.cpp.
    {
        nlohmann::json_schema::basic_error_handler::error(ptr, instance, message);
        std::cerr << "ERROR: '" << ptr << "' - '" << instance << "': " << message << "\n";
        failed_pointers.push_back(ptr);
    }
error() [6/6]
void store_ptr_err_handler::error (const nlohmann::json::json_pointer & ptr, const json & instance, const std::string & message) inline override private
Definition at line 54 of file issue-70-root-schema-constructor.cpp.
    {
        nlohmann::json_schema::basic_error_handler::error(ptr, instance, message);
        std::cerr << "ERROR: '" << ptr << "' - '" << instance << "': " << message << "\n";
        failed_pointers.push_back(ptr);
    }
reset() [1/6]
void store_ptr_err_handler::reset () inline override virtual
Reimplemented from nlohmann::json_schema::basic_error_handler.
Definition at line 87 of file binary-validation.cpp.
    {
        nlohmann::json_schema::basic_error_handler::reset();
        failed_pointers.clear();
    }
References nlohmann::json_schema::basic_error_handler::reset().
Referenced by main().
reset() [2/6]
void store_ptr_err_handler::reset () inline override virtual
Reimplemented from nlohmann::json_schema::basic_error_handler.
Definition at line 87 of file binary-validation.cpp.
    {
        nlohmann::json_schema::basic_error_handler::reset();
        failed_pointers.clear();
    }
reset() [3/6]
void store_ptr_err_handler::reset () inline override virtual
Reimplemented from nlohmann::json_schema::basic_error_handler.
Definition at line 64 of file errors.cpp.
    {
        nlohmann::json_schema::basic_error_handler::reset();
        failed_pointers.clear();
    }
References nlohmann::json_schema::basic_error_handler::reset().
Referenced by main().
reset() [4/6]
void store_ptr_err_handler::reset () inline override virtual
Reimplemented from nlohmann::json_schema::basic_error_handler.
Definition at line 64 of file errors.cpp.
    {
        nlohmann::json_schema::basic_error_handler::reset();
        failed_pointers.clear();
    }
reset() [5/6]
void store_ptr_err_handler::reset () inline override virtual
Reimplemented from nlohmann::json_schema::basic_error_handler.
Definition at line 64 of file issue-70-root-schema-constructor.cpp.
    {
        nlohmann::json_schema::basic_error_handler::reset();
        failed_pointers.clear();
    }
References nlohmann::json_schema::basic_error_handler::reset().
Referenced by main().
reset() [6/6]
void store_ptr_err_handler::reset () inline override virtual
Reimplemented from nlohmann::json_schema::basic_error_handler.
Definition at line 64 of file issue-70-root-schema-constructor.cpp.
    {
        nlohmann::json_schema::basic_error_handler::reset();
        failed_pointers.clear();
    }
Member Data Documentation
failed_pointers
std::vector< nlohmann::json::json_pointer > store_ptr_err_handler::failed_pointers
Definition at line 85 of file binary-validation.cpp.
The documentation for this class was generated from the following files:
lib/json-schema-validator/test/binary-validation.cpp
lib/json-schema-validator/test/errors.cpp
lib/json-schema-validator/test/issue-70-root-schema-constructor.cpp