MQTTSuite: inja::ForStatementNode Class Reference
inja::ForStatementNode Class Reference abstract
#include <inja.hpp>
Public Member Functions
ForStatementNode (BlockNode *const parent, size_t pos)
virtual void accept (NodeVisitor &v) const override=0
Public Member Functions inherited from inja::StatementNode
StatementNode (size_t pos)
Public Member Functions inherited from inja::AstNode
AstNode (size_t pos)
AstNode (const AstNode &)=default
AstNode & operator= (const AstNode &)=default
virtual ~AstNode ()
Public Attributes
ExpressionListNode condition
BlockNode body
BlockNode *const parent
Public Attributes inherited from inja::AstNode
size_t pos
Detailed Description
Definition at line 662 of file inja.hpp.
Constructor & Destructor Documentation
ForStatementNode()
inja::ForStatementNode::ForStatementNode (BlockNode *const parent, size_t pos) inline
Definition at line 668 of file inja.hpp.
            : StatementNode(pos)
            , parent(parent) {
        }
References parent, and inja::StatementNode::StatementNode().
Referenced by inja::ForArrayStatementNode::ForArrayStatementNode(), and inja::ForObjectStatementNode::ForObjectStatementNode().
Member Function Documentation
accept()
virtual void inja::ForStatementNode::accept (NodeVisitor & v) const override pure virtual
Implements inja::StatementNode.
Implemented in inja::ForArrayStatementNode, and inja::ForObjectStatementNode.
Member Data Documentation
body
BlockNode inja::ForStatementNode::body
Definition at line 665 of file inja.hpp.
condition
ExpressionListNode inja::ForStatementNode::condition
Definition at line 664 of file inja.hpp.
parent
BlockNode* const inja::ForStatementNode::parent
Definition at line 666 of file inja.hpp.
Referenced by ForStatementNode().
The documentation for this class was generated from the following file:
lib/inja.hpp