MQTTSuite: inja::ExtendsStatementNode Class Reference
inja::ExtendsStatementNode Class Reference
#include <inja.hpp>
Public Member Functions
ExtendsStatementNode (const std::string &file, size_t pos)
void accept (NodeVisitor &v) const override
Public Member Functions inherited from inja::StatementNode
StatementNode (size_t pos)
Public Member Functions inherited from inja::AstNode
AstNode (size_t pos)
AstNode (const AstNode &)=default
AstNode & operator= (const AstNode &)=default
virtual ~AstNode ()
Public Attributes
const std::string file
Public Attributes inherited from inja::AstNode
size_t pos
Detailed Description
Definition at line 746 of file inja.hpp.
Constructor & Destructor Documentation
ExtendsStatementNode()
inja::ExtendsStatementNode::ExtendsStatementNode (const std::string & file, size_t pos) inline explicit
Definition at line 750 of file inja.hpp.
            : StatementNode(pos)
            , file(file) {
        }
References ExtendsStatementNode(), and inja::StatementNode::StatementNode().
Referenced by ExtendsStatementNode().
Member Function Documentation
accept()
void inja::ExtendsStatementNode::accept (NodeVisitor & v) const inline override virtual
Implements inja::StatementNode.
Definition at line 755 of file inja.hpp.
{
            v.visit(*this);
        }
References inja::NodeVisitor::visit().
Member Data Documentation
file
const std::string inja::ExtendsStatementNode::file
Definition at line 748 of file inja.hpp.
The documentation for this class was generated from the following file:
lib/inja.hpp