MQTTSuite: inja::BlockStatementNode Class Reference
inja::BlockStatementNode Class Reference
#include <inja.hpp>
Public Member Functions
BlockStatementNode (BlockNode *const parent, const std::string &name, size_t pos)
void accept (NodeVisitor &v) const override
Public Member Functions inherited from inja::StatementNode
StatementNode (size_t pos)
Public Member Functions inherited from inja::AstNode
AstNode (size_t pos)
AstNode (const AstNode &)=default
AstNode & operator= (const AstNode &)=default
virtual ~AstNode ()
Public Attributes
const std::string name
BlockNode block
BlockNode *const parent
Public Attributes inherited from inja::AstNode
size_t pos
Detailed Description
Definition at line 760 of file inja.hpp.
Constructor & Destructor Documentation
BlockStatementNode()
inja::BlockStatementNode::BlockStatementNode (BlockNode *const parent, const std::string & name, size_t pos) inline explicit
Definition at line 766 of file inja.hpp.
            : StatementNode(pos)
            , name(name)
            , parent(parent) {
        }
References BlockStatementNode(), parent, and inja::StatementNode::StatementNode().
Referenced by BlockStatementNode().
Member Function Documentation
accept()
void inja::BlockStatementNode::accept (NodeVisitor & v) const inline override virtual
Implements inja::StatementNode.
Definition at line 772 of file inja.hpp.
{
            v.visit(*this);
        }
References inja::NodeVisitor::visit().
Member Data Documentation
block
BlockNode inja::BlockStatementNode::block
Definition at line 763 of file inja.hpp.
name
const std::string inja::BlockStatementNode::name
Definition at line 762 of file inja.hpp.
parent
BlockNode* const inja::BlockStatementNode::parent
Definition at line 764 of file inja.hpp.
Referenced by BlockStatementNode().
The documentation for this class was generated from the following file:
lib/inja.hpp