MQTTSuite: mqtt::mqttstore::lib::anonymous_namespace{StoragePlan.cpp}::ProjectionValidationErrorHandler Class Reference
mqtt::mqttstore::lib::anonymous_namespace{StoragePlan.cpp}::ProjectionValidationErrorHandler Class Reference
Public Member Functions
void error (const nlohmann::json::json_pointer &pointer, const nlohmann::json &instance, const std::string &message) override
std::string message () const
void error (const nlohmann::json::json_pointer &pointer, const nlohmann::json &instance, const std::string &message) override
std::string message () const
Public Member Functions inherited from nlohmann::json_schema::basic_error_handler
void error (const json::json_pointer &, const json &, const std::string &) override
virtual void reset ()
operator bool () const
Public Member Functions inherited from nlohmann::json_schema::error_handler
virtual ~error_handler ()
Private Attributes
std::vector< std::string > errors
Detailed Description
Definition at line 48 of file StoragePlan.cpp.
Member Function Documentation
error() [1/2]
void mqtt::mqttstore::lib::anonymous_namespace{StoragePlan.cpp}::ProjectionValidationErrorHandler::error (const nlohmann::json::json_pointer & pointer, const nlohmann::json & instance, const std::string & message) inline override
Definition at line 50 of file StoragePlan.cpp.
{
                nlohmann::json_schema::basic_error_handler::error(pointer, instance, message);
                std::ostringstream error;
                error << "  - " << pointer << ": " << message << " (value: " << jsonSummary(instance) << ")";
                errors.push_back(error.str());
            }
References nlohmann::json_schema::basic_error_handler::error(), and mqtt::mqttstore::lib::anonymous_namespace{StoragePlan.cpp}::jsonSummary().
error() [2/2]
void mqtt::mqttstore::lib::anonymous_namespace{StoragePlan.cpp}::ProjectionValidationErrorHandler::error (const nlohmann::json::json_pointer & pointer, const nlohmann::json & instance, const std::string & message) inline override
Definition at line 50 of file StoragePlan.cpp.
{
                nlohmann::json_schema::basic_error_handler::error(pointer, instance, message);
                std::ostringstream error;
                error << "  - " << pointer << ": " << message << " (value: " << jsonSummary(instance) << ")";
                errors.push_back(error.str());
            }
message() [1/2]
std::string mqtt::mqttstore::lib::anonymous_namespace{StoragePlan.cpp}::ProjectionValidationErrorHandler::message () const inline nodiscard
Definition at line 58 of file StoragePlan.cpp.
{
                std::string result;
                for (const std::string& error : errors) {
                    result += (result.empty() ? "" : "\n") + error;
                }
                return result;
            }
Referenced by mqtt::mqttstore::lib::anonymous_namespace{StoragePlan.cpp}::validateProjectionConfiguration().
message() [2/2]
std::string mqtt::mqttstore::lib::anonymous_namespace{StoragePlan.cpp}::ProjectionValidationErrorHandler::message () const inline nodiscard
Definition at line 58 of file StoragePlan.cpp.
{
                std::string result;
                for (const std::string& error : errors) {
                    result += (result.empty() ? "" : "\n") + error;
                }
                return result;
            }
Member Data Documentation
errors
std::vector< std::string > mqtt::mqttstore::lib::anonymous_namespace{StoragePlan.cpp}::ProjectionValidationErrorHandler::errors private
Definition at line 68 of file StoragePlan.cpp.
The documentation for this class was generated from the following file:
mqttstore/lib/StoragePlan.cpp