MQTTSuite: mqtt::bridge::lib::SSEDistributor::Event Class Reference
mqtt::bridge::lib::SSEDistributor::Event Class Reference
Public Member Functions
Event (const std::string &data, const std::string &event, const std::string &id)
Event (const Event &)=delete
Event (Event &&)=delete
Event & operator= (const Event &)=delete
Event & operator= (Event &&)=delete
const std::string & getData () const
const std::string & getEvent () const
const std::string & getId () const
Private Attributes
std::string data
std::string event
std::string id
Detailed Description
Definition at line 81 of file SSEDistributor.h.
Constructor & Destructor Documentation
Event() [1/3]
mqtt::bridge::lib::SSEDistributor::Event::Event (const std::string & data, const std::string & event, const std::string & id)
Definition at line 264 of file SSEDistributor.cpp.
        : data(data)
        , event(event)
        , id(id) {
    }
References data, event, and id.
Event() [2/3]
mqtt::bridge::lib::SSEDistributor::Event::Event (const Event &) delete
Event() [3/3]
mqtt::bridge::lib::SSEDistributor::Event::Event (Event &&) delete
Member Function Documentation
getData()
const std::string & mqtt::bridge::lib::SSEDistributor::Event::getData () const
Definition at line 270 of file SSEDistributor.cpp.
{
        return data;
    }
References data.
Referenced by mqtt::bridge::lib::SSEDistributor::addEventReceiver().
getEvent()
const std::string & mqtt::bridge::lib::SSEDistributor::Event::getEvent () const
Definition at line 274 of file SSEDistributor.cpp.
{
        return event;
    }
References event.
Referenced by mqtt::bridge::lib::SSEDistributor::addEventReceiver().
getId()
const std::string & mqtt::bridge::lib::SSEDistributor::Event::getId () const
Definition at line 278 of file SSEDistributor.cpp.
{
        return id;
    }
References id.
Referenced by mqtt::bridge::lib::SSEDistributor::addEventReceiver().
operator=() [1/2]
Event & mqtt::bridge::lib::SSEDistributor::Event::operator= (const Event &) delete
operator=() [2/2]
Event & mqtt::bridge::lib::SSEDistributor::Event::operator= (Event &&) delete
Member Data Documentation
data
std::string mqtt::bridge::lib::SSEDistributor::Event::data private
Definition at line 96 of file SSEDistributor.h.
Referenced by Event(), and getData().
event
std::string mqtt::bridge::lib::SSEDistributor::Event::event private
Definition at line 97 of file SSEDistributor.h.
Referenced by Event(), and getEvent().
id
std::string mqtt::bridge::lib::SSEDistributor::Event::id private
Definition at line 98 of file SSEDistributor.h.
Referenced by Event(), and getId().
The documentation for this class was generated from the following files:
mqttbridge/lib/SSEDistributor.h
mqttbridge/lib/SSEDistributor.cpp