MQTTSuite: nlohmann::json_schema::json_validator Class Reference
nlohmann::json_schema::json_validator Class Reference
#include <json-schema.hpp>
Public Member Functions
json_validator (schema_loader=nullptr, format_checker=nullptr, content_checker=nullptr)
json_validator (const json &, schema_loader=nullptr, format_checker=nullptr, content_checker=nullptr)
json_validator (json &&, schema_loader=nullptr, format_checker=nullptr, content_checker=nullptr)
json_validator (json_validator &&)
json_validator & operator= (json_validator &&)
json_validator (json_validator const &)=delete
json_validator & operator= (json_validator const &)=delete
~json_validator ()
void set_root_schema (const json &)
void set_root_schema (json &&)
json validate (const json &) const
json validate (const json &, error_handler &, const json_uri &initial_uri=json_uri("#")) const
Private Attributes
std::unique_ptr< root_schema > root_
Detailed Description
Definition at line 166 of file json-schema.hpp.
Constructor & Destructor Documentation
json_validator() [1/5]
nlohmann::json_schema::json_validator::json_validator (schema_loader loader = nullptr, format_checker format = nullptr, content_checker content = nullptr)
Definition at line 1457 of file json-validator.cpp.
    : root_(std::unique_ptr<root_schema>(new root_schema(std::move(loader),
                                                         std::move(format),
                                                         std::move(content))))
{
}
References root_, and nlohmann::json_schema::root_schema::root_schema().
Referenced by json_validator(), json_validator(), main(), main(), and main().
json_validator() [2/5]
nlohmann::json_schema::json_validator::json_validator (const json & schema, schema_loader loader = nullptr, format_checker format = nullptr, content_checker content = nullptr)
Definition at line 1466 of file json-validator.cpp.
    : json_validator(std::move(loader),
                     std::move(format),
                     std::move(content))
{
    set_root_schema(schema);
}
References json_validator(), and set_root_schema().
Referenced by should_throw(), and nlohmann::json_patch::validateJsonPatch().
json_validator() [3/5]
nlohmann::json_schema::json_validator::json_validator (json && schema, schema_loader loader = nullptr, format_checker format = nullptr, content_checker content = nullptr)
Definition at line 1477 of file json-validator.cpp.
    : json_validator(std::move(loader),
                     std::move(format),
                     std::move(content))
{
    set_root_schema(std::move(schema));
}
References json_validator(), and set_root_schema().
Referenced by main().
json_validator() [4/5]
nlohmann::json_schema::json_validator::json_validator (json_validator &&) default
json_validator() [5/5]
nlohmann::json_schema::json_validator::json_validator (json_validator const &) delete
~json_validator()
nlohmann::json_schema::json_validator::~json_validator () default
Member Function Documentation
operator=() [1/2]
json_validator & nlohmann::json_schema::json_validator::operator= (json_validator &&) default
operator=() [2/2]
json_validator & nlohmann::json_schema::json_validator::operator= (json_validator const &) delete
set_root_schema() [1/2]
void nlohmann::json_schema::json_validator::set_root_schema (const json & schema)
Definition at line 1495 of file json-validator.cpp.
{
    root_->set_root_schema(schema);
}
References root_, and nlohmann::json_schema::root_schema::set_root_schema().
Referenced by json_validator(), mqtt::bridge::lib::BridgeStore::loadAndValidate(), main(), main(), main(), and anonymous_namespace{issue-105-verbose-combination-errors.cpp}::validate().
set_root_schema() [2/2]
void nlohmann::json_schema::json_validator::set_root_schema (json && schema)
Definition at line 1500 of file json-validator.cpp.
{
    root_->set_root_schema(std::move(schema));
}
References root_, and nlohmann::json_schema::root_schema::set_root_schema().
Referenced by json_validator().
validate() [1/2]
json nlohmann::json_schema::json_validator::validate (const json & instance) const
Definition at line 1505 of file json-validator.cpp.
{
    throwing_error_handler err;
    return validate(instance, err);
}
References validate().
Referenced by mqtt::bridge::lib::BridgeStore::loadAndValidate(), main(), main(), mqtt::bridge::lib::BridgeStore::patch(), mqtt::lib::JsonMappingReader::readMappingFromFile(), mqtt::lib::JsonMappingReader::rollbackTo(), anonymous_namespace{issue-105-verbose-combination-errors.cpp}::validate(), and nlohmann::json_patch::validateJsonPatch().
validate() [2/2]
json nlohmann::json_schema::json_validator::validate (const json & instance, error_handler & err, const json_uri & initial_uri = json_uri("#")) const
Definition at line 1511 of file json-validator.cpp.
{
    json::json_pointer ptr;
    json_patch patch;
    root_->validate(ptr, instance, patch, err, initial_uri);
    return patch;
}
References root_, and nlohmann::json_schema::root_schema::validate().
Referenced by main(), main(), main(), mqtt::lib::admin::makeMappingAdminRouter(), anonymous_namespace{issue-105-verbose-combination-errors.cpp}::validate(), and validate().
Member Data Documentation
root_
std::unique_ptr<root_schema> nlohmann::json_schema::json_validator::root_ private
Definition at line 168 of file json-schema.hpp.
Referenced by json_validator(), set_root_schema(), set_root_schema(), and validate().
The documentation for this class was generated from the following files:
lib/json-schema-validator/src/nlohmann/json-schema.hpp
lib/json-schema-validator/src/json-validator.cpp