MQTTSuite: inja::StatisticsVisitor Class Reference
inja::StatisticsVisitor Class Reference
A class for counting statistics on a Template.
#include <inja.hpp>
Public Member Functions
StatisticsVisitor ()
Public Member Functions inherited from inja::NodeVisitor
virtual ~NodeVisitor ()=default
Public Attributes
size_t variable_counter {0}
Private Member Functions
void visit (const BlockNode &node) override
void visit (const TextNode &) override
void visit (const ExpressionNode &) override
void visit (const LiteralNode &) override
void visit (const DataNode &) override
void visit (const FunctionNode &node) override
void visit (const ExpressionListNode &node) override
void visit (const StatementNode &) override
void visit (const ForStatementNode &) override
void visit (const ForArrayStatementNode &node) override
void visit (const ForObjectStatementNode &node) override
void visit (const IfStatementNode &node) override
void visit (const IncludeStatementNode &) override
void visit (const ExtendsStatementNode &) override
void visit (const BlockStatementNode &node) override
void visit (const SetStatementNode &) override
Detailed Description
A class for counting statistics on a Template.
Definition at line 834 of file inja.hpp.
Constructor & Destructor Documentation
StatisticsVisitor()
inja::StatisticsVisitor::StatisticsVisitor () inline explicit
Definition at line 899 of file inja.hpp.
{
        }
Referenced by inja::Template::count_variables().
Member Function Documentation
visit() [1/16]
void inja::StatisticsVisitor::visit (const BlockNode & node) inline override private virtual
Implements inja::NodeVisitor.
Definition at line 835 of file inja.hpp.
{
            for (const auto& n : node.nodes) {
                n->accept(*this);
            }
        }
References inja::AstNode::accept(), and inja::BlockNode::nodes.
visit() [2/16]
void inja::StatisticsVisitor::visit (const BlockStatementNode & node) inline override private virtual
Implements inja::NodeVisitor.
Definition at line 889 of file inja.hpp.
{
            node.block.accept(*this);
        }
References inja::BlockNode::accept(), and inja::BlockStatementNode::block.
visit() [3/16]
void inja::StatisticsVisitor::visit (const DataNode &) inline override private virtual
Implements inja::NodeVisitor.
Definition at line 848 of file inja.hpp.
{
            variable_counter += 1;
        }
References variable_counter.
visit() [4/16]
void inja::StatisticsVisitor::visit (const ExpressionListNode & node) inline override private virtual
Implements inja::NodeVisitor.
Definition at line 858 of file inja.hpp.
{
            node.root->accept(*this);
        }
References inja::ExpressionNode::accept(), and inja::ExpressionListNode::root.
visit() [5/16]
void inja::StatisticsVisitor::visit (const ExpressionNode &) inline override private virtual
Implements inja::NodeVisitor.
Definition at line 843 of file inja.hpp.
{
        }
visit() [6/16]
void inja::StatisticsVisitor::visit (const ExtendsStatementNode &) inline override private virtual
Implements inja::NodeVisitor.
Definition at line 886 of file inja.hpp.
{
        }
visit() [7/16]
void inja::StatisticsVisitor::visit (const ForArrayStatementNode & node) inline override private virtual
Implements inja::NodeVisitor.
Definition at line 867 of file inja.hpp.
{
            node.condition.accept(*this);
            node.body.accept(*this);
        }
References inja::BlockNode::accept(), inja::ExpressionListNode::accept(), inja::ForStatementNode::body, and inja::ForStatementNode::condition.
visit() [8/16]
void inja::StatisticsVisitor::visit (const ForObjectStatementNode & node) inline override private virtual
Implements inja::NodeVisitor.
Definition at line 872 of file inja.hpp.
{
            node.condition.accept(*this);
            node.body.accept(*this);
        }
References inja::BlockNode::accept(), inja::ExpressionListNode::accept(), inja::ForStatementNode::body, and inja::ForStatementNode::condition.
visit() [9/16]
void inja::StatisticsVisitor::visit (const ForStatementNode &) inline override private virtual
Implements inja::NodeVisitor.
Definition at line 864 of file inja.hpp.
{
        }
visit() [10/16]
void inja::StatisticsVisitor::visit (const FunctionNode & node) inline override private virtual
Implements inja::NodeVisitor.
Definition at line 852 of file inja.hpp.
{
            for (const auto& n : node.arguments) {
                n->accept(*this);
            }
        }
References inja::ExpressionNode::accept(), and inja::FunctionNode::arguments.
visit() [11/16]
void inja::StatisticsVisitor::visit (const IfStatementNode & node) inline override private virtual
Implements inja::NodeVisitor.
Definition at line 877 of file inja.hpp.
{
            node.condition.accept(*this);
            node.true_statement.accept(*this);
            node.false_statement.accept(*this);
        }
References inja::BlockNode::accept(), inja::ExpressionListNode::accept(), inja::IfStatementNode::condition, inja::IfStatementNode::false_statement, and inja::IfStatementNode::true_statement.
visit() [12/16]
void inja::StatisticsVisitor::visit (const IncludeStatementNode &) inline override private virtual
Implements inja::NodeVisitor.
Definition at line 883 of file inja.hpp.
{
        }
visit() [13/16]
void inja::StatisticsVisitor::visit (const LiteralNode &) inline override private virtual
Implements inja::NodeVisitor.
Definition at line 845 of file inja.hpp.
{
        }
visit() [14/16]
void inja::StatisticsVisitor::visit (const SetStatementNode &) inline override private virtual
Implements inja::NodeVisitor.
Definition at line 893 of file inja.hpp.
{
        }
visit() [15/16]
void inja::StatisticsVisitor::visit (const StatementNode &) inline override private virtual
Implements inja::NodeVisitor.
Definition at line 862 of file inja.hpp.
{
        }
visit() [16/16]
void inja::StatisticsVisitor::visit (const TextNode &) inline override private virtual
Implements inja::NodeVisitor.
Definition at line 841 of file inja.hpp.
{
        }
Member Data Documentation
variable_counter
size_t inja::StatisticsVisitor::variable_counter {0}
Definition at line 897 of file inja.hpp.
{0};
Referenced by inja::Template::count_variables(), and visit().
The documentation for this class was generated from the following file:
lib/inja.hpp