MQTTSuite: mqtt::lib::JsonMappingReader Class Reference
mqtt::lib::JsonMappingReader Class Reference
#include <JsonMappingReader.h>
Classes
struct VersionEntry
Public Member Functions
JsonMappingReader ()=delete
Static Public Member Functions
static nlohmann::json & readMappingFromFile (const std::string &mapFilePath)
static const nlohmann::json & getSchema ()
static void saveDraft (const std::string &mapFilePath, const nlohmann::json &content)
static nlohmann::json readDraftOrActive (const std::string &mapFilePath)
static void deployDraft (const std::string &mapFilePath)
static void discardDraft (const std::string &mapFilePath)
static std::string getDraftPath (const std::string &mapFilePath)
static std::vector< VersionEntry > getHistory (const std::string &mapFilePath)
static void rollbackTo (const std::string &mapFilePath, const std::string &versionId)
Static Private Attributes
static nlohmann::json mappingJsonSchema = nlohmann::json::parse(mappingJsonSchemaString)
static const std::string mappingJsonSchemaString
static nlohmann::json mapFileJson
static nlohmann::json mapFileJsonDefaultPatched
Detailed Description
Definition at line 57 of file JsonMappingReader.h.
Constructor & Destructor Documentation
JsonMappingReader()
mqtt::lib::JsonMappingReader::JsonMappingReader () delete
Member Function Documentation
deployDraft()
void mqtt::lib::JsonMappingReader::deployDraft (const std::string & mapFilePath) static
Definition at line 165 of file JsonMappingReader.cpp.
{
        std::string draftPath = getDraftPath(mapFilePath);
        if (!fs::exists(draftPath))
            return;
        // 1. Inject creation timestamp into draft
        try {
            std::ifstream f(draftPath);
            nlohmann::json j;
            f >> j;
            f.close();
            auto now = std::chrono::system_clock::now();
            std::time_t now_c = std::chrono::system_clock::to_time_t(now);
            std::stringstream ss;
            ss << std::put_time(std::gmtime(&now_c), "%Y-%m-%dT%H:%M:%SZ");
            if (!j.contains("meta"))
                j["meta"] = nlohmann::json::object();
            j["meta"]["created"] = ss.str();
            j["meta"]["version"] = std::to_string(std::chrono::duration_cast<std::chrono::seconds>(now.time_since_epoch()).count());
            std::ofstream out(draftPath, std::ios::trunc);
            out << j.dump(2);
            out.close();
        } catch (const std::exception& e) {
            VLOG(1) << "Failed to inject metadata into draft: " << e.what();
        }
        // 2. Backup current active file
        if (fs::exists(mapFilePath)) {
            fs::path versionDir = fs::path(mapFilePath).parent_path() / "versions";
            if (!fs::exists(versionDir)) {
                fs::create_directories(versionDir);
            }
            auto now = std::chrono::system_clock::now();
            auto timestamp = std::chrono::duration_cast<std::chrono::seconds>(now.time_since_epoch()).count();
            std::string filename = fs::path(mapFilePath).filename().string();
            std::string backupPath = versionDir / (filename + "." + std::to_string(timestamp));
            fs::copy_file(mapFilePath, backupPath, fs::copy_options::overwrite_existing);
            // 3. Prune old versions (Keep last 50)
            try {
                std::vector<fs::path> versions;
                for (const auto& entry : fs::directory_iterator(versionDir)) {
                    if (entry.path().filename().string().starts_with(filename + ".")) {
                        versions.push_back(entry.path());
                    }
                }
                if (versions.size() > 50) {
                    std::sort(versions.begin(), versions.end(), [](const fs::path& a, const fs::path& b) {
                        return fs::last_write_time(a) < fs::last_write_time(b); // Oldest first
                    });
                    for (size_t i = 0; i < versions.size() - 50; ++i) {
                        fs::remove(versions[i]);
                    }
                }
            } catch (...) {
            }
        }
        // 4. Promote draft to active
        fs::rename(draftPath, mapFilePath);
        // Invalidate cache so next readMappingFromFile reloads it
        mapFileJson.clear();
    }
References getDraftPath(), and mapFileJson.
Referenced by mqtt::lib::admin::makeMappingAdminRouter().
discardDraft()
void mqtt::lib::JsonMappingReader::discardDraft (const std::string & mapFilePath) static
Definition at line 235 of file JsonMappingReader.cpp.
{
        std::string draftPath = getDraftPath(mapFilePath);
        if (fs::exists(draftPath)) {
            fs::remove(draftPath);
        }
    }
References getDraftPath().
Referenced by rollbackTo().
getDraftPath()
std::string mqtt::lib::JsonMappingReader::getDraftPath (const std::string & mapFilePath) static
Definition at line 134 of file JsonMappingReader.cpp.
{
        return mapFilePath + ".draft";
    }
Referenced by deployDraft(), discardDraft(), readDraftOrActive(), and saveDraft().
getHistory()
std::vector< JsonMappingReader::VersionEntry > mqtt::lib::JsonMappingReader::getHistory (const std::string & mapFilePath) static
Definition at line 242 of file JsonMappingReader.cpp.
{
        std::vector<VersionEntry> history;
        fs::path versionDir = fs::path(mapFilePath).parent_path() / "versions";
        std::string baseName = fs::path(mapFilePath).filename().string();
        if (!fs::exists(versionDir))
            return history;
        for (const auto& entry : fs::directory_iterator(versionDir)) {
            if (entry.path().filename().string().starts_with(baseName + ".")) {
                VersionEntry v;
                v.filename = entry.path().string();
                // Extract ID (timestamp) from filename extension
                v.id = entry.path().extension().string().substr(1);
                // Peek inside JSON to get the comment
                try {
                    std::ifstream f(v.filename);
                    nlohmann::json j;
                    f >> j;
                    if (j.contains("meta")) {
                        if (j["meta"].contains("comment"))
                            v.comment = j["meta"]["comment"];
                        if (j["meta"].contains("created"))
                            v.date = j["meta"]["created"];
                    }
                } catch (...) {
                }
                // Fallback date if not in meta
                if (v.date.empty()) {
                    try {
                        long long ts = std::stoll(v.id);
                        std::time_t t = static_cast<std::time_t>(ts);
                        std::stringstream ss;
                        ss << std::put_time(std::gmtime(&t), "%Y-%m-%dT%H:%M:%SZ");
                        v.date = ss.str();
                    } catch (...) {
                        v.date = "Unknown";
                    }
                }
                history.push_back(v);
            }
        }
        // Sort by ID (descending)
        std::sort(history.begin(), history.end(), [](const VersionEntry& a, const VersionEntry& b) {
            // String comparison of timestamps works if they are same length, but better to be safe
            try {
                return std::stoll(a.id) > std::stoll(b.id);
            } catch (...) {
                return a.id > b.id;
            }
        });
        return history;
    }
References mqtt::lib::JsonMappingReader::VersionEntry::id.
Referenced by mqtt::lib::admin::makeMappingAdminRouter().
getSchema()
const nlohmann::json & mqtt::lib::JsonMappingReader::getSchema () static
Definition at line 130 of file JsonMappingReader.cpp.
{
        return mappingJsonSchema;
    }
References mappingJsonSchema.
Referenced by mqtt::lib::admin::makeMappingAdminRouter().
readDraftOrActive()
nlohmann::json mqtt::lib::JsonMappingReader::readDraftOrActive (const std::string & mapFilePath) static
Definition at line 146 of file JsonMappingReader.cpp.
{
        std::string draftPath = getDraftPath(mapFilePath);
        if (fs::exists(draftPath)) {
            std::ifstream f(draftPath);
            if (f) {
                nlohmann::json j;
                f >> j;
                return j;
            }
        }
        // Fallback to active file
        std::ifstream f(mapFilePath);
        if (!f)
            throw std::runtime_error("Cannot open mapping file: " + mapFilePath);
        nlohmann::json j;
        f >> j;
        return j;
    }
References getDraftPath().
Referenced by mqtt::lib::admin::makeMappingAdminRouter().
readMappingFromFile()
nlohmann::json & mqtt::lib::JsonMappingReader::readMappingFromFile (const std::string & mapFilePath) static
Definition at line 77 of file JsonMappingReader.cpp.
{
        if (mapFileJson.empty()) {
            if (!mapFilePath.empty()) {
                std::ifstream mapFile(mapFilePath);
                if (mapFile.is_open()) {
                    VLOG(1) << "MappingFilePath: " << mapFilePath;
                    try {
                        mapFile >> mapFileJson;
                        try {
                            const nlohmann::json_schema::json_validator validator(
                                mappingJsonSchema, nullptr, nlohmann::json_schema::default_string_format_check);
                            try {
                                const nlohmann::json defaultPatch = validator.validate(mapFileJson);
                                try {
                                    mapFileJsonDefaultPatched = mapFileJson.patch(defaultPatch);
                                    VLOG(0) << "Patched: \n" << mapFileJson.dump(4);
                                } catch (const std::exception& e) {
                                    VLOG(1) << e.what();
                                    VLOG(1) << "Patching JSON with default patch failed:\n" << defaultPatch.dump(4);
                                    mapFileJson.clear();
                                }
                            } catch (const std::exception& e) {
                                VLOG(1) << "  Validating JSON failed:\n" << mapFileJson.dump(4);
                                VLOG(1) << "    " << e.what();
                                mapFileJson.clear();
                            }
                        } catch (const std::exception& e) {
                            VLOG(1) << e.what();
                            VLOG(1) << "Setting root json mapping schema failed:\n" << mappingJsonSchema.dump(4);
                            mapFileJson.clear();
                        }
                    } catch (const std::exception& e) {
                        VLOG(1) << "JSON map file parsing failed: " << e.what() << " at " << mapFile.tellg();
                        mapFileJson.clear();
                    }
                    mapFile.close();
                } else {
                    VLOG(1) << "MappingFilePath: " << mapFilePath << " not found";
                }
            } else {
                VLOG(1) << "MappingFilePath empty";
            }
        }
        return mapFileJsonDefaultPatched;
    }
References nlohmann::json_schema::default_string_format_check(), mapFileJson, mapFileJsonDefaultPatched, mappingJsonSchema, and nlohmann::json_schema::json_validator::validate().
Referenced by mqtt::mqttbroker::SocketContextFactory::create(), mqtt::mqttintegrator::SocketContextFactory::create(), and mqtt::mqttintegrator::websocket::SubProtocolFactory::create().
rollbackTo()
void mqtt::lib::JsonMappingReader::rollbackTo (const std::string & mapFilePath, const std::string & versionId) static
Definition at line 299 of file JsonMappingReader.cpp.
{
        fs::path versionDir = fs::path(mapFilePath).parent_path() / "versions";
        std::string baseName = fs::path(mapFilePath).filename().string();
        fs::path backupPath = versionDir / (baseName + "." + versionId);
        if (!fs::exists(backupPath)) {
            throw std::runtime_error("Version not found: " + versionId);
        }
        // Validate before rollback
        try {
            std::ifstream f(backupPath);
            nlohmann::json j;
            f >> j;
            const nlohmann::json_schema::json_validator validator(
                mappingJsonSchema, nullptr, nlohmann::json_schema::default_string_format_check);
            validator.validate(j);
        } catch (const std::exception& e) {
            throw std::runtime_error(std::string("Cannot rollback: Version is invalid against current schema: ") + e.what());
        }
        // Overwrite active file
        fs::copy_file(backupPath, mapFilePath, fs::copy_options::overwrite_existing);
        // Delete any existing draft to avoid confusion
        discardDraft(mapFilePath);
        mapFileJson.clear();
    }
References nlohmann::json_schema::default_string_format_check(), discardDraft(), mapFileJson, mappingJsonSchema, and nlohmann::json_schema::json_validator::validate().
Referenced by mqtt::lib::admin::makeMappingAdminRouter().
saveDraft()
void mqtt::lib::JsonMappingReader::saveDraft (const std::string & mapFilePath, const nlohmann::json & content) static
Definition at line 138 of file JsonMappingReader.cpp.
{
        std::ofstream out(getDraftPath(mapFilePath), std::ios::trunc);
        if (!out) {
            throw std::runtime_error("Cannot open draft file for writing: " + getDraftPath(mapFilePath));
        }
        out << content.dump(2) << std::endl;
    }
References getDraftPath().
Referenced by mqtt::lib::admin::makeMappingAdminRouter().
Member Data Documentation
mapFileJson
nlohmann::json mqtt::lib::JsonMappingReader::mapFileJson static private
Definition at line 87 of file JsonMappingReader.h.
Referenced by deployDraft(), readMappingFromFile(), and rollbackTo().
mapFileJsonDefaultPatched
nlohmann::json mqtt::lib::JsonMappingReader::mapFileJsonDefaultPatched static private
Definition at line 88 of file JsonMappingReader.h.
Referenced by readMappingFromFile().
mappingJsonSchema
nlohmann::json mqtt::lib::JsonMappingReader::mappingJsonSchema = nlohmann::json::parse(mappingJsonSchemaString) static private
Definition at line 84 of file JsonMappingReader.h.
Referenced by getSchema(), readMappingFromFile(), and rollbackTo().
mappingJsonSchemaString
const std::string mqtt::lib::JsonMappingReader::mappingJsonSchemaString static private
Definition at line 85 of file JsonMappingReader.h.
The documentation for this class was generated from the following files:
lib/JsonMappingReader.h
lib/JsonMappingReader.cpp