MQTTSuite: mqtt::lib::MqttMapper::DelayedQueue Class Reference
mqtt::lib::MqttMapper::DelayedQueue Class Reference
Public Member Functions
DelayedQueue (MqttMapper *mqttMapper)
~DelayedQueue ()
void delayAbsolute (const utils::Timeval &timeval, const std::string &topic, const std::string &message, uint8_t qoS, bool retain)
void delayPublish (const utils::Timeval &timeval, const std::string &topic, const std::string &message, uint8_t qoS, bool retain)
bool empty () const
std::size_t size () const
ScheduledPublish const & top () const
void pop ()
Private Member Functions
void processDue ()
void armDelayTimer ()
Private Attributes
MqttMapper * mqttMapper
std::size_t nextSeq = 0
std::priority_queue< ScheduledPublish, std::vector< ScheduledPublish >, EarlierFirst > minHeap
core::timer::Timer delayTimer
Detailed Description
Definition at line 126 of file MqttMapper.h.
Constructor & Destructor Documentation
DelayedQueue()
mqtt::lib::MqttMapper::DelayedQueue::DelayedQueue (MqttMapper * mqttMapper)
Definition at line 433 of file MqttMapper.cpp.
        : mqttMapper(mqttMapper) {
    }
References mqttMapper.
Referenced by mqtt::lib::MqttMapper::MqttMapper().
~DelayedQueue()
mqtt::lib::MqttMapper::DelayedQueue::~DelayedQueue ()
Definition at line 437 of file MqttMapper.cpp.
{
        delayTimer.cancel();
    }
References delayTimer.
Member Function Documentation
armDelayTimer()
void mqtt::lib::MqttMapper::DelayedQueue::armDelayTimer () private
Definition at line 458 of file MqttMapper.cpp.
{
        delayTimer.cancel();
        auto delay = top().when - utils::Timeval::currentTime();
        // clamp negative delay to 0 (if top().when is already due)
        if (delay < utils::Timeval{}) {
            delay = utils::Timeval{};
        }
        delayTimer = core::timer::Timer::singleshotTimer(
            [this]() {
                processDue();
                if (!empty()) {
                    armDelayTimer(); // re-arm for the next item
                }
            },
            delay);
    }
References armDelayTimer(), delayTimer, empty(), processDue(), top(), and mqtt::lib::MqttMapper::ScheduledPublish::when.
Referenced by armDelayTimer(), and delayPublish().
delayAbsolute()
void mqtt::lib::MqttMapper::DelayedQueue::delayAbsolute (const utils::Timeval & timeval, const std::string & topic, const std::string & message, uint8_t qoS, bool retain)
delayPublish()
void mqtt::lib::MqttMapper::DelayedQueue::delayPublish (const utils::Timeval & timeval, const std::string & topic, const std::string & message, uint8_t qoS, bool retain)
Definition at line 479 of file MqttMapper.cpp.
{
        minHeap.push(ScheduledPublish{
            utils::Timeval::currentTime() + timeval, timeval, nextSeq++, std::move(topic), std::move(message), qoS, retain});
        armDelayTimer();
    }
References armDelayTimer(), minHeap, and nextSeq.
Referenced by mqtt::lib::MqttMapper::publishMapping().
empty()
bool mqtt::lib::MqttMapper::DelayedQueue::empty () const
Definition at line 487 of file MqttMapper.cpp.
{
        return minHeap.empty();
    }
References minHeap.
Referenced by armDelayTimer(), and processDue().
pop()
void mqtt::lib::MqttMapper::DelayedQueue::pop ()
Definition at line 499 of file MqttMapper.cpp.
{
        minHeap.pop();
    }
References minHeap.
Referenced by processDue().
processDue()
void mqtt::lib::MqttMapper::DelayedQueue::processDue () private
Definition at line 441 of file MqttMapper.cpp.
{
        const auto now = utils::Timeval::currentTime();
        while (!empty() && top().when <= now) {
            const auto& sheduledPublish = top();
            VLOG(1) << "Publish delayed message";
            VLOG(1) << "  Topic: " << sheduledPublish.topic;
            VLOG(1) << "  Message: " << sheduledPublish.message;
            VLOG(1) << "  QoS: " << static_cast<int>(sheduledPublish.qoS);
            VLOG(1) << "  retain: " << sheduledPublish.retain;
            VLOG(1) << "  Delay: " << sheduledPublish.delay;
            mqttMapper->publishMapping(sheduledPublish.topic, sheduledPublish.message, sheduledPublish.qoS, sheduledPublish.retain);
            pop();
        }
    }
References mqtt::lib::MqttMapper::ScheduledPublish::delay, empty(), mqtt::lib::MqttMapper::ScheduledPublish::message, mqttMapper, pop(), mqtt::lib::MqttMapper::publishMapping(), mqtt::lib::MqttMapper::ScheduledPublish::qoS, mqtt::lib::MqttMapper::ScheduledPublish::retain, top(), mqtt::lib::MqttMapper::ScheduledPublish::topic, and mqtt::lib::MqttMapper::ScheduledPublish::when.
Referenced by armDelayTimer().
size()
std::size_t mqtt::lib::MqttMapper::DelayedQueue::size () const
Definition at line 491 of file MqttMapper.cpp.
{
        return minHeap.size();
    }
References minHeap.
top()
const MqttMapper::ScheduledPublish & mqtt::lib::MqttMapper::DelayedQueue::top () const
Definition at line 495 of file MqttMapper.cpp.
{
        return minHeap.top();
    }
References minHeap.
Referenced by armDelayTimer(), and processDue().
Member Data Documentation
delayTimer
core::timer::Timer mqtt::lib::MqttMapper::DelayedQueue::delayTimer private
Definition at line 149 of file MqttMapper.h.
Referenced by armDelayTimer(), and ~DelayedQueue().
minHeap
std::priority_queue<ScheduledPublish, std::vector<ScheduledPublish>, EarlierFirst> mqtt::lib::MqttMapper::DelayedQueue::minHeap private
Definition at line 147 of file MqttMapper.h.
Referenced by delayPublish(), empty(), pop(), size(), and top().
mqttMapper
MqttMapper* mqtt::lib::MqttMapper::DelayedQueue::mqttMapper private
Definition at line 145 of file MqttMapper.h.
Referenced by DelayedQueue(), and processDue().
nextSeq
std::size_t mqtt::lib::MqttMapper::DelayedQueue::nextSeq = 0 private
Definition at line 146 of file MqttMapper.h.
Referenced by delayPublish().
The documentation for this class was generated from the following files:
lib/MqttMapper.h
lib/MqttMapper.cpp