MQTTSuite: mqtt::bridge::lib::BridgeStore Class Reference
mqtt::bridge::lib::BridgeStore Class Reference
#include <BridgeStore.h>
Public Member Functions
BridgeStore (const BridgeStore &)=delete
BridgeStore (BridgeStore &&)=delete
BridgeStore & operator= (const BridgeStore &)=delete
BridgeStore & operator= (const BridgeStore &&)=delete
bool loadAndValidate (const std::string &fileName)
bool patch (const nlohmann::json &jsonPatch)
void activateStaged ()
Broker * getBroker (const std::string &fullInstanceName)
const std::map< std::string, Broker > & getBrokers () const
const std::map< const std::string, Bridge > & getBridgeMap ()
const nlohmann::json & getBridgesConfigJson ()
void mqttConnected (Broker &broker, mqtt::bridge::lib::Mqtt *mqtt) const
void mqttDisconnected (Broker &broker, mqtt::bridge::lib::Mqtt *mqtt) const
Static Public Member Functions
static BridgeStore & instance ()
Private Member Functions
BridgeStore ()=default
Private Attributes
std::map< const std::string, Bridge > bridgeMap
nlohmann::json bridgesConfigJsonActive
nlohmann::json bridgesConfigJsonStaged
nlohmann::json_schema::json_validator validator
std::string fileName
Detailed Description
Definition at line 61 of file BridgeStore.h.
Constructor & Destructor Documentation
BridgeStore() [1/3]
mqtt::bridge::lib::BridgeStore::BridgeStore () private default
BridgeStore() [2/3]
mqtt::bridge::lib::BridgeStore::BridgeStore (const BridgeStore &) delete
BridgeStore() [3/3]
mqtt::bridge::lib::BridgeStore::BridgeStore (BridgeStore &&) delete
Member Function Documentation
activateStaged()
void mqtt::bridge::lib::BridgeStore::activateStaged ()
Definition at line 165 of file BridgeStore.cpp.
{
        for (auto& [fullInstanceName, bridge] : bridgeMap) {
            bridge.clear();
        }
        bridgeMap.clear();
        bridgesConfigJsonActive = bridgesConfigJsonStaged;
        std::ofstream ofs(fileName, std::ios::binary);
        ofs << bridgesConfigJsonActive.dump(4);
        ofs.close();
        for (const nlohmann::json& bridgeConfigJson : bridgesConfigJsonActive["bridges"]) {
            bridgeMap.emplace(bridgeConfigJson["name"],
                              Bridge{bridgeConfigJson["name"], bridgeConfigJson["prefix"], bridgeConfigJson["disabled"]});
            for (const nlohmann::json& brokerConfigJson : bridgeConfigJson["brokers"]) {
                std::list<iot::mqtt::Topic> topics;
                for (const nlohmann::json& topicJson : brokerConfigJson["topics"]) {
                    if (!topicJson["topic"].get<std::string>().empty()) {
                        topics.emplace_back(topicJson["topic"], // cppcheck-suppress useStlAlgorithm
                                            topicJson["qos"]);
                    }
                }
                const nlohmann::json& mqtt = brokerConfigJson["mqtt"];
                const nlohmann::json& network = brokerConfigJson["network"];
                const std::string fullInstanceName =
                    bridgeMap.find(bridgeConfigJson["name"])->second.getName() + "+" + network["instance_name"].get<std::string>();
                bridgeMap.find(bridgeConfigJson["name"])
                    ->second.addBroker(fullInstanceName,
                                       Broker(bridgeMap.find(bridgeConfigJson["name"])->second,
                                              brokerConfigJson["session_store"],
                                              fullInstanceName,
                                              network["protocol"],
                                              network["encryption"],
                                              network["transport"],
                                              network[network["protocol"]],
                                              mqtt["client_id"],
                                              mqtt["keep_alive"],
                                              mqtt["clean_session"],
                                              mqtt["will_topic"],
                                              mqtt["will_message"],
                                              mqtt["will_qos"],
                                              mqtt["will_retain"],
                                              mqtt["username"],
                                              mqtt["password"],
                                              mqtt["loop_prevention"],
                                              brokerConfigJson["prefix"],
                                              brokerConfigJson["disabled"],
                                              topics));
            }
        }
    }
References bridgeMap, bridgesConfigJsonActive, bridgesConfigJsonStaged, and fileName.
Referenced by loadAndValidate(), and tryRestartBridges().
getBridgeMap()
const std::map< const std::string, Bridge > & mqtt::bridge::lib::BridgeStore::getBridgeMap ()
Definition at line 225 of file BridgeStore.cpp.
{
        return bridgeMap;
    }
References bridgeMap.
getBridgesConfigJson()
const nlohmann::json & mqtt::bridge::lib::BridgeStore::getBridgesConfigJson ()
Definition at line 229 of file BridgeStore.cpp.
{
        return bridgesConfigJsonActive;
    }
References bridgesConfigJsonActive.
getBroker()
Broker * mqtt::bridge::lib::BridgeStore::getBroker (const std::string & fullInstanceName)
Definition at line 258 of file BridgeStore.cpp.
{
        auto [bridgeName, instanceName] = split_plus(fullInstanceName);
        return bridgeMap.find(bridgeName)->second.getBroker(fullInstanceName);
    }
References bridgeMap.
Referenced by mqtt::bridge::SocketContextFactory::create(), and mqtt::mqttbridge::websocket::SubProtocolFactory::create().
getBrokers()
const std::map< std::string, Broker > & mqtt::bridge::lib::BridgeStore::getBrokers () const
instance()
BridgeStore & mqtt::bridge::lib::BridgeStore::instance () static
Definition at line 65 of file BridgeStore.cpp.
{
        static BridgeStore bridgeConfigLoader;
        return bridgeConfigLoader;
    }
Referenced by mqtt::bridge::SocketContextFactory::create(), mqtt::mqttbridge::websocket::SubProtocolFactory::create(), main(), mqtt::bridge::lib::Mqtt::onConnack(), mqtt::bridge::lib::Mqtt::onDisconnected(), and tryRestartBridges().
loadAndValidate()
bool mqtt::bridge::lib::BridgeStore::loadAndValidate (const std::string & fileName)
Definition at line 71 of file BridgeStore.cpp.
{
        this->fileName = fileName;
        bool success = bridgeMap.empty();
        if (success) {
            try {
                const nlohmann::json bridgeJsonSchema = nlohmann::json::parse(bridgeJsonSchemaString);
                validator.set_root_schema(bridgeJsonSchema);
                if (!fileName.empty()) {
                    std::ifstream bridgeConfigJsonFile(fileName);
                    if (bridgeConfigJsonFile.is_open()) {
                        VLOG(1) << "Bridge config JSON: " << fileName;
                        try {
                            bridgeConfigJsonFile >> bridgesConfigJsonStaged;
                            try {
                                try {
                                    const nlohmann::json defaultPatch = validator.validate(bridgesConfigJsonStaged);
                                    try {
                                        bridgesConfigJsonStaged = bridgesConfigJsonStaged.patch(defaultPatch);
                                        activateStaged();
                                        success = true;
                                    } catch (const std::exception& e) {
                                        VLOG(1) << "  Patching JSON with default patch failed:\n" << defaultPatch.dump(4);
                                        VLOG(1) << "    " << e.what();
                                    }
                                } catch (const std::exception& e) {
                                    VLOG(1) << "  Validating JSON failed:\n" << bridgesConfigJsonActive.dump(4);
                                    VLOG(1) << "    " << e.what();
                                }
                            } catch (const std::exception& e) {
                                VLOG(1) << "  Setting root json mapping schema failed:\n" << bridgeJsonSchema.dump(4);
                                VLOG(1) << "    " << e.what();
                            }
                        } catch (const std::exception& e) {
                            VLOG(1) << "  JSON map file parsing failed:" << e.what() << " at " << bridgeConfigJsonFile.tellg();
                        }
                        bridgeConfigJsonFile.close();
                    } else {
                        VLOG(1) << "BridgeJsonConfig: " << fileName << " not found";
                    }
                } else {
                    // Do not log missing path. In regular use this missing option is captured by the command line interface
                }
            } catch (const std::exception& e) {
                VLOG(1) << "Parsing schema failed: " << e.what();
                VLOG(1) << bridgeJsonSchemaString;
            }
        } else {
            VLOG(1) << "MappingFile already loaded and validated";
        }
        return success;
    }
References activateStaged(), bridgeMap, bridgesConfigJsonActive, bridgesConfigJsonStaged, fileName, nlohmann::json_schema::json_validator::set_root_schema(), nlohmann::json_schema::json_validator::validate(), and validator.
Referenced by main().
mqttConnected()
void mqtt::bridge::lib::BridgeStore::mqttConnected (Broker & broker, mqtt::bridge::lib::Mqtt * mqtt) const
Definition at line 233 of file BridgeStore.cpp.
{
        broker.getBridge().addMqtt(mqtt);
        bool allConnected = true;
        for (const auto& [bridgeName, bridge] : bridgeMap) {
            allConnected &= bridge.getAllConnected1();
        }
        if (allConnected) {
            mqtt::bridge::lib::SSEDistributor::instance().bridgesStarted();
        }
    }
References mqtt::bridge::lib::Bridge::addMqtt(), mqtt::bridge::lib::SSEDistributor::bridgesStarted(), mqtt::bridge::lib::Broker::getBridge(), and mqtt::bridge::lib::SSEDistributor::instance().
Referenced by mqtt::bridge::lib::Mqtt::onConnack().
mqttDisconnected()
void mqtt::bridge::lib::BridgeStore::mqttDisconnected (Broker & broker, mqtt::bridge::lib::Mqtt * mqtt) const
Definition at line 247 of file BridgeStore.cpp.
{
        broker.getBridge().removeMqtt(mqtt);
    }
References mqtt::bridge::lib::Broker::getBridge(), and mqtt::bridge::lib::Bridge::removeMqtt().
Referenced by mqtt::bridge::lib::Mqtt::onDisconnected().
operator=() [1/2]
BridgeStore & mqtt::bridge::lib::BridgeStore::operator= (const BridgeStore &&) delete
operator=() [2/2]
BridgeStore & mqtt::bridge::lib::BridgeStore::operator= (const BridgeStore &) delete
patch()
bool mqtt::bridge::lib::BridgeStore::patch (const nlohmann::json & jsonPatch)
Definition at line 134 of file BridgeStore.cpp.
{
        bool success = false;
        try {
            bridgesConfigJsonStaged = bridgesConfigJsonActive.patch(jsonPatch);
            try {
                const nlohmann::json defaultPatch = validator.validate(bridgesConfigJsonStaged);
                try {
                    bridgesConfigJsonStaged = bridgesConfigJsonStaged.patch(defaultPatch);
                    success = true;
                } catch (const std::exception& e) {
                    VLOG(1) << "  Patching JSON with default patch failed:\n" << defaultPatch.dump(4);
                    VLOG(1) << "    " << e.what();
                }
            } catch (const std::exception& e) {
                VLOG(1) << "  Validating JSON failed:\n" << bridgesConfigJsonActive.dump(4);
                VLOG(1) << "    " << e.what();
            }
        } catch (const std::exception& e) {
            VLOG(1) << "  Default Patch:\n" << bridgesConfigJsonActive.dump(4);
            VLOG(1) << "  Patching JSON with update failed:\n" << jsonPatch.dump(4);
            VLOG(1) << "    " << e.what();
        }
        return success;
    }
References bridgesConfigJsonActive, bridgesConfigJsonStaged, nlohmann::json_schema::json_validator::validate(), and validator.
Member Data Documentation
bridgeMap
std::map<const std::string, Bridge> mqtt::bridge::lib::BridgeStore::bridgeMap private
Definition at line 89 of file BridgeStore.h.
Referenced by activateStaged(), getBridgeMap(), getBroker(), and loadAndValidate().
bridgesConfigJsonActive
nlohmann::json mqtt::bridge::lib::BridgeStore::bridgesConfigJsonActive private
Definition at line 91 of file BridgeStore.h.
Referenced by activateStaged(), getBridgesConfigJson(), loadAndValidate(), and patch().
bridgesConfigJsonStaged
nlohmann::json mqtt::bridge::lib::BridgeStore::bridgesConfigJsonStaged private
Definition at line 92 of file BridgeStore.h.
Referenced by activateStaged(), loadAndValidate(), and patch().
fileName
std::string mqtt::bridge::lib::BridgeStore::fileName private
Definition at line 95 of file BridgeStore.h.
Referenced by activateStaged(), and loadAndValidate().
validator
nlohmann::json_schema::json_validator mqtt::bridge::lib::BridgeStore::validator private
Definition at line 93 of file BridgeStore.h.
Referenced by loadAndValidate(), and patch().
The documentation for this class was generated from the following files:
mqttbridge/lib/BridgeStore.h
mqttbridge/lib/BridgeStore.cpp