MQTTSuite: mqtt::lib::plugins::storage_plugin::Storage Class Reference
mqtt::lib::plugins::storage_plugin::Storage Class Reference
#include <Storage.h>
Public Member Functions
Storage (const Storage &)=delete
Storage & operator= (const Storage &)=delete
~Storage ()=default
Static Public Member Functions
static Storage & instance ()
static void store (const inja::Arguments &args)
static const std::string & recall (const inja::Arguments &args)
static int recall_as_int (const inja::Arguments &args)
static double recall_as_float (const inja::Arguments &args)
static bool is_empty (const inja::Arguments &args)
static bool exists (const inja::Arguments &args)
Private Member Functions
Storage ()=default
Private Attributes
std::map< std::string, std::string > storage
Detailed Description
Definition at line 70 of file Storage.h.
Constructor & Destructor Documentation
Storage() [1/2]
mqtt::lib::plugins::storage_plugin::Storage::Storage () private default
Storage() [2/2]
mqtt::lib::plugins::storage_plugin::Storage::Storage (const Storage &) delete
~Storage()
mqtt::lib::plugins::storage_plugin::Storage::~Storage () default
Member Function Documentation
exists()
bool mqtt::lib::plugins::storage_plugin::Storage::exists (const inja::Arguments & args) static
Definition at line 109 of file Storage.cpp.
{
        return instance().storage.contains(args.at(0)->get<std::string>());
    }
References instance(), and storage.
Referenced by is_empty(), recall_as_float(), and recall_as_int().
instance()
Storage & mqtt::lib::plugins::storage_plugin::Storage::instance () static
Definition at line 57 of file Storage.cpp.
{
        static Storage storage;
        return storage;
    }
Referenced by exists(), is_empty(), recall(), recall_as_float(), recall_as_int(), and store().
is_empty()
bool mqtt::lib::plugins::storage_plugin::Storage::is_empty (const inja::Arguments & args) static
Definition at line 99 of file Storage.cpp.
{
        bool result = true;
        if (exists(args)) {
            result = instance().storage[args.at(0)->get<std::string>()].empty();
        }
        return result;
    }
References exists(), instance(), and storage.
operator=()
Storage & mqtt::lib::plugins::storage_plugin::Storage::operator= (const Storage &) delete
recall()
const std::string & mqtt::lib::plugins::storage_plugin::Storage::recall (const inja::Arguments & args) static
Definition at line 67 of file Storage.cpp.
{
        return instance().storage[args.at(0)->get<std::string>()];
    }
References instance(), and storage.
recall_as_float()
double mqtt::lib::plugins::storage_plugin::Storage::recall_as_float (const inja::Arguments & args) static
Definition at line 85 of file Storage.cpp.
{
        double result = 0;
        if (exists(args)) {
            try {
                result = std::stod(instance().storage[args.at(0)->get<std::string>()]);
            } catch (const std::logic_error&) {
                // no error if not exist - just return '0'
            }
        }
        return result;
    }
References exists(), instance(), and storage.
recall_as_int()
int mqtt::lib::plugins::storage_plugin::Storage::recall_as_int (const inja::Arguments & args) static
Definition at line 71 of file Storage.cpp.
{
        int result = 0;
        if (exists(args)) {
            try {
                result = std::stoi(instance().storage[args.at(0)->get<std::string>()]);
            } catch (const std::logic_error&) {
                // no error if not exist - just return '0'
            }
        }
        return result;
    }
References exists(), instance(), and storage.
store()
void mqtt::lib::plugins::storage_plugin::Storage::store (const inja::Arguments & args) static
Definition at line 63 of file Storage.cpp.
{
        instance().storage[args.at(0)->get<std::string>()] = args.at(1)->get<std::string>();
    }
References instance(), and storage.
Member Data Documentation
storage
std::map<std::string, std::string> mqtt::lib::plugins::storage_plugin::Storage::storage private
Definition at line 95 of file Storage.h.
Referenced by exists(), is_empty(), recall(), recall_as_float(), recall_as_int(), and store().
The documentation for this class was generated from the following files:
lib/plugins/storage/Storage.h
lib/plugins/storage/Storage.cpp