MQTTSuite: nlohmann::json_uri Class Reference
nlohmann::json_uri Class Reference
#include <json-schema.hpp>
Public Member Functions
json_uri (const std::string &uri)
const std::string & scheme () const
const std::string & authority () const
const std::string & path () const
const json::json_pointer & pointer () const
const std::string & identifier () const
std::string fragment () const
std::string url () const
std::string location () const
json_uri derive (const std::string &uri) const
json_uri append (const std::string &field) const
std::string to_string () const
Static Public Member Functions
static std::string escape (const std::string &)
Protected Member Functions
void update (const std::string &uri)
std::tuple< std::string, std::string, std::string, std::string, std::string > as_tuple () const
Private Attributes
std::string urn_
std::string scheme_
std::string authority_
std::string path_
json::json_pointer pointer_
std::string identifier_
Friends
bool operator< (const json_uri &l, const json_uri &r)
bool operator== (const json_uri &l, const json_uri &r)
std::ostream & operator<< (std::ostream &os, const json_uri &u)
Detailed Description
Definition at line 47 of file json-schema.hpp.
Constructor & Destructor Documentation
json_uri()
nlohmann::json_uri::json_uri (const std::string & uri) inline
Definition at line 68 of file json-schema.hpp.
    {
        update(uri);
    }
References update().
Referenced by main().
Member Function Documentation
append()
json_uri nlohmann::json_uri::append (const std::string & field) const inline
Definition at line 103 of file json-schema.hpp.
    {
        if (identifier_ != "")
            return *this;
        json_uri u = *this;
        u.pointer_ /= field;
        return u;
    }
References pointer_.
Referenced by json_schema_validator::insert_schema(), nlohmann::json_schema::root_schema::insert_unknown_keyword(), and anonymous_namespace{json-validator.cpp}::schema::make().
as_tuple()
std::tuple< std::string, std::string, std::string, std::string, std::string > nlohmann::json_uri::as_tuple () const inline protected
Definition at line 62 of file json-schema.hpp.
    {
        return std::make_tuple(urn_, scheme_, authority_, path_, identifier_ != "" ? identifier_ : pointer_.to_string());
    }
References authority_, identifier_, path_, pointer_, scheme_, and urn_.
authority()
const std::string & nlohmann::json_uri::authority () const inline
Definition at line 74 of file json-schema.hpp.
{ return authority_; }
References authority_.
derive()
json_uri nlohmann::json_uri::derive (const std::string & uri) const inline
Definition at line 95 of file json-schema.hpp.
    {
        json_uri u = *this;
        u.update(uri);
        return u;
    }
References update().
Referenced by json_schema_validator::insert_schema(), anonymous_namespace{json-validator.cpp}::schema::make(), paths(), and pointer_plain_name().
escape()
std::string nlohmann::json_uri::escape (const std::string & src) static
Definition at line 137 of file json-uri.cpp.
{
    std::vector<std::pair<std::string, std::string>> chars = {
        {"~", "~0"},
        {"/", "~1"}};
    std::string l = src;
    for (const auto &c : chars) {
        std::size_t pos = 0;
        do {
            pos = l.find(c.first, pos);
            if (pos == std::string::npos)
                break;
            l.replace(pos, 1, c.second);
            pos += c.second.size();
        } while (1);
    }
    return l;
}
Referenced by json_schema_validator::insert_schema().
fragment()
std::string nlohmann::json_uri::fragment () const inline
Definition at line 80 of file json-schema.hpp.
    {
        if (identifier_ == "")
            return pointer_.to_string();
        else
            return identifier_;
    }
References identifier_, and pointer_.
Referenced by nlohmann::json_schema::root_schema::get_or_create_ref(), nlohmann::json_schema::root_schema::insert(), and nlohmann::json_schema::root_schema::validate().
identifier()
const std::string & nlohmann::json_uri::identifier () const inline
Definition at line 78 of file json-schema.hpp.
{ return identifier_; }
References identifier_.
Referenced by pointer_plain_name().
location()
std::string nlohmann::json_uri::location () const
Definition at line 102 of file json-uri.cpp.
{
    if (urn_.size())
        return urn_;
    std::stringstream s;
    if (scheme_.size() > 0)
        s << scheme_ << "://";
    s << authority_
      << path_;
    return s.str();
}
References authority_, path_, scheme_, and urn_.
Referenced by nlohmann::json_schema::root_schema::get_or_create_ref(), nlohmann::json_schema::root_schema::insert(), nlohmann::json_schema::root_schema::insert_unknown_keyword(), loader(), to_string(), url(), and nlohmann::json_schema::root_schema::validate().
path()
const std::string & nlohmann::json_uri::path () const inline
Definition at line 75 of file json-schema.hpp.
{ return path_; }
References path_.
Referenced by loader(), loader(), and loader().
pointer()
const json::json_pointer & nlohmann::json_uri::pointer () const inline
Definition at line 77 of file json-schema.hpp.
{ return pointer_; }
References pointer_.
Referenced by nlohmann::json_schema::root_schema::get_or_create_ref(), nlohmann::json_schema::root_schema::insert_unknown_keyword(), and pointer_plain_name().
scheme()
const std::string & nlohmann::json_uri::scheme () const inline
Definition at line 73 of file json-schema.hpp.
{ return scheme_; }
References scheme_.
to_string()
std::string nlohmann::json_uri::to_string () const
Definition at line 118 of file json-uri.cpp.
{
    std::stringstream s;
    s << location() << " # ";
    if (identifier_ == "")
        s << pointer_.to_string();
    else
        s << identifier_;
    return s.str();
}
References identifier_, location(), and pointer_.
Referenced by EXPECT_EQ(), nlohmann::json_schema::root_schema::get_or_create_ref(), nlohmann::json_schema::root_schema::insert(), json_schema_validator::insert_schema(), anonymous_namespace{json-validator.cpp}::schema::make(), anonymous_namespace{json-validator.cpp}::schema_ref::make_for_default_(), and nlohmann::json_schema::root_schema::validate().
update()
void nlohmann::json_uri::update (const std::string & uri) protected
Definition at line 16 of file json-uri.cpp.
{
    std::string pointer = ""; // default pointer is document-root
    // first split the URI into location and pointer
    auto pointer_separator = uri.find('#');
    if (pointer_separator != std::string::npos) {    // and extract the pointer-string if found
        pointer = uri.substr(pointer_separator + 1); // remove #
        // unescape %-values IOW, decode JSON-URI-formatted JSON-pointer
        std::size_t pos = pointer.size() - 1;
        do {
            pos = pointer.rfind('%', pos);
            if (pos == std::string::npos)
                break;
            if (pos >= pointer.size() - 2) {
                pos--;
                continue;
            }
            std::string hex = pointer.substr(pos + 1, 2);
            char ascii = static_cast<char>(std::strtoul(hex.c_str(), nullptr, 16));
            pointer.replace(pos, 3, 1, ascii);
            pos--;
        } while (1);
    }
    auto location = uri.substr(0, pointer_separator);
    if (location.size()) { // a location part has been found
        // if it is an URN take it as it is
        if (location.find("urn:") == 0) {
            urn_ = location;
            // and clear URL members
            scheme_ = "";
            authority_ = "";
            path_ = "";
        } else { // it is an URL
            // split URL in protocol, hostname and path
            std::size_t pos = 0;
            auto proto = location.find("://", pos);
            if (proto != std::string::npos) { // extract the protocol
                urn_ = ""; // clear URN-member if URL is parsed
                scheme_ = location.substr(pos, proto - pos);
                pos = 3 + proto; // 3 == "://"
                auto authority = location.find("/", pos);
                if (authority != std::string::npos) { // and the hostname (no proto without hostname)
                    authority_ = location.substr(pos, authority - pos);
                    pos = authority;
                }
            }
            auto path = location.substr(pos);
            // URNs cannot of have paths
            if (urn_.size() && path.size())
                throw std::invalid_argument("Cannot add a path (" + path + ") to an URN URI (" + urn_ + ")");
            if (path[0] == '/') // if it starts with a / it is root-path
                path_ = path;
            else if (pos == 0) { // the URL contained only a path and the current path has no / at the end, strip last element until / and append
                auto last_slash = path_.rfind('/');
                path_ = path_.substr(0, last_slash) + '/' + path;
            } else // otherwise it is a subfolder
                path_.append(path);
        }
    }
    pointer_ = ""_json_pointer;
    identifier_ = "";
    if (pointer[0] == '/')
        pointer_ = json::json_pointer(pointer);
    else
        identifier_ = pointer;
}
References authority_, identifier_, path_, pointer_, scheme_, and urn_.
Referenced by derive(), and json_uri().
url()
std::string nlohmann::json_uri::url () const inline
Definition at line 88 of file json-schema.hpp.
{ return location(); }
References location().
Referenced by loader(), loader(), and loader().
Friends And Related Symbol Documentation
operator<
bool operator< (const json_uri & l, const json_uri & r) friend
Definition at line 115 of file json-schema.hpp.
    {
        return l.as_tuple() < r.as_tuple();
    }
operator<<
std::ostream & operator<< (std::ostream & os, const json_uri & u) friend
Definition at line 132 of file json-uri.cpp.
{
    return os << u.to_string();
}
operator==
bool operator== (const json_uri & l, const json_uri & r) friend
Definition at line 120 of file json-schema.hpp.
    {
        return l.as_tuple() == r.as_tuple();
    }
Member Data Documentation
authority_
std::string nlohmann::json_uri::authority_ private
Definition at line 52 of file json-schema.hpp.
Referenced by as_tuple(), authority(), location(), and update().
identifier_
std::string nlohmann::json_uri::identifier_ private
Definition at line 56 of file json-schema.hpp.
Referenced by as_tuple(), fragment(), identifier(), to_string(), and update().
path_
std::string nlohmann::json_uri::path_ private
Definition at line 53 of file json-schema.hpp.
Referenced by as_tuple(), location(), path(), and update().
pointer_
json::json_pointer nlohmann::json_uri::pointer_ private
Definition at line 55 of file json-schema.hpp.
Referenced by append(), as_tuple(), fragment(), pointer(), to_string(), and update().
scheme_
std::string nlohmann::json_uri::scheme_ private
Definition at line 51 of file json-schema.hpp.
Referenced by as_tuple(), location(), scheme(), and update().
urn_
std::string nlohmann::json_uri::urn_ private
Definition at line 49 of file json-schema.hpp.
Referenced by as_tuple(), location(), and update().
The documentation for this class was generated from the following files:
lib/json-schema-validator/src/nlohmann/json-schema.hpp
lib/json-schema-validator/src/json-uri.cpp