MQTTSuite: mqtt::mqttbroker::lib::MqttModel::MqttModelEntry Class Reference
mqtt::mqttbroker::lib::MqttModel::MqttModelEntry Class Reference
Public Member Functions
MqttModelEntry (const Mqtt *mqtt)
~MqttModelEntry ()
MqttModelEntry (MqttModelEntry &&) noexcept=default
const Mqtt * getMqtt () const
std::string onlineSince () const
std::string onlineDuration () const
Private Attributes
const Mqtt * mqtt = nullptr
Detailed Description
Definition at line 73 of file MqttModel.h.
Constructor & Destructor Documentation
MqttModelEntry() [1/2]
mqtt::mqttbroker::lib::MqttModel::MqttModelEntry::MqttModelEntry (const Mqtt * mqtt)
Definition at line 188 of file MqttModel.cpp.
        : mqtt(mqtt) {
    }
References mqtt.
Referenced by mqtt::mqttbroker::lib::MqttModel::addClient().
~MqttModelEntry()
mqtt::mqttbroker::lib::MqttModel::MqttModelEntry::~MqttModelEntry ()
Definition at line 192 of file MqttModel.cpp.
{
    }
MqttModelEntry() [2/2]
mqtt::mqttbroker::lib::MqttModel::MqttModelEntry::MqttModelEntry (MqttModelEntry &&) default noexcept
Member Function Documentation
getMqtt()
const Mqtt * mqtt::mqttbroker::lib::MqttModel::MqttModelEntry::getMqtt () const
Definition at line 203 of file MqttModel.cpp.
{
        return mqtt;
    }
References mqtt.
Referenced by mqtt::mqttbroker::lib::MqttModel::addEventReceiver(), and mqtt::mqttbroker::lib::MqttModel::getMqtt().
onlineDuration()
std::string mqtt::mqttbroker::lib::MqttModel::MqttModelEntry::onlineDuration () const
Definition at line 199 of file MqttModel.cpp.
{
        return mqtt->getMqttContext()->getSocketConnection()->getSocketContext()->getOnlineDuration();
    }
References mqtt.
Referenced by mqtt::mqttbroker::lib::MqttModel::addClient(), and mqtt::mqttbroker::lib::MqttModel::addEventReceiver().
onlineSince()
std::string mqtt::mqttbroker::lib::MqttModel::MqttModelEntry::onlineSince () const
Definition at line 195 of file MqttModel.cpp.
{
        return mqtt->getMqttContext()->getSocketConnection()->getSocketContext()->getOnlineSince();
    }
References mqtt.
Referenced by mqtt::mqttbroker::lib::MqttModel::addClient(), and mqtt::mqttbroker::lib::MqttModel::addEventReceiver().
Member Data Documentation
mqtt
const Mqtt* mqtt::mqttbroker::lib::MqttModel::MqttModelEntry::mqtt = nullptr private
Definition at line 87 of file MqttModel.h.
Referenced by getMqtt(), MqttModelEntry(), onlineDuration(), and onlineSince().
The documentation for this class was generated from the following files:
mqttbroker/lib/MqttModel.h
mqttbroker/lib/MqttModel.cpp