MQTTSuite: inja::Parser Class Reference
inja::Parser Class Reference
Class for parsing an inja Template.
Public Member Functions
Parser (const ParserConfig &parser_config, const LexerConfig &lexer_config, TemplateStorage &template_storage, const FunctionStorage &function_storage)
Template parse (std::string_view input, std::string_view path)
void parse_into_template (Template &tmpl, std::string_view filename)
std::string load_file (const std::string &filename)
Private Types
using Arguments = std::vector< std::shared_ptr< ExpressionNode > >
using OperatorStack = std::stack< std::shared_ptr< FunctionNode > >
Private Member Functions
void throw_parser_error (const std::string &message) const
void get_next_token ()
void get_peek_token ()
void add_literal (Arguments &arguments, const char *content_ptr)
void add_operator (Arguments &arguments, OperatorStack &operator_stack)
void add_to_template_storage (std::string_view path, std::string &template_name)
std::string parse_filename () const
bool parse_expression (Template &tmpl, Token::Kind closing)
std::shared_ptr< ExpressionNode > parse_expression (Template &tmpl)
bool parse_statement (Template &tmpl, Token::Kind closing, std::string_view path)
void parse_into (Template &tmpl, std::string_view path)
Private Attributes
const ParserConfig & config
Lexer lexer
TemplateStorage & template_storage
const FunctionStorage & function_storage
Token tok
Token peek_tok
bool have_peek_tok {false}
std::string_view literal_start
BlockNode * current_block {nullptr}
ExpressionListNode * current_expression_list {nullptr}
std::stack< IfStatementNode * > if_statement_stack
std::stack< ForStatementNode * > for_statement_stack
std::stack< BlockStatementNode * > block_statement_stack
Detailed Description
Class for parsing an inja Template.
Definition at line 1539 of file inja.hpp.
Member Typedef Documentation
Arguments
using inja::Parser::Arguments = std::vector<std::shared_ptr<ExpressionNode> > private
Definition at line 1540 of file inja.hpp.
OperatorStack
using inja::Parser::OperatorStack = std::stack<std::shared_ptr<FunctionNode> > private
Definition at line 1541 of file inja.hpp.
Constructor & Destructor Documentation
Parser()
inja::Parser::Parser (const ParserConfig & parser_config, const LexerConfig & lexer_config, TemplateStorage & template_storage, const FunctionStorage & function_storage) inline explicit
Definition at line 2141 of file inja.hpp.
            : config(parser_config)
            , lexer(lexer_config)
            , template_storage(template_storage)
            , function_storage(function_storage) {
        }
References config, function_storage, inja::Lexer::Lexer(), lexer, and template_storage.
Referenced by inja::Environment::load_file(), inja::Environment::parse(), parse_into_template(), and inja::Environment::parse_template().
Member Function Documentation
add_literal()
void inja::Parser::add_literal (Arguments & arguments, const char * content_ptr) inline private
Definition at line 1581 of file inja.hpp.
{
            std::string_view data_text(literal_start.data(),
                                       static_cast<std::string_view::size_type>(tok.text.data() - literal_start.data()) + tok.text.size());
            arguments.emplace_back(std::make_shared<LiteralNode>(data_text, data_text.data() - content_ptr));
        }
References literal_start, inja::Token::text, and tok.
Referenced by parse_expression().
add_operator()
void inja::Parser::add_operator (Arguments & arguments, OperatorStack & operator_stack) inline private
Definition at line 1587 of file inja.hpp.
{
            auto function = operator_stack.top();
            operator_stack.pop();
            if (static_cast<int>(arguments.size()) < function->number_args) {
                throw_parser_error("too few arguments");
            }
            for (int i = 0; i < function->number_args; ++i) {
                function->arguments.insert(function->arguments.begin(), arguments.back());
                arguments.pop_back();
            }
            arguments.emplace_back(function);
        }
References inja::FunctionNode::arguments, inja::FunctionNode::number_args, and throw_parser_error().
Referenced by parse_expression().
add_to_template_storage()
void inja::Parser::add_to_template_storage (std::string_view path, std::string & template_name) inline private
Definition at line 1602 of file inja.hpp.
{
            if (template_storage.find(template_name) != template_storage.end()) {
                return;
            }
            std::string original_path = static_cast<std::string>(path);
            std::string original_name = template_name;
            if (config.search_included_templates_in_files) {
                // Build the relative path
                template_name = original_path + original_name;
                if (template_name.compare(0, 2, "./") == 0) {
                    template_name.erase(0, 2);
                }
                if (template_storage.find(template_name) == template_storage.end()) {
                    // Load file
                    std::ifstream file;
                    file.open(template_name);
                    if (!file.fail()) {
                        std::string text((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
                        auto include_template = Template(text);
                        template_storage.emplace(template_name, include_template);
                        parse_into_template(template_storage[template_name], template_name);
                        return;
                    } else if (!config.include_callback) {
                        INJA_THROW(FileError("failed accessing file at '" + template_name + "'"));
                    }
                }
            }
            // Try include callback
            if (config.include_callback) {
                auto include_template = config.include_callback(original_path, original_name);
                template_storage.emplace(template_name, include_template);
            }
        }
References config, inja::FileError::FileError(), inja::ParserConfig::include_callback, parse_into_template(), inja::ParserConfig::search_included_templates_in_files, inja::Template::Template(), and template_storage.
Referenced by parse_statement().
get_next_token()
void inja::Parser::get_next_token () inline private
Definition at line 1565 of file inja.hpp.
{
            if (have_peek_tok) {
                tok = peek_tok;
                have_peek_tok = false;
            } else {
                tok = lexer.scan();
            }
        }
References have_peek_tok, lexer, peek_tok, inja::Lexer::scan(), and tok.
Referenced by parse_expression(), parse_into(), and parse_statement().
get_peek_token()
void inja::Parser::get_peek_token () inline private
Definition at line 1574 of file inja.hpp.
{
            if (!have_peek_tok) {
                peek_tok = lexer.scan();
                have_peek_tok = true;
            }
        }
References have_peek_tok, lexer, peek_tok, and inja::Lexer::scan().
Referenced by parse_expression().
load_file()
std::string inja::Parser::load_file (const std::string & filename) inline
Definition at line 2165 of file inja.hpp.
{
            std::ifstream file;
            file.open(filename);
            if (file.fail()) {
                INJA_THROW(FileError("failed accessing file at '" + filename + "'"));
            }
            std::string text((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
            return text;
        }
References inja::FileError::FileError().
Referenced by inja::Environment::load_file(), and inja::Environment::parse_template().
parse()
Template inja::Parser::parse (std::string_view input, std::string_view path) inline
Definition at line 2151 of file inja.hpp.
{
            auto result = Template(static_cast<std::string>(input));
            parse_into(result, path);
            return result;
        }
References parse_into(), and inja::Template::Template().
Referenced by inja::Environment::parse().
parse_expression() [1/2]
std::shared_ptr< ExpressionNode > inja::Parser::parse_expression (Template & tmpl) inline private
Definition at line 1659 of file inja.hpp.
{
            size_t current_bracket_level{0};
            size_t current_brace_level{0};
            Arguments arguments;
            OperatorStack operator_stack;
            while (tok.kind != Token::Kind::Eof) {
                // Literals
                switch (tok.kind) {
                    case Token::Kind::String: {
                        if (current_brace_level == 0 && current_bracket_level == 0) {
                            literal_start = tok.text;
                            add_literal(arguments, tmpl.content.c_str());
                        }
                    } break;
                    case Token::Kind::Number: {
                        if (current_brace_level == 0 && current_bracket_level == 0) {
                            literal_start = tok.text;
                            add_literal(arguments, tmpl.content.c_str());
                        }
                    } break;
                    case Token::Kind::LeftBracket: {
                        if (current_brace_level == 0 && current_bracket_level == 0) {
                            literal_start = tok.text;
                        }
                        current_bracket_level += 1;
                    } break;
                    case Token::Kind::LeftBrace: {
                        if (current_brace_level == 0 && current_bracket_level == 0) {
                            literal_start = tok.text;
                        }
                        current_brace_level += 1;
                    } break;
                    case Token::Kind::RightBracket: {
                        if (current_bracket_level == 0) {
                            throw_parser_error("unexpected ']'");
                        }
                        current_bracket_level -= 1;
                        if (current_brace_level == 0 && current_bracket_level == 0) {
                            add_literal(arguments, tmpl.content.c_str());
                        }
                    } break;
                    case Token::Kind::RightBrace: {
                        if (current_brace_level == 0) {
                            throw_parser_error("unexpected '}'");
                        }
                        current_brace_level -= 1;
                        if (current_brace_level == 0 && current_bracket_level == 0) {
                            add_literal(arguments, tmpl.content.c_str());
                        }
                    } break;
                    case Token::Kind::Id: {
                        get_peek_token();
                        // Data Literal
                        if (tok.text == static_cast<decltype(tok.text)>("true") || tok.text == static_cast<decltype(tok.text)>("false") ||
                            tok.text == static_cast<decltype(tok.text)>("null")) {
                            if (current_brace_level == 0 && current_bracket_level == 0) {
                                literal_start = tok.text;
                                add_literal(arguments, tmpl.content.c_str());
                            }
                            // Operator
                        } else if (tok.text == "and" || tok.text == "or" || tok.text == "in" || tok.text == "not") {
                            goto parse_operator;
                            // Functions
                        } else if (peek_tok.kind == Token::Kind::LeftParen) {
                            auto func = std::make_shared<FunctionNode>(tok.text, tok.text.data() - tmpl.content.c_str());
                            get_next_token();
                            do {
                                get_next_token();
                                auto expr = parse_expression(tmpl);
                                if (!expr) {
                                    break;
                                }
                                func->number_args += 1;
                                func->arguments.emplace_back(expr);
                            } while (tok.kind == Token::Kind::Comma);
                            if (tok.kind != Token::Kind::RightParen) {
                                throw_parser_error("expected right parenthesis, got '" + tok.describe() + "'");
                            }
                            auto function_data = function_storage.find_function(func->name, func->number_args);
                            if (function_data.operation == FunctionStorage::Operation::None) {
                                throw_parser_error("unknown function " + func->name);
                            }
                            func->operation = function_data.operation;
                            if (function_data.operation == FunctionStorage::Operation::Callback) {
                                func->callback = function_data.callback;
                            }
                            arguments.emplace_back(func);
                            // Variables
                        } else {
                            arguments.emplace_back(
                                std::make_shared<DataNode>(static_cast<std::string>(tok.text), tok.text.data() - tmpl.content.c_str()));
                        }
                        // Operators
                    } break;
                    case Token::Kind::Equal:
                    case Token::Kind::NotEqual:
                    case Token::Kind::GreaterThan:
                    case Token::Kind::GreaterEqual:
                    case Token::Kind::LessThan:
                    case Token::Kind::LessEqual:
                    case Token::Kind::Plus:
                    case Token::Kind::Minus:
                    case Token::Kind::Times:
                    case Token::Kind::Slash:
                    case Token::Kind::Power:
                    case Token::Kind::Percent:
                    case Token::Kind::Dot: {
                    parse_operator:
                        FunctionStorage::Operation operation;
                        switch (tok.kind) {
                            case Token::Kind::Id: {
                                if (tok.text == "and") {
                                    operation = FunctionStorage::Operation::And;
                                } else if (tok.text == "or") {
                                    operation = FunctionStorage::Operation::Or;
                                } else if (tok.text == "in") {
                                    operation = FunctionStorage::Operation::In;
                                } else if (tok.text == "not") {
                                    operation = FunctionStorage::Operation::Not;
                                } else {
                                    throw_parser_error("unknown operator in parser.");
                                }
                            } break;
                            case Token::Kind::Equal: {
                                operation = FunctionStorage::Operation::Equal;
                            } break;
                            case Token::Kind::NotEqual: {
                                operation = FunctionStorage::Operation::NotEqual;
                            } break;
                            case Token::Kind::GreaterThan: {
                                operation = FunctionStorage::Operation::Greater;
                            } break;
                            case Token::Kind::GreaterEqual: {
                                operation = FunctionStorage::Operation::GreaterEqual;
                            } break;
                            case Token::Kind::LessThan: {
                                operation = FunctionStorage::Operation::Less;
                            } break;
                            case Token::Kind::LessEqual: {
                                operation = FunctionStorage::Operation::LessEqual;
                            } break;
                            case Token::Kind::Plus: {
                                operation = FunctionStorage::Operation::Add;
                            } break;
                            case Token::Kind::Minus: {
                                operation = FunctionStorage::Operation::Subtract;
                            } break;
                            case Token::Kind::Times: {
                                operation = FunctionStorage::Operation::Multiplication;
                            } break;
                            case Token::Kind::Slash: {
                                operation = FunctionStorage::Operation::Division;
                            } break;
                            case Token::Kind::Power: {
                                operation = FunctionStorage::Operation::Power;
                            } break;
                            case Token::Kind::Percent: {
                                operation = FunctionStorage::Operation::Modulo;
                            } break;
                            case Token::Kind::Dot: {
                                operation = FunctionStorage::Operation::AtId;
                            } break;
                            default: {
                                throw_parser_error("unknown operator in parser.");
                            }
                        }
                        auto function_node = std::make_shared<FunctionNode>(operation, tok.text.data() - tmpl.content.c_str());
                        while (!operator_stack.empty() && ((operator_stack.top()->precedence > function_node->precedence) ||
                                                           (operator_stack.top()->precedence == function_node->precedence &&
                                                            function_node->associativity == FunctionNode::Associativity::Left))) {
                            add_operator(arguments, operator_stack);
                        }
                        operator_stack.emplace(function_node);
                    } break;
                    case Token::Kind::Comma: {
                        if (current_brace_level == 0 && current_bracket_level == 0) {
                            goto break_loop;
                        }
                    } break;
                    case Token::Kind::Colon: {
                        if (current_brace_level == 0 && current_bracket_level == 0) {
                            throw_parser_error("unexpected ':'");
                        }
                    } break;
                    case Token::Kind::LeftParen: {
                        get_next_token();
                        auto expr = parse_expression(tmpl);
                        if (tok.kind != Token::Kind::RightParen) {
                            throw_parser_error("expected right parenthesis, got '" + tok.describe() + "'");
                        }
                        if (!expr) {
                            throw_parser_error("empty expression in parentheses");
                        }
                        arguments.emplace_back(expr);
                    } break;
                    default:
                        goto break_loop;
                }
                get_next_token();
            }
        break_loop:
            while (!operator_stack.empty()) {
                add_operator(arguments, operator_stack);
            }
            std::shared_ptr<ExpressionNode> expr;
            if (arguments.size() == 1) {
                expr = arguments[0];
                arguments = {};
            } else if (arguments.size() > 1) {
                throw_parser_error("malformed expression");
            }
            return expr;
        }
References inja::FunctionStorage::Add, add_literal(), add_operator(), inja::FunctionStorage::And, inja::FunctionNode::arguments, inja::FunctionNode::associativity, inja::FunctionStorage::AtId, inja::FunctionStorage::Callback, inja::FunctionStorage::FunctionData::callback, inja::FunctionNode::callback, inja::Token::Colon, inja::Token::Comma, inja::Template::content, inja::Token::describe(), inja::FunctionStorage::Division, inja::Token::Dot, inja::Token::Eof, inja::FunctionStorage::Equal, inja::Token::Equal, inja::FunctionStorage::find_function(), function_storage, get_next_token(), get_peek_token(), inja::FunctionStorage::Greater, inja::FunctionStorage::GreaterEqual, inja::Token::GreaterEqual, inja::Token::GreaterThan, inja::Token::Id, inja::FunctionStorage::In, inja::Token::kind, inja::FunctionNode::Left, inja::Token::LeftBrace, inja::Token::LeftBracket, inja::Token::LeftParen, inja::FunctionStorage::Less, inja::FunctionStorage::LessEqual, inja::Token::LessEqual, inja::Token::LessThan, literal_start, inja::Token::Minus, inja::FunctionStorage::Modulo, inja::FunctionStorage::Multiplication, inja::FunctionNode::name, inja::FunctionStorage::None, inja::FunctionStorage::Not, inja::FunctionStorage::NotEqual, inja::Token::NotEqual, inja::Token::Number, inja::FunctionNode::number_args, inja::FunctionStorage::FunctionData::operation, inja::FunctionNode::operation, inja::FunctionStorage::Or, parse_expression(), peek_tok, inja::Token::Percent, inja::Token::Plus, inja::FunctionStorage::Power, inja::Token::Power, inja::FunctionNode::precedence, inja::Token::RightBrace, inja::Token::RightBracket, inja::Token::RightParen, inja::Token::Slash, inja::Token::String, inja::FunctionStorage::Subtract, inja::Token::text, throw_parser_error(), inja::Token::Times, and tok.
Referenced by parse_expression(), and parse_expression().
parse_expression() [2/2]
bool inja::Parser::parse_expression (Template & tmpl, Token::Kind closing) inline private
Definition at line 1654 of file inja.hpp.
{
            current_expression_list->root = parse_expression(tmpl);
            return tok.kind == closing;
        }
References current_expression_list, inja::Token::kind, parse_expression(), inja::ExpressionListNode::root, and tok.
Referenced by parse_into(), and parse_statement().
parse_filename()
std::string inja::Parser::parse_filename () const inline private
Definition at line 1641 of file inja.hpp.
{
            if (tok.kind != Token::Kind::String) {
                throw_parser_error("expected string, got '" + tok.describe() + "'");
            }
            if (tok.text.length() < 2) {
                throw_parser_error("expected filename, got '" + static_cast<std::string>(tok.text) + "'");
            }
            // Remove first and last character ""
            return std::string{tok.text.substr(1, tok.text.length() - 2)};
        }
References inja::Token::describe(), inja::Token::kind, inja::Token::String, inja::Token::text, throw_parser_error(), and tok.
Referenced by parse_statement().
parse_into()
void inja::Parser::parse_into (Template & tmpl, std::string_view path) inline private
Definition at line 2078 of file inja.hpp.
{
            lexer.start(tmpl.content);
            current_block = &tmpl.root;
            for (;;) {
                get_next_token();
                switch (tok.kind) {
                    case Token::Kind::Eof: {
                        if (!if_statement_stack.empty()) {
                            throw_parser_error("unmatched if");
                        }
                        if (!for_statement_stack.empty()) {
                            throw_parser_error("unmatched for");
                        }
                    }
                        return;
                    case Token::Kind::Text: {
                        current_block->nodes.emplace_back(
                            std::make_shared<TextNode>(tok.text.data() - tmpl.content.c_str(), tok.text.size()));
                    } break;
                    case Token::Kind::StatementOpen: {
                        get_next_token();
                        if (!parse_statement(tmpl, Token::Kind::StatementClose, path)) {
                            throw_parser_error("expected statement, got '" + tok.describe() + "'");
                        }
                        if (tok.kind != Token::Kind::StatementClose) {
                            throw_parser_error("expected statement close, got '" + tok.describe() + "'");
                        }
                    } break;
                    case Token::Kind::LineStatementOpen: {
                        get_next_token();
                        if (!parse_statement(tmpl, Token::Kind::LineStatementClose, path)) {
                            throw_parser_error("expected statement, got '" + tok.describe() + "'");
                        }
                        if (tok.kind != Token::Kind::LineStatementClose && tok.kind != Token::Kind::Eof) {
                            throw_parser_error("expected line statement close, got '" + tok.describe() + "'");
                        }
                    } break;
                    case Token::Kind::ExpressionOpen: {
                        get_next_token();
                        auto expression_list_node = std::make_shared<ExpressionListNode>(tok.text.data() - tmpl.content.c_str());
                        current_block->nodes.emplace_back(expression_list_node);
                        current_expression_list = expression_list_node.get();
                        if (!parse_expression(tmpl, Token::Kind::ExpressionClose)) {
                            throw_parser_error("expected expression close, got '" + tok.describe() + "'");
                        }
                    } break;
                    case Token::Kind::CommentOpen: {
                        get_next_token();
                        if (tok.kind != Token::Kind::CommentClose) {
                            throw_parser_error("expected comment close, got '" + tok.describe() + "'");
                        }
                    } break;
                    default: {
                        throw_parser_error("unexpected token '" + tok.describe() + "'");
                    } break;
                }
            }
        }
References inja::Token::CommentClose, inja::Token::CommentOpen, inja::Template::content, current_block, current_expression_list, inja::Token::describe(), inja::Token::Eof, inja::Token::ExpressionClose, inja::Token::ExpressionOpen, for_statement_stack, get_next_token(), if_statement_stack, inja::Token::kind, lexer, inja::Token::LineStatementClose, inja::Token::LineStatementOpen, inja::BlockNode::nodes, parse_expression(), parse_statement(), inja::Template::root, inja::Lexer::start(), inja::Token::StatementClose, inja::Token::StatementOpen, inja::Token::Text, inja::Token::text, throw_parser_error(), and tok.
Referenced by parse(), and parse_into_template().
parse_into_template()
void inja::Parser::parse_into_template (Template & tmpl, std::string_view filename) inline
Definition at line 2157 of file inja.hpp.
{
            std::string_view path = filename.substr(0, filename.find_last_of("/\\") + 1);
            // StringRef path = sys::path::parent_path(filename);
            auto sub_parser = Parser(config, lexer.get_config(), template_storage, function_storage);
            sub_parser.parse_into(tmpl, path);
        }
References config, function_storage, inja::Lexer::get_config(), lexer, parse_into(), Parser(), and template_storage.
Referenced by add_to_template_storage(), and inja::Environment::parse_template().
parse_statement()
bool inja::Parser::parse_statement (Template & tmpl, Token::Kind closing, std::string_view path) inline private
Definition at line 1887 of file inja.hpp.
{
            if (tok.kind != Token::Kind::Id) {
                return false;
            }
            if (tok.text == static_cast<decltype(tok.text)>("if")) {
                get_next_token();
                auto if_statement_node = std::make_shared<IfStatementNode>(current_block, tok.text.data() - tmpl.content.c_str());
                current_block->nodes.emplace_back(if_statement_node);
                if_statement_stack.emplace(if_statement_node.get());
                current_block = &if_statement_node->true_statement;
                current_expression_list = &if_statement_node->condition;
                if (!parse_expression(tmpl, closing)) {
                    return false;
                }
            } else if (tok.text == static_cast<decltype(tok.text)>("else")) {
                if (if_statement_stack.empty()) {
                    throw_parser_error("else without matching if");
                }
                auto& if_statement_data = if_statement_stack.top();
                get_next_token();
                if_statement_data->has_false_statement = true;
                current_block = &if_statement_data->false_statement;
                // Chained else if
                if (tok.kind == Token::Kind::Id && tok.text == static_cast<decltype(tok.text)>("if")) {
                    get_next_token();
                    auto if_statement_node = std::make_shared<IfStatementNode>(true, current_block, tok.text.data() - tmpl.content.c_str());
                    current_block->nodes.emplace_back(if_statement_node);
                    if_statement_stack.emplace(if_statement_node.get());
                    current_block = &if_statement_node->true_statement;
                    current_expression_list = &if_statement_node->condition;
                    if (!parse_expression(tmpl, closing)) {
                        return false;
                    }
                }
            } else if (tok.text == static_cast<decltype(tok.text)>("endif")) {
                if (if_statement_stack.empty()) {
                    throw_parser_error("endif without matching if");
                }
                // Nested if statements
                while (if_statement_stack.top()->is_nested) {
                    if_statement_stack.pop();
                }
                auto& if_statement_data = if_statement_stack.top();
                get_next_token();
                current_block = if_statement_data->parent;
                if_statement_stack.pop();
            } else if (tok.text == static_cast<decltype(tok.text)>("block")) {
                get_next_token();
                if (tok.kind != Token::Kind::Id) {
                    throw_parser_error("expected block name, got '" + tok.describe() + "'");
                }
                const std::string block_name = static_cast<std::string>(tok.text);
                auto block_statement_node =
                    std::make_shared<BlockStatementNode>(current_block, block_name, tok.text.data() - tmpl.content.c_str());
                current_block->nodes.emplace_back(block_statement_node);
                block_statement_stack.emplace(block_statement_node.get());
                current_block = &block_statement_node->block;
                auto success = tmpl.block_storage.emplace(block_name, block_statement_node);
                if (!success.second) {
                    throw_parser_error("block with the name '" + block_name + "' does already exist");
                }
                get_next_token();
            } else if (tok.text == static_cast<decltype(tok.text)>("endblock")) {
                if (block_statement_stack.empty()) {
                    throw_parser_error("endblock without matching block");
                }
                auto& block_statement_data = block_statement_stack.top();
                get_next_token();
                current_block = block_statement_data->parent;
                block_statement_stack.pop();
            } else if (tok.text == static_cast<decltype(tok.text)>("for")) {
                get_next_token();
                // options: for a in arr; for a, b in obj
                if (tok.kind != Token::Kind::Id) {
                    throw_parser_error("expected id, got '" + tok.describe() + "'");
                }
                Token value_token = tok;
                get_next_token();
                // Object type
                std::shared_ptr<ForStatementNode> for_statement_node;
                if (tok.kind == Token::Kind::Comma) {
                    get_next_token();
                    if (tok.kind != Token::Kind::Id) {
                        throw_parser_error("expected id, got '" + tok.describe() + "'");
                    }
                    Token key_token = std::move(value_token);
                    value_token = tok;
                    get_next_token();
                    for_statement_node = std::make_shared<ForObjectStatementNode>(static_cast<std::string>(key_token.text),
                                                                                  static_cast<std::string>(value_token.text),
                                                                                  current_block,
                                                                                  tok.text.data() - tmpl.content.c_str());
                    // Array type
                } else {
                    for_statement_node = std::make_shared<ForArrayStatementNode>(
                        static_cast<std::string>(value_token.text), current_block, tok.text.data() - tmpl.content.c_str());
                }
                current_block->nodes.emplace_back(for_statement_node);
                for_statement_stack.emplace(for_statement_node.get());
                current_block = &for_statement_node->body;
                current_expression_list = &for_statement_node->condition;
                if (tok.kind != Token::Kind::Id || tok.text != static_cast<decltype(tok.text)>("in")) {
                    throw_parser_error("expected 'in', got '" + tok.describe() + "'");
                }
                get_next_token();
                if (!parse_expression(tmpl, closing)) {
                    return false;
                }
            } else if (tok.text == static_cast<decltype(tok.text)>("endfor")) {
                if (for_statement_stack.empty()) {
                    throw_parser_error("endfor without matching for");
                }
                auto& for_statement_data = for_statement_stack.top();
                get_next_token();
                current_block = for_statement_data->parent;
                for_statement_stack.pop();
            } else if (tok.text == static_cast<decltype(tok.text)>("include")) {
                get_next_token();
                std::string template_name = parse_filename();
                add_to_template_storage(path, template_name);
                current_block->nodes.emplace_back(
                    std::make_shared<IncludeStatementNode>(template_name, tok.text.data() - tmpl.content.c_str()));
                get_next_token();
            } else if (tok.text == static_cast<decltype(tok.text)>("extends")) {
                get_next_token();
                std::string template_name = parse_filename();
                add_to_template_storage(path, template_name);
                current_block->nodes.emplace_back(
                    std::make_shared<ExtendsStatementNode>(template_name, tok.text.data() - tmpl.content.c_str()));
                get_next_token();
            } else if (tok.text == static_cast<decltype(tok.text)>("set")) {
                get_next_token();
                if (tok.kind != Token::Kind::Id) {
                    throw_parser_error("expected variable name, got '" + tok.describe() + "'");
                }
                std::string key = static_cast<std::string>(tok.text);
                get_next_token();
                auto set_statement_node = std::make_shared<SetStatementNode>(key, tok.text.data() - tmpl.content.c_str());
                current_block->nodes.emplace_back(set_statement_node);
                current_expression_list = &set_statement_node->expression;
                if (tok.text != static_cast<decltype(tok.text)>("=")) {
                    throw_parser_error("expected '=', got '" + tok.describe() + "'");
                }
                get_next_token();
                if (!parse_expression(tmpl, closing)) {
                    return false;
                }
            } else {
                return false;
            }
            return true;
        }
References add_to_template_storage(), inja::BlockStatementNode::block, block_statement_stack, inja::Template::block_storage, inja::ForStatementNode::body, inja::Token::Comma, inja::ForStatementNode::condition, inja::IfStatementNode::condition, inja::Template::content, current_block, current_expression_list, inja::Token::describe(), inja::SetStatementNode::expression, inja::IfStatementNode::false_statement, for_statement_stack, get_next_token(), inja::IfStatementNode::has_false_statement, inja::Token::Id, if_statement_stack, inja::IfStatementNode::is_nested, inja::Token::kind, inja::BlockNode::nodes, inja::ForStatementNode::parent, inja::IfStatementNode::parent, inja::BlockStatementNode::parent, parse_expression(), parse_filename(), inja::Token::text, throw_parser_error(), tok, and inja::IfStatementNode::true_statement.
Referenced by parse_into().
throw_parser_error()
void inja::Parser::throw_parser_error (const std::string & message) const inline private
Definition at line 1561 of file inja.hpp.
{
            INJA_THROW(ParserError(message, lexer.current_position()));
        }
References inja::Lexer::current_position(), lexer, and inja::ParserError::ParserError().
Referenced by add_operator(), parse_expression(), parse_filename(), parse_into(), and parse_statement().
Member Data Documentation
block_statement_stack
std::stack<BlockStatementNode*> inja::Parser::block_statement_stack private
Definition at line 1559 of file inja.hpp.
Referenced by parse_statement().
config
const ParserConfig& inja::Parser::config private
Definition at line 1543 of file inja.hpp.
Referenced by add_to_template_storage(), parse_into_template(), and Parser().
current_block
BlockNode* inja::Parser::current_block {nullptr} private
Definition at line 1554 of file inja.hpp.
{nullptr};
Referenced by parse_into(), and parse_statement().
current_expression_list
ExpressionListNode* inja::Parser::current_expression_list {nullptr} private
Definition at line 1555 of file inja.hpp.
{nullptr};
Referenced by parse_expression(), parse_into(), and parse_statement().
for_statement_stack
std::stack<ForStatementNode*> inja::Parser::for_statement_stack private
Definition at line 1558 of file inja.hpp.
Referenced by parse_into(), and parse_statement().
function_storage
const FunctionStorage& inja::Parser::function_storage private
Definition at line 1547 of file inja.hpp.
Referenced by parse_expression(), parse_into_template(), and Parser().
have_peek_tok
bool inja::Parser::have_peek_tok {false} private
Definition at line 1550 of file inja.hpp.
{false};
Referenced by get_next_token(), and get_peek_token().
if_statement_stack
std::stack<IfStatementNode*> inja::Parser::if_statement_stack private
Definition at line 1557 of file inja.hpp.
Referenced by parse_into(), and parse_statement().
lexer
Lexer inja::Parser::lexer private
Definition at line 1545 of file inja.hpp.
Referenced by get_next_token(), get_peek_token(), parse_into(), parse_into_template(), Parser(), and throw_parser_error().
literal_start
std::string_view inja::Parser::literal_start private
Definition at line 1552 of file inja.hpp.
Referenced by add_literal(), and parse_expression().
peek_tok
Token inja::Parser::peek_tok private
Definition at line 1549 of file inja.hpp.
Referenced by get_next_token(), get_peek_token(), and parse_expression().
template_storage
TemplateStorage& inja::Parser::template_storage private
Definition at line 1546 of file inja.hpp.
Referenced by add_to_template_storage(), parse_into_template(), and Parser().
tok
Token inja::Parser::tok private
Definition at line 1549 of file inja.hpp.
Referenced by add_literal(), get_next_token(), parse_expression(), parse_expression(), parse_filename(), parse_into(), and parse_statement().
The documentation for this class was generated from the following file:
lib/inja.hpp