MQTTSuite: mqtt::mqttstore::websocket::SubProtocolFactory Class Reference
mqtt::mqttstore::websocket::SubProtocolFactory Class Reference
#include <SubProtocolFactory.h>
Public Member Functions
SubProtocolFactory ()
Private Member Functions
iot::mqtt::client::SubProtocol * create (web::websocket::SubProtocolContext *subProtocolContext) override
Detailed Description
Definition at line 55 of file SubProtocolFactory.h.
Constructor & Destructor Documentation
SubProtocolFactory()
mqtt::mqttstore::websocket::SubProtocolFactory::SubProtocolFactory () explicit
Definition at line 54 of file SubProtocolFactory.cpp.
        : web::websocket::SubProtocolFactory<web::websocket::client::SubProtocol>::SubProtocolFactory(NAME) {
    }
Referenced by mqttClientSubProtocolFactory().
Member Function Documentation
create()
iot::mqtt::client::SubProtocol * mqtt::mqttstore::websocket::SubProtocolFactory::create (web::websocket::SubProtocolContext * subProtocolContext) override private
Definition at line 58 of file SubProtocolFactory.cpp.
{
        const net::config::ConfigInstance* configInstance = subProtocolContext->getSocketConnection()->getConfigInstance();
        const lib::ConfigSession* configSession = configInstance->getSubCommand<lib::ConfigSession>();
        const lib::ConfigSubscribe* configSubscribe = configInstance->getSubCommand<lib::ConfigSubscribe>();
        const lib::ConfigDatabase* configDatabase = configInstance->getSubCommand<lib::ConfigDatabase>();
        const lib::ConfigStorage* configStorage = configDatabase->getSubCommand<lib::ConfigStorage>();
        const StorageOptions storageOptions = getStorageOptions(configStorage);
        lib::StoragePlan storagePlan;
        try {
            storagePlan = lib::StoragePlan::fromFile(storageOptions.projectionFile);
        } catch (const std::exception& exception) {
            VLOG(0) << subProtocolContext->getSocketConnection()->getConnectionName() << " MQTTStore startup failed: " << exception.what();
            throw;
        }
        return new iot::mqtt::client::SubProtocol(
            subProtocolContext,
            getName(),
            new mqtt::mqttstore::lib::Mqtt(subProtocolContext->getSocketConnection()->getConnectionName(),
                                           configSession->getClientId(),
                                           configSession->getQoS(),
                                           configSession->getKeepAlive(),
                                           !configSession->getRetainSession(),
                                           configSession->getWillTopic(),
                                           configSession->getWillMessage(),
                                           configSession->getWillQoS(),
                                           configSession->getWillRetain(),
                                           configSession->getUsername(),
                                           configSession->getPassword(),
                                           configSubscribe->getTopic(),
                                           {.database = configDatabase->getDatabase(),
                                            .username = configDatabase->getUsername(),
                                            .password = configDatabase->getPassword(),
                                            .host = configDatabase->getHost(),
                                            .port = configDatabase->getPort(),
                                            .socket = configDatabase->getSocket(),
                                            .flags = configDatabase->getFlags()},
                                           storageOptions.rawTable,
                                           storageOptions.autoCreateRawTable,
                                           std::move(storagePlan),
                                           configSession->getSessionStore()));
    }
References mqtt::mqttstore::lib::StoragePlan::fromFile(), anonymous_namespace{SubProtocolFactory.cpp}::getStorageOptions(), and anonymous_namespace{SubProtocolFactory.cpp}::StorageOptions::projectionFile.
The documentation for this class was generated from the following files:
mqttstore/websocket/SubProtocolFactory.h
mqttstore/websocket/SubProtocolFactory.cpp