MQTTSuite: inja::ExpressionNode Class Reference
inja::ExpressionNode Class Reference
#include <inja.hpp>
Public Member Functions
ExpressionNode (size_t pos)
void accept (NodeVisitor &v) const override
Public Member Functions inherited from inja::AstNode
AstNode (size_t pos)
AstNode (const AstNode &)=default
AstNode & operator= (const AstNode &)=default
virtual ~AstNode ()
Additional Inherited Members
Public Attributes inherited from inja::AstNode
size_t pos
Detailed Description
Definition at line 456 of file inja.hpp.
Constructor & Destructor Documentation
ExpressionNode()
inja::ExpressionNode::ExpressionNode (size_t pos) inline explicit
Definition at line 458 of file inja.hpp.
            : AstNode(pos) {
        }
References inja::AstNode::AstNode().
Referenced by inja::DataNode::DataNode(), inja::FunctionNode::FunctionNode(), inja::FunctionNode::FunctionNode(), and inja::LiteralNode::LiteralNode().
Member Function Documentation
accept()
void inja::ExpressionNode::accept (NodeVisitor & v) const inline override virtual
Implements inja::AstNode.
Reimplemented in inja::LiteralNode, and inja::FunctionNode.
Definition at line 462 of file inja.hpp.
{
            v.visit(*this);
        }
References inja::NodeVisitor::visit().
Referenced by inja::Renderer::eval_expression_list(), inja::Renderer::get_argument_vector(), inja::Renderer::get_arguments(), inja::StatisticsVisitor::visit(), inja::StatisticsVisitor::visit(), and inja::Renderer::visit().
The documentation for this class was generated from the following file:
lib/inja.hpp