MQTTSuite: mqtt::lib::ConfigApplication Class Reference
mqtt::lib::ConfigApplication Class Reference
#include <ConfigApplication.h>
Public Member Functions
template<typename ConcretConfigApplicationT>
ConfigApplication (utils::SubCommand *parent, ConcretConfigApplicationT *concretConfigApplication)
~ConfigApplication () override
ConfigApplication & setSessionStore (const std::string &sessionStore)
std::string getSessionStore () const
const std::shared_ptr< MqttMapper > getMqttMapper () const
bool setMappingFile (const std::string &mapFilename)
std::string getMappingFilename () const
bool setMapping (const std::string &mapping) const
std::string getMapping (int indent=2) const
bool persistMapping () const
template<typename ConcretConfigApplication>
ConfigApplication (utils::SubCommand *parent, ConcretConfigApplication *concretConfigApplication)
Protected Attributes
std::shared_ptr< MqttMapper > mqttMapper
CLI::Option * mappingFileOpt
CLI::Option * sessionStoreOpt
Private Member Functions
bool loadMapping (const std::string mapFilename)
Private Attributes
std::string mapFilename
Detailed Description
Definition at line 61 of file ConfigApplication.h.
Constructor & Destructor Documentation
ConfigApplication() [1/2]
template<typename ConcretConfigApplicationT> mqtt::lib::ConfigApplication::ConfigApplication (utils::SubCommand * parent, ConcretConfigApplicationT * concretConfigApplication)
Referenced by mqtt::lib::ConfigMqttBroker::ConfigMqttBroker(), and mqtt::lib::ConfigMqttIntegrator::ConfigMqttIntegrator().
~ConfigApplication()
mqtt::lib::ConfigApplication::~ConfigApplication () override default
ConfigApplication() [2/2]
template<typename ConcretConfigApplication> mqtt::lib::ConfigApplication::ConfigApplication (utils::SubCommand * parent, ConcretConfigApplication * concretConfigApplication)
Definition at line 63 of file ConfigApplication.cpp.
        : utils::SubCommand(parent, concretConfigApplication, "Applications")
        , mqttMapper(std::make_shared<MqttMapper>())
        , mappingFileOpt(        //
              addOptionFunction( //
                  "--mqtt-mapping-file",
                  [this](const std::string& mappFilename) {
                      try {
                          loadMapping(mappFilename);
                      } catch (std::runtime_error& e) {
                          this->mapFilename.clear();
                          throw CLI::ValidationError(getName(),
                                                     std::string("Activating mapping description in '" + mappFilename +
                                                                 "' failed\n"
                                                                 "What: " +
                                                                 e.what()));
                      }
                  },
                  "MQTT mapping file (json format) for integration",
                  "filename",
                  !CLI::ExistingDirectory))
        , sessionStoreOpt( //
              addOption(   //
                  "--mqtt-session-store",
                  "Path to file for the persistent session store",
                  "filename",
                  !CLI::ExistingDirectory)) {
    }
References loadMapping(), mapFilename, mappingFileOpt, and mqttMapper.
Member Function Documentation
getMapping()
std::string mqtt::lib::ConfigApplication::getMapping (int indent = 2) const
Definition at line 123 of file ConfigApplication.cpp.
{
        return mqttMapper->getMapping().dump(indent);
    }
References mqtt::lib::MqttMapper::getMapping(), and mqttMapper.
Referenced by persistMapping().
getMappingFilename()
std::string mqtt::lib::ConfigApplication::getMappingFilename () const
Definition at line 115 of file ConfigApplication.cpp.
{
        return mapFilename;
    }
References mapFilename.
Referenced by mqtt::lib::admin::makeMappingAdminRouter().
getMqttMapper()
const std::shared_ptr< MqttMapper > mqtt::lib::ConfigApplication::getMqttMapper () const
Definition at line 105 of file ConfigApplication.cpp.
{
        return mqttMapper;
    }
References mqttMapper.
Referenced by mqtt::mqttbroker::SocketContextFactory::create(), mqtt::mqttbroker::websocket::SubProtocolFactory::create(), mqtt::mqttintegrator::SocketContextFactory::create(), and mqtt::lib::admin::makeMappingAdminRouter().
getSessionStore()
std::string mqtt::lib::ConfigApplication::getSessionStore () const
Definition at line 101 of file ConfigApplication.cpp.
{
        return sessionStoreOpt->as<std::string>();
    }
References sessionStoreOpt.
Referenced by mqtt::mqttbroker::websocket::SubProtocolFactory::create(), and mqtt::mqttintegrator::SocketContextFactory::create().
loadMapping()
bool mqtt::lib::ConfigApplication::loadMapping (const std::string mapFilename) private
Definition at line 150 of file ConfigApplication.cpp.
{
        VLOG(1) << "Mapping file: " << mapFilename;
        this->mapFilename = mapFilename;
        bool mustReconnect = true;
        if (!mapFilename.empty()) {
            std::ifstream mapFile(mapFilename);
            if (mapFile.is_open()) {
                try {
                    mustReconnect = setMapping({std::istreambuf_iterator<char>(mapFile), std::istreambuf_iterator<char>()});
                    mapFile.close();
                    VLOG(1) << "Load mapping file success";
                } catch (const std::exception& e) {
                    mapFile.close();
                    throw std::runtime_error("Loading mapping description from '" + mapFilename +
                                             "' failed\n"
                                             "What: " +
                                             e.what());
                }
            } else {
                VLOG(1) << "Mapping file '" + mapFilename +
                               "' not found. Please provide a valid mapping file with the option --mqtt-mapping-file";
            }
        }
        return mustReconnect;
    }
References mapFilename, and setMapping().
Referenced by ConfigApplication(), and setMappingFile().
persistMapping()
bool mqtt::lib::ConfigApplication::persistMapping () const
Definition at line 127 of file ConfigApplication.cpp.
{
        bool success = false;
        std::ofstream mapFile(mapFilename, std::ios::trunc);
        if (mapFile.is_open()) {
            try {
                mapFile << getMapping();
                success = true;
                VLOG(1) << "Write mapping file seccess";
            } catch (const std::exception& e) {
                VLOG(1) << "Write mapping file failed: " << e.what();
            }
            mapFile.close();
        } else {
            VLOG(1) << "Cannot open mapping file for writing: " << mapFilename;
        }
        return success;
    }
References getMapping(), and mapFilename.
Referenced by mqtt::lib::admin::makeMappingAdminRouter().
setMapping()
bool mqtt::lib::ConfigApplication::setMapping (const std::string & mapping) const
Definition at line 119 of file ConfigApplication.cpp.
{
        return mqttMapper->setMapping(nlohmann::json::parse(mapping));
    }
References mqttMapper, and mqtt::lib::MqttMapper::setMapping().
Referenced by loadMapping().
setMappingFile()
bool mqtt::lib::ConfigApplication::setMappingFile (const std::string & mapFilename)
Definition at line 109 of file ConfigApplication.cpp.
{
        setDefaultValue(mappingFileOpt, mapFilename);
        return loadMapping(mapFilename);
    }
References loadMapping(), and mappingFileOpt.
setSessionStore()
ConfigApplication & mqtt::lib::ConfigApplication::setSessionStore (const std::string & sessionStore)
Definition at line 95 of file ConfigApplication.cpp.
{
        setDefaultValue(sessionStoreOpt, sessionStore);
        return *this;
    }
References sessionStoreOpt.
Member Data Documentation
mapFilename
std::string mqtt::lib::ConfigApplication::mapFilename private
Definition at line 88 of file ConfigApplication.h.
Referenced by ConfigApplication(), getMappingFilename(), loadMapping(), and persistMapping().
mappingFileOpt
CLI::Option* mqtt::lib::ConfigApplication::mappingFileOpt protected
Definition at line 84 of file ConfigApplication.h.
Referenced by ConfigApplication(), and setMappingFile().
mqttMapper
std::shared_ptr<MqttMapper> mqtt::lib::ConfigApplication::mqttMapper protected
Definition at line 82 of file ConfigApplication.h.
Referenced by ConfigApplication(), getMapping(), getMqttMapper(), and setMapping().
sessionStoreOpt
CLI::Option* mqtt::lib::ConfigApplication::sessionStoreOpt protected
Definition at line 85 of file ConfigApplication.h.
Referenced by getSessionStore(), and setSessionStore().
The documentation for this class was generated from the following files:
lib/ConfigApplication.h
lib/ConfigApplication.cpp