MQTTSuite: anonymous_namespace{json-validator.cpp}::type_schema Class Reference
anonymous_namespace{json-validator.cpp}::type_schema Class Reference
Public Member Functions
type_schema (json &sch, root_schema *root, const std::vector< nlohmann::json_uri > &uris)
type_schema (json &sch, root_schema *root, const std::vector< nlohmann::json_uri > &uris)
Public Member Functions inherited from anonymous_namespace{json-validator.cpp}::schema
virtual ~schema ()=default
schema (root_schema *root)
virtual const json & default_value (const json::json_pointer &, const json &, error_handler &) const
void set_default_value (const json &v)
virtual ~schema ()=default
schema (root_schema *root)
virtual const json & default_value (const json::json_pointer &, const json &, error_handler &) const
void set_default_value (const json &v)
Protected Member Functions
virtual std::shared_ptr< schema > make_for_default_ (std::shared_ptr<::schema > &, root_schema *, std::vector< nlohmann::json_uri > &, nlohmann::json &default_value) const override
virtual std::shared_ptr< schema > make_for_default_ (std::shared_ptr<::schema > &, root_schema *, std::vector< nlohmann::json_uri > &, nlohmann::json &default_value) const override
Private Member Functions
void validate (const json::json_pointer &ptr, const json &instance, json_patch &patch, error_handler &e) const override final
void validate (const json::json_pointer &ptr, const json &instance, json_patch &patch, error_handler &e) const override final
Static Private Member Functions
static std::shared_ptr< schema > make (json &schema, json::value_t type, root_schema *, const std::vector< nlohmann::json_uri > &, std::set< std::string > &)
static std::shared_ptr< schema > make (json &schema, json::value_t type, root_schema *, const std::vector< nlohmann::json_uri > &, std::set< std::string > &)
Private Attributes
std::vector< std::shared_ptr< schema > > type_
std::pair< bool, json > enum_
std::pair< bool, json > const_
std::vector< std::shared_ptr< schema > > logic_
std::shared_ptr< schema > if_
std::shared_ptr< schema > then_
std::shared_ptr< schema > else_
Additional Inherited Members
Static Public Member Functions inherited from anonymous_namespace{json-validator.cpp}::schema
static std::shared_ptr< schema > make (json &schema, root_schema *root, const std::vector< std::string > &key, std::vector< nlohmann::json_uri > uris)
static std::shared_ptr< schema > make (json &schema, root_schema *root, const std::vector< std::string > &key, std::vector< nlohmann::json_uri > uris)
Protected Attributes inherited from anonymous_namespace{json-validator.cpp}::schema
root_schema * root_
json default_value_ = nullptr
Detailed Description
Definition at line 536 of file json-validator.cpp.
Constructor & Destructor Documentation
type_schema() [1/2]
anonymous_namespace{json-validator.cpp}::type_schema::type_schema (json & sch, root_schema * root, const std::vector< nlohmann::json_uri > & uris) inline
Definition at line 609 of file json-validator.cpp.
        : schema(root), type_(static_cast<uint8_t>(json::value_t::discarded) + 1)
    {
        // association between JSON-schema-type and NLohmann-types
        static const std::vector<std::pair<std::string, json::value_t>> schema_types = {
            {"null", json::value_t::null},
            {"object", json::value_t::object},
            {"array", json::value_t::array},
            {"string", json::value_t::string},
            {"boolean", json::value_t::boolean},
            {"integer", json::value_t::number_integer},
            {"number", json::value_t::number_float},
        };
        std::set<std::string> known_keywords;
        auto attr = sch.find("type");
        if (attr == sch.end()) // no type field means all sub-types possible
            for (auto &t : schema_types)
                type_[static_cast<uint8_t>(t.second)] = type_schema::make(sch, t.second, root, uris, known_keywords);
        else {
            switch (attr.value().type()) { // "type": "type"
            case json::value_t::string: {
                auto schema_type = attr.value().get<std::string>();
                for (auto &t : schema_types)
                    if (t.first == schema_type)
                        type_[static_cast<uint8_t>(t.second)] = type_schema::make(sch, t.second, root, uris, known_keywords);
            } break;
            case json::value_t::array: // "type": ["type1", "type2"]
                for (auto &array_value : attr.value()) {
                    auto schema_type = array_value.get<std::string>();
                    for (auto &t : schema_types)
                        if (t.first == schema_type)
                            type_[static_cast<uint8_t>(t.second)] = type_schema::make(sch, t.second, root, uris, known_keywords);
                }
                break;
            default:
                break;
            }
            sch.erase(attr);
        }
        attr = sch.find("default");
        if (attr != sch.end()) {
            set_default_value(attr.value());
            sch.erase(attr);
        }
        for (auto &key : known_keywords)
            sch.erase(key);
        // with nlohmann::json float instance (but number in schema-definition) can be seen as unsigned or integer -
        // reuse the number-validator for integer values as well, if they have not been specified explicitly
        if (type_[static_cast<uint8_t>(json::value_t::number_float)] && !type_[static_cast<uint8_t>(json::value_t::number_integer)])
            type_[static_cast<uint8_t>(json::value_t::number_integer)] = type_[static_cast<uint8_t>(json::value_t::number_float)];
        // #54: JSON-schema does not differentiate between unsigned and signed integer - nlohmann::json does
        // we stick with JSON-schema: use the integer-validator if instance-value is unsigned
        type_[static_cast<uint8_t>(json::value_t::number_unsigned)] = type_[static_cast<uint8_t>(json::value_t::number_integer)];
        // special for binary types
        if (type_[static_cast<uint8_t>(json::value_t::string)]) {
            type_[static_cast<uint8_t>(json::value_t::binary)] = type_[static_cast<uint8_t>(json::value_t::string)];
        }
        attr = sch.find("enum");
        if (attr != sch.end()) {
            enum_ = {true, attr.value()};
            sch.erase(attr);
        }
        attr = sch.find("const");
        if (attr != sch.end()) {
            const_ = {true, attr.value()};
            sch.erase(attr);
        }
        attr = sch.find("not");
        if (attr != sch.end()) {
            logic_.push_back(std::make_shared<logical_not>(attr.value(), root, uris));
            sch.erase(attr);
        }
        attr = sch.find("allOf");
        if (attr != sch.end()) {
            logic_.push_back(std::make_shared<logical_combination<allOf>>(attr.value(), root, uris));
            sch.erase(attr);
        }
        attr = sch.find("anyOf");
        if (attr != sch.end()) {
            logic_.push_back(std::make_shared<logical_combination<anyOf>>(attr.value(), root, uris));
            sch.erase(attr);
        }
        attr = sch.find("oneOf");
        if (attr != sch.end()) {
            logic_.push_back(std::make_shared<logical_combination<oneOf>>(attr.value(), root, uris));
            sch.erase(attr);
        }
        attr = sch.find("if");
        if (attr != sch.end()) {
            auto attr_then = sch.find("then");
            auto attr_else = sch.find("else");
            if (attr_then != sch.end() || attr_else != sch.end()) {
                if_ = schema::make(attr.value(), root, {"if"}, uris);
                if (attr_then != sch.end()) {
                    then_ = schema::make(attr_then.value(), root, {"then"}, uris);
                    sch.erase(attr_then);
                }
                if (attr_else != sch.end()) {
                    else_ = schema::make(attr_else.value(), root, {"else"}, uris);
                    sch.erase(attr_else);
                }
            }
            sch.erase(attr);
        }
    }
References anonymous_namespace{json-validator.cpp}::allOf, anonymous_namespace{json-validator.cpp}::anyOf, const_, else_, enum_, if_, logic_, anonymous_namespace{json-validator.cpp}::schema::make(), make(), anonymous_namespace{json-validator.cpp}::oneOf, anonymous_namespace{json-validator.cpp}::schema::schema(), anonymous_namespace{json-validator.cpp}::schema::set_default_value(), then_, and type_.
type_schema() [2/2]
anonymous_namespace{json-validator.cpp}::type_schema::type_schema (json & sch, root_schema * root, const std::vector< nlohmann::json_uri > & uris) inline
Definition at line 609 of file json-validator.cpp.
        : schema(root), type_(static_cast<uint8_t>(json::value_t::discarded) + 1)
    {
        // association between JSON-schema-type and NLohmann-types
        static const std::vector<std::pair<std::string, json::value_t>> schema_types = {
            {"null", json::value_t::null},
            {"object", json::value_t::object},
            {"array", json::value_t::array},
            {"string", json::value_t::string},
            {"boolean", json::value_t::boolean},
            {"integer", json::value_t::number_integer},
            {"number", json::value_t::number_float},
        };
        std::set<std::string> known_keywords;
        auto attr = sch.find("type");
        if (attr == sch.end()) // no type field means all sub-types possible
            for (auto &t : schema_types)
                type_[static_cast<uint8_t>(t.second)] = type_schema::make(sch, t.second, root, uris, known_keywords);
        else {
            switch (attr.value().type()) { // "type": "type"
            case json::value_t::string: {
                auto schema_type = attr.value().get<std::string>();
                for (auto &t : schema_types)
                    if (t.first == schema_type)
                        type_[static_cast<uint8_t>(t.second)] = type_schema::make(sch, t.second, root, uris, known_keywords);
            } break;
            case json::value_t::array: // "type": ["type1", "type2"]
                for (auto &array_value : attr.value()) {
                    auto schema_type = array_value.get<std::string>();
                    for (auto &t : schema_types)
                        if (t.first == schema_type)
                            type_[static_cast<uint8_t>(t.second)] = type_schema::make(sch, t.second, root, uris, known_keywords);
                }
                break;
            default:
                break;
            }
            sch.erase(attr);
        }
        attr = sch.find("default");
        if (attr != sch.end()) {
            set_default_value(attr.value());
            sch.erase(attr);
        }
        for (auto &key : known_keywords)
            sch.erase(key);
        // with nlohmann::json float instance (but number in schema-definition) can be seen as unsigned or integer -
        // reuse the number-validator for integer values as well, if they have not been specified explicitly
        if (type_[static_cast<uint8_t>(json::value_t::number_float)] && !type_[static_cast<uint8_t>(json::value_t::number_integer)])
            type_[static_cast<uint8_t>(json::value_t::number_integer)] = type_[static_cast<uint8_t>(json::value_t::number_float)];
        // #54: JSON-schema does not differentiate between unsigned and signed integer - nlohmann::json does
        // we stick with JSON-schema: use the integer-validator if instance-value is unsigned
        type_[static_cast<uint8_t>(json::value_t::number_unsigned)] = type_[static_cast<uint8_t>(json::value_t::number_integer)];
        // special for binary types
        if (type_[static_cast<uint8_t>(json::value_t::string)]) {
            type_[static_cast<uint8_t>(json::value_t::binary)] = type_[static_cast<uint8_t>(json::value_t::string)];
        }
        attr = sch.find("enum");
        if (attr != sch.end()) {
            enum_ = {true, attr.value()};
            sch.erase(attr);
        }
        attr = sch.find("const");
        if (attr != sch.end()) {
            const_ = {true, attr.value()};
            sch.erase(attr);
        }
        attr = sch.find("not");
        if (attr != sch.end()) {
            logic_.push_back(std::make_shared<logical_not>(attr.value(), root, uris));
            sch.erase(attr);
        }
        attr = sch.find("allOf");
        if (attr != sch.end()) {
            logic_.push_back(std::make_shared<logical_combination<allOf>>(attr.value(), root, uris));
            sch.erase(attr);
        }
        attr = sch.find("anyOf");
        if (attr != sch.end()) {
            logic_.push_back(std::make_shared<logical_combination<anyOf>>(attr.value(), root, uris));
            sch.erase(attr);
        }
        attr = sch.find("oneOf");
        if (attr != sch.end()) {
            logic_.push_back(std::make_shared<logical_combination<oneOf>>(attr.value(), root, uris));
            sch.erase(attr);
        }
        attr = sch.find("if");
        if (attr != sch.end()) {
            auto attr_then = sch.find("then");
            auto attr_else = sch.find("else");
            if (attr_then != sch.end() || attr_else != sch.end()) {
                if_ = schema::make(attr.value(), root, {"if"}, uris);
                if (attr_then != sch.end()) {
                    then_ = schema::make(attr_then.value(), root, {"then"}, uris);
                    sch.erase(attr_then);
                }
                if (attr_else != sch.end()) {
                    else_ = schema::make(attr_else.value(), root, {"else"}, uris);
                    sch.erase(attr_else);
                }
            }
            sch.erase(attr);
        }
    }
Member Function Documentation
make() [1/2]
std::shared_ptr< schema > anonymous_namespace{json-validator.cpp}::type_schema::make (json & schema, json::value_t type, root_schema * root, const std::vector< nlohmann::json_uri > & uris, std::set< std::string > & kw) static private
Definition at line 1318 of file json-validator.cpp.
{
    switch (type) {
    case json::value_t::null:
        return std::make_shared<null>(schema, root);
    case json::value_t::number_unsigned:
    case json::value_t::number_integer:
        return std::make_shared<numeric<json::number_integer_t>>(schema, root, kw);
    case json::value_t::number_float:
        return std::make_shared<numeric<json::number_float_t>>(schema, root, kw);
    case json::value_t::string:
        return std::make_shared<string>(schema, root);
    case json::value_t::boolean:
        return std::make_shared<boolean_type>(schema, root);
    case json::value_t::object:
        return std::make_shared<object>(schema, root, uris);
    case json::value_t::array:
        return std::make_shared<array>(schema, root, uris);
    case json::value_t::discarded: // not a real type - silence please
        break;
    case json::value_t::binary:
        break;
    }
    return nullptr;
}
Referenced by type_schema().
make() [2/2]
std::shared_ptr< schema > anonymous_namespace{json-validator.cpp}::type_schema::make (json & schema, json::value_t type, root_schema * , const std::vector< nlohmann::json_uri > & , std::set< std::string > &) static private
make_for_default_() [1/2]
virtual std::shared_ptr< schema > anonymous_namespace{json-validator.cpp}::type_schema::make_for_default_ (std::shared_ptr<::schema > & , root_schema * , std::vector< nlohmann::json_uri > & , nlohmann::json & default_value) const inline override protected virtual
Reimplemented from anonymous_namespace{json-validator.cpp}::schema.
Definition at line 597 of file json-validator.cpp.
    {
        auto result = std::make_shared<type_schema>(*this);
        result->set_default_value(default_value);
        return result;
    };
References anonymous_namespace{json-validator.cpp}::schema::set_default_value().
make_for_default_() [2/2]
virtual std::shared_ptr< schema > anonymous_namespace{json-validator.cpp}::type_schema::make_for_default_ (std::shared_ptr<::schema > & , root_schema * , std::vector< nlohmann::json_uri > & , nlohmann::json & default_value) const inline override protected virtual
Reimplemented from anonymous_namespace{json-validator.cpp}::schema.
Definition at line 597 of file json-validator.cpp.
    {
        auto result = std::make_shared<type_schema>(*this);
        result->set_default_value(default_value);
        return result;
    };
validate() [1/2]
void anonymous_namespace{json-validator.cpp}::type_schema::validate (const json::json_pointer & ptr, const json & instance, json_patch & patch, error_handler & e) const inline final override private virtual
Implements anonymous_namespace{json-validator.cpp}::schema.
Definition at line 550 of file json-validator.cpp.
    {
        // depending on the type of instance run the type specific validator - if present
        auto type = type_[static_cast<uint8_t>(instance.type())];
        if (type)
            type->validate(ptr, instance, patch, e);
        else
            e.error(ptr, instance, "unexpected instance type");
        if (enum_.first) {
            bool seen_in_enum = false;
            for (auto &v : enum_.second)
                if (instance == v) {
                    seen_in_enum = true;
                    break;
                }
            if (!seen_in_enum)
                e.error(ptr, instance, "instance not found in required enum");
        }
        if (const_.first &&
            const_.second != instance)
            e.error(ptr, instance, "instance not const");
        for (auto l : logic_)
            l->validate(ptr, instance, patch, e);
        if (if_) {
            first_error_handler err;
            if_->validate(ptr, instance, patch, err);
            if (!err) {
                if (then_)
                    then_->validate(ptr, instance, patch, e);
            } else {
                if (else_)
                    else_->validate(ptr, instance, patch, e);
            }
        }
        if (instance.is_null()) {
            patch.add(nlohmann::json::json_pointer{}, default_value_);
        }
    }
References nlohmann::json_patch::add(), const_, anonymous_namespace{json-validator.cpp}::schema::default_value_, else_, enum_, nlohmann::json_schema::error_handler::error(), if_, logic_, then_, type_, and anonymous_namespace{json-validator.cpp}::schema::validate().
validate() [2/2]
void anonymous_namespace{json-validator.cpp}::type_schema::validate (const json::json_pointer & ptr, const json & instance, json_patch & patch, error_handler & e) const inline final override private virtual
Implements anonymous_namespace{json-validator.cpp}::schema.
Definition at line 550 of file json-validator.cpp.
    {
        // depending on the type of instance run the type specific validator - if present
        auto type = type_[static_cast<uint8_t>(instance.type())];
        if (type)
            type->validate(ptr, instance, patch, e);
        else
            e.error(ptr, instance, "unexpected instance type");
        if (enum_.first) {
            bool seen_in_enum = false;
            for (auto &v : enum_.second)
                if (instance == v) {
                    seen_in_enum = true;
                    break;
                }
            if (!seen_in_enum)
                e.error(ptr, instance, "instance not found in required enum");
        }
        if (const_.first &&
            const_.second != instance)
            e.error(ptr, instance, "instance not const");
        for (auto l : logic_)
            l->validate(ptr, instance, patch, e);
        if (if_) {
            first_error_handler err;
            if_->validate(ptr, instance, patch, err);
            if (!err) {
                if (then_)
                    then_->validate(ptr, instance, patch, e);
            } else {
                if (else_)
                    else_->validate(ptr, instance, patch, e);
            }
        }
        if (instance.is_null()) {
            patch.add(nlohmann::json::json_pointer{}, default_value_);
        }
    }
Member Data Documentation
const_
std::pair< bool, json > anonymous_namespace{json-validator.cpp}::type_schema::const_ private
Definition at line 539 of file json-validator.cpp.
Referenced by type_schema(), and validate().
else_
std::shared_ptr< schema > anonymous_namespace{json-validator.cpp}::type_schema::else_ private
Definition at line 548 of file json-validator.cpp.
Referenced by type_schema(), and validate().
enum_
std::pair< bool, json > anonymous_namespace{json-validator.cpp}::type_schema::enum_ private
Definition at line 539 of file json-validator.cpp.
Referenced by type_schema(), and validate().
if_
std::shared_ptr< schema > anonymous_namespace{json-validator.cpp}::type_schema::if_ private
Definition at line 548 of file json-validator.cpp.
Referenced by type_schema(), and validate().
logic_
std::vector< std::shared_ptr< schema > > anonymous_namespace{json-validator.cpp}::type_schema::logic_ private
Definition at line 540 of file json-validator.cpp.
Referenced by type_schema(), and validate().
then_
std::shared_ptr< schema > anonymous_namespace{json-validator.cpp}::type_schema::then_ private
Definition at line 548 of file json-validator.cpp.
Referenced by type_schema(), and validate().
type_
std::vector< std::shared_ptr< schema > > anonymous_namespace{json-validator.cpp}::type_schema::type_ private
Definition at line 538 of file json-validator.cpp.
Referenced by type_schema(), and validate().
The documentation for this class was generated from the following file:
lib/json-schema-validator/src/json-validator.cpp