MQTTSuite: mqtt::bridge::lib::SSEDistributor Class Reference
mqtt::bridge::lib::SSEDistributor Class Reference
#include <SSEDistributor.h>
Classes
class EventReceiver
class Event
Public Member Functions
SSEDistributor (const SSEDistributor &)=delete
SSEDistributor & operator= (const SSEDistributor &)=delete
SSEDistributor (SSEDistributor &&)=delete
SSEDistributor & operator= (SSEDistributor &&)=delete
~SSEDistributor ()=default
void addEventReceiver (const std::shared_ptr< express::Response > &response, const std::string &lastEventId)
void bridgesStarting ()
void bridgesStarted ()
void bridgesStopping ()
void bridgesStopped ()
void bridgeDisabled (const std::string &bridgeName)
void bridgeStarting (const std::string &bridgeName)
void bridgeStarted (const std::string &bridgeName)
void bridgeStopping (const std::string &bridgeName)
void bridgeStopped (const std::string &bridgeName)
void brokerDisabled (const std::string &bridgeName, const std::string &instanceName)
void brokerConnecting (const std::string &bridgeName, const std::string &instanceName)
void brokerConnected (const std::string &bridgeName, const std::string &instanceName)
void brokerDisconnecting (const std::string &bridgeName, const std::string &instanceName)
void brokerDisconnected (const std::string &bridgeName, const std::string &instanceName)
Static Public Member Functions
static SSEDistributor & instance ()
Private Member Functions
SSEDistributor ()
void sendEvent (const std::string &data, const std::string &event="", const std::string &id="")
void sendJsonEvent (const nlohmann::json &json, const std::string &event="", const std::string &id="")
std::string bridgesStartedAt () const
Static Private Member Functions
static void sendEvent (const std::shared_ptr< express::Response > &response, const std::string &data, const std::string &event, const std::string &id)
static void sendJsonEvent (const std::shared_ptr< express::Response > &response, const nlohmann::json &json, const std::string &event="", const std::string &id="")
static std::string timePointToString (const std::chrono::time_point< std::chrono::system_clock > &timePoint)
static std::string durationToString (const std::chrono::time_point< std::chrono::system_clock > &bevore, const std::chrono::time_point< std::chrono::system_clock > &later=std::chrono::system_clock::now())
Private Attributes
std::list< EventReceiver > eventReceiverList
std::chrono::time_point< std::chrono::system_clock > onlineSinceTimePoint
std::chrono::time_point< std::chrono::system_clock > bridgesStartTimePoint
uint64_t id = 0
std::list< Event > replayEvents
Detailed Description
Definition at line 63 of file SSEDistributor.h.
Constructor & Destructor Documentation
SSEDistributor() [1/3]
mqtt::bridge::lib::SSEDistributor::SSEDistributor () private
Definition at line 64 of file SSEDistributor.cpp.
        : onlineSinceTimePoint(std::chrono::system_clock::now()) {
    }
References onlineSinceTimePoint.
SSEDistributor() [2/3]
mqtt::bridge::lib::SSEDistributor::SSEDistributor (const SSEDistributor &) delete
SSEDistributor() [3/3]
mqtt::bridge::lib::SSEDistributor::SSEDistributor (SSEDistributor &&) delete
~SSEDistributor()
mqtt::bridge::lib::SSEDistributor::~SSEDistributor () default
Member Function Documentation
addEventReceiver()
void mqtt::bridge::lib::SSEDistributor::addEventReceiver (const std::shared_ptr< express::Response > & response, const std::string & lastEventId)
Definition at line 74 of file SSEDistributor.cpp.
{
        auto& eventReceiver = eventReceiverList.emplace_back(response);
        response->getSocketContext()->onDisconnected([this, &eventReceiver]() {
            eventReceiverList.remove(eventReceiver);
        });
        for (const auto& event : replayEvents) {
            sendEvent(response, event.getData(), event.getEvent(), event.getId());
        }
    }
References eventReceiverList, mqtt::bridge::lib::SSEDistributor::Event::getData(), mqtt::bridge::lib::SSEDistributor::Event::getEvent(), mqtt::bridge::lib::SSEDistributor::Event::getId(), replayEvents, and sendEvent().
Referenced by main().
bridgeDisabled()
void mqtt::bridge::lib::SSEDistributor::bridgeDisabled (const std::string & bridgeName)
Definition at line 144 of file SSEDistributor.cpp.
{
        sendJsonEvent(
            {{"at", timePointToString(std::chrono::system_clock::now())}, {"name", bridgeName}}, "bridge_disabled", std::to_string(id++));
    }
References id.
bridgesStarted()
void mqtt::bridge::lib::SSEDistributor::bridgesStarted ()
Definition at line 132 of file SSEDistributor.cpp.
{
        sendJsonEvent({{"at", timePointToString(std::chrono::system_clock::now())}}, "bridges_started", std::to_string(id++));
    }
References id.
Referenced by mqtt::bridge::lib::BridgeStore::mqttConnected().
bridgesStartedAt()
std::string mqtt::bridge::lib::SSEDistributor::bridgesStartedAt () const private
Definition at line 199 of file SSEDistributor.cpp.
{
        return timePointToString(bridgesStartTimePoint);
    }
References bridgesStartTimePoint.
bridgesStarting()
void mqtt::bridge::lib::SSEDistributor::bridgesStarting ()
Definition at line 126 of file SSEDistributor.cpp.
{
        replayEvents.clear();
        sendJsonEvent({{"at", timePointToString(std::chrono::system_clock::now())}}, "bridges_starting", std::to_string(id++));
    }
References id, and replayEvents.
Referenced by startBridges().
bridgesStopped()
void mqtt::bridge::lib::SSEDistributor::bridgesStopped ()
Definition at line 140 of file SSEDistributor.cpp.
{
        sendJsonEvent({{"at", timePointToString(std::chrono::system_clock::now())}}, "bridges_stopped", std::to_string(id++));
    }
References id.
Referenced by tryRestartBridges().
bridgesStopping()
void mqtt::bridge::lib::SSEDistributor::bridgesStopping ()
Definition at line 136 of file SSEDistributor.cpp.
{
        sendJsonEvent({{"at", timePointToString(std::chrono::system_clock::now())}}, "bridges_stopping", std::to_string(id++));
    }
References id.
Referenced by closeBridges().
bridgeStarted()
void mqtt::bridge::lib::SSEDistributor::bridgeStarted (const std::string & bridgeName)
Definition at line 154 of file SSEDistributor.cpp.
{
        sendJsonEvent(
            {{"at", timePointToString(std::chrono::system_clock::now())}, {"name", bridgeName}}, "bridge_started", std::to_string(id++));
    }
References id.
Referenced by mqtt::bridge::lib::Bridge::addMqtt().
bridgeStarting()
void mqtt::bridge::lib::SSEDistributor::bridgeStarting (const std::string & bridgeName)
Definition at line 149 of file SSEDistributor.cpp.
{
        sendJsonEvent(
            {{"at", timePointToString(std::chrono::system_clock::now())}, {"name", bridgeName}}, "bridge_starting", std::to_string(id++));
    }
References id.
bridgeStopped()
void mqtt::bridge::lib::SSEDistributor::bridgeStopped (const std::string & bridgeName)
Definition at line 164 of file SSEDistributor.cpp.
{
        sendJsonEvent(
            {{"at", timePointToString(std::chrono::system_clock::now())}, {"name", bridgeName}}, "bridge_stopped", std::to_string(id++));
    }
References id.
Referenced by mqtt::bridge::lib::Bridge::removeMqtt().
bridgeStopping()
void mqtt::bridge::lib::SSEDistributor::bridgeStopping (const std::string & bridgeName)
Definition at line 159 of file SSEDistributor.cpp.
{
        sendJsonEvent(
            {{"at", timePointToString(std::chrono::system_clock::now())}, {"name", bridgeName}}, "bridge_stopping", std::to_string(id++));
    }
References id.
brokerConnected()
void mqtt::bridge::lib::SSEDistributor::brokerConnected (const std::string & bridgeName, const std::string & instanceName)
Definition at line 181 of file SSEDistributor.cpp.
{
        sendJsonEvent({{"at", timePointToString(std::chrono::system_clock::now())}, {"bridge", bridgeName}, {"instance", instanceName}},
                      "broker_connected",
                      std::to_string(id++));
    }
References id.
Referenced by mqtt::bridge::lib::Bridge::addMqtt().
brokerConnecting()
void mqtt::bridge::lib::SSEDistributor::brokerConnecting (const std::string & bridgeName, const std::string & instanceName)
Definition at line 175 of file SSEDistributor.cpp.
{
        sendJsonEvent({{"at", timePointToString(std::chrono::system_clock::now())}, {"bridge", bridgeName}, {"instance", instanceName}},
                      "broker_connecting",
                      std::to_string(id++));
    }
References id.
brokerDisabled()
void mqtt::bridge::lib::SSEDistributor::brokerDisabled (const std::string & bridgeName, const std::string & instanceName)
Definition at line 169 of file SSEDistributor.cpp.
{
        sendJsonEvent({{"at", timePointToString(std::chrono::system_clock::now())}, {"bridge", bridgeName}, {"instance", instanceName}},
                      "broker_disabled",
                      std::to_string(id++));
    }
References id.
brokerDisconnected()
void mqtt::bridge::lib::SSEDistributor::brokerDisconnected (const std::string & bridgeName, const std::string & instanceName)
Definition at line 193 of file SSEDistributor.cpp.
{
        sendJsonEvent({{"at", timePointToString(std::chrono::system_clock::now())}, {"bridge", bridgeName}, {"instance", instanceName}},
                      "broker_disconnected",
                      std::to_string(id++));
    }
References id.
Referenced by mqtt::bridge::lib::Bridge::removeMqtt().
brokerDisconnecting()
void mqtt::bridge::lib::SSEDistributor::brokerDisconnecting (const std::string & bridgeName, const std::string & instanceName)
Definition at line 187 of file SSEDistributor.cpp.
{
        sendJsonEvent({{"at", timePointToString(std::chrono::system_clock::now())}, {"bridge", bridgeName}, {"instance", instanceName}},
                      "broker_disconnecting",
                      std::to_string(id++));
    }
References id.
durationToString()
std::string mqtt::bridge::lib::SSEDistributor::durationToString (const std::chrono::time_point< std::chrono::system_clock > & bevore, const std::chrono::time_point< std::chrono::system_clock > & later = std::chrono::system_clock::now()) static private
Definition at line 218 of file SSEDistributor.cpp.
{
        using seconds_duration_type = std::chrono::duration<std::chrono::seconds::rep>::rep;
        seconds_duration_type totalSeconds = std::chrono::duration_cast<std::chrono::seconds>(later - bevore).count();
        // Compute days, hours, minutes, and seconds
        seconds_duration_type days = totalSeconds / 86400; // 86400 seconds in a day
        seconds_duration_type remainder = totalSeconds % 86400;
        seconds_duration_type hours = remainder / 3600;
        remainder = remainder % 3600;
        seconds_duration_type minutes = remainder / 60;
        seconds_duration_type seconds = remainder % 60;
        // Format the components into a string using stringstream
        std::ostringstream oss;
        if (days > 0) {
            oss << days << " day" << (days == 1 ? "" : "s") << ", ";
        }
        oss << std::setw(2) << std::setfill('0') << hours << ":" << std::setw(2) << std::setfill('0') << minutes << ":" << std::setw(2)
            << std::setfill('0') << seconds;
        return oss.str();
    }
instance()
SSEDistributor & mqtt::bridge::lib::SSEDistributor::instance () static
Definition at line 68 of file SSEDistributor.cpp.
{
        static SSEDistributor sseDistributor;
        return sseDistributor;
    }
Referenced by mqtt::bridge::lib::Bridge::addMqtt(), closeBridges(), main(), mqtt::bridge::lib::BridgeStore::mqttConnected(), mqtt::bridge::lib::Bridge::removeMqtt(), startBridges(), and tryRestartBridges().
operator=() [1/2]
SSEDistributor & mqtt::bridge::lib::SSEDistributor::operator= (const SSEDistributor &) delete
operator=() [2/2]
SSEDistributor & mqtt::bridge::lib::SSEDistributor::operator= (SSEDistributor &&) delete
sendEvent() [1/2]
void mqtt::bridge::lib::SSEDistributor::sendEvent (const std::shared_ptr< express::Response > & response, const std::string & data, const std::string & event, const std::string & id) static private
Definition at line 87 of file SSEDistributor.cpp.
{
        if (response->isConnected()) {
            if (!event.empty()) {
                response->sendFragment("event:" + event);
            }
            if (!id.empty()) {
                response->sendFragment("id:" + id);
            }
            response->sendFragment("data:" + data);
            response->sendFragment();
        }
    }
Referenced by addEventReceiver(), sendEvent(), and sendJsonEvent().
sendEvent() [2/2]
void mqtt::bridge::lib::SSEDistributor::sendEvent (const std::string & data, const std::string & event = "", const std::string & id = "") private
Definition at line 110 of file SSEDistributor.cpp.
{
        VLOG(0) << "Server sent event: " << event << "\n" << data;
        for (const auto& eventReceiver : eventReceiverList) {
            if (const auto& response = eventReceiver.getResponse()) {
                sendEvent(response, data, event, id);
            }
        }
        replayEvents.emplace_back(data, event, id);
    }
References eventReceiverList, mqtt::bridge::lib::SSEDistributor::EventReceiver::getResponse(), replayEvents, and sendEvent().
Referenced by sendJsonEvent().
sendJsonEvent() [1/2]
void mqtt::bridge::lib::SSEDistributor::sendJsonEvent (const nlohmann::json & json, const std::string & event = "", const std::string & id = "") private
Definition at line 122 of file SSEDistributor.cpp.
{
        sendEvent(json.dump(), event, id);
    }
References sendEvent().
sendJsonEvent() [2/2]
void mqtt::bridge::lib::SSEDistributor::sendJsonEvent (const std::shared_ptr< express::Response > & response, const nlohmann::json & json, const std::string & event = "", const std::string & id = "") static private
Definition at line 103 of file SSEDistributor.cpp.
{
        sendEvent(response, json.dump(), event, id);
    }
References sendEvent().
timePointToString()
std::string mqtt::bridge::lib::SSEDistributor::timePointToString (const std::chrono::time_point< std::chrono::system_clock > & timePoint) static private
Definition at line 203 of file SSEDistributor.cpp.
{
        std::time_t time = std::chrono::system_clock::to_time_t(timePoint);
        const std::tm* tm_ptr = std::gmtime(&time);
        char buffer[100];
        std::string onlineSince = "Formatting error";
        // Format: "2025-02-02 14:30:00"
        if (std::strftime(buffer, sizeof(buffer), "%Y-%m-%d %H:%M:%S", tm_ptr)) {
            onlineSince = std::string(buffer) + " UTC";
        }
        return onlineSince;
    }
Member Data Documentation
bridgesStartTimePoint
std::chrono::time_point<std::chrono::system_clock> mqtt::bridge::lib::SSEDistributor::bridgesStartTimePoint private
Definition at line 158 of file SSEDistributor.h.
Referenced by bridgesStartedAt().
eventReceiverList
std::list<EventReceiver> mqtt::bridge::lib::SSEDistributor::eventReceiverList private
Definition at line 156 of file SSEDistributor.h.
Referenced by addEventReceiver(), and sendEvent().
id
uint64_t mqtt::bridge::lib::SSEDistributor::id = 0 private
Definition at line 159 of file SSEDistributor.h.
Referenced by bridgeDisabled(), bridgesStarted(), bridgesStarting(), bridgesStopped(), bridgesStopping(), bridgeStarted(), bridgeStarting(), bridgeStopped(), bridgeStopping(), brokerConnected(), brokerConnecting(), brokerDisabled(), brokerDisconnected(), and brokerDisconnecting().
onlineSinceTimePoint
std::chrono::time_point<std::chrono::system_clock> mqtt::bridge::lib::SSEDistributor::onlineSinceTimePoint private
Definition at line 157 of file SSEDistributor.h.
Referenced by SSEDistributor().
replayEvents
std::list<Event> mqtt::bridge::lib::SSEDistributor::replayEvents private
Definition at line 161 of file SSEDistributor.h.
Referenced by addEventReceiver(), bridgesStarting(), and sendEvent().
The documentation for this class was generated from the following files:
mqttbridge/lib/SSEDistributor.h
mqttbridge/lib/SSEDistributor.cpp