MQTTSuite: conanfile.JsonSchemaValidatorConan Class Reference
conanfile.JsonSchemaValidatorConan Class Reference
Public Member Functions
layout (self)
build (self)
package (self)
package_info (self)
Static Public Attributes
str name = 'JsonSchemaValidator'
version = get_version()
str url = 'https://github.com/pboettch/json-schema-validator'
str license = 'MIT'
str settings = 'os', 'compiler', 'build_type', 'arch'
dict options
dict default_options
str generators = "CMakeDeps"
list exports_sources
tuple requires
Protected Member Functions
_configure_cmake (self)
Static Protected Attributes
_cmake = None
Detailed Description
Definition at line 18 of file conanfile.py.
Member Function Documentation
_configure_cmake()
conanfile.JsonSchemaValidatorConan._configure_cmake (self) protected
Definition at line 49 of file conanfile.py.
    def _configure_cmake(self):
        if self._cmake:
            return self._cmake
        self._cmake = CMake(self)
        self._cmake.definitions['JSON_VALIDATOR_BUILD_EXAMPLES'] = self.options.build_examples
        self._cmake.definitions['JSON_VALIDATOR_BUILD_TESTS'] = self.options.build_tests
        self._cmake.configure()
        return self._cmake
References conanfile.JsonSchemaValidatorConan._cmake, and conanfile.JsonSchemaValidatorConan.options.
Referenced by conanfile.JsonSchemaValidatorConan.build(), and conanfile.JsonSchemaValidatorConan.package().
build()
conanfile.JsonSchemaValidatorConan.build (self)
Definition at line 62 of file conanfile.py.
    def build(self):
        cmake = self._configure_cmake()
        cmake.configure()
        cmake.build()
References conanfile.JsonSchemaValidatorConan._configure_cmake().
layout()
conanfile.JsonSchemaValidatorConan.layout (self)
Definition at line 58 of file conanfile.py.
    def layout(self):
        build_type = str(self.settings.build_type).lower()
        self.folders.build = "build-{}".format(build_type)
References conanfile.JsonSchemaValidatorConan.settings.
package()
conanfile.JsonSchemaValidatorConan.package (self)
Definition at line 67 of file conanfile.py.
    def package(self):
        cmake = self._configure_cmake()
        cmake.install()
References conanfile.JsonSchemaValidatorConan._configure_cmake().
package_info()
conanfile.JsonSchemaValidatorConan.package_info (self)
Definition at line 71 of file conanfile.py.
    def package_info(self):
        includedir = os.path.join(self.package_folder, "include")
        self.cpp_info.includedirs = [includedir]
        libdir = os.path.join(self.package_folder, "lib")
        self.cpp_info.libdirs = [libdir]
        self.cpp_info.libs += tools.collect_libs(self, libdir)
        bindir = os.path.join(self.package_folder, "bin")
        self.output.info("Appending PATH environment variable: {}".format(bindir))
        self.env_info.PATH.append(bindir)
        self.user_info.VERSION = self.version
References conanfile.JsonSchemaValidatorConan.version.
Member Data Documentation
_cmake
conanfile.JsonSchemaValidatorConan._cmake = None static protected
Definition at line 47 of file conanfile.py.
Referenced by conanfile.JsonSchemaValidatorConan._configure_cmake().
default_options
dict conanfile.JsonSchemaValidatorConan.default_options static
Initial value:
=  {
        'shared': False,
        'fPIC': True,
        'build_examples': True,
        'build_tests': False
    }
Definition at line 30 of file conanfile.py.
exports_sources
list conanfile.JsonSchemaValidatorConan.exports_sources static
Initial value:
=  [
        'CMakeLists.txt',
        'nlohmann_json_schema_validatorConfig.cmake.in',
        'src/*',
        'app/*',
        'test/*',
    ]
Definition at line 37 of file conanfile.py.
generators
str conanfile.JsonSchemaValidatorConan.generators = "CMakeDeps" static
Definition at line 36 of file conanfile.py.
license
str conanfile.JsonSchemaValidatorConan.license = 'MIT' static
Definition at line 22 of file conanfile.py.
name
str conanfile.JsonSchemaValidatorConan.name = 'JsonSchemaValidator' static
Definition at line 19 of file conanfile.py.
options
dict conanfile.JsonSchemaValidatorConan.options static
Initial value:
=  {
        'shared': [True, False],
        'fPIC': [True, False],
        'build_examples': [True, False],
        'build_tests': [True, False]
    }
Definition at line 24 of file conanfile.py.
Referenced by conanfile.JsonSchemaValidatorConan._configure_cmake().
requires
tuple conanfile.JsonSchemaValidatorConan.requires static
Initial value:
=  (
        'nlohmann_json/3.11.2'
    )
Definition at line 44 of file conanfile.py.
settings
str conanfile.JsonSchemaValidatorConan.settings = 'os', 'compiler', 'build_type', 'arch' static
Definition at line 23 of file conanfile.py.
Referenced by conanfile.JsonSchemaValidatorConan.layout().
url
str conanfile.JsonSchemaValidatorConan.url = 'https://github.com/pboettch/json-schema-validator' static
Definition at line 21 of file conanfile.py.
version
conanfile.JsonSchemaValidatorConan.version = get_version() static
Definition at line 20 of file conanfile.py.
Referenced by conanfile.JsonSchemaValidatorConan.package_info().
The documentation for this class was generated from the following file:
lib/json-schema-validator/conanfile.py