MQTTSuite: inja::IfStatementNode Class Reference
inja::IfStatementNode Class Reference
#include <inja.hpp>
Public Member Functions
IfStatementNode (BlockNode *const parent, size_t pos)
IfStatementNode (bool is_nested, BlockNode *const parent, size_t pos)
void accept (NodeVisitor &v) const override
Public Member Functions inherited from inja::StatementNode
StatementNode (size_t pos)
Public Member Functions inherited from inja::AstNode
AstNode (size_t pos)
AstNode (const AstNode &)=default
AstNode & operator= (const AstNode &)=default
virtual ~AstNode ()
Public Attributes
ExpressionListNode condition
BlockNode true_statement
BlockNode false_statement
BlockNode *const parent
const bool is_nested
bool has_false_statement {false}
Public Attributes inherited from inja::AstNode
size_t pos
Detailed Description
Definition at line 706 of file inja.hpp.
Constructor & Destructor Documentation
IfStatementNode() [1/2]
inja::IfStatementNode::IfStatementNode (BlockNode *const parent, size_t pos) inline explicit
Definition at line 716 of file inja.hpp.
            : StatementNode(pos)
            , parent(parent)
            , is_nested(false) {
        }
References is_nested, parent, and inja::StatementNode::StatementNode().
IfStatementNode() [2/2]
inja::IfStatementNode::IfStatementNode (bool is_nested, BlockNode *const parent, size_t pos) inline explicit
Definition at line 721 of file inja.hpp.
            : StatementNode(pos)
            , parent(parent)
            , is_nested(is_nested) {
        }
References is_nested, parent, and inja::StatementNode::StatementNode().
Member Function Documentation
accept()
void inja::IfStatementNode::accept (NodeVisitor & v) const inline override virtual
Implements inja::StatementNode.
Definition at line 727 of file inja.hpp.
{
            v.visit(*this);
        }
References inja::NodeVisitor::visit().
Member Data Documentation
condition
ExpressionListNode inja::IfStatementNode::condition
Definition at line 708 of file inja.hpp.
false_statement
BlockNode inja::IfStatementNode::false_statement
Definition at line 710 of file inja.hpp.
has_false_statement
bool inja::IfStatementNode::has_false_statement {false}
Definition at line 714 of file inja.hpp.
{false};
Referenced by inja::Renderer::visit().
is_nested
const bool inja::IfStatementNode::is_nested
Definition at line 713 of file inja.hpp.
Referenced by IfStatementNode(), and IfStatementNode().
parent
BlockNode* const inja::IfStatementNode::parent
Definition at line 711 of file inja.hpp.
Referenced by IfStatementNode(), and IfStatementNode().
true_statement
BlockNode inja::IfStatementNode::true_statement
Definition at line 709 of file inja.hpp.
The documentation for this class was generated from the following file:
lib/inja.hpp