MQTTSuite: mqtt::mqttstore::lib::ConfigStorage Class Reference
mqtt::mqttstore::lib::ConfigStorage Class Reference
#include <ConfigSections.h>
Public Member Functions
ConfigStorage (utils::SubCommand *parent)
~ConfigStorage () override
std::string getRawTable () const
bool getAutoCreateRawTable () const
std::string getProjectionFile () const
Static Public Attributes
static constexpr std::string_view NAME {"storage"}
static constexpr std::string_view DESCRIPTION {"Generic MQTT persistence behavior"}
Private Attributes
CLI::Option * rawTableOpt
CLI::Option * autoCreateRawTableOpt
CLI::Option * projectionFileOpt
Detailed Description
Definition at line 101 of file ConfigSections.h.
Constructor & Destructor Documentation
ConfigStorage()
mqtt::mqttstore::lib::ConfigStorage::ConfigStorage (utils::SubCommand * parent)
Definition at line 158 of file ConfigSections.cpp.
        : utils::SubCommand(parent, this, "Storage behavior")
        , rawTableOpt(setConfigurable(
              addOption("--raw-table", "Raw MQTT envelope table", "identifier", "mqtt_messages", CLI::TypeValidator<std::string>()), true))
        , autoCreateRawTableOpt(setConfigurable(addFlag("--auto-create-raw-table{true}",
                                                        "Create the raw MQTT envelope table automatically",
                                                        "bool",
                                                        "true",
                                                        CLI::IsMember({"true", "false"})),
                                                true))
        , projectionFileOpt(setConfigurable(
              addOption("--projection-file", "Optional JSON file describing typed projections", "filename", CLI::ExistingFile), true)) {
    }
References autoCreateRawTableOpt, and rawTableOpt.
~ConfigStorage()
mqtt::mqttstore::lib::ConfigStorage::~ConfigStorage () override default
Member Function Documentation
getAutoCreateRawTable()
bool mqtt::mqttstore::lib::ConfigStorage::getAutoCreateRawTable () const nodiscard
Definition at line 178 of file ConfigSections.cpp.
{
        return autoCreateRawTableOpt->as<bool>();
    }
References autoCreateRawTableOpt.
Referenced by anonymous_namespace{SocketContextFactory.cpp}::getStorageOptions(), and anonymous_namespace{SubProtocolFactory.cpp}::getStorageOptions().
getProjectionFile()
std::string mqtt::mqttstore::lib::ConfigStorage::getProjectionFile () const nodiscard
Definition at line 182 of file ConfigSections.cpp.
{
        return projectionFileOpt->as<std::string>();
    }
References projectionFileOpt.
Referenced by anonymous_namespace{SocketContextFactory.cpp}::getStorageOptions(), and anonymous_namespace{SubProtocolFactory.cpp}::getStorageOptions().
getRawTable()
std::string mqtt::mqttstore::lib::ConfigStorage::getRawTable () const nodiscard
Definition at line 174 of file ConfigSections.cpp.
{
        return rawTableOpt->as<std::string>();
    }
References rawTableOpt.
Referenced by anonymous_namespace{SocketContextFactory.cpp}::getStorageOptions(), and anonymous_namespace{SubProtocolFactory.cpp}::getStorageOptions().
Member Data Documentation
autoCreateRawTableOpt
CLI::Option* mqtt::mqttstore::lib::ConfigStorage::autoCreateRawTableOpt private
Definition at line 115 of file ConfigSections.h.
Referenced by ConfigStorage(), and getAutoCreateRawTable().
DESCRIPTION
std::string_view mqtt::mqttstore::lib::ConfigStorage::DESCRIPTION {"Generic MQTT persistence behavior"} static constexpr
Definition at line 104 of file ConfigSections.h.
{"Generic MQTT persistence behavior"};
NAME
std::string_view mqtt::mqttstore::lib::ConfigStorage::NAME {"storage"} static constexpr
Definition at line 103 of file ConfigSections.h.
{"storage"};
projectionFileOpt
CLI::Option* mqtt::mqttstore::lib::ConfigStorage::projectionFileOpt private
Definition at line 116 of file ConfigSections.h.
Referenced by getProjectionFile().
rawTableOpt
CLI::Option* mqtt::mqttstore::lib::ConfigStorage::rawTableOpt private
Definition at line 114 of file ConfigSections.h.
Referenced by ConfigStorage(), and getRawTable().
The documentation for this class was generated from the following files:
mqttstore/lib/ConfigSections.h
mqttstore/lib/ConfigSections.cpp