MQTTSuite: nlohmann::json_schema::error_handler Class Reference
nlohmann::json_schema::error_handler Class Reference abstract
#include <json-schema.hpp>
Public Member Functions
virtual ~error_handler ()
virtual void error (const json::json_pointer &, const json &, const std::string &)=0
Detailed Description
Definition at line 138 of file json-schema.hpp.
Constructor & Destructor Documentation
~error_handler()
virtual nlohmann::json_schema::error_handler::~error_handler () inline virtual
Definition at line 141 of file json-schema.hpp.
{}
Member Function Documentation
error()
virtual void nlohmann::json_schema::error_handler::error (const json::json_pointer & , const json & , const std::string &) pure virtual
Implemented in nlohmann::json_schema::basic_error_handler, anonymous_namespace{json-validator.cpp}::first_error_handler, anonymous_namespace{json-validator.cpp}::first_error_handler, anonymous_namespace{json-validator.cpp}::throwing_error_handler, and anonymous_namespace{json-validator.cpp}::throwing_error_handler.
Referenced by anonymous_namespace{json-validator.cpp}::schema_ref::default_value(), anonymous_namespace{json-validator.cpp}::logical_combination< combine_logic >::is_validate_complete(), anonymous_namespace{json-validator.cpp}::logical_combination< combine_logic >::is_validate_complete(), anonymous_namespace{json-validator.cpp}::string::validate(), anonymous_namespace{json-validator.cpp}::numeric< T >::validate(), anonymous_namespace{json-validator.cpp}::null::validate(), anonymous_namespace{json-validator.cpp}::boolean::validate(), anonymous_namespace{json-validator.cpp}::required::validate(), anonymous_namespace{json-validator.cpp}::schema_ref::validate(), anonymous_namespace{json-validator.cpp}::logical_not::validate(), anonymous_namespace{json-validator.cpp}::logical_combination< combine_logic >::validate(), anonymous_namespace{json-validator.cpp}::object::validate(), anonymous_namespace{json-validator.cpp}::array::validate(), anonymous_namespace{json-validator.cpp}::type_schema::validate(), and nlohmann::json_schema::root_schema::validate().
The documentation for this class was generated from the following file:
lib/json-schema-validator/src/nlohmann/json-schema.hpp