MQTTSuite: mqtt::bridge::lib::Bridge Class Reference
mqtt::bridge::lib::Bridge Class Reference
#include <Bridge.h>
Public Member Functions
Bridge (const std::string &name, const std::string &prefix, bool disabled)
void clear ()
const std::string & getName () const
void addBroker (const std::string &fullInstanceName, Broker &&broker)
Broker * getBroker (const std::string &fullInstanceName)
const std::map< const std::string, Broker > & getBrokerMap () const
void addMqtt (mqtt::bridge::lib::Mqtt *mqtt)
void removeMqtt (mqtt::bridge::lib::Mqtt *mqtt)
void publish (const mqtt::bridge::lib::Mqtt *originMqtt, const iot::mqtt::packets::Publish &publish)
const std::list< const mqtt::bridge::lib::Mqtt * > & getMqttList () const
const std::string & getPrefix () const
bool getDisabled () const
bool getAllConnected1 () const
bool operator< (const Bridge &rhs) const
Private Attributes
std::string name
std::string prefix
bool disabled
std::size_t enabledBroker = 0
std::map< const std::string, Broker > brokerMap
std::list< const mqtt::bridge::lib::Mqtt * > mqttList
Detailed Description
Definition at line 68 of file Bridge.h.
Constructor & Destructor Documentation
Bridge()
mqtt::bridge::lib::Bridge::Bridge (const std::string & name, const std::string & prefix, bool disabled) explicit
Definition at line 61 of file Bridge.cpp.
        : name(name)
        , prefix(prefix)
        , disabled(disabled) {
    }
References disabled, name, and prefix.
Member Function Documentation
addBroker()
void mqtt::bridge::lib::Bridge::addBroker (const std::string & fullInstanceName, Broker && broker)
Definition at line 71 of file Bridge.cpp.
{
        enabledBroker += !broker.getDisabled() ? 1 : 0;
        brokerMap.emplace(fullInstanceName, std::move(broker));
    }
References brokerMap, enabledBroker, and mqtt::bridge::lib::Broker::getDisabled().
addMqtt()
void mqtt::bridge::lib::Bridge::addMqtt (mqtt::bridge::lib::Mqtt * mqtt)
Definition at line 85 of file Bridge.cpp.
{
        mqttList.push_back(mqtt);
        mqtt::bridge::lib::SSEDistributor::instance().brokerConnected(name,
                                                                      mqtt->getMqttContext()->getSocketConnection()->getInstanceName());
        if (mqttList.size() == enabledBroker) {
            mqtt::bridge::lib::SSEDistributor::instance().bridgeStarted(name);
        }
    }
References mqtt::bridge::lib::SSEDistributor::bridgeStarted(), mqtt::bridge::lib::SSEDistributor::brokerConnected(), enabledBroker, mqtt::bridge::lib::SSEDistributor::instance(), mqttList, and name.
Referenced by mqtt::bridge::lib::BridgeStore::mqttConnected().
clear()
void mqtt::bridge::lib::Bridge::clear () inline
Definition at line 72 of file Bridge.h.
                     {
            brokerMap.clear();
        }
References brokerMap.
getAllConnected1()
bool mqtt::bridge::lib::Bridge::getAllConnected1 () const
Definition at line 129 of file Bridge.cpp.
{
        return mqttList.size() == enabledBroker || disabled;
    }
References disabled, enabledBroker, and mqttList.
getBroker()
Broker * mqtt::bridge::lib::Bridge::getBroker (const std::string & fullInstanceName)
Definition at line 77 of file Bridge.cpp.
{
        return &brokerMap.find(fullInstanceName)->second;
    }
References brokerMap.
getBrokerMap()
const std::map< const std::string, Broker > & mqtt::bridge::lib::Bridge::getBrokerMap () const
Definition at line 81 of file Bridge.cpp.
{
        return brokerMap;
    }
References brokerMap.
getDisabled()
bool mqtt::bridge::lib::Bridge::getDisabled () const
Definition at line 125 of file Bridge.cpp.
{
        return disabled;
    }
References disabled.
getMqttList()
const std::list< const Mqtt * > & mqtt::bridge::lib::Bridge::getMqttList () const
Definition at line 137 of file Bridge.cpp.
{
        return mqttList;
    }
References mqttList.
getName()
const std::string & mqtt::bridge::lib::Bridge::getName () const
Definition at line 67 of file Bridge.cpp.
{
        return name;
    }
References name.
Referenced by mqtt::bridge::SocketContextFactory::create(), and mqtt::mqttbridge::websocket::SubProtocolFactory::create().
getPrefix()
const std::string & mqtt::bridge::lib::Bridge::getPrefix () const
Definition at line 121 of file Bridge.cpp.
{
        return prefix;
    }
References prefix.
operator<()
bool mqtt::bridge::lib::Bridge::operator< (const Bridge & rhs) const
Definition at line 133 of file Bridge.cpp.
{
        return name < rhs.name;
    }
References name.
publish()
void mqtt::bridge::lib::Bridge::publish (const mqtt::bridge::lib::Mqtt * originMqtt, const iot::mqtt::packets::Publish & publish)
Definition at line 107 of file Bridge.cpp.
{
        for (const mqtt::bridge::lib::Mqtt* destinationMqtt : mqttList) {
            if (originMqtt != destinationMqtt) {    // Do not reflect message to origin broker. Avoid message looping
                destinationMqtt->sendPublish(prefix //
                                                 + originMqtt->getBroker().getPrefix()      //
                                                 + destinationMqtt->getBroker().getPrefix() //
                                                 + publish.getTopic(),
                                             publish.getMessage(),
                                             publish.getQoS(),
                                             publish.getRetain());
            }
        }
    }
References mqtt::bridge::lib::Mqtt::getBroker(), mqtt::bridge::lib::Broker::getPrefix(), mqttList, and prefix.
Referenced by mqtt::bridge::lib::Mqtt::onPublish().
removeMqtt()
void mqtt::bridge::lib::Bridge::removeMqtt (mqtt::bridge::lib::Mqtt * mqtt)
Definition at line 96 of file Bridge.cpp.
{
        mqttList.remove(mqtt);
        mqtt::bridge::lib::SSEDistributor::instance().brokerDisconnected(name,
                                                                         mqtt->getMqttContext()->getSocketConnection()->getInstanceName());
        if (mqttList.size() == 0) {
            mqtt::bridge::lib::SSEDistributor::instance().bridgeStopped(name);
        }
    }
References mqtt::bridge::lib::SSEDistributor::bridgeStopped(), mqtt::bridge::lib::SSEDistributor::brokerDisconnected(), mqtt::bridge::lib::SSEDistributor::instance(), mqttList, and name.
Referenced by mqtt::bridge::lib::BridgeStore::mqttDisconnected().
Member Data Documentation
brokerMap
std::map<const std::string, Broker> mqtt::bridge::lib::Bridge::brokerMap private
Definition at line 103 of file Bridge.h.
Referenced by addBroker(), clear(), getBroker(), and getBrokerMap().
disabled
bool mqtt::bridge::lib::Bridge::disabled private
Definition at line 100 of file Bridge.h.
Referenced by Bridge(), getAllConnected1(), and getDisabled().
enabledBroker
std::size_t mqtt::bridge::lib::Bridge::enabledBroker = 0 private
Definition at line 101 of file Bridge.h.
Referenced by addBroker(), addMqtt(), and getAllConnected1().
mqttList
std::list<const mqtt::bridge::lib::Mqtt*> mqtt::bridge::lib::Bridge::mqttList private
Definition at line 104 of file Bridge.h.
Referenced by addMqtt(), getAllConnected1(), getMqttList(), publish(), and removeMqtt().
name
std::string mqtt::bridge::lib::Bridge::name private
Definition at line 98 of file Bridge.h.
Referenced by addMqtt(), Bridge(), getName(), operator<(), and removeMqtt().
prefix
std::string mqtt::bridge::lib::Bridge::prefix private
Definition at line 99 of file Bridge.h.
Referenced by Bridge(), getPrefix(), and publish().
The documentation for this class was generated from the following files:
mqttbridge/lib/Bridge.h
mqttbridge/lib/Bridge.cpp