MQTTSuite: anonymous_namespace{json-validator.cpp}::logical_combination_error_handler Class Reference
anonymous_namespace{json-validator.cpp}::logical_combination_error_handler Class Reference
Classes
struct error_entry
Public Member Functions
void error (const json::json_pointer &ptr, const json &instance, const std::string &message) override
void propagate (error_handler &e, const std::string &prefix) const
operator bool () const
void error (const json::json_pointer &ptr, const json &instance, const std::string &message) override
void propagate (error_handler &e, const std::string &prefix) const
operator bool () const
Public Member Functions inherited from nlohmann::json_schema::error_handler
virtual ~error_handler ()
Public Attributes
std::vector< error_entry > error_entry_list_
Detailed Description
Definition at line 429 of file json-validator.cpp.
Member Function Documentation
error() [1/2]
void anonymous_namespace{json-validator.cpp}::logical_combination_error_handler::error (const json::json_pointer & ptr, const json & instance, const std::string & message) inline override virtual
Implements nlohmann::json_schema::error_handler.
Definition at line 440 of file json-validator.cpp.
    {
        error_entry_list_.push_back(error_entry{ptr, instance, message});
    }
References error_entry_list_.
error() [2/2]
void anonymous_namespace{json-validator.cpp}::logical_combination_error_handler::error (const json::json_pointer & ptr, const json & instance, const std::string & message) inline override virtual
Implements nlohmann::json_schema::error_handler.
Definition at line 440 of file json-validator.cpp.
    {
        error_entry_list_.push_back(error_entry{ptr, instance, message});
    }
operator bool() [1/2]
anonymous_namespace{json-validator.cpp}::logical_combination_error_handler::operator bool () const inline
Definition at line 451 of file json-validator.cpp.
{ return !error_entry_list_.empty(); }
References error_entry_list_.
operator bool() [2/2]
anonymous_namespace{json-validator.cpp}::logical_combination_error_handler::operator bool () const inline
Definition at line 451 of file json-validator.cpp.
{ return !error_entry_list_.empty(); }
propagate() [1/2]
void anonymous_namespace{json-validator.cpp}::logical_combination_error_handler::propagate (error_handler & e, const std::string & prefix) const inline
Definition at line 445 of file json-validator.cpp.
    {
        for (const error_entry &entry : error_entry_list_)
            e.error(entry.ptr_, entry.instance_, prefix + entry.message_);
    }
References nlohmann::json_schema::error_handler::error(), error_entry_list_, anonymous_namespace{json-validator.cpp}::logical_combination_error_handler::error_entry::instance_, anonymous_namespace{json-validator.cpp}::logical_combination_error_handler::error_entry::message_, and anonymous_namespace{json-validator.cpp}::logical_combination_error_handler::error_entry::ptr_.
Referenced by anonymous_namespace{json-validator.cpp}::logical_combination< combine_logic >::is_validate_complete(), and anonymous_namespace{json-validator.cpp}::logical_combination< combine_logic >::validate().
propagate() [2/2]
void anonymous_namespace{json-validator.cpp}::logical_combination_error_handler::propagate (error_handler & e, const std::string & prefix) const inline
Definition at line 445 of file json-validator.cpp.
    {
        for (const error_entry &entry : error_entry_list_)
            e.error(entry.ptr_, entry.instance_, prefix + entry.message_);
    }
Member Data Documentation
error_entry_list_
std::vector< error_entry > anonymous_namespace{json-validator.cpp}::logical_combination_error_handler::error_entry_list_
Definition at line 438 of file json-validator.cpp.
Referenced by error(), anonymous_namespace{json-validator.cpp}::logical_combination< combine_logic >::is_validate_complete(), operator bool(), and propagate().
The documentation for this class was generated from the following file:
lib/json-schema-validator/src/json-validator.cpp