MQTTSuite: inja::DataNode Class Reference
inja::DataNode Class Reference
#include <inja.hpp>
Public Member Functions
DataNode (std::string_view ptr_name, size_t pos)
void accept (NodeVisitor &v) const override
Public Member Functions inherited from inja::ExpressionNode
ExpressionNode (size_t pos)
void accept (NodeVisitor &v) const override
Public Member Functions inherited from inja::AstNode
AstNode (size_t pos)
AstNode (const AstNode &)=default
AstNode & operator= (const AstNode &)=default
virtual ~AstNode ()
Static Public Member Functions
static std::string convert_dot_to_ptr (std::string_view ptr_name)
Public Attributes
const std::string name
const json::json_pointer ptr
Public Attributes inherited from inja::AstNode
size_t pos
Detailed Description
Definition at line 481 of file inja.hpp.
Constructor & Destructor Documentation
DataNode()
inja::DataNode::DataNode (std::string_view ptr_name, size_t pos) inline explicit
Definition at line 497 of file inja.hpp.
            : ExpressionNode(pos)
            , name(ptr_name)
            , ptr(json::json_pointer(convert_dot_to_ptr(ptr_name))) {
        }
References convert_dot_to_ptr(), inja::ExpressionNode::ExpressionNode(), name, and ptr.
Member Function Documentation
accept()
void inja::DataNode::accept (NodeVisitor & v) const inline override virtual
Implements inja::AstNode.
Definition at line 503 of file inja.hpp.
{
            v.visit(*this);
        }
References inja::NodeVisitor::visit().
convert_dot_to_ptr()
std::string inja::DataNode::convert_dot_to_ptr (std::string_view ptr_name) inline static
Definition at line 486 of file inja.hpp.
{
            std::string result;
            do {
                std::string_view part;
                std::tie(part, ptr_name) = string_view::split(ptr_name, '.');
                result.push_back('/');
                result.append(part.begin(), part.end());
            } while (!ptr_name.empty());
            return result;
        }
References inja::string_view::split().
Referenced by DataNode(), and inja::Renderer::visit().
Member Data Documentation
name
const std::string inja::DataNode::name
Definition at line 483 of file inja.hpp.
Referenced by DataNode(), inja::Renderer::eval_expression_list(), inja::Renderer::get_argument_vector(), inja::Renderer::get_arguments(), inja::Renderer::visit(), and inja::Renderer::visit().
ptr
const json::json_pointer inja::DataNode::ptr
Definition at line 484 of file inja.hpp.
Referenced by DataNode(), and inja::Renderer::visit().
The documentation for this class was generated from the following file:
lib/inja.hpp