MQTTSuite: mqtt::mqttbroker::lib::Mqtt Class Reference
mqtt::mqttbroker::lib::Mqtt Class Reference
#include <Mqtt.h>
Classes
struct EarlierFirst
class DelayedQueue
struct ScheduledPublish
Public Member Functions
Mqtt (const std::string &connectionName, const std::shared_ptr< iot::mqtt::server::broker::Broker > &broker, const std::shared_ptr< mqtt::lib::MqttMapper > &mqttMapper)
void subscribe (const std::string &topic, uint8_t qoS)
void unsubscribe (const std::string &topic)
Private Member Functions
void onConnect (const iot::mqtt::packets::Connect &connect) final
void onPublish (const iot::mqtt::packets::Publish &publish) final
void onSubscribe (const iot::mqtt::packets::Subscribe &subscribe) final
void onUnsubscribe (const iot::mqtt::packets::Unsubscribe &unsubscribe) final
void onDisconnected () final
Private Attributes
std::shared_ptr< mqtt::lib::MqttMapper > mqttMapper
DelayedQueue delayedQueue
Detailed Description
Definition at line 75 of file Mqtt.h.
Constructor & Destructor Documentation
Mqtt()
mqtt::mqttbroker::lib::Mqtt::Mqtt (const std::string & connectionName, const std::shared_ptr< iot::mqtt::server::broker::Broker > & broker, const std::shared_ptr< mqtt::lib::MqttMapper > & mqttMapper) explicit
Definition at line 70 of file Mqtt.cpp.
        : iot::mqtt::server::Mqtt(connectionName, broker)
        , mqttMapper(mqttMapper)
        , delayedQueue(this) {
    }
References mqtt::mqttbroker::lib::Mqtt::DelayedQueue::DelayedQueue(), delayedQueue, and mqttMapper.
Referenced by mqtt::mqttbroker::SocketContextFactory::create().
Member Function Documentation
onConnect()
void mqtt::mqttbroker::lib::Mqtt::onConnect (const iot::mqtt::packets::Connect & connect) final private
Definition at line 154 of file Mqtt.cpp.
{
        MqttModel::instance().connectClient(this);
    }
References mqtt::mqttbroker::lib::MqttModel::connectClient(), and mqtt::mqttbroker::lib::MqttModel::instance().
onDisconnected()
void mqtt::mqttbroker::lib::Mqtt::onDisconnected () final private
Definition at line 189 of file Mqtt.cpp.
{
        MqttModel::instance().disconnectClient(clientId);
    }
References mqtt::mqttbroker::lib::MqttModel::disconnectClient(), and mqtt::mqttbroker::lib::MqttModel::instance().
onPublish()
void mqtt::mqttbroker::lib::Mqtt::onPublish (const iot::mqtt::packets::Publish & publish) final private
Definition at line 158 of file Mqtt.cpp.
{
        MqttModel::instance().publishMessage(publish.getTopic(), publish.getMessage(), publish.getQoS(), publish.getRetain());
        if (mqttMapper != nullptr) {
            mqtt::lib::MqttMapper::MappedPublishes mappedPublishes = mqttMapper->getMappings(publish);
            for (const mqtt::lib::MqttMapper::ScheduledPublish& delayedPublish : mappedPublishes.second) {
                delayedQueue.delayPublish(delayedPublish.delay, delayedPublish.publish);
            }
            for (const iot::mqtt::packets::Publish& mappedPublish : mappedPublishes.first) {
                broker->publish(
                    clientId, mappedPublish.getTopic(), mappedPublish.getMessage(), mappedPublish.getQoS(), mappedPublish.getRetain());
                onPublish(mappedPublish);
            }
        }
    }
References mqtt::lib::MqttMapper::ScheduledPublish::delay, delayedQueue, mqtt::mqttbroker::lib::Mqtt::DelayedQueue::delayPublish(), mqtt::lib::MqttMapper::getMappings(), mqtt::mqttbroker::lib::MqttModel::instance(), mqttMapper, onPublish(), mqtt::lib::MqttMapper::ScheduledPublish::publish, and mqtt::mqttbroker::lib::MqttModel::publishMessage().
Referenced by onPublish(), and mqtt::mqttbroker::lib::Mqtt::DelayedQueue::processDue().
onSubscribe()
void mqtt::mqttbroker::lib::Mqtt::onSubscribe (const iot::mqtt::packets::Subscribe & subscribe) final private
Definition at line 177 of file Mqtt.cpp.
{
        for (const iot::mqtt::Topic& topic : subscribe.getTopics()) {
            MqttModel::instance().subscribeClient(clientId, topic.getName(), topic.getQoS());
        }
    }
References mqtt::mqttbroker::lib::MqttModel::instance(), and mqtt::mqttbroker::lib::MqttModel::subscribeClient().
Referenced by subscribe().
onUnsubscribe()
void mqtt::mqttbroker::lib::Mqtt::onUnsubscribe (const iot::mqtt::packets::Unsubscribe & unsubscribe) final private
Definition at line 183 of file Mqtt.cpp.
{
        for (const std::string& topic : unsubscribe.getTopics()) {
            MqttModel::instance().unsubscribeClient(clientId, topic);
        }
    }
References mqtt::mqttbroker::lib::MqttModel::instance(), and mqtt::mqttbroker::lib::MqttModel::unsubscribeClient().
Referenced by unsubscribe().
subscribe()
void mqtt::mqttbroker::lib::Mqtt::subscribe (const std::string & topic, uint8_t qoS)
Definition at line 144 of file Mqtt.cpp.
{
        broker->subscribe(clientId, topic, qoS);
        onSubscribe(iot::mqtt::packets::Subscribe(0, {{topic, qoS}}));
    }
References onSubscribe().
unsubscribe()
void mqtt::mqttbroker::lib::Mqtt::unsubscribe (const std::string & topic)
Definition at line 149 of file Mqtt.cpp.
{
        broker->unsubscribe(clientId, topic);
        onUnsubscribe(iot::mqtt::packets::Unsubscribe(0, {{topic, 0}}));
    }
References onUnsubscribe().
Member Data Documentation
delayedQueue
DelayedQueue mqtt::mqttbroker::lib::Mqtt::delayedQueue private
Definition at line 119 of file Mqtt.h.
Referenced by Mqtt(), and onPublish().
mqttMapper
std::shared_ptr<mqtt::lib::MqttMapper> mqtt::mqttbroker::lib::Mqtt::mqttMapper private
Definition at line 118 of file Mqtt.h.
Referenced by Mqtt(), and onPublish().
The documentation for this class was generated from the following files:
mqttbroker/lib/Mqtt.h
mqttbroker/lib/Mqtt.cpp