MQTTSuite: inja::AstNode Class Reference
inja::AstNode Class Reference abstract
Base node class for the abstract syntax tree (AST).
#include <inja.hpp>
Public Member Functions
virtual void accept (NodeVisitor &v) const =0
AstNode (size_t pos)
AstNode (const AstNode &)=default
AstNode & operator= (const AstNode &)=default
virtual ~AstNode ()
Public Attributes
size_t pos
Detailed Description
Base node class for the abstract syntax tree (AST).
Definition at line 414 of file inja.hpp.
Constructor & Destructor Documentation
AstNode() [1/2]
inja::AstNode::AstNode (size_t pos) inline
Definition at line 420 of file inja.hpp.
            : pos(pos) {
        }
References pos.
Referenced by inja::BlockNode::BlockNode(), inja::ExpressionListNode::ExpressionListNode(), inja::ExpressionListNode::ExpressionListNode(), inja::ExpressionNode::ExpressionNode(), inja::StatementNode::StatementNode(), and inja::TextNode::TextNode().
AstNode() [2/2]
inja::AstNode::AstNode (const AstNode &) default
~AstNode()
virtual inja::AstNode::~AstNode () inline virtual
Definition at line 425 of file inja.hpp.
{
        }
Member Function Documentation
accept()
virtual void inja::AstNode::accept (NodeVisitor & v) const pure virtual
Implemented in inja::BlockNode, inja::TextNode, inja::ExpressionNode, inja::LiteralNode, inja::DataNode, inja::FunctionNode, inja::ExpressionListNode, inja::ForArrayStatementNode, inja::ForObjectStatementNode, inja::IfStatementNode, inja::IncludeStatementNode, inja::ExtendsStatementNode, inja::BlockStatementNode, inja::SetStatementNode, inja::StatementNode, and inja::ForStatementNode.
Referenced by inja::StatisticsVisitor::visit(), and inja::Renderer::visit().
operator=()
AstNode & inja::AstNode::operator= (const AstNode &) default
Member Data Documentation
pos
size_t inja::AstNode::pos
Definition at line 418 of file inja.hpp.
Referenced by AstNode(), inja::Renderer::throw_renderer_error(), and inja::Renderer::visit().
The documentation for this class was generated from the following file:
lib/inja.hpp