MQTTSuite: nlohmann::json_schema::basic_error_handler Class Reference
nlohmann::json_schema::basic_error_handler Class Reference
#include <json-schema.hpp>
Public Member Functions
void error (const json::json_pointer &, const json &, const std::string &) override
virtual void reset ()
operator bool () const
Public Member Functions inherited from nlohmann::json_schema::error_handler
virtual ~error_handler ()
Private Attributes
bool error_ {false}
Detailed Description
Definition at line 145 of file json-schema.hpp.
Member Function Documentation
error()
void nlohmann::json_schema::basic_error_handler::error (const json::json_pointer & , const json & , const std::string &) inline override virtual
Implements nlohmann::json_schema::error_handler.
Definition at line 150 of file json-schema.hpp.
    {
        error_ = true;
    }
References error_.
Referenced by store_ptr_err_handler::error(), custom_error_handler::error(), store_ptr_err_handler::error(), store_err_handler::error(), and main().
operator bool()
nlohmann::json_schema::basic_error_handler::operator bool () const inline
Definition at line 156 of file json-schema.hpp.
{ return error_; }
References error_.
reset()
virtual void nlohmann::json_schema::basic_error_handler::reset () inline virtual
Reimplemented in store_ptr_err_handler, store_ptr_err_handler, store_ptr_err_handler, store_ptr_err_handler, store_err_handler, store_err_handler, store_ptr_err_handler, and store_ptr_err_handler.
Definition at line 155 of file json-schema.hpp.
{ error_ = false; }
References error_.
Referenced by store_ptr_err_handler::reset(), and store_err_handler::reset().
Member Data Documentation
error_
bool nlohmann::json_schema::basic_error_handler::error_ {false} private
Definition at line 147 of file json-schema.hpp.
{false};
Referenced by error(), operator bool(), and reset().
The documentation for this class was generated from the following file:
lib/json-schema-validator/src/nlohmann/json-schema.hpp