MQTTSuite: mqtt::mqttbroker::lib::MqttModel Class Reference
mqtt::mqttbroker::lib::MqttModel Class Reference
#include <MqttModel.h>
Classes
class MqttModelEntry
class EventReceiver
Public Member Functions
void addEventReceiver (const std::shared_ptr< express::Response > &response, const std::string &lastEventId, const std::shared_ptr< iot::mqtt::server::broker::Broker > &broker)
void connectClient (Mqtt *mqtt)
void disconnectClient (const std::string &clientId)
void subscribeClient (const std::string &clientId, const std::string &topic, const uint8_t qos)
void unsubscribeClient (const std::string &clientId, const std::string &topic)
void publishMessage (const std::string &topic, const std::string &message, uint8_t qoS, bool retain)
const std::map< std::string, MqttModelEntry > & getClients () const
Mqtt * getMqtt (const std::string &clientId) const
std::string onlineSince () const
std::string onlineDuration () const
Static Public Member Functions
static MqttModel & instance ()
Private Member Functions
MqttModel ()
void sendEvent (const std::string &data, const std::string &event="", const std::string &id="") const
void sendJsonEvent (const nlohmann::json &json, const std::string &event="", const std::string &id="") const
Static Private Member Functions
static void sendEvent (const std::shared_ptr< express::Response > &response, const std::string &data, const std::string &event, const std::string &id)
static void sendJsonEvent (const std::shared_ptr< express::Response > &response, const nlohmann::json &json, const std::string &event="", const std::string &id="")
static std::string timePointToString (const std::chrono::time_point< std::chrono::system_clock > &timePoint)
static std::string durationToString (const std::chrono::time_point< std::chrono::system_clock > &bevore, const std::chrono::time_point< std::chrono::system_clock > &later=std::chrono::system_clock::now())
Private Attributes
std::map< std::string, MqttModelEntry > modelMap
std::list< EventReceiver > eventReceiverList
std::chrono::time_point< std::chrono::system_clock > onlineSinceTimePoint
uint64_t id = 0
Friends
void to_json (nlohmann::json &j, const MqttModel::MqttModelEntry &mqttModelEntry)
Detailed Description
Definition at line 74 of file MqttModel.h.
Constructor & Destructor Documentation
MqttModel()
mqtt::mqttbroker::lib::MqttModel::MqttModel () private
Definition at line 200 of file MqttModel.cpp.
        : onlineSinceTimePoint(std::chrono::system_clock::now()) {
    }
References onlineSinceTimePoint.
Member Function Documentation
addEventReceiver()
void mqtt::mqttbroker::lib::MqttModel::addEventReceiver (const std::shared_ptr< express::Response > & response, const std::string & lastEventId, const std::shared_ptr< iot::mqtt::server::broker::Broker > & broker)
Definition at line 210 of file MqttModel.cpp.
{
        auto& eventReceiver = eventReceiverList.emplace_back(response);
        response->getSocketContext()->onDisconnected([this, &eventReceiver]() {
            eventReceiverList.remove(eventReceiver);
        });
        /*
            {
                "title": "MQTTBroker",
                "creator": {
                    "name": "Volker Christian",
                    "url": "https://github.com/VolkerChristian/"
                },
                "broker": {
                    "name": "MQTTBroker",
                    "url": "https://github.com/SNodeC/mqttsuite/tree/master/mqttbroker"
                },
                "suite": {
                    "name": "MQTTSuite",
                    "url": "https://github.com/SNodeC/mqttsuite"
                },
                "snodec": {
                    "name": "SNode.C",
                    "url": "https://github.com/SNodeC/snode.c"
                },
                "since": "2025-12-25 10:30:00 UTC",
                "duration": "2 days, 03:45:12"
            }
        */
        sendJsonEvent(response,
                      {
                          {"title", "MQTTBroker"},
                          {"creator", {{"name", "Volker Christian"}, {"url", "https://github.com/VolkerChristian"}}},
                          {"broker", {{"name", "MQTTBroker"}, {"url", "https://github.com/SNodeC/mqttsuite/tree/master/mqttbroker"}}},
                          {"suite", {{"name", "MQTTSuite"}, {"url", "https://github.com/SNodeC/mqttsuite"}}},
                          {"snodec", {{"name", "SNode.C"}, {"url", "https://github.com/SNodeC/snode.c"}}},
                          {"since", onlineSince()},
                          {"duration", onlineDuration()},
                      },
                      "ui-initialize",
                      std::to_string(id++));
        for (const auto& modelMapEntry : modelMap) {
            sendJsonEvent(response, modelMapEntry.second, "client-connected", std::to_string(id++));
        }
        for (const auto& [topic, clients] : broker->getSubscriptionTree()) {
            for (const auto& client : clients) {
                sendJsonEvent(response, subscribe{topic, client.first, client.second}, "client-subscribed", std::to_string(id++));
            }
        }
        for (const auto& [topic, retained] : broker->getRetainTree()) {
            sendJsonEvent(response, retaine{topic, retained.first, retained.second}, "retained-message-set", std::to_string(id++));
        }
    }
References eventReceiverList, id, modelMap, onlineDuration(), and onlineSince().
Referenced by getRouter().
connectClient()
void mqtt::mqttbroker::lib::MqttModel::connectClient (Mqtt * mqtt)
Definition at line 270 of file MqttModel.cpp.
{
        MqttModelEntry& mqttModelEntry = modelMap.emplace(mqtt->getClientId(), mqtt).first->second;
        sendJsonEvent(mqttModelEntry, "client-connected", std::to_string(id++));
    }
References id, and modelMap.
Referenced by mqtt::mqttbroker::lib::Mqtt::onConnect().
disconnectClient()
void mqtt::mqttbroker::lib::MqttModel::disconnectClient (const std::string & clientId)
Definition at line 276 of file MqttModel.cpp.
{
        if (modelMap.contains(clientId)) {
            sendJsonEvent(modelMap[clientId], "client-disconnected", std::to_string(id++));
            modelMap.erase(clientId);
        }
    }
References id, and modelMap.
Referenced by mqtt::mqttbroker::lib::Mqtt::onDisconnected().
durationToString()
std::string mqtt::mqttbroker::lib::MqttModel::durationToString (const std::chrono::time_point< std::chrono::system_clock > & bevore, const std::chrono::time_point< std::chrono::system_clock > & later = std::chrono::system_clock::now()) static private
Definition at line 377 of file MqttModel.cpp.
{
        using seconds_duration_type = std::chrono::duration<std::chrono::seconds::rep>::rep;
        seconds_duration_type totalSeconds = std::chrono::duration_cast<std::chrono::seconds>(later - bevore).count();
        // Compute days, hours, minutes, and seconds
        seconds_duration_type days = totalSeconds / 86400; // 86400 seconds in a day
        seconds_duration_type remainder = totalSeconds % 86400;
        seconds_duration_type hours = remainder / 3600;
        remainder = remainder % 3600;
        seconds_duration_type minutes = remainder / 60;
        seconds_duration_type seconds = remainder % 60;
        // Format the components into a string using stringstream
        std::ostringstream oss;
        if (days > 0) {
            oss << days << " day" << (days == 1 ? "" : "s") << ", ";
        }
        oss << std::setw(2) << std::setfill('0') << hours << ":" << std::setw(2) << std::setfill('0') << minutes << ":" << std::setw(2)
            << std::setfill('0') << seconds;
        return oss.str();
    }
getClients()
const std::map< std::string, MqttModel::MqttModelEntry > & mqtt::mqttbroker::lib::MqttModel::getClients () const
Definition at line 302 of file MqttModel.cpp.
{
        return modelMap;
    }
References modelMap.
getMqtt()
Mqtt * mqtt::mqttbroker::lib::MqttModel::getMqtt (const std::string & clientId) const
Definition at line 306 of file MqttModel.cpp.
{
        Mqtt* mqtt = nullptr;
        auto modelIt = modelMap.find(clientId);
        if (modelIt != modelMap.end()) {
            mqtt = modelIt->second.getMqtt();
        }
        return mqtt;
    }
References mqtt::mqttbroker::lib::MqttModel::MqttModelEntry::getMqtt(), and modelMap.
instance()
MqttModel & mqtt::mqttbroker::lib::MqttModel::instance () static
Definition at line 204 of file MqttModel.cpp.
{
        static MqttModel mqttModel;
        return mqttModel;
    }
Referenced by getRouter(), mqtt::mqttbroker::lib::Mqtt::onConnect(), mqtt::mqttbroker::lib::Mqtt::onDisconnected(), mqtt::mqttbroker::lib::Mqtt::onPublish(), mqtt::mqttbroker::lib::Mqtt::onSubscribe(), and mqtt::mqttbroker::lib::Mqtt::onUnsubscribe().
onlineDuration()
std::string mqtt::mqttbroker::lib::MqttModel::onlineDuration () const
Definition at line 321 of file MqttModel.cpp.
{
        return durationToString(onlineSinceTimePoint);
    }
References onlineSinceTimePoint.
Referenced by addEventReceiver().
onlineSince()
std::string mqtt::mqttbroker::lib::MqttModel::onlineSince () const
Definition at line 317 of file MqttModel.cpp.
{
        return timePointToString(onlineSinceTimePoint);
    }
References onlineSinceTimePoint.
Referenced by addEventReceiver().
publishMessage()
void mqtt::mqttbroker::lib::MqttModel::publishMessage (const std::string & topic, const std::string & message, uint8_t qoS, bool retain)
Definition at line 292 of file MqttModel.cpp.
{
        if (retain) {
            if (!message.empty()) {
                sendJsonEvent(retaine{topic, message, qoS}, "retained-message-set", std::to_string(id++));
            } else {
                sendJsonEvent(release{topic}, "retained-message-deleted", std::to_string(id++));
            }
        }
    }
References id.
Referenced by mqtt::mqttbroker::lib::Mqtt::onPublish().
sendEvent() [1/2]
void mqtt::mqttbroker::lib::MqttModel::sendEvent (const std::shared_ptr< express::Response > & response, const std::string & data, const std::string & event, const std::string & id) static private
Definition at line 325 of file MqttModel.cpp.
{
        if (response->isConnected()) {
            if (!event.empty()) {
                response->sendFragment("event:" + event);
            }
            if (!id.empty()) {
                response->sendFragment("id:" + id);
            }
            response->sendFragment("data:" + data);
            response->sendFragment();
        }
    }
Referenced by sendEvent(), and sendJsonEvent().
sendEvent() [2/2]
void mqtt::mqttbroker::lib::MqttModel::sendEvent (const std::string & data, const std::string & event = "", const std::string & id = "") const private
Definition at line 348 of file MqttModel.cpp.
{
        for (auto& eventReceiver : eventReceiverList) {
            if (const auto& response = eventReceiver.response.lock()) {
                sendEvent(response, data, event, id);
            }
        }
    }
References eventReceiverList, mqtt::mqttbroker::lib::MqttModel::EventReceiver::response, and sendEvent().
Referenced by sendJsonEvent().
sendJsonEvent() [1/2]
void mqtt::mqttbroker::lib::MqttModel::sendJsonEvent (const nlohmann::json & json, const std::string & event = "", const std::string & id = "") const private
Definition at line 356 of file MqttModel.cpp.
{
        VLOG(0) << "Server sent event: " << event << "\n" << json.dump(4);
        sendEvent(json.dump(), event, id);
    }
References sendEvent().
sendJsonEvent() [2/2]
void mqtt::mqttbroker::lib::MqttModel::sendJsonEvent (const std::shared_ptr< express::Response > & response, const nlohmann::json & json, const std::string & event = "", const std::string & id = "") static private
Definition at line 341 of file MqttModel.cpp.
{
        sendEvent(response, json.dump(), event, id);
    }
References sendEvent().
subscribeClient()
void mqtt::mqttbroker::lib::MqttModel::subscribeClient (const std::string & clientId, const std::string & topic, const uint8_t qos)
Definition at line 284 of file MqttModel.cpp.
{
        sendJsonEvent(subscribe{topic, clientId, qos}, "client-subscribed", std::to_string(id++));
    }
References id.
Referenced by mqtt::mqttbroker::lib::Mqtt::onSubscribe().
timePointToString()
std::string mqtt::mqttbroker::lib::MqttModel::timePointToString (const std::chrono::time_point< std::chrono::system_clock > & timePoint) static private
Definition at line 362 of file MqttModel.cpp.
{
        std::time_t time = std::chrono::system_clock::to_time_t(timePoint);
        std::tm* tm_ptr = std::gmtime(&time);
        char buffer[100];
        std::string onlineSince = "Formatting error";
        // Format: "2025-02-02 14:30:00"
        if (std::strftime(buffer, sizeof(buffer), "%Y-%m-%d %H:%M:%S", tm_ptr)) {
            onlineSince = std::string(buffer) + " UTC";
        }
        return onlineSince;
    }
unsubscribeClient()
void mqtt::mqttbroker::lib::MqttModel::unsubscribeClient (const std::string & clientId, const std::string & topic)
Definition at line 288 of file MqttModel.cpp.
{
        sendJsonEvent(unsubscribe{clientId, topic}, "client-unsubscribed", std::to_string(id++));
    }
References id.
Referenced by mqtt::mqttbroker::lib::Mqtt::onUnsubscribe().
Friends And Related Symbol Documentation
to_json
void to_json (nlohmann::json & j, const MqttModel::MqttModelEntry & mqttModelEntry) friend
Definition at line 99 of file MqttModel.cpp.
{
        const Mqtt* mqtt = mqttModelEntry.getMqtt();
        const core::socket::stream::SocketConnection* socketConnection = mqtt->getMqttContext()->getSocketConnection();
        j = {{"clientId", mqtt->getClientId()},
             {"since", mqttModelEntry.onlineSince()},
             {"duration", mqttModelEntry.onlineDuration()},
             {"connectionName", mqtt->getConnectionName()},
             {"cleanSession", mqtt->getCleanSession()},
             {"connectFlags", mqtt->getConnectFlags()},
             {"username", mqtt->getUsername()},
             {"usernameFlag", mqtt->getUsernameFlag()},
             {"password", mqtt->getPassword()},
             {"passwordFlag", mqtt->getPasswordFlag()},
             {"keepAlive", mqtt->getKeepAlive()},
             {"protocol", mqtt->getProtocol()},
             {"protocolLevel", mqtt->getLevel()},
             {"loopPrevention", !mqtt->getReflect()},
             {"willMessage", mqtt->getWillMessage()},
             {"willTopic", mqtt->getWillTopic()},
             {"willQoS", mqtt->getWillQoS()},
             {"willFlag", mqtt->getWillFlag()},
             {"willRetain", mqtt->getWillRetain()},
             {"localAddress", socketConnection->getLocalAddress().toString()},
             {"remoteAddress", socketConnection->getRemoteAddress().toString()}};
    }
References mqtt::mqttbroker::lib::MqttModel::MqttModelEntry::getMqtt(), mqtt::mqttbroker::lib::MqttModel::MqttModelEntry::onlineDuration(), and mqtt::mqttbroker::lib::MqttModel::MqttModelEntry::onlineSince().
Member Data Documentation
eventReceiverList
std::list<EventReceiver> mqtt::mqttbroker::lib::MqttModel::eventReceiverList private
Definition at line 148 of file MqttModel.h.
Referenced by addEventReceiver(), and sendEvent().
id
uint64_t mqtt::mqttbroker::lib::MqttModel::id = 0 private
Definition at line 150 of file MqttModel.h.
Referenced by addEventReceiver(), connectClient(), disconnectClient(), publishMessage(), subscribeClient(), and unsubscribeClient().
modelMap
std::map<std::string, MqttModelEntry> mqtt::mqttbroker::lib::MqttModel::modelMap private
Definition at line 147 of file MqttModel.h.
Referenced by addEventReceiver(), connectClient(), disconnectClient(), getClients(), and getMqtt().
onlineSinceTimePoint
std::chrono::time_point<std::chrono::system_clock> mqtt::mqttbroker::lib::MqttModel::onlineSinceTimePoint private
Definition at line 149 of file MqttModel.h.
Referenced by MqttModel(), onlineDuration(), and onlineSince().
The documentation for this class was generated from the following files:
mqttbroker/lib/MqttModel.h
mqttbroker/lib/MqttModel.cpp