MQTTSuite: anonymous_namespace{json-validator.cpp}::schema Class Reference
anonymous_namespace{json-validator.cpp}::schema Class Reference abstract
Public Member Functions
virtual ~schema ()=default
schema (root_schema *root)
virtual void validate (const json::json_pointer &ptr, const json &instance, json_patch &patch, error_handler &e) const =0
virtual const json & default_value (const json::json_pointer &, const json &, error_handler &) const
void set_default_value (const json &v)
virtual ~schema ()=default
schema (root_schema *root)
virtual void validate (const json::json_pointer &ptr, const json &instance, json_patch &patch, error_handler &e) const =0
virtual const json & default_value (const json::json_pointer &, const json &, error_handler &) const
void set_default_value (const json &v)
Static Public Member Functions
static std::shared_ptr< schema > make (json &schema, root_schema *root, const std::vector< std::string > &key, std::vector< nlohmann::json_uri > uris)
static std::shared_ptr< schema > make (json &schema, root_schema *root, const std::vector< std::string > &key, std::vector< nlohmann::json_uri > uris)
Protected Member Functions
virtual std::shared_ptr< schema > make_for_default_ (std::shared_ptr<::schema > &, root_schema *, std::vector< nlohmann::json_uri > &, nlohmann::json &) const
virtual std::shared_ptr< schema > make_for_default_ (std::shared_ptr<::schema > &, root_schema *, std::vector< nlohmann::json_uri > &, nlohmann::json &) const
Protected Attributes
root_schema * root_
json default_value_ = nullptr
Detailed Description
Definition at line 38 of file json-validator.cpp.
Constructor & Destructor Documentation
~schema() [1/2]
virtual anonymous_namespace{json-validator.cpp}::schema::~schema () virtual default
schema() [1/2]
anonymous_namespace{json-validator.cpp}::schema::schema (root_schema * root) inline
Definition at line 57 of file json-validator.cpp.
        : root_(root) {}
References root_.
Referenced by anonymous_namespace{json-validator.cpp}::array::array(), anonymous_namespace{json-validator.cpp}::boolean::boolean(), anonymous_namespace{json-validator.cpp}::boolean_type::boolean_type(), anonymous_namespace{json-validator.cpp}::logical_not::logical_not(), anonymous_namespace{json-validator.cpp}::null::null(), anonymous_namespace{json-validator.cpp}::object::object(), anonymous_namespace{json-validator.cpp}::required::required(), anonymous_namespace{json-validator.cpp}::schema_ref::schema_ref(), anonymous_namespace{json-validator.cpp}::string::string(), and anonymous_namespace{json-validator.cpp}::type_schema::type_schema().
~schema() [2/2]
virtual anonymous_namespace{json-validator.cpp}::schema::~schema () virtual default
schema() [2/2]
anonymous_namespace{json-validator.cpp}::schema::schema (root_schema * root) inline
Definition at line 57 of file json-validator.cpp.
        : root_(root) {}
Member Function Documentation
default_value() [1/2]
virtual const json & anonymous_namespace{json-validator.cpp}::schema::default_value (const json::json_pointer & , const json & , error_handler &) const inline virtual
Reimplemented in anonymous_namespace{json-validator.cpp}::logical_not, anonymous_namespace{json-validator.cpp}::logical_not, anonymous_namespace{json-validator.cpp}::schema_ref, and anonymous_namespace{json-validator.cpp}::schema_ref.
Definition at line 62 of file json-validator.cpp.
    {
        return default_value_;
    }
References default_value_.
Referenced by anonymous_namespace{json-validator.cpp}::logical_not::default_value(), anonymous_namespace{json-validator.cpp}::schema_ref::default_value(), and anonymous_namespace{json-validator.cpp}::object::validate().
default_value() [2/2]
virtual const json & anonymous_namespace{json-validator.cpp}::schema::default_value (const json::json_pointer & , const json & , error_handler &) const inline virtual
Reimplemented in anonymous_namespace{json-validator.cpp}::logical_not, anonymous_namespace{json-validator.cpp}::logical_not, anonymous_namespace{json-validator.cpp}::schema_ref, and anonymous_namespace{json-validator.cpp}::schema_ref.
Definition at line 62 of file json-validator.cpp.
    {
        return default_value_;
    }
make() [1/2]
std::shared_ptr< schema > anonymous_namespace{json-validator.cpp}::schema::make (json & schema, root_schema * root, const std::vector< std::string > & key, std::vector< nlohmann::json_uri > uris) static
Definition at line 1355 of file json-validator.cpp.
{
    // remove URIs which contain plain name identifiers, as sub-schemas cannot be referenced
    for (auto uri = uris.begin(); uri != uris.end();)
        if (uri->identifier() != "")
            uri = uris.erase(uri);
        else
            uri++;
    // append to all URIs the keys for this sub-schema
    for (auto &key : keys)
        for (auto &uri : uris)
            uri = uri.append(key);
    std::shared_ptr<::schema> sch;
    // boolean schema
    if (schema.type() == json::value_t::boolean)
        sch = std::make_shared<boolean>(schema, root);
    else if (schema.type() == json::value_t::object) {
        auto attr = schema.find("$id"); // if $id is present, this schema can be referenced by this ID
                                        // as an additional URI
        if (attr != schema.end()) {
            if (std::find(uris.begin(),
                          uris.end(),
                          attr.value().get<std::string>()) == uris.end())
                uris.push_back(uris.back().derive(attr.value().get<std::string>())); // so add it to the list if it is not there already
            schema.erase(attr);
        }
        auto findDefinitions = [&](const std::string &defs) -> bool {
            attr = schema.find(defs);
            if (attr != schema.end()) {
                for (auto &def : attr.value().items())
                    schema::make(def.value(), root, {defs, def.key()}, uris);
                schema.erase(attr);
                return true;
            }
            return false;
        };
        if (!findDefinitions("$defs")) {
            findDefinitions("definitions");
        }
        attr = schema.find("$ref");
        if (attr != schema.end()) { // this schema is a reference
            // the last one on the uri-stack is the last id seen before coming here,
            // so this is the origial URI for this reference, the $ref-value has thus be resolved from it
            auto id = uris.back().derive(attr.value().get<std::string>());
            sch = root->get_or_create_ref(id);
            schema.erase(attr);
            // special case where we break draft-7 and allow overriding of properties when a $ref is used
            attr = schema.find("default");
            if (attr != schema.end()) {
                // copy the referenced schema depending on the underlying type and modify the default value
                if (auto new_sch = sch->make_for_default_(sch, root, uris, attr.value())) {
                    sch = new_sch;
                }
                schema.erase(attr);
            }
        } else {
            sch = std::make_shared<type_schema>(schema, root, uris);
        }
        schema.erase("$schema");
        schema.erase("title");
        schema.erase("description");
    } else {
        throw std::invalid_argument("invalid JSON-type for a schema for " + uris[0].to_string() + ", expected: boolean or object");
    }
    for (auto &uri : uris) { // for all URIs this schema is referenced by
        root->insert(uri, sch);
        if (schema.type() == json::value_t::object)
            for (auto &u : schema.items())
                root->insert_unknown_keyword(uri, u.key(), u.value()); // insert unknown keywords for later reference
    }
    return sch;
}
References nlohmann::json_uri::append(), nlohmann::json_uri::derive(), nlohmann::json_schema::root_schema::get_or_create_ref(), nlohmann::json_schema::root_schema::insert(), nlohmann::json_schema::root_schema::insert_unknown_keyword(), make(), make_for_default_(), and nlohmann::json_uri::to_string().
Referenced by anonymous_namespace{json-validator.cpp}::array::array(), nlohmann::json_schema::root_schema::get_or_create_ref(), nlohmann::json_schema::root_schema::insert_unknown_keyword(), anonymous_namespace{json-validator.cpp}::logical_combination< combine_logic >::logical_combination(), anonymous_namespace{json-validator.cpp}::logical_not::logical_not(), make(), anonymous_namespace{json-validator.cpp}::object::object(), nlohmann::json_schema::root_schema::set_root_schema(), and anonymous_namespace{json-validator.cpp}::type_schema::type_schema().
make() [2/2]
static std::shared_ptr< schema > anonymous_namespace{json-validator.cpp}::schema::make (json & schema, root_schema * root, const std::vector< std::string > & key, std::vector< nlohmann::json_uri > uris) static
make_for_default_() [1/2]
virtual std::shared_ptr< schema > anonymous_namespace{json-validator.cpp}::schema::make_for_default_ (std::shared_ptr<::schema > & , root_schema * , std::vector< nlohmann::json_uri > & , nlohmann::json &) const inline protected virtual
Reimplemented in anonymous_namespace{json-validator.cpp}::type_schema, anonymous_namespace{json-validator.cpp}::type_schema, anonymous_namespace{json-validator.cpp}::schema_ref, and anonymous_namespace{json-validator.cpp}::schema_ref.
Definition at line 45 of file json-validator.cpp.
    {
        return nullptr;
    };
Referenced by make().
make_for_default_() [2/2]
virtual std::shared_ptr< schema > anonymous_namespace{json-validator.cpp}::schema::make_for_default_ (std::shared_ptr<::schema > & , root_schema * , std::vector< nlohmann::json_uri > & , nlohmann::json &) const inline protected virtual
Reimplemented in anonymous_namespace{json-validator.cpp}::type_schema, anonymous_namespace{json-validator.cpp}::type_schema, anonymous_namespace{json-validator.cpp}::schema_ref, and anonymous_namespace{json-validator.cpp}::schema_ref.
Definition at line 45 of file json-validator.cpp.
    {
        return nullptr;
    };
set_default_value() [1/2]
void anonymous_namespace{json-validator.cpp}::schema::set_default_value (const json & v) inline
Definition at line 67 of file json-validator.cpp.
{ default_value_ = v; }
References default_value_.
Referenced by anonymous_namespace{json-validator.cpp}::type_schema::make_for_default_(), anonymous_namespace{json-validator.cpp}::schema_ref::make_for_default_(), anonymous_namespace{json-validator.cpp}::object::object(), and anonymous_namespace{json-validator.cpp}::type_schema::type_schema().
set_default_value() [2/2]
void anonymous_namespace{json-validator.cpp}::schema::set_default_value (const json & v) inline
Definition at line 67 of file json-validator.cpp.
{ default_value_ = v; }
validate() [1/2]
virtual void anonymous_namespace{json-validator.cpp}::schema::validate (const json::json_pointer & ptr, const json & instance, json_patch & patch, error_handler & e) const pure virtual
Implemented in anonymous_namespace{json-validator.cpp}::boolean_type, anonymous_namespace{json-validator.cpp}::boolean_type, anonymous_namespace{json-validator.cpp}::string, anonymous_namespace{json-validator.cpp}::string, anonymous_namespace{json-validator.cpp}::numeric< T >, anonymous_namespace{json-validator.cpp}::numeric< T >, anonymous_namespace{json-validator.cpp}::null, anonymous_namespace{json-validator.cpp}::null, anonymous_namespace{json-validator.cpp}::boolean, anonymous_namespace{json-validator.cpp}::boolean, anonymous_namespace{json-validator.cpp}::required, anonymous_namespace{json-validator.cpp}::required, anonymous_namespace{json-validator.cpp}::schema_ref, anonymous_namespace{json-validator.cpp}::schema_ref, anonymous_namespace{json-validator.cpp}::logical_not, anonymous_namespace{json-validator.cpp}::logical_not, anonymous_namespace{json-validator.cpp}::logical_combination< combine_logic >, anonymous_namespace{json-validator.cpp}::logical_combination< combine_logic >, anonymous_namespace{json-validator.cpp}::object, anonymous_namespace{json-validator.cpp}::object, anonymous_namespace{json-validator.cpp}::array, anonymous_namespace{json-validator.cpp}::array, anonymous_namespace{json-validator.cpp}::type_schema, and anonymous_namespace{json-validator.cpp}::type_schema.
Referenced by anonymous_namespace{json-validator.cpp}::schema_ref::validate(), anonymous_namespace{json-validator.cpp}::logical_not::validate(), anonymous_namespace{json-validator.cpp}::logical_combination< combine_logic >::validate(), anonymous_namespace{json-validator.cpp}::object::validate(), anonymous_namespace{json-validator.cpp}::array::validate(), anonymous_namespace{json-validator.cpp}::type_schema::validate(), and nlohmann::json_schema::root_schema::validate().
validate() [2/2]
virtual void anonymous_namespace{json-validator.cpp}::schema::validate (const json::json_pointer & ptr, const json & instance, json_patch & patch, error_handler & e) const pure virtual
Implemented in anonymous_namespace{json-validator.cpp}::boolean_type, anonymous_namespace{json-validator.cpp}::boolean_type, anonymous_namespace{json-validator.cpp}::string, anonymous_namespace{json-validator.cpp}::string, anonymous_namespace{json-validator.cpp}::numeric< T >, anonymous_namespace{json-validator.cpp}::numeric< T >, anonymous_namespace{json-validator.cpp}::null, anonymous_namespace{json-validator.cpp}::null, anonymous_namespace{json-validator.cpp}::boolean, anonymous_namespace{json-validator.cpp}::boolean, anonymous_namespace{json-validator.cpp}::required, anonymous_namespace{json-validator.cpp}::required, anonymous_namespace{json-validator.cpp}::schema_ref, anonymous_namespace{json-validator.cpp}::schema_ref, anonymous_namespace{json-validator.cpp}::logical_not, anonymous_namespace{json-validator.cpp}::logical_not, anonymous_namespace{json-validator.cpp}::logical_combination< combine_logic >, anonymous_namespace{json-validator.cpp}::logical_combination< combine_logic >, anonymous_namespace{json-validator.cpp}::object, anonymous_namespace{json-validator.cpp}::object, anonymous_namespace{json-validator.cpp}::array, anonymous_namespace{json-validator.cpp}::array, anonymous_namespace{json-validator.cpp}::type_schema, and anonymous_namespace{json-validator.cpp}::type_schema.
Member Data Documentation
default_value_
json anonymous_namespace{json-validator.cpp}::schema::default_value_ = nullptr protected
Definition at line 42 of file json-validator.cpp.
Referenced by default_value(), anonymous_namespace{json-validator.cpp}::schema_ref::default_value(), set_default_value(), and anonymous_namespace{json-validator.cpp}::type_schema::validate().
root_
root_schema * anonymous_namespace{json-validator.cpp}::schema::root_ protected
Definition at line 41 of file json-validator.cpp.
Referenced by schema(), anonymous_namespace{json-validator.cpp}::string::string(), and anonymous_namespace{json-validator.cpp}::string::validate().
The documentation for this class was generated from the following file:
lib/json-schema-validator/src/json-validator.cpp