MQTTSuite: mqtt::mqttintegrator::lib::Mqtt::DelayedQueue Class Reference
mqtt::mqttintegrator::lib::Mqtt::DelayedQueue Class Reference
Classes
struct EarlierFirst
Public Member Functions
DelayedQueue (Mqtt *mqtt)
~DelayedQueue ()
void delayPublish (const utils::Timeval &delay, const iot::mqtt::packets::Publish &publish)
bool empty () const
ScheduledPublish const & top () const
void pop ()
Private Member Functions
void processDue ()
void armDelayTimer ()
Private Attributes
Mqtt * mqtt
std::size_t nextSeq = 0
std::priority_queue< ScheduledPublish, std::vector< ScheduledPublish >, EarlierFirst > minHeap
core::timer::Timer delayTimer
Detailed Description
Definition at line 106 of file Mqtt.h.
Constructor & Destructor Documentation
DelayedQueue()
mqtt::mqttintegrator::lib::Mqtt::DelayedQueue::DelayedQueue (Mqtt * mqtt) explicit
Definition at line 188 of file Mqtt.cpp.
        : mqtt(mqtt) {
    }
References mqtt.
Referenced by mqtt::mqttintegrator::lib::Mqtt::Mqtt().
~DelayedQueue()
mqtt::mqttintegrator::lib::Mqtt::DelayedQueue::~DelayedQueue ()
Definition at line 192 of file Mqtt.cpp.
{
        delayTimer.cancel();
    }
References delayTimer.
Member Function Documentation
armDelayTimer()
void mqtt::mqttintegrator::lib::Mqtt::DelayedQueue::armDelayTimer () private
Definition at line 209 of file Mqtt.cpp.
{
        delayTimer.cancel();
        auto delay = top().when - utils::Timeval::currentTime();
        if (delay < utils::Timeval{}) {
            delay = utils::Timeval{};
        }
        delayTimer = core::timer::Timer::singleshotTimer(
            [this]() {
                processDue();
                if (!empty()) {
                    armDelayTimer();
                }
            },
            delay);
    }
References armDelayTimer(), delayTimer, empty(), processDue(), top(), and mqtt::mqttintegrator::lib::Mqtt::ScheduledPublish::when.
Referenced by armDelayTimer(), and delayPublish().
delayPublish()
void mqtt::mqttintegrator::lib::Mqtt::DelayedQueue::delayPublish (const utils::Timeval & delay, const iot::mqtt::packets::Publish & publish)
Definition at line 228 of file Mqtt.cpp.
{
        minHeap.emplace(utils::Timeval::currentTime() + delay, nextSeq++, publish, delay);
        armDelayTimer();
    }
References armDelayTimer(), minHeap, and nextSeq.
Referenced by mqtt::mqttintegrator::lib::Mqtt::onPublish().
empty()
bool mqtt::mqttintegrator::lib::Mqtt::DelayedQueue::empty () const
Definition at line 233 of file Mqtt.cpp.
{
        return minHeap.empty();
    }
References minHeap.
Referenced by armDelayTimer(), and processDue().
pop()
void mqtt::mqttintegrator::lib::Mqtt::DelayedQueue::pop ()
Definition at line 241 of file Mqtt.cpp.
{
        minHeap.pop();
    }
References minHeap.
Referenced by processDue().
processDue()
void mqtt::mqttintegrator::lib::Mqtt::DelayedQueue::processDue () private
Definition at line 196 of file Mqtt.cpp.
{
        const auto now = utils::Timeval::currentTime();
        while (!empty() && top().when <= now) {
            const iot::mqtt::packets::Publish duePublish = top().publish;
            pop();
            mqtt->sendPublish(duePublish.getTopic(), duePublish.getMessage(), duePublish.getQoS(), duePublish.getRetain());
            mqtt->onPublish(duePublish);
        }
    }
References empty(), mqtt, mqtt::mqttintegrator::lib::Mqtt::onPublish(), pop(), mqtt::mqttintegrator::lib::Mqtt::ScheduledPublish::publish, top(), and mqtt::mqttintegrator::lib::Mqtt::ScheduledPublish::when.
Referenced by armDelayTimer().
top()
Mqtt::ScheduledPublish const & mqtt::mqttintegrator::lib::Mqtt::DelayedQueue::top () const
Definition at line 237 of file Mqtt.cpp.
{
        return minHeap.top();
    }
References minHeap.
Referenced by armDelayTimer(), and processDue().
Member Data Documentation
delayTimer
core::timer::Timer mqtt::mqttintegrator::lib::Mqtt::DelayedQueue::delayTimer private
Definition at line 127 of file Mqtt.h.
Referenced by armDelayTimer(), and ~DelayedQueue().
minHeap
std::priority_queue<ScheduledPublish, std::vector<ScheduledPublish>, EarlierFirst> mqtt::mqttintegrator::lib::Mqtt::DelayedQueue::minHeap private
Definition at line 125 of file Mqtt.h.
Referenced by delayPublish(), empty(), pop(), and top().
mqtt
Mqtt* mqtt::mqttintegrator::lib::Mqtt::DelayedQueue::mqtt private
Definition at line 123 of file Mqtt.h.
Referenced by DelayedQueue(), and processDue().
nextSeq
std::size_t mqtt::mqttintegrator::lib::Mqtt::DelayedQueue::nextSeq = 0 private
Definition at line 124 of file Mqtt.h.
Referenced by delayPublish().
The documentation for this class was generated from the following files:
mqttintegrator/lib/Mqtt.h
mqttintegrator/lib/Mqtt.cpp