MQTTSuite: store_err_handler Class Reference
store_err_handler Class Reference
Public Member Functions
void reset () override
void reset () override
Public Member Functions inherited from nlohmann::json_schema::basic_error_handler
void error (const json::json_pointer &, const json &, const std::string &) override
operator bool () const
Public Member Functions inherited from nlohmann::json_schema::error_handler
virtual ~error_handler ()
Public Attributes
std::vector< nlohmann::json::json_pointer > failed
Private Member Functions
void error (const nlohmann::json::json_pointer &ptr, const json &instance, const std::string &message) override
void error (const nlohmann::json::json_pointer &ptr, const json &instance, const std::string &message) override
Detailed Description
Definition at line 41 of file issue-149-entry-selection.cpp.
Member Function Documentation
error() [1/2]
void store_err_handler::error (const nlohmann::json::json_pointer & ptr, const json & instance, const std::string & message) inline override private
Definition at line 43 of file issue-149-entry-selection.cpp.
    {
        nlohmann::json_schema::basic_error_handler::error(ptr, instance, message);
        std::cerr << "ERROR: '" << ptr << "' - '" << instance << "': " << message << "\n";
        failed.push_back(ptr);
    }
References nlohmann::json_schema::basic_error_handler::error(), and failed.
error() [2/2]
void store_err_handler::error (const nlohmann::json::json_pointer & ptr, const json & instance, const std::string & message) inline override private
Definition at line 43 of file issue-149-entry-selection.cpp.
    {
        nlohmann::json_schema::basic_error_handler::error(ptr, instance, message);
        std::cerr << "ERROR: '" << ptr << "' - '" << instance << "': " << message << "\n";
        failed.push_back(ptr);
    }
reset() [1/2]
void store_err_handler::reset () inline override virtual
Reimplemented from nlohmann::json_schema::basic_error_handler.
Definition at line 53 of file issue-149-entry-selection.cpp.
    {
        nlohmann::json_schema::basic_error_handler::reset();
        failed.clear();
    }
References failed, and nlohmann::json_schema::basic_error_handler::reset().
Referenced by main().
reset() [2/2]
void store_err_handler::reset () inline override virtual
Reimplemented from nlohmann::json_schema::basic_error_handler.
Definition at line 53 of file issue-149-entry-selection.cpp.
    {
        nlohmann::json_schema::basic_error_handler::reset();
        failed.clear();
    }
Member Data Documentation
failed
std::vector< nlohmann::json::json_pointer > store_err_handler::failed
Definition at line 51 of file issue-149-entry-selection.cpp.
Referenced by error(), main(), and reset().
The documentation for this class was generated from the following file:
lib/json-schema-validator/test/issue-149-entry-selection.cpp