MQTTSuite: lib/json-schema-validator/test/errors.cpp File Reference
errors.cpp File Reference
#include <nlohmann/json-schema.hpp>
#include <iostream>
Classes
class anonymous_namespace{errors.cpp}::store_ptr_err_handler
Namespaces
namespace anonymous_namespace{errors.cpp}
Macros
#define EXPECT_EQ(a, b)
Functions
int main (void)
Variables
static int error_count
static json anonymous_namespace{errors.cpp}::person_schema
Macro Definition Documentation
EXPECT_EQ
#define EXPECT_EQ (a, b)
Value:
    do {                                                             \
        if (a != b) {                                                \
            std::cerr << "Failed: '" << a << "' != '" << b << "'\n"; \
            error_count++;                                           \
        }                                                            \
    } while (0)
Definition at line 7 of file errors.cpp.
#define EXPECT_EQ(a, b)                                              \
    do {                                                             \
        if (a != b) {                                                \
            std::cerr << "Failed: '" << a << "' != '" << b << "'\n"; \
            error_count++;                                           \
        }                                                            \
    } while (0)
Function Documentation
main()
int main (void)
Definition at line 73 of file errors.cpp.
{
    json_validator validator;
    try {
        validator.set_root_schema(person_schema); // insert root-schema
    } catch (const std::exception &e) {
        std::cerr << "Validation of schema failed, here is why: " << e.what() << "\n";
        return EXIT_FAILURE;
    }
    store_ptr_err_handler err;
    validator.validate({{"age", 42}, {"name", "John"}}, err); // OK
    EXPECT_EQ(err.failed_pointers.size(), 0);
    err.reset();
    validator.validate({{"age", 42}}, err); // no name
    EXPECT_EQ(err.failed_pointers.size(), 1);
    EXPECT_EQ(err.failed_pointers[0].to_string(), "");
    err.reset();
    validator.validate({{"street", "Boulevard"}}, err); // no name and no age
    EXPECT_EQ(err.failed_pointers.size(), 3);
    EXPECT_EQ(err.failed_pointers[0].to_string(), "");
    EXPECT_EQ(err.failed_pointers[1].to_string(), "");
    EXPECT_EQ(err.failed_pointers[2].to_string(), "");
    err.reset();
    validator.validate({{"age", 42}, {"name", 12}}, err); // name must be a string
    EXPECT_EQ(err.failed_pointers.size(), 1);
    EXPECT_EQ(err.failed_pointers[0].to_string(), "/name");
    err.reset();
    validator.validate({
                           {"age", 42},
                           {"name", "John"},
                           {"phones", {1234, "223"}},
                       },
                       err); // name must be a string
    EXPECT_EQ(err.failed_pointers.size(), 1);
    EXPECT_EQ(err.failed_pointers[0].to_string(), "/phones/1");
    err.reset();
    validator.validate({
                           {"age", 42},
                           {"name", "John"},
                           {"phones", {0}},
                           {"post-code", 12345},
                       },
                       err); // name must be a string
    EXPECT_EQ(err.failed_pointers.size(), 1);
    EXPECT_EQ(err.failed_pointers[0].to_string(), "");
    err.reset();
    return error_count;
}
References error_count, anonymous_namespace{errors.cpp}::store_ptr_err_handler::failed_pointers, anonymous_namespace{errors.cpp}::person_schema, anonymous_namespace{errors.cpp}::store_ptr_err_handler::reset(), nlohmann::json_schema::json_validator::set_root_schema(), and nlohmann::json_schema::json_validator::validate().
Variable Documentation
error_count
int error_count static
Definition at line 5 of file errors.cpp.
Referenced by main().