MQTTSuite: lib/json-schema-validator/example/format.cpp File Reference
format.cpp File Reference
#include <iostream>
#include <nlohmann/json-schema.hpp>
Classes
class json_validator
Functions
static void uri_format_checker (const std::string &format, const std::string &value)
int main ()
Variables
static json uri_schema
static json good_uri = {{"myUri", "http://hostname.com/"}}
static json bad_uri = {{"myUri", "http:/hostname.com/"}}
Function Documentation
main()
int main (void)
Definition at line 34 of file format.cpp.
{
    json_validator validator(nullptr, uri_format_checker); // create validator
    try {
        validator.set_root_schema(uri_schema); // insert root-schema
    } catch (const std::exception &e) {
        std::cerr << "Validation of schema failed, here is why: " << e.what() << "\n";
        return EXIT_FAILURE;
    }
    validator.validate(good_uri);
    try {
        validator.validate(bad_uri);
    } catch (const std::exception &e) {
        std::cerr << "Validation expectedly failed, here is why: " << e.what() << "\n";
    }
    return EXIT_SUCCESS;
}
References bad_uri, good_uri, nlohmann::json_schema::json_validator::json_validator(), nlohmann::json_schema::json_validator::set_root_schema(), uri_format_checker(), uri_schema, and nlohmann::json_schema::json_validator::validate().
uri_format_checker()
void uri_format_checker (const std::string & format, const std::string & value) static
Definition at line 25 of file format.cpp.
{
    if (format == "uri") {
        if (value.find("://") == std::string::npos)
            throw std::invalid_argument("URI does not contain :// - invalid");
    } else
        throw std::logic_error("Don't know how to validate " + format);
}
Referenced by main().
Variable Documentation
bad_uri
json bad_uri = {{"myUri", "http:/hostname.com/"}} static
Definition at line 23 of file format.cpp.
{{"myUri", "http:/hostname.com/"}};
Referenced by main().
good_uri
json good_uri = {{"myUri", "http://hostname.com/"}} static
Definition at line 22 of file format.cpp.
{{"myUri", "http://hostname.com/"}};
Referenced by main().
uri_schema
json uri_schema static
Initial value:
= R"(
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "myUri": {
      "type":"string",
      "format": "uri"
    }
  }
})"_json
Definition at line 9 of file format.cpp.
Referenced by main().