MQTTSuite: lib/json-schema-validator/test/issue-149-entry-selection.cpp File Reference
issue-149-entry-selection.cpp File Reference
#include <nlohmann/json-schema.hpp>
#include <iostream>
Classes
class anonymous_namespace{issue-149-entry-selection.cpp}::store_err_handler
Namespaces
namespace anonymous_namespace{issue-149-entry-selection.cpp}
Macros
#define EXPECT_EQ(a, b)
Functions
int main (void)
Variables
static int anonymous_namespace{issue-149-entry-selection.cpp}::error_count
static json anonymous_namespace{issue-149-entry-selection.cpp}::person_schema
static json_validator validator (person_schema)
Macro Definition Documentation
EXPECT_EQ
#define EXPECT_EQ (a, b)
Value:
    do {                                                             \
        if (a != b) {                                                \
            std::cerr << "Failed: '" << a << "' != '" << b << "'\n"; \
            error_count++;                                           \
        }                                                            \
    } while (0)
Definition at line 13 of file issue-149-entry-selection.cpp.
#define EXPECT_EQ(a, b)                                              \
    do {                                                             \
        if (a != b) {                                                \
            std::cerr << "Failed: '" << a << "' != '" << b << "'\n"; \
            error_count++;                                           \
        }                                                            \
    } while (0)
Function Documentation
main()
int main (void)
Definition at line 64 of file issue-149-entry-selection.cpp.
{
    store_err_handler err;
    validator.validate(1, err); // OK
    EXPECT_EQ(err.failed.size(), 0);
    err.reset();
    validator.validate("1", err); // no name
    EXPECT_EQ(err.failed.size(), 1);
    err.reset();
    validator.validate(1, err, json_uri("#/definitions/B"));
    EXPECT_EQ(err.failed.size(), 0);
    err.reset();
    validator.validate("1", err, json_uri("#/definitions/B"));
    EXPECT_EQ(err.failed.size(), 1);
    err.reset();
    validator.validate({{"b", 1}}, err, json_uri("#/definitions/A"));
    EXPECT_EQ(err.failed.size(), 0);
    err.reset();
    validator.validate({{"b", "1"}}, err, json_uri("#/definitions/A"));
    EXPECT_EQ(err.failed.size(), 1);
    err.reset();
    return error_count;
}
References anonymous_namespace{issue-149-entry-selection.cpp}::error_count, anonymous_namespace{issue-149-entry-selection.cpp}::store_err_handler::failed, nlohmann::json_uri::json_uri(), anonymous_namespace{issue-149-entry-selection.cpp}::store_err_handler::reset(), nlohmann::json_schema::json_validator::validate(), and validator.
Variable Documentation
validator
json_validator validator(person_schema) (person_schema) static
Referenced by main().