MQTTSuite: lib/json-schema-validator/test/issue-229-oneof-default-values.cpp File Reference
issue-229-oneof-default-values.cpp File Reference
#include <iostream>
#include <nlohmann/json-schema.hpp>
Functions
static void loader (const json_uri &uri, json &schema)
int main (void)
Variables
static const json default_schema
Function Documentation
loader()
static void loader (const json_uri & uri, json & schema) static
Definition at line 40 of file issue-229-oneof-default-values.cpp.
{
    schema = default_schema;
}
References default_schema.
Referenced by main().
main()
int main (void)
Definition at line 45 of file issue-229-oneof-default-values.cpp.
{
    json_validator validator(loader);
    validator.set_root_schema(default_schema);
    json data = R"({"name": "bar"})"_json;
    json expected = R"(
        [
            {
                "op": "add",
                "path": "/code",
                "value": 2
            }
        ]
    )"_json;
    json patch = validator.validate(data);
    if (patch != expected) {
        std::cerr << "Patch contains wrong operation: '" << patch.dump() << "' instead of expected '" << expected.dump() << "'" << std::endl;
        return 1;
    }
    return 0;
}
References default_schema, nlohmann::json_schema::json_validator::json_validator(), loader(), nlohmann::json_schema::json_validator::set_root_schema(), and nlohmann::json_schema::json_validator::validate().
Variable Documentation
default_schema
static const json default_schema static
Definition at line 8 of file issue-229-oneof-default-values.cpp.
Referenced by loader(), and main().