MQTTSuite: mqttbridge/mqttbridge.cpp File Reference
mqttbridge.cpp File Reference
#include "ConfigBridge.h"
#include "SocketContextFactory.h"
#include "config.h"
#include "lib/BridgeStore.h"
#include "lib/Mqtt.h"
#include "lib/SSEDistributor.h"
Concepts
concept HasSocketClientConfig
concept StreamSocketClient
Functions
static void startBridges ()
static void tryRestartBridges ()
static void handleAutoConnectControllers (std::shared_ptr< core::socket::stream::AutoConnectControl > &autoConnectController)
static void handleConnector (core::eventreceiver::ConnectEventReceiver *connectEventReceiver)
static void addBridgeBrokerConnection (core::socket::stream::SocketConnection *socketConnection)
static void delBridgeBrokerConnection (core::socket::stream::SocketConnection *socketConnection)
static void closeBridges ()
static void reportState (const std::string &instanceName, const core::socket::SocketAddress &socketAddress, const core::socket::State &state)
template<template< typename SocketContextFactory, typename... Args > typename SocketClientT>
requires StreamSocketClient<SocketClientT<mqtt::bridge::SocketContextFactory>>
SocketClientT< mqtt::bridge::SocketContextFactory > startClient (const std::string &instanceName, const std::function< void(typename SocketClientT< mqtt::bridge::SocketContextFactory >::Config &)> &configurator)
template<typename HttpClient>
requires requires { typename HttpClient::Config; typename HttpClient::SocketAddress; } && std::constructible_from<HttpClient, const std::string&, std::function<void(const std::shared_ptr<web::http::client::MasterRequest>&)>&&, std::function<void(const std::shared_ptr<web::http::client::MasterRequest>&)>&&> && requires(HttpClient& httpClient) { { httpClient.getConfig() } -> std::same_as<typename HttpClient::Config&>; httpClient.setOnConnected(std::declval<std::function<void(core::socket::stream::SocketConnection*)>>()) .setOnDisconnect(std::declval<std::function<void(core::socket::stream::SocketConnection*)>>()) .setOnInitState(std::declval<std::function<void(core::eventreceiver::ConnectEventReceiver*)>>()) .setOnAutoConnectControl(std::declval<std::function<void(std::shared_ptr<core::socket::stream::AutoConnectControl>)>>()) .connect(std::declval<std::function<void(const typename HttpClient::SocketAddress&, const core::socket::State&)>>()); }
void startClient (const std::string &name, const std::function< void(typename HttpClient::Config &)> &configurator)
int main (int argc, char *argv[])
Variables
static std::set< core::eventreceiver::ConnectEventReceiver * > activeConnectors
static std::set< std::shared_ptr< core::socket::stream::AutoConnectControl > > autoConnectControllers
static bool restart = false
Function Documentation
addBridgeBrokerConnection()
void addBridgeBrokerConnection (core::socket::stream::SocketConnection * socketConnection) static
Definition at line 163 of file mqttbridge.cpp.
{
    VLOG(1) << "Connection established: " << socketConnection->getInstanceName();
}
Referenced by startClient(), and startClient().
closeBridges()
void closeBridges () static
Definition at line 173 of file mqttbridge.cpp.
{
    mqtt::bridge::lib::SSEDistributor::instance().bridgesStopping();
    for (const auto& [bridgeName, bridge] : mqtt::bridge::lib::BridgeStore::instance().getBridgeMap()) {
        mqtt::bridge::lib::SSEDistributor::instance().bridgeStopping(bridgeName);
        for (const auto& mqtt : bridge.getMqttList()) {
            mqtt::bridge::lib::SSEDistributor::instance().brokerDisconnecting(
                bridgeName, mqtt->getMqttContext()->getSocketConnection()->getInstanceName());
            mqtt->sendDisconnect();
            mqtt->getMqttContext()
                ->getSocketConnection()
                ->getConfigInstance()
                ->getSection<net::config::ConfigPhysicalSocketClient>()
                ->setReconnect(false);
        }
    }
    for (auto connectEventReceiver : activeConnectors) {
        connectEventReceiver->stopConnect();
    }
    for (auto autoConnectControler : autoConnectControllers) {
        autoConnectControler->stopReconnectAndRetry();
    }
    autoConnectControllers.clear();
    restart = true;
}
References autoConnectControllers, mqtt::bridge::lib::SSEDistributor::bridgesStopping(), mqtt::bridge::lib::SSEDistributor::instance(), and restart.
delBridgeBrokerConnection()
void delBridgeBrokerConnection (core::socket::stream::SocketConnection * socketConnection) static
Definition at line 167 of file mqttbridge.cpp.
{
    VLOG(1) << "Connection closed: " << socketConnection->getInstanceName();
    tryRestartBridges();
}
References tryRestartBridges().
Referenced by startClient(), and startClient().
handleAutoConnectControllers()
void handleAutoConnectControllers (std::shared_ptr< core::socket::stream::AutoConnectControl > & autoConnectController) static
Definition at line 149 of file mqttbridge.cpp.
{
    autoConnectControllers.insert(autoConnectController);
}
References autoConnectControllers.
handleConnector()
void handleConnector (core::eventreceiver::ConnectEventReceiver * connectEventReceiver) static
Definition at line 153 of file mqttbridge.cpp.
{
    if (connectEventReceiver->isEnabled()) {
        activeConnectors.insert(connectEventReceiver);
    } else {
        activeConnectors.erase(connectEventReceiver);
        tryRestartBridges();
    }
}
References activeConnectors, and tryRestartBridges().
Referenced by startClient(), and startClient().
main()
int main (int argc, char * argv[])
Definition at line 572 of file mqttbridge.cpp.
{
#if defined(LINK_WEBSOCKET_STATIC) || defined(LINK_SUBPROTOCOL_STATIC)
    web::websocket::client::SocketContextUpgradeFactory::link();
#endif
#ifdef LINK_SUBPROTOCOL_STATIC
    web::websocket::client::SubProtocolFactorySelector::link("mqtt", mqttClientSubProtocolFactory);
#endif
    utils::Config::addInstance<mqtt::bridge::ConfigBridge>();
    core::SNodeC::init(argc, argv);
    const express::Router router(express::middleware::JsonMiddleware());
    router.get("/api/bridge/config", [] APPLICATION(req, res) { // cppcheck-suppress unknownMacro
        res->send(mqtt::bridge::lib::BridgeStore::instance().getBridgesConfigJson().dump(4));
    });
    router.patch("/api/bridge/config", [] APPLICATION(req, res) {
        req->getAttribute<nlohmann::json>(
            [&res](nlohmann::json& jsonPatch) {
                std::string jsonString = jsonPatch.dump(4);
                VLOG(1) << jsonString;
                if (!restart) {
                    closeBridges();
                    if (mqtt::bridge::lib::BridgeStore::instance().patch(jsonPatch)) {
                        res->send(R"({"success": true, "message": "Bridge config patch applied"})"_json.dump());
                        tryRestartBridges();
                    } else {
                        res->status(404).send(R"({"success": false, "message": "Bridge config patch failed to applie"})"_json.dump());
                    }
                } else {
                    res->status(409).send(
                        R"({"success": false, "message": "Bridge is in restarting state. Patch not applied"})"_json.dump());
                }
            },
            [&res](const std::string& key) {
                VLOG(1) << "Attribute type not found: " << key;
                res->status(400).send("Attribute type not found: " + key);
            });
    });
    router.get("/api/bridge/sse", [] APPLICATION(req, res) {
        if (web::http::ciContains(req->get("Accept"), "text/event-stream")) {
            res->set("Content-Type", "text/event-stream") //
                .set("Cache-Control", "no-cache")
                .set("Connection", "keep-alive");
            res->sendHeader();
            std::string data{"data"};
            mqtt::bridge::lib::SSEDistributor::instance().addEventReceiver(res, req->get("Last-Event-ID"));
        } else {
            res->redirect("/clients");
        }
    });
    router.get("/", [] APPLICATION(req, res) {
        res->redirect("/config");
    });
    router.get("/config", [] APPLICATION(req, res) {
        res->redirect("/config/index.html");
    });
    router.use("/config", express::middleware::StaticMiddleware(utils::Config::getInstance<mqtt::bridge::ConfigBridge>()->getHtmlDir()));
    router.get("*", [] APPLICATION(req, res) {
        res->redirect("/config/index.html");
    });
    express::legacy::in::Server("admin-legacy", router, reportState, [](auto& config) {
        config.setPort(8081);
        config.setRetry();
        config.setReuseAddress();
    });
    express::tls::in::Server("admin-tls", router, reportState, [](auto& config) {
        config.setPort(8082);
        config.setRetry();
        config.setReuseAddress();
    });
    if (mqtt::bridge::lib::BridgeStore::instance().loadAndValidate(
            utils::Config::getInstance<mqtt::bridge::ConfigBridge>()->getDefinitionFile())) {
        startBridges();
    } else {
        VLOG(1) << "Loading bridge definition file failed";
    }
    return core::SNodeC::start();
}
References mqtt::bridge::lib::SSEDistributor::addEventReceiver(), mqtt::bridge::lib::BridgeStore::instance(), mqtt::bridge::lib::SSEDistributor::instance(), mqtt::bridge::lib::BridgeStore::loadAndValidate(), reportState(), and startBridges().
reportState()
void reportState (const std::string & instanceName, const core::socket::SocketAddress & socketAddress, const core::socket::State & state) static
Definition at line 206 of file mqttbridge.cpp.
{
    switch (state) {
        case core::socket::State::OK:
            VLOG(1) << instanceName << ": connected to '" << socketAddress.toString() << "'";
            break;
        case core::socket::State::DISABLED:
            VLOG(1) << instanceName << ": disabled";
            break;
        case core::socket::State::ERROR:
            VLOG(1) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
            break;
        case core::socket::State::FATAL:
            VLOG(1) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
            break;
    }
}
Referenced by main().
startBridges()
void startBridges () static
Definition at line 343 of file mqttbridge.cpp.
{
    mqtt::bridge::lib::SSEDistributor::instance().bridgesStarting();
    for (const auto& [bridgeName, bridge] : mqtt::bridge::lib::BridgeStore::instance().getBridgeMap()) {
        VLOG(0) << "Starting bridge: " << bridgeName;
        if (!bridge.getDisabled()) {
            mqtt::bridge::lib::SSEDistributor::instance().bridgeStarting(bridgeName);
            for (const auto& [fullInstanceName, broker] : bridge.getBrokerMap()) {
                if (!broker.getDisabled()) {
                    mqtt::bridge::lib::SSEDistributor::instance().brokerConnecting(bridgeName, fullInstanceName);
                    VLOG(1) << "  Creating broker instance: " << fullInstanceName;
                    VLOG(1) << "    Broker prefix: " << broker.getPrefix();
                    VLOG(1) << "    Broker client id: " << broker.getClientId();
                    VLOG(1) << "    Broker disabled: " << broker.getDisabled();
                    VLOG(1) << "    Broker address: " << broker.getAddress();
                    VLOG(1) << "    Broker prefix: " << broker.getPrefix();
                    VLOG(1) << "    Broker username: " << broker.getUsername();
                    VLOG(1) << "    Broker password: " << broker.getPassword();
                    VLOG(1) << "    Broker client-id: " << broker.getClientId();
                    VLOG(1) << "    Broker clean session: " << broker.getCleanSession();
                    VLOG(1) << "    Broker will-topic: " << broker.getWillTopic();
                    VLOG(1) << "    Broker will-message: " << broker.getWillMessage();
                    VLOG(1) << "    Broker will-qos: " << static_cast<int>(broker.getWillQoS());
                    VLOG(1) << "    Broker will-retain: " << broker.getWillRetain();
                    VLOG(1) << "    Broker loop prevention: " << broker.getLoopPrevention();
                    VLOG(1) << "    Bridge disabled: " << bridge.getDisabled();
                    VLOG(1) << "    Bridge prefix: " << bridge.getPrefix();
                    VLOG(1) << "    Bridge Transport: " << broker.getTransport();
                    VLOG(1) << "    Bridge Protocol: " << broker.getProtocol();
                    VLOG(1) << "    Bridge Encryption: " << broker.getEncryption();
                    VLOG(1) << "    Topics:";
                    const std::list<iot::mqtt::Topic>& topics = broker.getTopics();
                    for (const iot::mqtt::Topic& topic : topics) {
                        VLOG(1) << "      " << topic.getName() << ":" << static_cast<uint16_t>(topic.getQoS());
                    }
                    const std::string& transport = broker.getTransport();
                    const std::string& protocol = broker.getProtocol();
                    const std::string& encryption = broker.getEncryption();
                    if (transport == "stream") {
                        if (protocol == "in") {
                            if (encryption == "legacy") {
#if defined(CONFIG_MQTTSUITE_BRIDGE_TCP_IPV4)
                                startClient<net::in::stream::legacy::SocketClient>(fullInstanceName, [&broker](auto& config) {
                                    config.setDisableNagleAlgorithm();
                                    config.Remote::setHost(broker.getAddress()["host"]);
                                    config.Remote::setPort(broker.getAddress()["port"]);
                                    config.setDisabled(broker.getDisabled() || broker.getBridge().getDisabled());
                                });
#else  // CONFIG_MQTTSUITE_BRIDGE_TCP_IPV4
                                VLOG(1) << "    Transport '" << transport << "', protocol '" << protocol << "', encryption '" << encryption
                                        << "' not supported.";
#endif // CONFIG_MQTTSUITE_BRIDGE_TCP_IPV4
                            } else if (encryption == "tls") {
#if defined(CONFIG_MQTTSUITE_BRIDGE_TLS_IPV4)
                                startClient<net::in::stream::tls::SocketClient>(fullInstanceName, [&broker](auto& config) {
                                    config.setDisableNagleAlgorithm();
                                    config.Remote::setHost(broker.getAddress()["host"]);
                                    config.Remote::setPort(broker.getAddress()["port"]);
                                    config.setDisabled(broker.getDisabled() || broker.getBridge().getDisabled());
                                });
#else  // CONFIG_MQTTSUITE_BRIDGE_TLS_IPV4
                                VLOG(1) << "    Transport '" << transport << "', protocol '" << protocol << "', encryption '" << encryption
                                        << "' not supported.";
#endif // CONFIG_MQTTSUITE_BRIDGE_TLS_IPV4
                            }
                        } else if (protocol == "in6") {
                            if (encryption == "legacy") {
#if defined(CONFIG_MQTTSUITE_BRIDGE_TCP_IPV6)
                                startClient<net::in6::stream::legacy::SocketClient>(fullInstanceName, [&broker](auto& config) {
                                    config.setDisableNagleAlgorithm();
                                    config.Remote::setHost(broker.getAddress()["host"]);
                                    config.Remote::setPort(broker.getAddress()["port"]);
                                    config.setDisabled(broker.getDisabled() || broker.getBridge().getDisabled());
                                });
#else  // CONFIG_MQTTSUITE_BRIDGE_TCP_IPV6
                                VLOG(1) << "    Transport '" << transport << "', protocol '" << protocol << "', encryption '" << encryption
                                        << "' not supported.";
#endif // CONFIG_MQTTSUITE_BRIDGE_TCP_IPV6
                            } else if (encryption == "tls") {
#if defined(CONFIG_MQTTSUITE_BRIDGE_TLS_IPV6)
                                startClient<net::in6::stream::tls::SocketClient>(fullInstanceName, [&broker](auto& config) {
                                    config.setDisableNagleAlgorithm();
                                    config.Remote::setHost(broker.getAddress()["host"]);
                                    config.Remote::setPort(broker.getAddress()["port"]);
                                    config.setDisabled(broker.getDisabled() || broker.getBridge().getDisabled());
                                });
#else  // CONFIG_MQTTSUITE_BRIDGE_TLS_IPV6
                                VLOG(1) << "    Transport '" << transport << "', protocol '" << protocol << "', encryption '" << encryption
                                        << "' not supported.";
#endif // CONFIG_MQTTSUITE_BRIDGE_TLS_IPV6
                            }
                        } else if (protocol == "un") {
                            if (encryption == "legacy") {
#if defined(CONFIG_MQTTSUITE_BRIDGE_UNIX)
                                startClient<net::un::stream::legacy::SocketClient>(fullInstanceName, [&broker](auto& config) {
                                    config.Remote::setSunPath(broker.getAddress()["host"]);
                                    config.setDisabled(broker.getDisabled() || broker.getBridge().getDisabled());
                                });
#else  // CONFIG_MQTTSUITE_BRIDGE_UNIX
                                VLOG(1) << "    Transport '" << transport << "', protocol '" << protocol << "', encryption '" << encryption
                                        << "' not supported.";
#endif // CONFIG_MQTTSUITE_BRIDGE_UNIX
                            } else if (encryption == "tls") {
#if defined(CONFIG_MQTTSUITE_BRIDGE_UNIX_TLS)
                                startClient<net::un::stream::tls::SocketClient>(fullInstanceName, [&broker](auto& config) {
                                    config.Remote::setSunPath(broker.getAddress()["host"]);
                                    config.setDisabled(broker.getDisabled() || broker.getBridge().getDisabled());
                                });
#else  // CONFIG_MQTTSUITE_BRIDGE_UNIX_TLS
                                VLOG(1) << "    Transport '" << transport << "', protocol '" << protocol << "', encryption '" << encryption
                                        << "' not supported.";
#endif // CONFIG_MQTTSUITE_BRIDGE_UNIX_TLS
                            }
                        }
                    } else if (transport == "websocket") {
                        if (protocol == "in") {
                            if (encryption == "legacy") {
#if defined(CONFIG_MQTTSUITE_BRIDGE_TCP_IPV4) && defined(CONFIG_MQTTSUITE_BRIDGE_WS)
                                startClient<web::http::legacy::in::Client>(fullInstanceName, [&broker](auto& config) {
                                    config.setDisableNagleAlgorithm();
                                    config.Remote::setHost(broker.getAddress()["host"]);
                                    config.Remote::setPort(broker.getAddress()["port"]);
                                    config.setDisabled(broker.getDisabled() || broker.getBridge().getDisabled());
                                });
#else  // CONFIG_MQTTSUITE_BRIDGE_TCP_IPV4 && CONFIG_MQTTSUITE_BRIDGE_WS
                                VLOG(1) << "    Transport '" << transport << "', protocol '" << protocol << "', encryption '" << encryption
                                        << "' not supported.";
#endif // CONFIG_MQTTSUITE_BRIDGE_TCP_IPV4 && CONFIG_MQTTSUITE_BRIDGE_WS
                            } else if (encryption == "tls") {
#if defined(CONFIG_MQTTSUITE_BRIDGE_TLS_IPV4) && defined(CONFIG_MQTTSUITE_BRIDGE_WSS)
                                startClient<web::http::tls::in::Client>(fullInstanceName, [&broker](auto& config) {
                                    config.setDisableNagleAlgorithm();
                                    config.Remote::setHost(broker.getAddress()["host"]);
                                    config.Remote::setPort(broker.getAddress()["port"]);
                                    config.setDisabled(broker.getDisabled() || broker.getBridge().getDisabled());
                                });
#else  // CONFIG_MQTTSUITE_BRIDGE_TLS_IPV4 && CONFIG_MQTTSUITE_BRIDGE_WSS
                                VLOG(1) << "    Transport '" << transport << "', protocol '" << protocol << "', encryption '" << encryption
                                        << "' not supported.";
#endif // CONFIG_MQTTSUITE_BRIDGE_TLS_IPV4 && CONFIG_MQTTSUITE_BRIDGE_WSS
                            }
                        } else if (protocol == "in6") {
                            if (encryption == "legacy") {
#if defined(CONFIG_MQTTSUITE_BRIDGE_TCP_IPV6) && defined(CONFIG_MQTTSUITE_BRIDGE_WS)
                                startClient<web::http::legacy::in6::Client>(fullInstanceName, [&broker](auto& config) {
                                    config.setDisableNagleAlgorithm();
                                    config.Remote::setHost(broker.getAddress()["host"]);
                                    config.Remote::setPort(broker.getAddress()["port"]);
                                    config.setDisabled(broker.getDisabled() || broker.getBridge().getDisabled());
                                });
#else  // CONFIG_MQTTSUITE_BRIDGE_TCP_IPV6 && CONFIG_MQTTSUITE_BRIDGE_WS
                                VLOG(1) << "    Transport '" << transport << "', protocol '" << protocol << "', encryption '" << encryption
                                        << "' not supported.";
#endif // CONFIG_MQTTSUITE_BRIDGE_TCP_IPV6&&  CONFIG_MQTTSUITE_BRIDGE_WS
                            } else if (encryption == "tls") {
#if defined(CONFIG_MQTTSUITE_BRIDGE_TLS_IPV6) && defined(CONFIG_MQTTSUITE_BRIDGE_WSS)
                                startClient<web::http::tls::in6::Client>(fullInstanceName, [&broker](auto& config) {
                                    config.setDisableNagleAlgorithm();
                                    config.Remote::setHost(broker.getAddress()["host"]);
                                    config.Remote::setPort(broker.getAddress()["port"]);
                                    config.setDisabled(broker.getDisabled() || broker.getBridge().getDisabled());
                                });
#else  // CONFIG_MQTTSUITE_BRIDGE_TLS_IPV6 && CONFIG_MQTTSUITE_BRIDGE_WSS
                                VLOG(1) << "    Transport '" << transport << "', protocol '" << protocol << "', encryption '" << encryption
                                        << "' not supported.";
#endif // CONFIG_MQTTSUITE_BRIDGE_TLS_IPV6 && CONFIG_MQTTSUITE_BRIDGE_WSS
                            }
                        } else if (protocol == "un") {
                            if (encryption == "legacy") {
#if defined(CONFIG_MQTTSUITE_BRIDGE_UNIX) && defined(CONFIG_MQTTSUITE_BRIDGE_WS)
                                startClient<web::http::legacy::un::Client>(fullInstanceName, [&broker](auto& config) {
                                    config.Remote::setSunPath(broker.getAddress()["path"]);
                                    config.setDisabled(broker.getDisabled() || broker.getBridge().getDisabled());
                                });
#else  // CONFIG_MQTTSUITE_BRIDGE_UNIX && CONFIG_MQTTSUITE_BRIDGE_WS
                                VLOG(1) << "    Transport '" << transport << "', protocol '" << protocol << "', encryption '" << encryption
                                        << "' not supported.";
#endif // CONFIG_MQTTSUITE_BRIDGE_UNIX &&  CONFIG_MQTTSUITE_BRIDGE_WS
                            } else if (encryption == "tls") {
#if defined(CONFIG_MQTTSUITE_BRIDGE_UNIX_TLS) && defined(CONFIG_MQTTSUITE_BRIDGE_WSS)
                                startClient<web::http::tls::un::Client>(fullInstanceName, [&broker](auto& config) {
                                    config.Remote::setSunPath(broker.getAddress()["path"]);
                                    config.setDisabled(broker.getDisabled() || broker.getBridge().getDisabled());
                                });
#else  // CONFIG_MQTTSUITE_BRIDGE_UNIX_TLS && CONFIG_MQTTSUITE_BRIDGE_WSS
                                VLOG(1) << "    Transport '" << transport << "', protocol '" << protocol << "', encryption '" << encryption
                                        << "' not supported.";
#endif // CONFIG_MQTTSUITE_BRIDGE_UNIX_TLS && CONFIG_MQTTSUITE_BRIDGE_WSS
                            }
                        }
                    } else {
                        VLOG(1) << "    Transport '" << transport << "' not supported.";
                    }
                } else {
                    mqtt::bridge::lib::SSEDistributor::instance().brokerDisabled(bridgeName, fullInstanceName);
                }
            }
        } else {
            mqtt::bridge::lib::SSEDistributor::instance().bridgeDisabled(bridgeName);
        }
    }
}
References mqtt::bridge::lib::SSEDistributor::bridgesStarting(), and mqtt::bridge::lib::SSEDistributor::instance().
Referenced by main(), and tryRestartBridges().
startClient() [1/2]
template<template< typename SocketContextFactory, typename... Args > typename SocketClientT> requires StreamSocketClient<SocketClientT<mqtt::bridge::SocketContextFactory>> SocketClientT< mqtt::bridge::SocketContextFactory > startClient (const std::string & instanceName, const std::function< void(typename SocketClientT< mqtt::bridge::SocketContextFactory >::Config &)> & configurator)
Definition at line 235 of file mqttbridge.cpp.
{
    using Client = SocketClientT<mqtt::bridge::SocketContextFactory>;
    using SocketAddress = typename Client::SocketAddress;
    Client socketClient = core::socket::stream::Client<Client>(instanceName, configurator);
    socketClient.getConfig().ConfigInstance::configurable(false);
    socketClient.getConfig().Remote::configurable(false);
    socketClient.getConfig().setRetry().setRetryBase(1);
    socketClient.getConfig().setReconnect();
    socketClient.getConfig().getDisabled();
    socketClient
        .setOnConnected([](core::socket::stream::SocketConnection* socketConnection) {
            addBridgeBrokerConnection(socketConnection);
        })
        .setOnDisconnect([](core::socket::stream::SocketConnection* socketConnection) {
            delBridgeBrokerConnection(socketConnection);
        })
        .setOnInitState([](core::eventreceiver::ConnectEventReceiver* connectEventReceiver) {
            handleConnector(connectEventReceiver);
        })
        .setOnAutoConnectControl([](std::shared_ptr<core::socket::stream::AutoConnectControl> autoConnectControl) {
            handleAutoConnectControllers(autoConnectControl);
        })
        .connect([instanceName](const SocketAddress& socketAddress, const core::socket::State& state) {
            reportState(instanceName, socketAddress, state);
        });
    return socketClient;
}
References addBridgeBrokerConnection(), delBridgeBrokerConnection(), and handleConnector().
startClient() [2/2]
template<typename HttpClient> requires requires { typename HttpClient::Config; typename HttpClient::SocketAddress; } && std::constructible_from<HttpClient, const std::string&, std::function<void(const std::shared_ptr<web::http::client::MasterRequest>&)>&&, std::function<void(const std::shared_ptr<web::http::client::MasterRequest>&)>&&> && requires(HttpClient& httpClient) { { httpClient.getConfig() } -> std::same_as<typename HttpClient::Config&>; httpClient.setOnConnected(std::declval<std::function<void(core::socket::stream::SocketConnection*)>>()) .setOnDisconnect(std::declval<std::function<void(core::socket::stream::SocketConnection*)>>()) .setOnInitState(std::declval<std::function<void(core::eventreceiver::ConnectEventReceiver*)>>()) .setOnAutoConnectControl(std::declval<std::function<void(std::shared_ptr<core::socket::stream::AutoConnectControl>)>>()) .connect(std::declval<std::function<void(const typename HttpClient::SocketAddress&, const core::socket::State&)>>()); } void startClient (const std::string & name, const std::function< void(typename HttpClient::Config &)> & configurator)
Definition at line 287 of file mqttbridge.cpp.
{
    using SocketAddress = typename HttpClient::SocketAddress;
    HttpClient httpClient(
        name,
        [](const std::shared_ptr<web::http::client::MasterRequest>& req) {
            const std::string connectionName = req->getSocketContext()->getSocketConnection()->getConnectionName();
            req->set("Sec-WebSocket-Protocol", "mqtt");
            req->upgrade(
                "/ws",
                "websocket",
                [connectionName](bool success) {
                    VLOG(1) << connectionName << ": HTTP Upgrade (http -> websocket||"
                            << "mqtt" << ") start " << (success ? "success" : "failed");
                },
                []([[maybe_unused]] const std::shared_ptr<web::http::client::Request>& req,
                   [[maybe_unused]] const std::shared_ptr<web::http::client::Response>& res,
                   [[maybe_unused]] bool success) {
                },
                [connectionName]([[maybe_unused]] const std::shared_ptr<web::http::client::Request>& req, const std::string& message) {
                    VLOG(1) << connectionName << ": Request parse error: " << message;
                });
        },
        []([[maybe_unused]] const std::shared_ptr<web::http::client::Request>& req) {
            VLOG(1) << "Session ended";
        });
    configurator(httpClient.getConfig());
    httpClient.getConfig().ConfigInstance::configurable(false);
    httpClient.getConfig().Remote::configurable(false);
    httpClient.getConfig().setRetry().setRetryBase(1);
    httpClient.getConfig().setReconnect();
    httpClient.getConfig().getDisabled();
    httpClient
        .setOnConnected([](core::socket::stream::SocketConnection* socketConnection) {
            addBridgeBrokerConnection(socketConnection);
        })
        .setOnDisconnect([](core::socket::stream::SocketConnection* socketConnection) {
            delBridgeBrokerConnection(socketConnection);
        })
        .setOnInitState([](core::eventreceiver::ConnectEventReceiver* connectEventReceiver) {
            handleConnector(connectEventReceiver);
        })
        .setOnAutoConnectControl([](std::shared_ptr<core::socket::stream::AutoConnectControl> autoConnectControl) {
            handleAutoConnectControllers(autoConnectControl);
        })
        .connect([name](const SocketAddress& socketAddress, const core::socket::State& state) {
            reportState(name, socketAddress, state);
        });
}
References addBridgeBrokerConnection(), delBridgeBrokerConnection(), and handleConnector().
tryRestartBridges()
void tryRestartBridges () static
Definition at line 127 of file mqttbridge.cpp.
{
    bool empty = true;
    for (const auto& [bridgeName, bridge] : mqtt::bridge::lib::BridgeStore::instance().getBridgeMap()) {
        empty &= bridge.getMqttList().empty();
    }
    if (empty && activeConnectors.empty() && restart) {
        mqtt::bridge::lib::SSEDistributor::instance().bridgesStopped();
        core::EventReceiver::atNextTick([]() {
            mqtt::bridge::lib::BridgeStore::instance().activateStaged();
            startBridges();
            utils::Config::parse2();
            restart = false;
        });
    }
}
References mqtt::bridge::lib::BridgeStore::activateStaged(), mqtt::bridge::lib::SSEDistributor::bridgesStopped(), mqtt::bridge::lib::BridgeStore::instance(), mqtt::bridge::lib::SSEDistributor::instance(), restart, and startBridges().
Referenced by delBridgeBrokerConnection(), and handleConnector().
Variable Documentation
activeConnectors
std::set< core::eventreceiver::ConnectEventReceiver * > activeConnectors static
Definition at line 120 of file mqttbridge.cpp.
Referenced by handleConnector().
autoConnectControllers
std::set< std::shared_ptr< core::socket::stream::AutoConnectControl > > autoConnectControllers static
Definition at line 121 of file mqttbridge.cpp.
Referenced by closeBridges(), and handleAutoConnectControllers().
restart
bool restart = false static
Definition at line 123 of file mqttbridge.cpp.
Referenced by closeBridges(), and tryRestartBridges().