MQTTSuite: mqtt/mqtt.cpp File Reference
mqtt.cpp File Reference
#include "SocketContextFactory.h"
Functions
static void reportState (const std::string &instanceName, const core::socket::SocketAddress &socketAddress, const core::socket::State &state)
template<typename HttpClient >
void startClient (const std::string &name, const std::function< void(typename HttpClient::Config &)> &configurator)
static void createConfig (CLI::App *sessionApp, CLI::App *subApp, CLI::App *pubApp)
static void createConfig (net::config::ConfigInstance &config)
int main (int argc, char *argv[])
Function Documentation
createConfig() [1/2]
static void createConfig (CLI::App * sessionApp, CLI::App * subApp, CLI::App * pubApp) static
Definition at line 134 of file mqtt.cpp.
{
    sessionApp->configurable(false);
    subApp->configurable(false);
    pubApp->configurable(false);
    CLI::Option* clientIdOpt = sessionApp->add_option("--client-id", "MQTT Client-ID")
                                   ->group(sessionApp->get_formatter()->get_label("Persistent Options"))
                                   ->type_name("[string]");
    sessionApp->add_option("--qos", "Quality of service")
        ->group(sessionApp->get_formatter()->get_label("Persistent Options"))
        ->type_name("[uint8_t]")
        ->default_val(0)
        ->configurable();
    sessionApp->add_flag("--retain-session{true},-r{true}", "Clean session")
        ->group(sessionApp->get_formatter()->get_label("Persistent Options"))
        ->type_name("[bool]")
        ->default_str("false")
        ->check(CLI::IsMember({"true", "false"}))
        ->configurable()
        ->needs(clientIdOpt);
    sessionApp->add_option("--keep-alive", "Quality of service")
        ->group(sessionApp->get_formatter()->get_label("Persistent Options"))
        ->type_name("[uint8_t]")
        ->default_val(60)
        ->configurable();
    sessionApp->add_option("--will-topic", "MQTT will topic")
        ->group(sessionApp->get_formatter()->get_label("Persistent Options"))
        ->type_name("[string]")
        ->configurable();
    sessionApp->add_option("--will-message", "MQTT will message")
        ->group(sessionApp->get_formatter()->get_label("Persistent Options"))
        ->type_name("[string]")
        ->configurable();
    sessionApp->add_option("--will-qos", "MQTT will quality of service")
        ->group(sessionApp->get_formatter()->get_label("Persistent Options"))
        ->type_name("[uint8_t]")
        ->default_val(0)
        ->configurable();
    sessionApp->add_flag("--will-retain{true}", "MQTT will message retain")
        ->group(sessionApp->get_formatter()->get_label("Persistent Options"))
        ->default_str("false")
        ->type_name("[bool]")
        ->check(CLI::IsMember({"true", "false"}))
        ->configurable();
    sessionApp->add_option("--username", "MQTT username")
        ->group(sessionApp->get_formatter()->get_label("Persistent Options"))
        ->type_name("[string]")
        ->configurable();
    sessionApp->add_option("--password", "MQTT password")
        ->group(sessionApp->get_formatter()->get_label("Persistent Options"))
        ->type_name("[string]")
        ->configurable();
    subApp->add_option("--topic", "List of topics subscribing to")
        ->group(subApp->get_formatter()->get_label("Persistent Options"))
        ->default_str("#")
        ->type_name("[string list]")
        ->take_all()
        ->allow_extra_args()
        ->configurable();
    pubApp->needs(pubApp->add_option("--topic", "Topic publishing to")
                      ->group(pubApp->get_formatter()->get_label("Persistent Options"))
                      ->type_name("[string]")
                      ->required()
                      ->configurable());
    pubApp->needs(pubApp->add_option("--message", "Message to publish")
                      ->group(pubApp->get_formatter()->get_label("Persistent Options"))
                      ->type_name("[string]")
                      ->required()
                      ->configurable());
    pubApp->add_flag("--retain{true},-r{true}", "Retain message")
        ->group(pubApp->get_formatter()->get_label("Persistent Options"))
        ->default_str("false")
        ->type_name("[bool]")
        ->check(CLI::IsMember({"true", "false"}))
        ->configurable();
}
Referenced by createConfig(), and main().
createConfig() [2/2]
static void createConfig (net::config::ConfigInstance & config) static
Definition at line 224 of file mqtt.cpp.
{
    createConfig(config.addSection("session", "MQTT session behavior", "Connection"),
                 config.addSection("sub", "Configuration for application mqttsub", "Applications"),
                 config.addSection("pub", "Configuration for application mqttpub", "Applications"));
}
References createConfig().
main()
int main (int argc, char * argv[])
Definition at line 230 of file mqtt.cpp.
{
    core::SNodeC::init(argc, argv);
#if defined(LINK_WEBSOCKET_STATIC) || defined(LINK_SUBPROTOCOL_STATIC)
    web::websocket::client::SocketContextUpgradeFactory::link();
#endif
#ifdef LINK_SUBPROTOCOL_STATIC
    web::websocket::client::SubProtocolFactorySelector::link("mqtt", mqttClientSubProtocolFactory);
#endif
    utils::Config::app->get_formatter()->label("SUBCOMMAND", "APPLICATION | CONNECTION | INSTANCE");
    utils::Config::app->get_formatter()->label("SUBCOMMANDS", "APPLICATION | CONNECTION | INSTANCES");
    createConfig(utils::Config::addInstance("session", "MQTT session behavior", "Connection"),
                 utils::Config::addInstance("sub", "Configuration for application mqttsub", "Applications"),
                 utils::Config::addInstance("pub", "Configuration for application mqttpub", "Applications"));
    // Start of application
    net::in::stream::legacy::Client<mqtt::mqtt::SocketContextFactory>("in-mqtt", [](auto& config) {
        config.Remote::setPort(1883);
        config.setRetry();
        config.setRetryBase(1);
        config.setDisableNagleAlgorithm();
        createConfig(config);
    }).connect([](const auto& socketAddress, const core::socket::State& state) {
        reportState("in-mqtt", socketAddress, state);
    });
    net::in::stream::tls::Client<mqtt::mqtt::SocketContextFactory>("in-mqtts", [](auto& config) {
        config.Remote::setPort(1883);
        config.setRetry();
        config.setRetryBase(1);
        config.setDisableNagleAlgorithm();
        config.setDisabled();
        createConfig(config);
    }).connect([](const auto& socketAddress, const core::socket::State& state) {
        reportState("in-mqtts", socketAddress, state);
    });
    net::in6::stream::legacy::Client<mqtt::mqtt::SocketContextFactory>("in6-mqtt", [](auto& config) {
        config.Remote::setPort(1883);
        config.setRetry();
        config.setRetryBase(1);
        config.setDisableNagleAlgorithm();
        config.setDisabled();
        createConfig(config);
    }).connect([](const auto& socketAddress, const core::socket::State& state) {
        reportState("in6-mqtt", socketAddress, state);
    });
    net::in6::stream::tls::Client<mqtt::mqtt::SocketContextFactory>("in6-mqtts", [](auto& config) {
        config.Remote::setPort(1883);
        config.setRetry();
        config.setRetryBase(1);
        config.setDisableNagleAlgorithm();
        config.setDisabled();
        createConfig(config);
    }).connect([](const auto& socketAddress, const core::socket::State& state) {
        reportState("in6-mqtts", socketAddress, state);
    });
    net::un::stream::legacy::Client<mqtt::mqtt::SocketContextFactory>("un-mqtt", [](auto& config) {
        config.Remote::setSunPath("/var/mqttbroker-un-mqtt");
        config.setRetry();
        config.setRetryBase(1);
        config.setDisabled();
        createConfig(config);
    }).connect([](const auto& socketAddress, const core::socket::State& state) {
        reportState("un-mqtt", socketAddress, state);
    });
    net::un::stream::tls::Client<mqtt::mqtt::SocketContextFactory>("un-mqtts", [](auto& config) {
        config.Remote::setSunPath("/var/mqttbroker-un-mqtts");
        config.setRetry();
        config.setRetryBase(1);
        config.setDisabled();
        createConfig(config);
    }).connect([](const auto& socketAddress, const core::socket::State& state) {
        reportState("un-mqtts", socketAddress, state);
    });
    startClient<web::http::legacy::in::Client>("in-wsmqtt", [](auto& config) {
        config.Remote::setPort(8080);
        config.setRetry();
        config.setRetryBase(1);
        config.setDisableNagleAlgorithm();
        config.setDisabled();
        createConfig(config);
    });
    startClient<web::http::tls::in::Client>("in-wsmqtts", [](auto& config) {
        config.Remote::setPort(8088);
        config.setRetry();
        config.setRetryBase(1);
        config.setDisableNagleAlgorithm();
        config.setDisabled();
        createConfig(config);
    });
    startClient<web::http::legacy::in6::Client>("in6-wsmqtt", [](auto& config) {
        config.Remote::setPort(8080);
        config.setRetry();
        config.setRetryBase(1);
        config.setDisableNagleAlgorithm();
        config.setDisabled();
        createConfig(config);
    });
    startClient<web::http::tls::in6::Client>("in6-wsmqtts", [](auto& config) {
        config.Remote::setPort(8088);
        config.setReconnect();
        config.setRetry();
        config.setRetryBase(1);
        config.setDisableNagleAlgorithm();
        config.setDisabled();
        createConfig(config);
    });
    return core::SNodeC::start();
}
References createConfig(), and startClient().
reportState()
static void reportState (const std::string & instanceName, const core::socket::SocketAddress & socketAddress, const core::socket::State & state) static
Definition at line 83 of file mqtt.cpp.
{
    switch (state) {
        case core::socket::State::OK:
            VLOG(1) << instanceName << ": connected to '" << socketAddress.toString() << "'";
            break;
        case core::socket::State::DISABLED:
            VLOG(1) << instanceName << ": disabled";
            break;
        case core::socket::State::ERROR:
            VLOG(1) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
            break;
        case core::socket::State::FATAL:
            VLOG(1) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
            break;
    }
}
startClient()
template<typename HttpClient > void startClient (const std::string & name, const std::function< void(typename HttpClient::Config &)> & configurator = nullptr)
Definition at line 101 of file mqtt.cpp.
{
    using SocketAddress = typename HttpClient::SocketAddress;
    const HttpClient httpClient(
        name,
        [](const std::shared_ptr<web::http::client::Request>& req) {
            const std::string connectionName = req->getSocketContext()->getSocketConnection()->getConnectionName();
            req->set("Sec-WebSocket-Protocol", "mqtt");
            req->upgrade(
                "/ws",
                "websocket",
                [connectionName](const std::shared_ptr<web::http::client::Request>& req, bool success) {
                    VLOG(1) << connectionName << ": HTTP Upgrade (http -> " << req->header("upgrade") << "|"
                            << req->header("Sec-WebSocket-Protocol") << ") start " << (success ? "success" : "failed");
                },
                []([[maybe_unused]] const std::shared_ptr<web::http::client::Request>& req,
                   [[maybe_unused]] const std::shared_ptr<web::http::client::Response>& res,
                   [[maybe_unused]] bool success) {
                });
        },
        []([[maybe_unused]] const std::shared_ptr<web::http::client::Request>& req) {
            VLOG(1) << "Session ended";
        });
    configurator(httpClient.getConfig());
    httpClient.connect([name](const SocketAddress& socketAddress, const core::socket::State& state) {
        reportState(name, socketAddress, state);
    });
}
Referenced by main().