MQTTSuite: anonymous_namespace{SocketContextFactory.cpp} Namespace Reference
anonymous_namespace{SocketContextFactory.cpp} Namespace Reference
Classes
struct StorageOptions
Functions
StorageOptions getStorageOptions (const mqtt::mqttstore::lib::ConfigStorage *configStorage)
Function Documentation
getStorageOptions()
StorageOptions anonymous_namespace{SocketContextFactory.cpp}::getStorageOptions (const mqtt::mqttstore::lib::ConfigStorage * configStorage)
Definition at line 39 of file SocketContextFactory.cpp.
{
        if (configStorage == nullptr) {
            return {};
        }
        return {.rawTable = configStorage->getRawTable(),
                .autoCreateRawTable = configStorage->getAutoCreateRawTable(),
                .projectionFile = configStorage->getProjectionFile()};
    }
References anonymous_namespace{SocketContextFactory.cpp}::StorageOptions::autoCreateRawTable, mqtt::mqttstore::lib::ConfigStorage::getAutoCreateRawTable(), mqtt::mqttstore::lib::ConfigStorage::getProjectionFile(), mqtt::mqttstore::lib::ConfigStorage::getRawTable(), anonymous_namespace{SocketContextFactory.cpp}::StorageOptions::projectionFile, and anonymous_namespace{SocketContextFactory.cpp}::StorageOptions::rawTable.
Referenced by mqtt::mqttstore::SocketContextFactory::create().