var namespaceinja =
[
    [ "string_view", "namespaceinja_1_1string__view.html", [
      [ "slice", "namespaceinja_1_1string__view.html#a898871016595d8f34d1b4ea55b3e8684", null ],
      [ "split", "namespaceinja_1_1string__view.html#a558eea0fb71692e125bcc9e2aab9df71", null ],
      [ "starts_with", "namespaceinja_1_1string__view.html#a78e9922c080101c22e54419f7caa83d8", null ]
    ] ],
    [ "FunctionStorage", "classinja_1_1FunctionStorage.html", "classinja_1_1FunctionStorage" ],
    [ "SourceLocation", "structinja_1_1SourceLocation.html", "structinja_1_1SourceLocation" ],
    [ "InjaError", "structinja_1_1InjaError.html", "structinja_1_1InjaError" ],
    [ "ParserError", "structinja_1_1ParserError.html", "structinja_1_1ParserError" ],
    [ "RenderError", "structinja_1_1RenderError.html", "structinja_1_1RenderError" ],
    [ "FileError", "structinja_1_1FileError.html", "structinja_1_1FileError" ],
    [ "DataError", "structinja_1_1DataError.html", "structinja_1_1DataError" ],
    [ "NodeVisitor", "classinja_1_1NodeVisitor.html", "classinja_1_1NodeVisitor" ],
    [ "AstNode", "classinja_1_1AstNode.html", "classinja_1_1AstNode" ],
    [ "BlockNode", "classinja_1_1BlockNode.html", "classinja_1_1BlockNode" ],
    [ "TextNode", "classinja_1_1TextNode.html", "classinja_1_1TextNode" ],
    [ "ExpressionNode", "classinja_1_1ExpressionNode.html", "classinja_1_1ExpressionNode" ],
    [ "LiteralNode", "classinja_1_1LiteralNode.html", "classinja_1_1LiteralNode" ],
    [ "DataNode", "classinja_1_1DataNode.html", "classinja_1_1DataNode" ],
    [ "FunctionNode", "classinja_1_1FunctionNode.html", "classinja_1_1FunctionNode" ],
    [ "ExpressionListNode", "classinja_1_1ExpressionListNode.html", "classinja_1_1ExpressionListNode" ],
    [ "StatementNode", "classinja_1_1StatementNode.html", "classinja_1_1StatementNode" ],
    [ "ForStatementNode", "classinja_1_1ForStatementNode.html", "classinja_1_1ForStatementNode" ],
    [ "ForArrayStatementNode", "classinja_1_1ForArrayStatementNode.html", "classinja_1_1ForArrayStatementNode" ],
    [ "ForObjectStatementNode", "classinja_1_1ForObjectStatementNode.html", "classinja_1_1ForObjectStatementNode" ],
    [ "IfStatementNode", "classinja_1_1IfStatementNode.html", "classinja_1_1IfStatementNode" ],
    [ "IncludeStatementNode", "classinja_1_1IncludeStatementNode.html", "classinja_1_1IncludeStatementNode" ],
    [ "ExtendsStatementNode", "classinja_1_1ExtendsStatementNode.html", "classinja_1_1ExtendsStatementNode" ],
    [ "BlockStatementNode", "classinja_1_1BlockStatementNode.html", "classinja_1_1BlockStatementNode" ],
    [ "SetStatementNode", "classinja_1_1SetStatementNode.html", "classinja_1_1SetStatementNode" ],
    [ "StatisticsVisitor", "classinja_1_1StatisticsVisitor.html", "classinja_1_1StatisticsVisitor" ],
    [ "Template", "structinja_1_1Template.html", "structinja_1_1Template" ],
    [ "LexerConfig", "structinja_1_1LexerConfig.html", "structinja_1_1LexerConfig" ],
    [ "ParserConfig", "structinja_1_1ParserConfig.html", "structinja_1_1ParserConfig" ],
    [ "RenderConfig", "structinja_1_1RenderConfig.html", "structinja_1_1RenderConfig" ],
    [ "Token", "structinja_1_1Token.html", "structinja_1_1Token" ],
    [ "Lexer", "classinja_1_1Lexer.html", "classinja_1_1Lexer" ],
    [ "Parser", "classinja_1_1Parser.html", "classinja_1_1Parser" ],
    [ "Renderer", "classinja_1_1Renderer.html", "classinja_1_1Renderer" ],
    [ "Environment", "classinja_1_1Environment.html", "classinja_1_1Environment" ],
    [ "Arguments", "namespaceinja.html#a012d663296619810e0a7a2d1f0986357", null ],
    [ "CallbackFunction", "namespaceinja.html#a9b3c1dbbfa0bcf63424d53791d539e59", null ],
    [ "json", "namespaceinja.html#aea17f29b0aca3b98657af767e69f2473", null ],
    [ "TemplateStorage", "namespaceinja.html#a931bd54de1093a20a02845e99266036e", null ],
    [ "VoidCallbackFunction", "namespaceinja.html#a4f2a4e263d4314dc548eadf19ea28e28", null ],
    [ "get_source_location", "namespaceinja.html#ab7c8c54f2caeb72095cd78a7ff7b6c37", null ],
    [ "render", "namespaceinja.html#a539106781b52cc6117fc132f927a9dec", null ],
    [ "render_to", "namespaceinja.html#a996f16f78b37d05e19cf44ac74d83e7e", null ],
    [ "replace_substring", "namespaceinja.html#a0d679f660536e174d17e3299bec96bd4", null ]
];