MQTTSuite: mqtt::mqttbroker::lib Namespace Reference
mqtt::mqttbroker::lib Namespace Reference
Classes
class Mqtt
class MqttModel
Functions
static std::string windowId (const std::string &clientId)
static std::string href (const std::string &text, const std::string &url, const std::string &windowId, uint16_t width, uint16_t height)
Function Documentation
href()
std::string mqtt::mqttbroker::lib::href (const std::string & text, const std::string & url, const std::string & windowId, uint16_t width, uint16_t height) static
Definition at line 96 of file MqttModel.cpp.
{
        return "<a href=\"#\" onClick=\""
               "let key = '" +
               windowId +
               "'; "
               "if (!localStorage.getItem(key)) "
               "  localStorage.setItem(key, key + '-' + Math.random().toString(36).substr(2, 6)); "
               "let uniqueId = localStorage.getItem(key); "
               "if (!window._openWindows) window._openWindows = {}; "
               "if (!window._openWindows[uniqueId] || window._openWindows[uniqueId].closed) { "
               "  window._openWindows[uniqueId] = window.open('" +
               url + "', uniqueId, 'width=" + std::to_string(width) + ", height=" + std::to_string(height) +
               ",location=no, menubar=no, status=no, toolbar=no'); "
               "} else { "
               "  window._openWindows[uniqueId].focus(); "
               "} return false;\" "
               "style=\"color:inherit;\">" +
               text + "</a>";
    }
Referenced by mqtt::mqttbroker::lib::MqttModel::addClient(), and mqtt::mqttbroker::lib::MqttModel::addEventReceiver().
windowId()
std::string mqtt::mqttbroker::lib::windowId (const std::string & clientId) static
Definition at line 82 of file MqttModel.cpp.
{
        std::ostringstream windowId("window");
        for (char ch : clientId) {
            if (std::isalnum(static_cast<unsigned char>(ch))) {
                windowId << ch;
            } else {
                windowId << std::hex << std::uppercase << std::setw(2) << std::setfill('0')
                         << static_cast<int>(static_cast<unsigned char>(ch));
            }
        }
        return windowId.str();
    }
Referenced by mqtt::mqttbroker::lib::MqttModel::addClient(), and mqtt::mqttbroker::lib::MqttModel::addEventReceiver().