MQTTSuite: nlohmann::json_schema Namespace Reference
nlohmann::json_schema Namespace Reference
Classes
class basic_error_handler
class error_handler
class json_validator
class root_schema
Typedefs
typedef std::function< void(const json_uri &, json &)> schema_loader
typedef std::function< void(const std::string &, const std::string &)> format_checker
typedef std::function< void(const std::string &, const std::string &, const json &)> content_checker
Functions
void default_string_format_check (const std::string &format, const std::string &value)
Variables
json draft7_schema_builtin
Typedef Documentation
content_checker
typedef std::function<void(const std::string & , const std::string & , const json &)> nlohmann::json_schema::content_checker
Definition at line 135 of file json-schema.hpp.
format_checker
typedef std::function<void(const std::string & , const std::string &)> nlohmann::json_schema::format_checker
Definition at line 134 of file json-schema.hpp.
schema_loader
typedef std::function<void(const json_uri & , json &)> nlohmann::json_schema::schema_loader
Definition at line 133 of file json-schema.hpp.
Function Documentation
default_string_format_check()
void nlohmann::json_schema::default_string_format_check (const std::string & format, const std::string & value)
Checks validity for built-ins by converting the definitions given as ABNF in the linked RFC from
See also
https://json-schema.org/understanding-json-schema/reference/string.html#built-in-formats into regular expressions using
https://www.msweet.org/abnf/ and some manual editing.
https://json-schema.org/latest/json-schema-validation.html
Checks validity of JSON schema built-in string format specifiers like 'date-time', 'ipv4', ...
Definition at line 353 of file string-format-check.cpp.
{
    if (format == "date-time") {
        rfc3339_date_time_check(value);
    } else if (format == "date") {
        rfc3339_date_check(value);
    } else if (format == "time") {
        rfc3339_time_check(value);
    } else if (format == "uri") {
        rfc3986_uri_check(value);
    } else if (format == "email") {
        if (!is_ascii(value)) {
            throw std::invalid_argument(value + " contains non-ASCII values, not RFC 5321 compliant.");
        }
        if (!is_address(&*value.begin(), &*value.end())) {
            throw std::invalid_argument(value + " is not a valid email according to RFC 5321.");
        }
    } else if (format == "idn-email") {
        if (!is_address(&*value.begin(), &*value.end())) {
            throw std::invalid_argument(value + " is not a valid idn-email according to RFC 6531.");
        }
    } else if (format == "hostname") {
        static const REGEX_NAMESPACE::regex hostRegex{hostname};
        if (!REGEX_NAMESPACE::regex_match(value, hostRegex)) {
            throw std::invalid_argument(value + " is not a valid hostname according to RFC 3986 Appendix A.");
        }
    } else if (format == "ipv4") {
        const static REGEX_NAMESPACE::regex ipv4Regex{"^" + ipv4Address + "$"};
        if (!REGEX_NAMESPACE::regex_match(value, ipv4Regex)) {
            throw std::invalid_argument(value + " is not an IPv4 string according to RFC 2673.");
        }
    } else if (format == "ipv6") {
        static const REGEX_NAMESPACE::regex ipv6Regex{ipv6Address};
        if (!REGEX_NAMESPACE::regex_match(value, ipv6Regex)) {
            throw std::invalid_argument(value + " is not an IPv6 string according to RFC 5954.");
        }
    } else if (format == "uuid") {
        static const REGEX_NAMESPACE::regex uuidRegex{uuid};
        if (!REGEX_NAMESPACE::regex_match(value, uuidRegex)) {
            throw std::invalid_argument(value + " is not an uuid string according to RFC 4122.");
        }
    } else if (format == "regex") {
        try {
            REGEX_NAMESPACE::regex re(value, std::regex::ECMAScript);
        } catch (std::exception &exception) {
            throw exception;
        }
    } else {
        /* yet unsupported JSON schema draft 7 built-ins */
        static const std::vector<std::string> jsonSchemaStringFormatBuiltIns{
            "date-time", "time", "date", "email", "idn-email", "hostname", "idn-hostname", "ipv4", "ipv6", "uri",
            "uri-reference", "iri", "iri-reference", "uri-template", "json-pointer", "relative-json-pointer", "regex"};
        if (std::find(jsonSchemaStringFormatBuiltIns.begin(), jsonSchemaStringFormatBuiltIns.end(), format) != jsonSchemaStringFormatBuiltIns.end()) {
            throw std::logic_error("JSON schema string format built-in " + format + " not yet supported. " +
                                   "Please open an issue or use a custom format checker.");
        }
        throw std::logic_error("Don't know how to validate " + format);
    }
}
References anonymous_namespace{string-format-check.cpp}::hostname, anonymous_namespace{string-format-check.cpp}::ipv4Address, anonymous_namespace{string-format-check.cpp}::ipv6Address, is_address(), anonymous_namespace{string-format-check.cpp}::is_ascii(), anonymous_namespace{string-format-check.cpp}::rfc3339_date_check(), anonymous_namespace{string-format-check.cpp}::rfc3339_date_time_check(), anonymous_namespace{string-format-check.cpp}::rfc3339_time_check(), anonymous_namespace{string-format-check.cpp}::rfc3986_uri_check(), and anonymous_namespace{string-format-check.cpp}::uuid.
Referenced by main(), main(), and testStringFormat().
Variable Documentation
draft7_schema_builtin
json nlohmann::json_schema::draft7_schema_builtin extern
Referenced by loader().