MQTTSuite: mqtt::mqttstore::lib::anonymous_namespace{StoragePlan.cpp} Namespace Reference
mqtt::mqttstore::lib::anonymous_namespace{StoragePlan.cpp} Namespace Reference
Classes
class ProjectionValidationErrorHandler
Functions
std::string jsonSummary (const nlohmann::json &json)
void validateProjectionConfiguration (const nlohmann::json &json)
std::vector< std::string > splitTopic (const std::string &topic)
Function Documentation
jsonSummary()
std::string mqtt::mqttstore::lib::anonymous_namespace{StoragePlan.cpp}::jsonSummary (const nlohmann::json & json) nodiscard
Definition at line 37 of file StoragePlan.cpp.
{
            std::string summary = json.dump();
            constexpr std::size_t maxSummaryLength = 160;
            if (summary.size() > maxSummaryLength) {
                summary.resize(maxSummaryLength);
                summary += "...";
            }
            return summary;
        }
Referenced by mqtt::mqttstore::lib::anonymous_namespace{StoragePlan.cpp}::ProjectionValidationErrorHandler::error().
splitTopic()
std::vector< std::string > mqtt::mqttstore::lib::anonymous_namespace{StoragePlan.cpp}::splitTopic (const std::string & topic) nodiscard
Definition at line 89 of file StoragePlan.cpp.
{
            std::vector<std::string> result;
            std::stringstream topicStream(topic);
            for (std::string level; std::getline(topicStream, level, '/');) {
                result.push_back(level);
            }
            if (!topic.empty() && topic.back() == '/') {
                result.emplace_back();
            }
            return result;
        }
validateProjectionConfiguration()
void mqtt::mqttstore::lib::anonymous_namespace{StoragePlan.cpp}::validateProjectionConfiguration (const nlohmann::json & json)
Definition at line 71 of file StoragePlan.cpp.
{
            try {
                const nlohmann::json projectionJsonSchema = nlohmann::json::parse(projectionJsonSchemaString);
                const nlohmann::json_schema::json_validator validator(
                    projectionJsonSchema, nullptr, nlohmann::json_schema::default_string_format_check);
                ProjectionValidationErrorHandler errorHandler;
                static_cast<void>(validator.validate(json, errorHandler));
                if (errorHandler) {
                    throw std::runtime_error("Validating mqttstore projection file failed:\n" + errorHandler.message());
                }
            } catch (const std::runtime_error&) {
                throw;
            } catch (const std::exception& exception) {
                throw std::runtime_error("Validating mqttstore projection file failed: " + std::string(exception.what()));
            }
        }
References nlohmann::json_schema::default_string_format_check(), and mqtt::mqttstore::lib::anonymous_namespace{StoragePlan.cpp}::ProjectionValidationErrorHandler::message().
Referenced by mqtt::mqttstore::lib::StoragePlan::fromJson().