MQTTSuite: anonymous_namespace{issue-105-verbose-combination-errors.cpp} Namespace Reference
anonymous_namespace{issue-105-verbose-combination-errors.cpp} Namespace Reference
Classes
class MyErrorHandler
Functions
auto generateSchema (const std::string &first_combination, const std::string &second_combination) -> nlohmann::json
auto operator<< (std::string first, const std::string &second) -> std::string
auto rootError (const std::string &combination_type, std::size_t number_of_subschemas) -> std::string
auto combinationError (const std::string &combination_type, std::size_t test_case_number) -> std::string
auto validate (const nlohmann::json &schema, const nlohmann::json &instance, nlohmann::json_schema::error_handler *error_handler=nullptr) -> void
auto simpleTest (const std::string &first_combination, const std::string &second_combination) -> void
auto verboseTest (const std::string &first_combination, const std::string &second_combination) -> void
Variables
int g_error_count = 0
const std::string g_schema_template
Function Documentation
combinationError()
auto anonymous_namespace{issue-105-verbose-combination-errors.cpp}::combinationError (const std::string & combination_type, std::size_t test_case_number) -> std::string
Definition at line 152 of file issue-105-verbose-combination-errors.cpp.
{
    return "[combination: " + combination_type + " / case#" + std::to_string(test_case_number) + "]";
}
Referenced by verboseTest().
generateSchema()
auto anonymous_namespace{issue-105-verbose-combination-errors.cpp}::generateSchema (const std::string & first_combination, const std::string & second_combination) -> nlohmann::json
Definition at line 99 of file issue-105-verbose-combination-errors.cpp.
{
    static const std::regex first_replace_re{"%COMBINATION_FIRST_LEVEL%"};
    static const std::regex second_replace_re{"%COMBINATION_SECOND_LEVEL%"};
    std::string intermediate = std::regex_replace(g_schema_template, first_replace_re, first_combination);
    return nlohmann::json::parse(std::regex_replace(intermediate, second_replace_re, second_combination));
}
References g_schema_template.
Referenced by simpleTest(), and verboseTest().
operator<<()
auto anonymous_namespace{issue-105-verbose-combination-errors.cpp}::operator<< (std::string first, const std::string & second) -> std::string
Definition at line 140 of file issue-105-verbose-combination-errors.cpp.
{
    first += ".*";
    first += second;
    return first;
}
Referenced by verboseTest().
rootError()
auto anonymous_namespace{issue-105-verbose-combination-errors.cpp}::rootError (const std::string & combination_type, std::size_t number_of_subschemas) -> std::string
Definition at line 147 of file issue-105-verbose-combination-errors.cpp.
{
    return "no subschema has succeeded, but one of them is required to validate. Type: " + combination_type + ", number of failed subschemas: " + std::to_string(number_of_subschemas);
}
Referenced by simpleTest(), and verboseTest().
simpleTest()
auto anonymous_namespace{issue-105-verbose-combination-errors.cpp}::simpleTest (const std::string & first_combination, const std::string & second_combination) -> void
Definition at line 175 of file issue-105-verbose-combination-errors.cpp.
{
    const nlohmann::json schema = generateSchema(first_combination, second_combination);
    EXPECT_THROW_WITH_MESSAGE(validate(schema, nlohmann::json{{"first", {{"second", 1}}}}), rootError(first_combination, 3));
    if (second_combination == "oneOf") {
        EXPECT_THROW_WITH_MESSAGE(validate(schema, nlohmann::json{{"first", {{"second", 8}}}}), rootError(first_combination, 3));
    }
    EXPECT_THROW_WITH_MESSAGE(validate(schema, nlohmann::json{{"first", 10}}), rootError(first_combination, 3));
    EXPECT_THROW_WITH_MESSAGE(validate(schema, nlohmann::json{{"first", "short"}}), rootError(first_combination, 3));
}
References generateSchema(), rootError(), and validate().
Referenced by main().
validate()
auto anonymous_namespace{issue-105-verbose-combination-errors.cpp}::validate (const nlohmann::json & schema, const nlohmann::json & instance, nlohmann::json_schema::error_handler * error_handler = nullptr) -> void
Definition at line 160 of file issue-105-verbose-combination-errors.cpp.
{
    nlohmann::json_schema::json_validator validator;
    validator.set_root_schema(schema);
    if (error_handler) {
        validator.validate(instance, *error_handler);
    } else {
        validator.validate(instance);
    }
}
References nlohmann::json_schema::json_validator::set_root_schema(), nlohmann::json_schema::json_validator::validate(), and nlohmann::json_schema::json_validator::validate().
Referenced by simpleTest(), and verboseTest().
verboseTest()
auto anonymous_namespace{issue-105-verbose-combination-errors.cpp}::verboseTest (const std::string & first_combination, const std::string & second_combination) -> void
Definition at line 186 of file issue-105-verbose-combination-errors.cpp.
{
    const nlohmann::json schema = generateSchema(first_combination, second_combination);
    {
        MyErrorHandler error_handler;
        validate(schema, nlohmann::json{{"first", {{"second", 1}}}}, &error_handler);
        const MyErrorHandler::ErrorEntryList &error_list = error_handler.getErrors();
        EXPECT_EQ(error_list.size(), 6);
        EXPECT_EQ(error_list[0].ptr, nlohmann::json::json_pointer{"/first"});
        EXPECT_MATCH(error_list[0].message, rootError(first_combination, 3));
        EXPECT_EQ(error_list[1].ptr, nlohmann::json::json_pointer{"/first/second"});
        EXPECT_MATCH(error_list[1].message, combinationError(first_combination, 0) << rootError(second_combination, 2));
        EXPECT_EQ(error_list[2].ptr, nlohmann::json::json_pointer{"/first/second"});
        EXPECT_MATCH(error_list[2].message, combinationError(first_combination, 0) << combinationError(second_combination, 0) << "instance is below minimum of 5");
        EXPECT_EQ(error_list[3].ptr, nlohmann::json::json_pointer{"/first/second"});
        EXPECT_MATCH(error_list[3].message, combinationError(first_combination, 0) << combinationError(second_combination, 1) << "instance is not a multiple of 2.0");
        EXPECT_EQ(error_list[4].ptr, nlohmann::json::json_pointer{"/first"});
        EXPECT_MATCH(error_list[4].message, combinationError(first_combination, 1) << "unexpected instance type");
        EXPECT_EQ(error_list[5].ptr, nlohmann::json::json_pointer{"/first"});
        EXPECT_MATCH(error_list[5].message, combinationError(first_combination, 2) << "unexpected instance type");
    }
    {
        MyErrorHandler error_handler;
        validate(schema, nlohmann::json{{"first", {{"second", "not-an-integer"}}}}, &error_handler);
        const MyErrorHandler::ErrorEntryList &error_list = error_handler.getErrors();
        EXPECT_EQ(error_list.size(), 6);
        EXPECT_EQ(error_list[0].ptr, nlohmann::json::json_pointer{"/first"});
        EXPECT_MATCH(error_list[0].message, rootError(first_combination, 3));
        EXPECT_EQ(error_list[1].ptr, nlohmann::json::json_pointer{"/first/second"});
        EXPECT_MATCH(error_list[1].message, combinationError(first_combination, 0) << rootError(second_combination, 2));
        EXPECT_EQ(error_list[2].ptr, nlohmann::json::json_pointer{"/first/second"});
        EXPECT_MATCH(error_list[2].message, combinationError(first_combination, 0) << combinationError(second_combination, 0) << "unexpected instance type");
        EXPECT_EQ(error_list[3].ptr, nlohmann::json::json_pointer{"/first/second"});
        EXPECT_MATCH(error_list[3].message, combinationError(first_combination, 0) << combinationError(second_combination, 1) << "unexpected instance type");
        EXPECT_EQ(error_list[4].ptr, nlohmann::json::json_pointer{"/first"});
        EXPECT_MATCH(error_list[4].message, combinationError(first_combination, 1) << "unexpected instance type");
        EXPECT_EQ(error_list[5].ptr, nlohmann::json::json_pointer{"/first"});
        EXPECT_MATCH(error_list[5].message, combinationError(first_combination, 2) << "unexpected instance type");
    }
    if (second_combination == "oneOf") {
        MyErrorHandler error_handler;
        validate(schema, nlohmann::json{{"first", {{"second", 8}}}}, &error_handler);
        const MyErrorHandler::ErrorEntryList &error_list = error_handler.getErrors();
        EXPECT_EQ(error_list.size(), 4);
        EXPECT_EQ(error_list[0].ptr, nlohmann::json::json_pointer{"/first"});
        EXPECT_MATCH(error_list[0].message, rootError(first_combination, 3));
        EXPECT_EQ(error_list[1].ptr, nlohmann::json::json_pointer{"/first/second"});
        EXPECT_MATCH(error_list[1].message, combinationError(first_combination, 0) << "more than one subschema has succeeded, but exactly one of them is required to validate");
        EXPECT_EQ(error_list[2].ptr, nlohmann::json::json_pointer{"/first"});
        EXPECT_MATCH(error_list[2].message, combinationError(first_combination, 1) << "unexpected instance type");
        EXPECT_EQ(error_list[3].ptr, nlohmann::json::json_pointer{"/first"});
        EXPECT_MATCH(error_list[3].message, combinationError(first_combination, 2) << "unexpected instance type");
    }
    {
        MyErrorHandler error_handler;
        validate(schema, nlohmann::json{{"first", 10}}, &error_handler);
        const MyErrorHandler::ErrorEntryList &error_list = error_handler.getErrors();
        EXPECT_EQ(error_list.size(), 4);
        EXPECT_EQ(error_list[0].ptr, nlohmann::json::json_pointer{"/first"});
        EXPECT_MATCH(error_list[0].message, rootError(first_combination, 3));
        EXPECT_EQ(error_list[1].ptr, nlohmann::json::json_pointer{"/first"});
        EXPECT_MATCH(error_list[1].message, combinationError(first_combination, 0) << "unexpected instance type");
        EXPECT_EQ(error_list[2].ptr, nlohmann::json::json_pointer{"/first"});
        EXPECT_MATCH(error_list[2].message, combinationError(first_combination, 1) << "instance is below minimum of 20");
        EXPECT_EQ(error_list[3].ptr, nlohmann::json::json_pointer{"/first"});
        EXPECT_MATCH(error_list[3].message, combinationError(first_combination, 2) << "unexpected instance type");
    }
    {
        MyErrorHandler error_handler;
        validate(schema, nlohmann::json{{"first", "short"}}, &error_handler);
        const MyErrorHandler::ErrorEntryList &error_list = error_handler.getErrors();
        EXPECT_EQ(error_list.size(), 4);
        EXPECT_EQ(error_list[0].ptr, nlohmann::json::json_pointer{"/first"});
        EXPECT_MATCH(error_list[0].message, rootError(first_combination, 3));
        EXPECT_EQ(error_list[1].ptr, nlohmann::json::json_pointer{"/first"});
        EXPECT_MATCH(error_list[1].message, combinationError(first_combination, 0) << "unexpected instance type");
        EXPECT_EQ(error_list[2].ptr, nlohmann::json::json_pointer{"/first"});
        EXPECT_MATCH(error_list[2].message, combinationError(first_combination, 1) << "unexpected instance type");
        EXPECT_EQ(error_list[3].ptr, nlohmann::json::json_pointer{"/first"});
        EXPECT_MATCH(error_list[3].message, combinationError(first_combination, 2) << "instance is too short as per minLength:10");
    }
}
References combinationError(), generateSchema(), anonymous_namespace{issue-105-verbose-combination-errors.cpp}::MyErrorHandler::getErrors(), anonymous_namespace{issue-105-verbose-combination-errors.cpp}::MyErrorHandler::ErrorEntry::message, operator<<(), anonymous_namespace{issue-105-verbose-combination-errors.cpp}::MyErrorHandler::ErrorEntry::ptr, rootError(), and validate().
Referenced by main().
Variable Documentation
g_error_count
int anonymous_namespace{issue-105-verbose-combination-errors.cpp}::g_error_count = 0
Definition at line 57 of file issue-105-verbose-combination-errors.cpp.
Referenced by main().
g_schema_template
const std::string anonymous_namespace{issue-105-verbose-combination-errors.cpp}::g_schema_template
Definition at line 62 of file issue-105-verbose-combination-errors.cpp.
Referenced by generateSchema().