MQTTSuite: inja::string_view Namespace Reference
inja::string_view Namespace Reference
Functions
std::string_view slice (std::string_view view, size_t start, size_t end)
std::pair< std::string_view, std::string_view > split (std::string_view view, char Separator)
bool starts_with (std::string_view view, std::string_view prefix)
Function Documentation
slice()
std::string_view inja::string_view::slice (std::string_view view, size_t start, size_t end) inline
Definition at line 311 of file inja.hpp.
{
            start = std::min(start, view.size());
            end = std::min(std::max(start, end), view.size());
            return view.substr(start, end - start);
        }
Referenced by inja::get_source_location(), inja::Lexer::make_token(), inja::Lexer::scan(), and split().
split()
std::pair< std::string_view, std::string_view > inja::string_view::split (std::string_view view, char Separator) inline
Definition at line 317 of file inja.hpp.
{
            size_t idx = view.find(Separator);
            if (idx == std::string_view::npos) {
                return std::make_pair(view, std::string_view());
            }
            return std::make_pair(slice(view, 0, idx), slice(view, idx + 1, std::string_view::npos));
        }
References slice().
Referenced by inja::DataNode::convert_dot_to_ptr().
starts_with()
bool inja::string_view::starts_with (std::string_view view, std::string_view prefix) inline
Definition at line 325 of file inja.hpp.
{
            return (view.size() >= prefix.size() && view.compare(0, prefix.size(), prefix) == 0);
        }
Referenced by inja::Lexer::scan(), inja::Lexer::scan_body(), and inja::Lexer::start().