MQTTSuite: lib/json-schema-validator/example/readme.cpp File Reference
readme.cpp File Reference
#include <iomanip>
#include <iostream>
#include <nlohmann/json-schema.hpp>
Functions
int main ()
Variables
static json person_schema
static json bad_person = {{"age", 42}}
static json good_person = {{"name", "Albert"}, {"age", 42}, {"address", {{"street", "Main Street"}}}}
static json good_defaulted_person = {{"name", "Knut"}, {"age", 69}, {"address", {}}}
Function Documentation
main()
int main (void)
Definition at line 49 of file readme.cpp.
{
    /* json-parse the schema */
    json_validator validator; // create validator
    try {
        validator.set_root_schema(person_schema); // insert root-schema
    } catch (const std::exception &e) {
        std::cerr << "Validation of schema failed, here is why: " << e.what() << "\n";
        return EXIT_FAILURE;
    }
    /* json-parse the people - API of 1.0.0, default throwing error handler */
    for (auto &person : {bad_person, good_person, good_defaulted_person}) {
        std::cout << "About to validate this person:\n"
                  << std::setw(2) << person << std::endl;
        try {
            auto defaultPatch = validator.validate(person); // validate the document - uses the default throwing error-handler
            std::cout << "Validation succeeded\n";
            std::cout << "Patch with defaults: " << defaultPatch.dump(2) << std::endl;
        } catch (const std::exception &e) {
            std::cerr << "Validation failed, here is why: " << e.what() << "\n";
        }
    }
    /* json-parse the people - with custom error handler */
    class custom_error_handler : public nlohmann::json_schema::basic_error_handler
    {
        void error(const nlohmann::json::json_pointer &ptr, const json &instance, const std::string &message) override
        {
            nlohmann::json_schema::basic_error_handler::error(ptr, instance, message);
            std::cerr << "ERROR: '" << ptr << "' - '" << instance << "': " << message << "\n";
        }
    };
    for (auto &person : {bad_person, good_person}) {
        std::cout << "About to validate this person:\n"
                  << std::setw(2) << person << std::endl;
        custom_error_handler err;
        validator.validate(person, err); // validate the document
        if (err)
            std::cerr << "Validation failed\n";
        else
            std::cout << "Validation succeeded\n";
    }
    return EXIT_SUCCESS;
}
References bad_person, nlohmann::json_schema::basic_error_handler::error(), good_defaulted_person, good_person, person_schema, nlohmann::json_schema::json_validator::set_root_schema(), nlohmann::json_schema::json_validator::validate(), and nlohmann::json_schema::json_validator::validate().
Variable Documentation
bad_person
static json bad_person = {{"age", 42}} static
Definition at line 45 of file readme.cpp.
{{"age", 42}};
Referenced by main().
good_defaulted_person
static json good_defaulted_person = {{"name", "Knut"}, {"age", 69}, {"address", {}}} static
Definition at line 47 of file readme.cpp.
{{"name", "Knut"}, {"age", 69}, {"address", {}}};
Referenced by main().
good_person
static json good_person = {{"name", "Albert"}, {"age", 42}, {"address", {{"street", "Main Street"}}}} static
Definition at line 46 of file readme.cpp.
{{"name", "Albert"}, {"age", 42}, {"address", {{"street", "Main Street"}}}};
Referenced by main().
person_schema
static json person_schema static
Definition at line 10 of file readme.cpp.
Referenced by main().