SNode.C: inja::Template Struct Reference
inja::Template Struct Reference
The main inja Template.
#include <inja.hpp>
Public Member Functions
Template ()
Template (const std::string &content)
unsigned int count_variables ()
Return number of variables (total number, not distinct ones) in the template.
Public Attributes
BlockNode root
std::string content
std::map< std::string, std::shared_ptr< BlockStatementNode > > block_storage
Detailed Description
The main inja Template.
Definition at line 886 of file inja.hpp.
Constructor & Destructor Documentation
Template() [1/2]
inja::Template::Template () inline explicit
Definition at line 891 of file inja.hpp.
{
        }
Template() [2/2]
inja::Template::Template (const std::string & content) inline explicit
Definition at line 893 of file inja.hpp.
            : content(content) {
        }
References Template().
Referenced by Template().
Member Function Documentation
count_variables()
unsigned int inja::Template::count_variables () inline
Return number of variables (total number, not distinct ones) in the template.
Definition at line 898 of file inja.hpp.
{
            auto statistic_visitor = StatisticsVisitor();
            root.accept(statistic_visitor);
            return statistic_visitor.variable_counter;
        }
References inja::StatisticsVisitor::StatisticsVisitor(), and inja::StatisticsVisitor::variable_counter.
Member Data Documentation
block_storage
std::map<std::string, std::shared_ptr<BlockStatementNode> > inja::Template::block_storage
Definition at line 889 of file inja.hpp.
content
std::string inja::Template::content
Definition at line 888 of file inja.hpp.
root
BlockNode inja::Template::root
Definition at line 887 of file inja.hpp.
The documentation for this struct was generated from the following file:
lib/inja.hpp