MQTTSuite: inja::InjaError Struct Reference
inja::InjaError Struct Reference
#include <inja.hpp>
Public Member Functions
InjaError (const std::string &type, const std::string &message)
InjaError (const std::string &type, const std::string &message, SourceLocation location)
Public Attributes
const std::string type
const std::string message
const SourceLocation location
Detailed Description
Definition at line 255 of file inja.hpp.
Constructor & Destructor Documentation
InjaError() [1/2]
inja::InjaError::InjaError (const std::string & type, const std::string & message) inline explicit
Definition at line 261 of file inja.hpp.
            : std::runtime_error("[inja.exception." + type + "] " + message)
            , type(type)
            , message(message)
            , location({0, 0}) {
        }
References InjaError(), and location.
Referenced by InjaError().
InjaError() [2/2]
inja::InjaError::InjaError (const std::string & type, const std::string & message, SourceLocation location) inline explicit
Definition at line 268 of file inja.hpp.
            : std::runtime_error("[inja.exception." + type + "] (at " + std::to_string(location.line) + ":" +
                                 std::to_string(location.column) + ") " + message)
            , type(type)
            , message(message)
            , location(location) {
        }
References InjaError(), and location.
Referenced by InjaError().
Member Data Documentation
location
const SourceLocation inja::InjaError::location
Definition at line 259 of file inja.hpp.
Referenced by InjaError(), InjaError(), and mqtt::lib::MqttMapper::publishMappedTemplate().
message
const std::string inja::InjaError::message
Definition at line 257 of file inja.hpp.
type
const std::string inja::InjaError::type
Definition at line 256 of file inja.hpp.
The documentation for this struct was generated from the following file:
lib/inja.hpp