MQTTSuite: lib/json-schema-validator/test/uri.cpp File Reference
uri.cpp File Reference
#include <cstdlib>
#include <nlohmann/json-schema.hpp>
#include <iostream>
Functions
static void EXPECT_EQ (const std::string &a, const std::string &b)
static void EXPECT_EQ (const nlohmann::json_uri &a, const std::string &b)
static void paths (json_uri start, const std::string &full, const std::string &full_path, const std::string &no_path)
static void pointer_plain_name (json_uri start, const std::string &full, const std::string &full_path, const std::string &no_path)
int main (void)
Variables
static int errors
Function Documentation
EXPECT_EQ() [1/2]
static void EXPECT_EQ (const nlohmann::json_uri & a, const std::string & b) static
Definition at line 27 of file uri.cpp.
{
    EXPECT_EQ(a.to_string(), b);
}
References EXPECT_EQ(), and nlohmann::json_uri::to_string().
Referenced by paths(), and pointer_plain_name().
EXPECT_EQ() [2/2]
static void EXPECT_EQ (const std::string & a, const std::string & b) static
Definition at line 19 of file uri.cpp.
{
    if (a != b) {
        std::cerr << "Failed: '" << a << "' != '" << b << "'\n";
        errors++;
    }
}
References errors.
Referenced by EXPECT_EQ(), and pointer_plain_name().
main()
int main (void)
Definition at line 86 of file uri.cpp.
{
    json_uri empty("");
    paths(empty,
          "",
          "",
          "");
    json_uri http("http://json-schema.org/draft-07/schema#");
    paths(http,
          "http://json-schema.org/draft-07/schema",
          "http://json-schema.org/draft-07",
          "http://json-schema.org");
    pointer_plain_name(http,
                       "http://json-schema.org/draft-07/schema",
                       "http://json-schema.org/draft-07",
                       "http://json-schema.org");
    return errors;
}
References errors, nlohmann::json_uri::json_uri(), paths(), and pointer_plain_name().
paths()
static void paths (json_uri start, const std::string & full, const std::string & full_path, const std::string & no_path) static
Definition at line 32 of file uri.cpp.
{
    EXPECT_EQ(start, full + " # ");
    auto a = start.derive("other.json");
    EXPECT_EQ(a, full_path + "/other.json # ");
    auto b = a.derive("base.json");
    EXPECT_EQ(b, full_path + "/base.json # ");
    auto c = b.derive("subdir/base.json");
    EXPECT_EQ(c, full_path + "/subdir/base.json # ");
    auto d = c.derive("subdir2/base.json");
    EXPECT_EQ(d, full_path + "/subdir/subdir2/base.json # ");
    auto e = c.derive("/subdir2/base.json");
    EXPECT_EQ(e, no_path + "/subdir2/base.json # ");
    auto f = c.derive("new.json");
    EXPECT_EQ(f, full_path + "/subdir/new.json # ");
    auto g = c.derive("/new.json");
    EXPECT_EQ(g, no_path + "/new.json # ");
}
References nlohmann::json_uri::derive(), and EXPECT_EQ().
Referenced by main().
pointer_plain_name()
static void pointer_plain_name (json_uri start, const std::string & full, const std::string & full_path, const std::string & no_path) static
Definition at line 61 of file uri.cpp.
{
    auto a = start.derive("#/json/path");
    EXPECT_EQ(a, full + " # /json/path");
    a = start.derive("#/json/special_%22");
    EXPECT_EQ(a, full + " # /json/special_\"");
    a = a.derive("#foo");
    EXPECT_EQ(a, full + " # foo");
    a = a.derive("#foo/looks_like_json/poiner/but/isnt");
    EXPECT_EQ(a, full + " # foo/looks_like_json/poiner/but/isnt");
    EXPECT_EQ(a.identifier(), "foo/looks_like_json/poiner/but/isnt");
    EXPECT_EQ(a.pointer().to_string(), "");
    a = a.derive("#/looks_like_json/poiner/and/it/is");
    EXPECT_EQ(a, full + " # /looks_like_json/poiner/and/it/is");
    EXPECT_EQ(a.pointer().to_string(), "/looks_like_json/poiner/and/it/is");
    EXPECT_EQ(a.identifier(), "");
}
References nlohmann::json_uri::derive(), EXPECT_EQ(), EXPECT_EQ(), nlohmann::json_uri::identifier(), and nlohmann::json_uri::pointer().
Referenced by main().
Variable Documentation
errors
static int errors static
Definition at line 17 of file uri.cpp.
Referenced by EXPECT_EQ(), and main().